### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [Wechat-Group/WxJava#1091]
Hi
The following lines have cryptographic API misuses. <br> File name => weixin-java-miniapp/src/main/java/cn/binarywang/wx/miniapp/util/crypt/WxMaCryptUtils.java: Line number => 31: API name => AlgorithmParameters:<BR> File name => weixin-java-miniapp/src/main/java/cn/binarywang/wx/miniapp/util/crypt/WxMaCryptUtils.java: Line number => 37: API name => Cipher:<BR> File name => weixin-java-miniapp/src/main/java/cn/binarywang/wx/miniapp/util/crypt/WxMaCryptUtils.java: Line number => 34: API name => Cipher:First parameter (with value "AES/CBC/NoPadding") should be any of AES/CBC/{Empty String, PKCS7Padding, PKCS5Padding, ISO10126Padding}<BR> File name => weixin-java-miniapp/src/main/java/cn/binarywang/wx/miniapp/util/crypt/WxMaCryptUtils.java: Line number => 32: API name => IvParameterSpec:<BR> File name => weixin-java-miniapp/src/main/java/cn/binarywang/wx/miniapp/util/crypt/WxMaCryptUtils.java: Line number => 35: API name => SecretKeySpec:<BR> File name => weixin-java-miniapp/src/main/java/cn/binarywang/wx/miniapp/util/crypt/WxMaCryptUtils.java: Line number => 35: API name => SecretKeySpec:<BR> File name => weixin-java-miniapp/src/main/java/cn/binarywang/wx/miniapp/util/crypt/WxMaCryptUtils.java: Line number => 37: API name => Cipher:<BR> File name => weixin-java-pay/src/main/java/com/github/binarywang/wxpay/service/impl/EntPayServiceImpl.java: Line number => 123: API name => Cipher:First parameter (with value "RSA/ECB/OAEPWithSHA1AndMGF1Padding") should be any of RSA/ECB/{Empty String, PKCS1Padding, OAEPWithMD5AndMGF1Padding, OAEPWithSHA-224AndMGF1Padding, OAEPWithSHA-256AndMGF1Padding, OAEPWithSHA-384AndMGF1Padding, OAEPWithSHA-512AndMGF1Padding}<BR> File name => weixin-java-pay/src/main/java/com/github/binarywang/wxpay/bean/notify/WxPayRefundNotifyResult.java: Line number => 55: API name => Cipher:<BR> File name => weixin-java-pay/src/main/java/com/github/binarywang/wxpay/bean/notify/WxPayRefundNotifyResult.java: Line number => 55: API name => Cipher:<BR> File name => weixin-java-pay/src/main/java/com/github/binarywang/wxpay/bean/notify/WxPayRefundNotifyResult.java: Line number => 51: API name => SecretKeySpec:<BR> File name => weixin-java-pay/src/main/java/com/github/binarywang/wxpay/service/impl/EntPayServiceImpl.java: Line number => 129: API name => Cipher:<BR> File name => weixin-java-pay/src/main/java/com/github/binarywang/wxpay/bean/notify/WxPayRefundNotifyResult.java: Line number => 53: API name => Cipher:First parameter (with value "AES/ECB/PKCS5Padding") should be any of AES/{CBC, GCM, PCBC, CTR, CTS, CFB, OFB}<BR> File name => weixin-java-pay/src/main/java/com/github/binarywang/wxpay/config/WxPayConfig.java: Line number => 142: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => weixin-java-pay/src/main/java/com/github/binarywang/wxpay/service/impl/EntPayServiceImpl.java: Line number => 129: API name => Cipher:<BR> File name => weixin-java-pay/src/main/java/com/github/binarywang/wxpay/bean/notify/WxPayRefundNotifyResult.java: Line number => 51: API name => SecretKeySpec:<BR> File name => weixin-java-common/src/main/java/me/chanjar/weixin/common/util/crypto/WxCryptUtil.java: Line number => 241: API name => SecretKeySpec:<BR> File name => weixin-java-common/src/main/java/me/chanjar/weixin/common/util/crypto/WxCryptUtil.java: Line number => 186: API name => Cipher:First parameter (with value "AES/CBC/NoPadding") should be any of AES/CBC/{Empty String, PKCS7Padding, PKCS5Padding, ISO10126Padding}<BR> File name => weixin-java-common/src/main/java/me/chanjar/weixin/common/util/crypto/WxCryptUtil.java: Line number => 187: API name => SecretKeySpec:<BR> File name => weixin-java-common/src/main/java/me/chanjar/weixin/common/util/crypto/WxCryptUtil.java: Line number => 240: API name => Cipher:First parameter (with value "AES/CBC/NoPadding") should be any of AES/CBC/{Empty String, PKCS7Padding, PKCS5Padding, ISO10126Padding}<BR> File name => weixin-java-common/src/main/java/me/chanjar/weixin/common/util/crypto/WxCryptUtil.java: Line number => 250: API name => Cipher:<BR> File name => weixin-java-common/src/main/java/me/chanjar/weixin/common/util/crypto/WxCryptUtil.java: Line number => 192: API name => Cipher:<BR> File name => weixin-java-common/src/main/java/me/chanjar/weixin/common/util/crypto/WxCryptUtil.java: Line number => 187: API name => SecretKeySpec:<BR> File name => weixin-java-common/src/main/java/me/chanjar/weixin/common/util/SignUtils.java: Line number => 30: API name => SecretKeySpec:<BR> File name => weixin-java-common/src/main/java/me/chanjar/weixin/common/util/crypto/WxCryptUtil.java: Line number => 250: API name => Cipher:<BR> File name => weixin-java-common/src/main/java/me/chanjar/weixin/common/util/crypto/WxCryptUtil.java: Line number => 241: API name => SecretKeySpec:<BR> File name => weixin-java-common/src/main/java/me/chanjar/weixin/common/util/crypto/WxCryptUtil.java: Line number => 192: API name => Cipher:<BR> File name => weixin-java-common/src/main/java/me/chanjar/weixin/common/util/SignUtils.java: Line number => 30: API name => SecretKeySpec:<BR> File name => weixin-java-common/src/main/java/me/chanjar/weixin/common/util/crypto/WxCryptUtil.java: Line number => 188: API name => IvParameterSpec:<BR> File name => weixin-java-common/src/main/java/me/chanjar/weixin/common/util/crypto/WxCryptUtil.java: Line number => 242: API name => IvParameterSpec:<BR>

**Comment by binarywang** [comment]
这是什么鬼，基于什么得来的，能否翻译下？

**Comment by binarywang** [comment]
不知道说的啥，先关闭
