### ISSUE TITLE
小程序直播相关接口

### ISSUE THREAD

**Issue by zpp0318** [Wechat-Group/WxJava#1727]
微信官方文档
https://api.weixin.qq.com/wxa/business/getliveinfo?access_token=
请求方式为https   
项目中实际请求方式为：
http://api.weixin.qq.com/wxa/business/

### 模块版本情况
* WxJava 模块名: wx-java-miniapp
* WxJava 版本号:3.8.0

### 详细描述
请求方式应为https     实际请求方式为http  故请求微信直播类接口报错     错误代码43003  错误信息   需要使用https

**Comment by binarywang** [comment]
早已修复，请注意使用最新版
