### ISSUE TITLE
微信小程序发送客服消息，为什么服务器只能收到一条消息，后面的都收不到？

### ISSUE THREAD

**Issue by whyus** [Wechat-Group/WxJava#1729]
下载小程序demo模块，后台配置了appkey等参数，然后验证通过，但是点击客服消息的时候event消息，后面用户发送消息并没有转发到服务器后台，是demo哪里配置不对吗

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号:3.8.0

### 详细描述
这段代码执行了第一次，后面用户发送的消息没有跑进来，路由的入口哪里的日志也没有打印出来，所以微信并没有转发到这里
 private final WxMaMessageHandler logHandler = (wxMessage, context, service, sessionManager) -> {
        System.out.println("收到消息：" + wxMessage.toString());
        service.getMsgService().sendKefuMsg(WxMaKefuMessage.newTextBuilder().content("收到信息为：" + wxMessage.toJson())
            .toUser(wxMessage.getFromUser()).build());
        return null;
    };
日志打印了下面这句，而且每次点击客服按钮就打印下面一句，请问是什么原因，谢谢了
请求参数】：{"touser":"oENu15P_ouecoIr95O8hqz-flnV0","msgtype":"text","text":{"content":"收到信息为：{\"ToUserName\":\"gh_75d707a67e92\",\"FromUserName\":\"oENu15P_ouecoIr95O8hqz-flnV0\",\"CreateTime\":1598154568,\"MsgType\":\"event\",\"Event\":\"user_enter_tempsession\",\"SessionFrom\":\"wxapp\"}"}}
【响应数据】：{"errcode":0,"errmsg":"ok"}
2020-08-23 11:49:28.238 DEBUG 58781 --- [geRouter-pool-5] c.b.w.miniapp.message.WxMaMessageRouter  : End session access: async=true, sessionId=oENu15P_oueco

**Comment by binarywang** [comment]
你这是demo的问题，建议在demo下提问，另外建议仔细调试下看看，来顺便了解程序的处理逻辑
