### ISSUE TITLE
609425

### ISSUE THREAD

**Issue by tiancaishuhe** [Wechat-Group/WxJava#1823]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
WxConsts.text  没有text

### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号:3.9.0

### 详细描述
WxConsts.text  没有text

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by binarywang** [comment]
什么鬼

**Comment by binarywang** [comment]
完全看不懂，建议描述清楚，重新按格式发帖
