### ISSUE TITLE
项目中锁的问题

### ISSUE THREAD

**Issue by Endtostart** [Wechat-Group/WxJava#1825]
项目中中更新component_verify_ticket 和 component_access_token等信息时，获取的锁不是分布式锁，当多实例部署的时候会存在问题。
建议换成分布式锁

**Comment by binarywang** [comment]
自己更换即可

**Comment by Endtostart** [comment]
> 自己更换即可

thanks, 看到了不同储存模式的锁的不同。我可以选择redis存储模式。
但是，还是建议 即使用户选择内存存储模式，锁也应该分布式锁。当然只是建议。

**Comment by binarywang** [comment]
内存模式不适用于多实例部署场景吧，有啥意义呢
