### ISSUE TITLE
海关推单，自助清关接口调用功能缺失

### ISSUE THREAD

**Issue by kawhii** [Wechat-Group/WxJava#1830]
### 微信支付报关

进口电商需要进行清关推单，需要用到此产品，希望能添加该接口sdk调用

### 官方文档地址
https://pay.weixin.qq.com/wiki/doc/api/wxpay/external_v3/ch/pages/declarecustom_v3.shtml

**Comment by binarywang** [comment]
欢迎自行实现并提交PR，因为此接口可能需要提供可用账号进行接口调试，你正好用到这块，可能是最佳的实现人选。
否则可能没人能帮忙实现，则可能无限期推迟实现。
