### ISSUE TITLE
公众号和小程序生成二维码

### ISSUE THREAD

**Issue by gentryhuang** [Wechat-Group/WxJava#1831]
公众号和小程序生成二维码返回File的接口使用 nio 工具生成文件路径，但是服务器上没有对应的写权限，文件路径能否支持配置？当然如果使用返回byte[]的然后自行封装的话倒是不用考虑权限问题。

**Comment by binarywang** [comment]
创建文件是放在系统tmp目录，不会连临时目录的读写权限都不给吧，那我真无语了

**Comment by gentryhuang** [comment]
嗯嗯，确实不给，需要在指定的目录下操作文件。不过问题不大，对于小程序目前我重写 QrcodeRequestExecutor 中的方法然后自行指定路径，并把 WxMaServiceImpl中的WxMaQrcodeService 换下就可以了。其实也可以使用返回字节数组的方法，主要考虑了下插拔式开发，其它的没啥问题。很棒的一个开源项目！ 楼主没问题就关了哈。

**Comment by binarywang** [comment]
好吧，真是我见识少了。
不过你如果觉得必要，可以增加重载方法，实现完测试没问题直接提交PR即可，万一有其他小伙伴也需要呢
