### ISSUE TITLE
3.9.0版本wxmp模块公众号关注报错

### ISSUE THREAD

**Issue by ccyy-git** [Wechat-Group/WxJava#1833]
![image](https://user-images.githubusercontent.com/66662376/97677246-f621e880-1acc-11eb-80d4-029eebef6d6c.png)

微信公众号模块关注和取消关注报错3.9.0版本的

**Comment by binarywang** [comment]
自己打印下原始响应内容，看到底是什么东西？感觉可能是伪造的请求

**Comment by ccyy-git** [comment]
> 自己打印下原始响应内容，看到底是什么东西？感觉可能是伪造的请求

![image](https://user-images.githubusercontent.com/66662376/97820208-095cd000-1ce8-11eb-9a5b-00b3693ec163.png)
伪造请求的判断过了

**Comment by binarywang** [comment]
你这请求明显有问题，要求的是xml

**Comment by ccyy-git** [comment]
> 你这请求明显有问题，要求的是xml

对，就是不知道为什么requestBody为什么不是xml，而是这个数字，不是官方的问题，我用官方demo没问题weixin-java-mp-demo-springboot。。现在好郁闷。谢谢了

**Comment by tianxiaoyunyou** [comment]
我同样版本也是同样的问题，普通用户发送消息，接受消息时，加密模式下@RequestBody String requestBody为空，明文模式就是一串数字。

**Comment by binarywang** [comment]
是否参考过demo？对比下是你哪里配置出了问题？或许是spring的相关配置问题

**Comment by tianxiaoyunyou** [comment]
我把直接把demo复制过来的，其他参数都是正常的。不行的话，我就多加HttpServletRequest request吧，直接从request上取数。
**demo调用代码：**
@PostMapping(produces = "application/xml; charset=UTF-8")
	public String post(@PathVariable String appid,
					   @RequestBody String requestBody,
					   @RequestParam("signature") String signature,
					   @RequestParam("timestamp") String timestamp,
					   @RequestParam("nonce") String nonce,
					   @RequestParam("openid") String openid,
					   @RequestParam(name = "encrypt_type", required = false) String encType,
					   @RequestParam(name = "msg_signature", required = false) String msgSignaturet) {
		log.info("\n接收微信请求：[openid=[{}], [signature=[{}], encType=[{}], msgSignature=[{}],"
				+ " timestamp=[{}], nonce=[{}], requestBody=[\n{}\n] ",
			openid, signature, encType, msgSignature, timestamp, nonce, requestBody);

**控制台输出：**
接收微信请求：[openid=[oGQsS0kzIcPt4yxIwjpVPBwaO8Wo], [signature=[4c854b831ba8e62607bdcbf8ae6319938373ac3c], encType=[null], msgSignature=[null], timestamp=[1605600796], nonce=[1178209226], requestBody=[
160560079622986675227738254
]

**Comment by binarywang** [comment]
你先用demo跑看有没有问题，再来对比差在哪里

**Comment by binarywang** [comment]
有问题请新开issue，如果是对demo理解有问题，请在对应demo处发issue
