### ISSUE TITLE
3.9.0 版本 BaseWxPayRequest 缺少 fentoyuan 方法

### ISSUE THREAD

**Issue by superwg1984** [Wechat-Group/WxJava#1835]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
3.9.0 版本 BaseWxPayRequest 缺少 fentoyuan 方法

### 模块版本情况
* WxJava 模块名:  wx-java-pay-spring-boot-starter
* WxJava 版本号: 3.9.0

### 详细描述
3.9.0 版本 BaseWxPayRequest 缺少 fentoyuan 方法

**Comment by binarywang** [comment]
为啥需要，说出你的使用场景呗

**Comment by binarywang** [comment]
如果确实需要，请使用 `com.github.binarywang.wxpay.bean.result.BaseWxPayResult#fenToYuan` 。
这是个公共静态方法，随便用
