### ISSUE TITLE
希望新增合单支付接口

### ISSUE THREAD

**Issue by qeprwjcgya** [Wechat-Group/WxJava#1839]
### 简要描述
使用合单支付接口，用户只输入一次密码，即可完成多个订单的支付

### 官方文档地址
https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/combine/chapter3_2.shtml

**Comment by binarywang** [comment]
这个其实已经实现了，请注意看版本更新日志或者直接搜索源码。
具体方法为：`com.github.binarywang.wxpay.service.EcommerceService#combine`
