### ISSUE TITLE
企业第三方应用开发消息处理类不正确

### ISSUE THREAD

**Issue by BlankOfPi** [Wechat-Group/WxJava#1851]
### 简要描述
企业第三方应用开发消息处理类不正确

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号: 3.9.5.B

### 详细描述
/**
 * 处理微信推送消息的处理器接口
 *
 * @author Daniel Qian
 */
public interface WxCpTpMessageHandler {

  /**
   * Handle wx cp xml out message.
   *
   * @param wxMessage      the wx message
   * @param context        上下文，如果handler或interceptor之间有信息要传递，可以用这个
   * @param wxCpService    the wx cp service
   * @param sessionManager the session manager
   * @return xml格式的消息 ，如果在异步规则里处理的话，可以返回null
   * @throws WxErrorException the wx error exception
   */
  WxCpXmlOutMessage handle(WxCpXmlMessage wxMessage,
                           Map<String, Object> context,
                           WxCpTpService wxCpService,
                           WxSessionManager sessionManager) throws WxErrorException;

}

**Comment by binarywang** [comment]
最新版已经修复了
