### ISSUE TITLE
微信小程序项目报缺少JedisLock的jar包

### ISSUE THREAD

**Issue by HaiTao-G** [Wechat-Group/WxJava#1854]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号:3.9.4.B

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__

### 日志
Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: com/github/jedis/lock/JedisLock

**Comment by binarywang** [comment]
jedis-lock的依赖是optional的，你项目中用到了对应功能，就需要自己手动加入依赖。
