### ISSUE TITLE
小程序直播相关接口不全

### ISSUE THREAD

**Issue by echoesink** [Wechat-Group/WxJava#1858]
缺少小程序直播相关的功能：
比如：编辑直播间、获取直播间推流地址、直播间小助手管理功能；成员管理管理功能等等。

文微信文档 https://developers.weixin.qq.com/miniprogram/dev/framework/liveplayer/studio-api.html

**Comment by binarywang** [comment]
目前确实只是实现了部分接口，是比较常用的接口，如果你列出的接口需要实现，欢迎直接自行实现，并提交PR

**Comment by binarywang** [comment]
直播间管理、直播间小助手管理等功能已经实现，其他如果需要请单独提issue
