### ISSUE TITLE
微信开放平台

### ISSUE THREAD

**Issue by zacat** [Wechat-Group/WxJava#1860]
### 简要描述
通过code来获取用户信息，调用失败。

### 模块版本情况
* WxJava 模块名: weixin-java-open
* WxJava 版本号: 3.9.8.B

**Comment by binarywang** [comment]
你这描述也太精简了吧

**Comment by zacat** [comment]
WxOAuth2AccessToken  accessToken = weixinService.getMpService().getOAuth2Service().getAccessToken(s);
                if (accessToken != null) {
                    WxOAuth2UserInfo wxMpUser = weixinService.getMpService().getOAuth2Service().getUserInfo(accessToken, null);
}

getMpService()的返回的方法：
  WxMpService wxMpService = wxOpenService.getWxOpenComponentService().getWxMpServiceByAppid(wxMpConfig.getAppId());
            WxMpDefaultConfigImpl wxMpConfigStorage = new WxMpDefaultConfigImpl();
            wxMpConfigStorage.setAppId(wxMpConfig.getAppId());
            wxMpConfigStorage.setSecret(wxMpConfig.getSecret());
            wxMpConfigStorage.setToken(wxMpConfig.getToken());
            wxMpConfigStorage.setAesKey(wxMpConfig.getAseKey());
            wxMpService.setWxMpConfigStorage(wxMpConfigStorage);
            return wxMpService;

**Comment by binarywang** [comment]
报啥错误也不说下吗？

**Comment by zacat** [comment]
没有报错，就这句话，wxMpUser返回空值
WxOAuth2UserInfo wxMpUser = weixinService.getMpService().getOAuth2Service().getUserInfo(accessToken, null);

**Comment by binarywang** [comment]
空值问题很简单，自己调试下就知道是什么东西没配置导致的

> 没有报错，就这句话，wxMpUser返回空值
> WxOAuth2UserInfo wxMpUser = weixinService.getMpService().getOAuth2Service().getUserInfo(accessToken, null);

**Comment by zacat** [comment]
换成3.8.0没有问题。

**Comment by binarywang** [comment]
没明白你为啥要通过那么复杂的方法来调用oauth2相关接口，为啥不直接通过`me.chanjar.weixin.open.api.impl.WxOpenOAuth2ServiceImpl`这个构建实例来完成相关接口调用？
