### ISSUE TITLE
提审素材上传接口

### ISSUE THREAD

**Issue by yangyh22** [Wechat-Group/WxJava#1866]
### 官方文档地址
__https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Mini_Programs/code/submit_audit.html__

**Comment by yangyh22** [comment]
换了一个实现方式可以上传成功，但是没有返回mediaid，代码如下所示
`            WxMediaUploadResult execute = wxOpenMaService.execute(MediaUploadRequestExecutor.create(wxOpenMaService.getRequestHttp()),
                    "https://api.weixin.qq.com/wxa/uploadmedia",
                    tmpFile);`
但是，```WxMediaUploadResult ```中的字段名称是```mediaId``` 而这个【提审素材上传接口】返回的是```mediaid```，所以我自定义了```Result``` 以及相应的```RequestExecutor```。这个时候就能成功的拿到```mediaid```请问大佬们还有没有更好的解决方案。

**Comment by binarywang** [comment]
欢迎直接提交你实现好的代码，提交PR，这就是最好的解决办法
