### ISSUE TITLE
疑问？

### ISSUE THREAD

**Issue by Endtostart** [Wechat-Group/WxJava#1876]
WxCpTpService 类和 WxCpService区别是什么。在使用时如何定位和关联？

**Comment by binarywang** [comment]
TP是第三方应用，独立使用

**Comment by Endtostart** [comment]
这个类 WxCpServiceOnTpImpl 存在的意义不是太明白？
我现在开发的应用属于第三方服务方，属于多租户形式。会有很多企业授权企业微信给我。
那么我是否后续调用只用WxCpTpService这个类？ 还是说我存下来所有授权用户的access_token，然后使用 WxCpService 类去调用微信，每次使用时都new 一个 WxCpService示例，并赋值对应的 access_token

**Comment by Endtostart** [comment]
> TP是第三方应用，独立使用

**Comment by binarywang** [comment]
@feye 有空可以帮忙看看这位小伙伴的疑问

**Comment by ChaoyongWang** [comment]
> 这个类 WxCpServiceOnTpImpl 存在的意义不是太明白？
> 我现在开发的应用属于第三方服务方，属于多租户形式。会有很多企业授权企业微信给我。
> 那么我是否后续调用只用WxCpTpService这个类？ 还是说我存下来所有授权用户的access_token，然后使用 WxCpService 类去调用微信，每次使用时都new 一个 WxCpService示例，并赋值对应的 access_token

@Endtostart 你好，请问这个问题后来解决了吗？

**Comment by Bleoo** [comment]
各位有人解决了吗？
