### ISSUE TITLE
关于 getWxCpTpConfigStorage()  方法被废弃的疑问

### ISSUE THREAD

**Issue by Endtostart** [Wechat-Group/WxJava#1877]
WxCpTpService 类中 getWxCpTpConfigStorage()标注为废弃，但是 WxCpTpCryptUtil 构造方法需要 WxCpTpConfigStorage 参数，本来打算通过 WxCpTpService 类获取，废弃之后如何获取？还有就是废弃的原因？

**Comment by LeoInnovateLab** [comment]
同问+1

**Comment by binarywang** [comment]
源码注释里不是有写吗？

**Comment by binarywang** [comment]
@xworks
