### ISSUE TITLE
SpringBoot2的Redis默认实现已改为Lettuce，目前项目还是使用的Jedis，请问什么时候能支持？

### ISSUE THREAD

**Issue by Rebuilding127** [Wechat-Group/WxJava#1879]
在demo示例及源码中对WxMpService的配置中，关于Redis的配置都是用的Jedis实现，查找源码也没有发现有Lettuce的实现支持，请问下什么时候能添加下？

**Comment by binarywang** [comment]
lettuce不熟，如果你比较熟，建议可以尝试增加支持，提交PR

**Comment by Rebuilding127** [comment]
十分抱歉，之前太忙没时间处理。这两天本来想自己实现提交一下，无意中发现网上已经有现成的实现代码，可以参考下：
[WxJava使用lettcue客户端redis实现](https://gitee.com/welitis/blog_code/blob/master/wxjava-redis-demo/src/main/java/com/example/wxjavaredisdemo/config/WxMaLettuceRedisConfigImpl.java)

**Comment by binarywang** [comment]
你可以直接提交PR
