### ISSUE TITLE
版本3.9.9.B，缺少依赖，启动报错

### ISSUE THREAD

**Issue by jason-liu475** [Wechat-Group/WxJava#1880]
https://github.com/Wechat-Group/WxJava/blob/b351ef761c2e2270e56581943c7705a3e9725ea7/weixin-java-pay/src/main/java/com/github/binarywang/wxpay/service/impl/BaseWxPayServiceImpl.java#L26

**Comment by binarywang** [comment]
大哥，是你版本问题吧，请检查common包

**Comment by jason-liu475** [comment]
确实是，common包换成同样版本就没问题了
