### ISSUE TITLE
BaseWxMpServiceImpl#getTicket当失效时并发会有锁饥饿问题

### ISSUE THREAD

**Issue by zhanghuihuang** [Wechat-Group/WxJava#1881]
### 简要描述
使用JedisDistributedLock这种情况,获取的lock对象在setAppId时初始化了分布式锁,里面持有一个jedisLock对象
jedisLock的acquire和release方法加了synchronized,需要对象锁
JedisDistributedLock的lock和unlock分别会调用jedisLock的acquire和release方法,如果出现并发时,有一个线程获取了分布式锁,在执行业务逻辑时,其他线程都是在尝试获取锁,争抢jedisLock的对象锁,此时要释放分布式锁,也要参与争抢jedisLock的对象锁才能释放,只有争抢到对象锁后,才能释放,概率比较小.即使释放后,后续已经过了第一次check的线程也会出现类似情况,导致一段时间的对象锁争抢,过期时的并发度越大,越有可能出现锁饥饿现象

### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号:develop

**Comment by newway520** [comment]
这个问题线上也遇到过，随着用户请求数增多，锁竞争越来越激烈最后所有接口出现pending状态。
目前是将WxMpDefaultConfigImpl改成WxMpRedissonConfigImpl的实现方式来解决分布式锁问题。

**Comment by wangjia2016** [comment]
![image](https://user-images.githubusercontent.com/16084076/110601019-7d8c1080-81bf-11eb-8c36-891b95e9072d.png)

我用的3.9.4.B的版本，测试环境 基本就两三个人访问，也有问题

**Comment by binarywang** [comment]
楼上已经给了解决方案
