### ISSUE TITLE
WxMaLiveService微信小程序直播接口返回值的问题

### ISSUE THREAD

**Issue by cloud13th** [Wechat-Group/WxJava#1884]
### 简要描述
微信小程序直播相关的接口 WxMaLiveService 中,许多接口的返回值被过滤掉了,但是有些业务需要获取相关的返回值反写到本地数据库中,返回值被过滤掉造成了很多不便.

例如:
创建直播间接口,在API中返回的只是直播间ID,但是在官方文档中返回数据中包含`qrcode_url`参数,这个参数业务上需要保存到本地数据库中,由于接口调用有频率限制,如果通过直播间ID再调用其他接口,会造成不必要的次数消耗.
相关文档链接:https://developers.weixin.qq.com/miniprogram/dev/framework/liveplayer/studio-api.html#1

PS: 版本3.9.0中关于小程序直播的接口不全,在3.9.9.B中有完善,所以新版本什么时候能发布一个稳定版的啊?

### 官方文档地址
https://developers.weixin.qq.com/miniprogram/dev/framework/liveplayer/studio-api.html

**Comment by binarywang** [comment]
你所说的被过滤掉了，只是可能没加上，可能是开发人员的疏忽或者官方后来才增加的。
建议如果你发现有缺失字段，直接提交PR。
毕竟目前使用的人不多，如果大家都不使用，不去发现问题，也不去修复，我们的版本就永远没法稳定

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/issues/1886 已新建issue
