### ISSUE TITLE
企业微信更新员工自定义字段（网页类型）时，序列化失败

### ISSUE THREAD

**Issue by caowenhao** [Wechat-Group/WxJava#1892]
### 简要描述
更新员工自定义字段时，序列化失败

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号: 3.9.0

### 详细描述
WxCpUserGsonAdapter中 JsonElement serialize(WxCpUser user, Type typeOfSrc, JsonSerializationContext context)方法中网页类型没有设置type以及name的值

  if (user.getExtAttrs().size() > 0) {
            attrsJsonArray = new JsonArray();
            Iterator var14 = user.getExtAttrs().iterator();
            while(var14.hasNext()) {
                Attr attr = (Attr)var14.next();
                JsonObject attrJson = new JsonObject();
                attrsJsonArray.add(attrJson);
                if (attr.getType() == null) {
                    attrJson.addProperty("name", attr.getName());
                    attrJson.addProperty("value", attr.getTextValue());
                } else {
                    switch(attr.getType()) {
                    case 0:
                        attrJson = new JsonObject();
                        attrJson.addProperty("value", attr.getTextValue());
                        attrJson.add("text", attrJson);
                        break;
                    case 1:
                        attrJson = new JsonObject();
                        attrJson.addProperty("url", attr.getWebUrl());
                        attrJson.addProperty("title", attr.getWebTitle());
                        attrJson.add("web", attrJson);
                    }
                }
            }

### 日志
转换后的json如下：
**"extattr":{"attrs":[{"text":{"value":"01482"}},{"web":{"url":"https://www.baidu.com","title":"3-103"}}]},**

**Comment by binarywang** [comment]
你说的这个问题早已修复，建议你看真正的最新的源码，而不是反编译的代码。

**Comment by binarywang** [comment]
参考 #1738
