### ISSUE TITLE
小程序支付接多个商户号怎么配置参数

### ISSUE THREAD

**Issue by 2015015445** [Wechat-Group/WxJava#1893]
小程序需要接多家商户平台，需要配置多个mchId,根据不同情况支付给不同商户，这个怎么配置呢，只能配一个WxPayConfig，这个有解决方案吗

**Comment by 2015015445** [comment]
或者说动态配置商户号等参数，不要从yml里读，从数据库拿

**Comment by gaelthas** [comment]
一个小程序只能对应一个商户号。我之前也想搞这样的，发现不行的。

**Comment by binarywang** [comment]
楼上说的对
