### ISSUE TITLE
小程序中WxMaLiveRoomInfo类的成员变量命名不规范

### ISSUE THREAD

**Issue by 91geek** [Wechat-Group/WxJava#1896]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名:  weixin-java-miniapp
* WxJava 版本号: 3.9.3.B

### 详细描述
cn.binarywang.wx.miniapp.bean.live.WxMaLiveRoomInfo这个类中的成员变量名字不规范。
  /**
   * 是否关闭分享 【0：开启，1：关闭】默认开启分享（直播开始后不允许修改）
   **/
  **private Integer loseShare;**
应修复为private Integer **c**loseShare;

**Comment by binarywang** [comment]
这个已修复，注意看最新代码
