### ISSUE TITLE
小程序api接口域名地址无法支持切换

### ISSUE THREAD

**Issue by peterzhou12345** [Wechat-Group/WxJava#1897]
微信API接口api.weixin.qq.com经常无法访问，WxMaService 不支持自定义切换微信api其他接口，微信官方能支持的接口包括：https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/Interface_field_description.html

**Comment by binarywang** [comment]
后续可以考虑，也欢迎楼主提供可行方案PR代码
