### ISSUE TITLE
微信电子发票→设置商户联系方式参数有误吧

### ISSUE THREAD

**Issue by 380862139** [Wechat-Group/WxJava#1898]
* WxJava 模块名: me.chanjar.weixin.mp.bean.invoice.merchant.MerchantContactInfo
* WxJava 版本号:3.9.0

![1](https://user-images.githubusercontent.com/38513805/100546633-5c04ba00-329d-11eb-86fa-3a5efb16fa8d.png)
![2](https://user-images.githubusercontent.com/38513805/100546637-5effaa80-329d-11eb-97e9-8bcc5040ca19.png)

**Comment by 380862139** [comment]
time_out →  timeOut

**Comment by binarywang** [comment]
请贴出具体文档地址，并描述清楚，不要发图片，有时看不到

**Comment by 380862139** [comment]
WxJava - MP Java SDK 4.0.0 API
类me.chanjar.weixin.mp.bean.invoice.merchant.MerchantContactInfo扩展Object实现可序列化
序列化字段
String phone
联系电话
Integer timeout
开票超时时间

微信文档：17 设置商户联系方式
https://developers.weixin.qq.com/doc/offiaccount/WeChat_Invoice/E_Invoice/Vendor_API_List.html#17

参数 | 类型 | 是否必填 | 描述
time_out | int | 是 | 开票超时时间
phone | string | 是 | 联系电话

在使用中timeout参数不对，需要使用timeOut
