### ISSUE TITLE
是否有计划新增微信智能对话平台

### ISSUE THREAD

**Issue by 721806280** [Wechat-Group/WxJava#1900]
https://developers.weixin.qq.com/doc/aispeech/platform/INTRODUCTION.html

**Comment by binarywang** [comment]
目前没有计划，都没听说过，但楼主最好贴个文档的地址吧？

**Comment by 721806280** [comment]
@binarywang  https://developers.weixin.qq.com/doc/aispeech/platform/INTERFACEDOCUMENT.html

**Comment by binarywang** [comment]
暂无计划，如果楼主需要使用到此功能，建议自行实现代码，并提交PR
