### ISSUE TITLE
这个wx-java-pay有合单支付吗？

### ISSUE THREAD

**Issue by kelvin-cai** [Wechat-Group/WxJava#1901]
就是先生成了多个微信统一下单接口，得到商户订单号后，把所有的商户订单号一起支付，把3个金额合并成一个支付。

**Comment by binarywang** [comment]
你可以对照你所要求的接口文档，在本项目源码中搜索对应的接口地址，就可以知道是否有实现

**Comment by william-abel** [comment]
> 就是先生成了多个微信统一下单接口，得到商户订单号后，把所有的商户订单号一起支付，把3个金额合并成一个支付。

你找到了吗?

**Comment by binarywang** [comment]
自己根据文档里的接口搜就行了，没有的话，请提出新的issue，或者直接自己动手然后提供PR代码上来
