### ISSUE TITLE
生成二维码不能带参数吗？只看到sceneId这一个参数。

### ISSUE THREAD

**Issue by Figoshu** [Wechat-Group/WxJava#1903]
生成二维码不能带参数吗？只看到sceneId这一个参数，看了Test文档和impl里面都没有查到相关参数。官方不是有一个action_info这个参数嘛。

另再请教一下，sceneId这个参数是干什么的，官方说场景参数，但是具体时间用来作什么的呢？
感谢！

**Comment by binarywang** [comment]
请看清楚所有的方法，另外所有参数都是跟你自己业务场景需要设定用途的
