### ISSUE TITLE
微信公众平台上传永久非图文素材materialFileUpload可否新增一个用inputStream上传的api

### ISSUE THREAD

**Issue by 721806280** [Wechat-Group/WxJava#1911]
微信公众平台上传永久非图文素材materialFileUpload可否新增一个用inputStream上传的api

### 简要描述
weixin-java 4.0版

微信公众平台上传永久非图文素材materialFileUpload可否新增一个用inputStream上传的api,  功能与materialFileUpload一致，期望使用InputStream或byte[];

**Comment by binarywang** [comment]
建议如果有需求，可以自行实现代码并提交PR

**Comment by binarywang** [comment]
目前参数过于负杂，不易于改造，建议有好的实现方案，随时提交PR
