### ISSUE TITLE
为什么要抛出显示异常

### ISSUE THREAD

**Issue by Chad2li** [Wechat-Group/WxJava#1912]
正常业务下，没有需要处理的异常，为什么不能内部使用RuntimeException，每个方法都需要显示地try catch，导致项目中存在大量的try catch语句，而我仅仅是将它转换为 RuntimeException，因为对于微信的异常，无论是参数错误还是网络问题，都需要人工处理，我无法在代码逻辑中处理

建议：在代码中无能为力的异常，请抛出： RuntimeException

**Comment by Chad2li** [comment]
鉴于代码中会产生大量的 try catch语句，已弃用该项目...

**Comment by binarywang** [comment]
楼主过于着急下定论了吧，你所谓的无能为力的异常，真的是无法处理的吗？可能跟你自己存在已经的固有习惯冲突而已。
而且目前来说并没发现其他人在抱怨这种问题，说明大部分人还是认可这种处理方式的。
