### ISSUE TITLE
使用unionid 并弃用opendi

### ISSUE THREAD

**Issue by Chad2li** [Wechat-Group/WxJava#1913]
openid为历史遗留问题，不能支持多应用场景，现在官方文档已经建议使用unionid

**Comment by binarywang** [comment]
请描述清楚问题，如果可以请按模版来详细说明你的问题

**Comment by binarywang** [comment]
如果已经弃用，就不用劳神回复，不再打扰。
如果还想说什么，请新开issue描述清楚问题，暂时关闭此issue
