### ISSUE TITLE
企业微信发送应用消息接口增加是否开启重复消息检查等新增参数

### ISSUE THREAD

**Issue by chenxiangweifeng** [Wechat-Group/WxJava#1915]
是否开启重复消息检查的配置（enable_duplicate_check等），好像没看到呢。。
weixin-java-cp 版本 3.9.0

**Comment by binarywang** [comment]
请给出具体的文档

**Comment by chenxiangweifeng** [comment]
![image](https://user-images.githubusercontent.com/33818312/101709791-17fa8c00-3acb-11eb-9849-d88e777e9f50.png)
注： https://work.weixin.qq.com/api/doc/90000/90135/90236            发送应用消息接口

**Comment by chenxiangweifeng** [comment]
enable_duplicate_check | 否 | 表示是否开启重复消息检查，0表示否，1表示是，默认0
-- | -- | --
duplicate_check_interval | 否 | 表示是否重复消息检查的时间间隔，默认1800s，最大不超过4小时

**Comment by chenxiangweifeng** [comment]
> 请给出具体的文档

enable_duplicate_check | 否 | 表示是否开启重复消息检查，0表示否，1表示是，默认0
-- | -- | --
duplicate_check_interval | 否 | 表示是否重复消息检查的时间间隔，默认1800s，最大不超过4小时

 https://work.weixin.qq.com/api/doc/90000/90135/90236 发送应用消息接口

**Comment by binarywang** [comment]
看样子是新增加的字段。 
而且你要是不发文档，谁会想到你是说的这个接口。

**Comment by chenxiangweifeng** [comment]
> 看样子是新增加的字段。
> 而且你要是不发文档，谁会想到你是说的这个接口。

后续版本会考虑更新进去不？

**Comment by binarywang** [comment]
可能会考虑，但建议如果自己有研发能力，可以自行添加相关实现，并提交PR
