### ISSUE TITLE
能否实现公众号粉丝向顾问（导购助手）发消息的接口

### ISSUE THREAD

**Issue by pershow** [Wechat-Group/WxJava#1919]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/issues/1686  重复问题，如果有哪个接口特别急需，请在对应issue下回复
