### ISSUE TITLE
微信开放平台中的网站扫码登录功能如何实现

### ISSUE THREAD

**Issue by as365** [Wechat-Group/WxJava#1921]
### 简要描述
微信开放平台中的网站扫码登录功能如何实现，SDK包中没有找到对应的实现呢，望指教，谢谢

### 官方文档地址
https://developers.weixin.qq.com/doc/oplatform/Website_App/WeChat_Login/Wechat_Login.html

**Comment by binarywang** [comment]
看oauth2相关的类
