### ISSUE TITLE
查询订单最大分账比例

### ISSUE THREAD

**Issue by guicw** [Wechat-Group/WxJava#1922]
### 简要描述

腾讯最近开放了这个接口

### 官方文档地址

https://developers.weixin.qq.com/community/develop/doc/000e027713c6b049c47a50bb75c000

**Comment by guicw** [comment]
### API接口地址
https://pay.weixin.qq.com/wiki/doc/api/allocation_sl.php?chapter=25_11&index=8

**Comment by binarywang** [comment]
https://pay.weixin.qq.com/wiki/doc/api/allocation_sl.php?chapter=25_11&index=8
实际文档地址不是这个吗？

**Comment by guicw** [comment]
是的呢
