### ISSUE TITLE
如果一个项目中同时包含服务号和pc网站支持微信扫码登录

### ISSUE THREAD

**Issue by as365** [Wechat-Group/WxJava#1925]
### 简要描述
项目中想同时实现微信服务号功能和微信扫码登录网站功能，有两个不同的appid，请问如何整合初始化呢，谢谢，
程序在生成buildQrConnectUrl时，如何指定使用哪个appid呢？服务号的appid，和网站应用的appid时不能通用的，请问这个问题如何解决呢，谢谢

**Comment by binarywang** [comment]
直接用mp模块就行

**Comment by as365** [comment]
直接用mp模块没有问题，那这两个不同类型的appid如何指定初始化呢？全部配置在mp的配置文件里好像也不行，buildQrConnectUrl不对

**Comment by binarywang** [comment]
参考demo，配置成两个独立的账号

**Comment by as365** [comment]
> 参考demo，配置成两个独立的账号

您的意思是写两个配置文件初始化，还是把两个账号都当成公众号处理来初始化，那使用的时候如何指定使用哪个呢？

**Comment by binarywang** [comment]
> > 参考demo，配置成两个独立的账号
> 
> 您的意思是写两个配置文件初始化，还是把两个账号都当成公众号处理来初始化，那使用的时候如何指定使用哪个呢？

你看下demo项目就清楚了，配置写到一个文件里

**Comment by as365** [comment]
公众号的demo吗？没看到关于网站扫码登录的demo呢，

**Comment by binarywang** [comment]
> 公众号的demo吗？没看到关于网站扫码登录的demo呢，

你调用对应接口就是了，很简单的，找下oauth2相关的接口

**Comment by as365** [comment]
看过了 public String buildQrConnectUrl(String redirectUri, String scope, String state) {
    return String.format(QRCONNECT_URL.getUrl(this.getWxMpConfigStorage()), this.getWxMpConfigStorage().getAppId(),
      URIUtil.encodeURIComponent(redirectUri), scope, StringUtils.trimToEmpty(state));
  }就是上面这段代码，其中QRCONNECT_URL.getUrl(this.getWxMpConfigStorage()), this.getWxMpConfigStorage().getAppId()都是需要项目启动时初始化的，但是服务号和网站扫码的appid时不同的类型，请问如何初始化，及如何切换呢，你们的sdk中确实没有找到相关的文件或者配置说明，真心希望指导一下，谢谢

**Comment by as365** [comment]
配置文件的属性和格式也是不一样的，难道把这2个appid都初始化为公众号的来使用吗

**Comment by binarywang** [comment]
https://github.com/binarywang/weixin-java-mp-demo

你是否看过这个demo？

**Comment by as365** [comment]
看过了此demo了，但是这里的配置是针对公众号的，网站扫码登录的appid不属于公众号，下面这个配置也无法使用啊，我的公众号和网站扫码登录一共有2个appid，一个是公众平台的，一个是开放平台的，具体调用哪个，在程序sdk里是如何切换的，能指导一下吗？谢谢
wx:
  mp:
    useRedis: false
    redisConfig:
      host: 127.0.0.1
      port: 6379
    configs:
      - appId: 1111 # 第一个公众号的appid
        secret: 1111 # 公众号的appsecret
        token: 111 # 接口配置里的Token值
        aesKey: 111 # 接口配置里的EncodingAESKey值
      - appId: 2222 # 第二个公众号的appid，以下同上
        secret: 1111
        token: 111
        aesKey: 111

**Comment by as365** [comment]
比如我开发公众号功能时需要用到appid1（公众平台），但是网站扫码登录时需要用到appid2（开放平台），就是到了这里不知道代码如何切换了，看了你们的sdk封装，有些不明白这里的切换机制了，麻烦有时间指导一下，谢谢

**Comment by binarywang** [comment]
不用那么死脑筋吧，你把你的应用当作一个公众号即可。
至于如何切换，你参考controller里的代码。

**Comment by as365** [comment]
主要是这里return String.format(QRCONNECT_URL.getUrl(this.getWxMpConfigStorage()), this.getWxMpConfigStorage().getAppId(),，其中this.getWxMpConfigStorage().getAppId()就是获取当前使用的appid，但是由于能力有限，没有看出这个在那百年切换的谢谢

**Comment by binarywang** [comment]
如有进一步的问题，请到对应demo处讨论，谢谢
