### ISSUE TITLE
建议使用本地缓存框架

### ISSUE THREAD

**Issue by Arabira1** [Wechat-Group/WxJava#1926]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
你好，我现在看到在配置service时的default实现(cn.binarywang.wx.miniapp.config.impl.WxMaDefaultConfigImpl)
只有使用本地缓存,能否使用例如guava或者Caffeine这类的内存框架来做本地临时缓存呢？
### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by binarywang** [comment]
没必要，一般很少使用本地模式，都是采用的分布式存储，要么是数据库，要么是redis。
