### ISSUE TITLE
一个AppId，在不同的项目中，如何统一维护接口调用凭证

### ISSUE THREAD

**Issue by wison-j** [Wechat-Group/WxJava#1931]
对一个公众号开发，有移动端（多个）、中台（多个）、管理后端（多个）等等，这些项目是独立部署的（服务之间不可互相调用），如果分别引用weixin-java-mp的话，如果想要使用接口调用凭证调用微信方法，必然会独立刷新accesstoken(在微信文档中是有5分钟平滑过渡)，就是说一小时一个应用可以调用12次；如此计算n*12*24<2000次，n最大是6，如果超过6个项目，请问有什么方式能重写accessToken的方法，比如把accessToken放入数据库中，wxjava也能配置成从数据库读取accessToken,保证能一个公众号可以扩展更多应用而不超过accessToken调用上限呢？

**Comment by binarywang** [comment]
自己实现不同的config接口实现，保证其中一个应用允许刷新，其他应用仅允许获取
