### ISSUE TITLE
企业微信12月21日更新API新需求

### ISSUE THREAD

**Issue by zengguangping** [Wechat-Group/WxJava#1934]
### 企业微信API更新
(1) 内部/第三方 获取企业的全部群发记录API需求   官方地址  https://work.weixin.qq.com/api/doc/90000/90135/93338
(2) 企业内部开发获取手机号随机串需求  官方地址   https://work.weixin.qq.com/api/doc/90000/90135/92790
(3) 内部/第三方 群变更回调更新为3个回调  客户群创建事件 客户群变更事件 客户群解散事件 官方地址https://work.weixin.qq.com/api/doc/90000/90135/92130
(4) 内部/第三方 企业微信标签回调  
1.企业客户标签创建事件 官方地址https://work.weixin.qq.com/api/doc/90000/90135/92130#%E4%BC%81%E4%B8%9A%E5%AE%A2%E6%88%B7%E6%A0%87%E7%AD%BE%E5%88%9B%E5%BB%BA%E4%BA%8B%E4%BB%B6
2. 企业客户标签变更事件  官方地址 https://work.weixin.qq.com/api/doc/90000/90135/92130#%E4%BC%81%E4%B8%9A%E5%AE%A2%E6%88%B7%E6%A0%87%E7%AD%BE%E5%8F%98%E6%9B%B4%E4%BA%8B%E4%BB%B6
3. 企业客户标签删除事件  官方地址  https://work.weixin.qq.com/api/doc/90000/90135/92130#%E4%BC%81%E4%B8%9A%E5%AE%A2%E6%88%B7%E6%A0%87%E7%AD%BE%E5%88%A0%E9%99%A4%E4%BA%8B%E4%BB%B6
(5) 内部/第三方  获取客户朋友圈全部的发表记录需求 官方地址  https://work.weixin.qq.com/api/doc/90001/90143/93443

**Comment by binarywang** [comment]
谢谢楼主及时提醒，不过内容太多，建议分开提issue，分别跟踪实现
