### ISSUE TITLE
v3敏感信息加密未对list属性字段加密

### ISSUE THREAD

**Issue by HaiTao-G** [Wechat-Group/WxJava#1940]
### 简要描述
list属性没有加密

### 模块版本情况
* WxJava 模块名: wxjava-pay
* WxJava 版本号:4.0.0

### 详细描述
RsaCryptoUtil.encryptFields(request, validCertificate);这个方法是对v3的接口的敏感信息进行加密，如果加密的实体类属性字段有list的属性时，是没有加密的，现在加密的信息只有string字段和实体，应该增加反射对list字段的处理。

**Comment by binarywang** [comment]
如果有开发能力，欢迎自行实现代码，测试通过后直接提交PR
