### ISSUE TITLE
版本升级不兼容

### ISSUE THREAD

**Issue by jettwangcj** [Wechat-Group/WxJava#1941]
由于微信消息取消模板消息了，所以后面我们增加小程序订阅消息，因为我把 weixin-java-miniapp 模块版本从 3.4.0 升级到 4.0.0 
升级之后我发现 cn.binarywang.wx.miniapp.bean.WxMaTemplateMessage 这个类在4.0.0这个版本已经没有了，而我们很多消息暂时还是依赖模板消息的，我想请问这种情况我该怎么做？

**Comment by binarywang** [comment]
删掉相关代码， 因为已经废弃的接口本来也用不了了
