### ISSUE TITLE
代小程序业务中的代码管理----提交审核参数

### ISSUE THREAD

**Issue by BrighterAmmo** [Wechat-Group/WxJava#1944]
### 简要描述
提交审核时参数与微信文档的示例及描述有出入，且preview_info预览信息传入后会报错说微信解析xml格式出错，
47001 data format error

### 模块版本情况
* WxJava 模块名: weixin-java-open
* WxJava 版本号: 3.9.0 / 4.0.1.B （目前只用了这2版本）
类名 WxOpenMaSubmitAuditMessage
字段 List<WxOpenMaPreviewInfo> previewInfo

### 详细描述
经过一些简单的测试，大致确定previewInfo字段应该是单个对象WxOpenMaPreviewInfo，而不能是集合
微信文档
https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Mini_Programs/code/submit_audit.html

**Comment by binarywang** [comment]
看来是个很简单的问题，你其实可以直接提交PR了
