### ISSUE TITLE
企业微信接口权限不足问题

### ISSUE THREAD

**Issue by zengguangping** [Wechat-Group/WxJava#1945]
自建应用由于使用的是应用的Secret 有些接口会出现权限不足问题
需要使用客户的Secret  或者有些需要使用通讯录Secret 才有权限

我目前做法是提前替换了Secret 到内存中

            

            WxCpService selfWxCpService = corpInfoService.getSelfWxCpService(corpId);
            WxCpExternalContactService externalContactService = selfWxCpService.getExternalContactService();
            String[] stringTids = {tagId};
            WxCpConfigStorage wxCpConfigStorage = selfWxCpService.getWxCpConfigStorage();

            val configStorage = new WxCpDefaultConfigImpl();
            configStorage.setAgentId(wxCpConfigStorage.getAgentId());
            configStorage.setCorpId(wxCpConfigStorage.getCorpId());
            configStorage.setCorpSecret("orR7vxfOykHXF2yrhl8-li4YISPfIs8jj79JRgX2tJg");
            configStorage.setToken(Constants.WX_CP_TOKEN);
            configStorage.setAesKey(Constants.WX_CP_AES_KEY);
            selfWxCpService.setWxCpConfigStorage(configStorage);

            //删除标签
            externalContactService.delCorpTag(stringTids, null);

            selfWxCpService.setWxCpConfigStorage(wxCpConfigStorage);

**Comment by zhaoyuanlu** [comment]
这个问题应该是你accessToken没区分应用的问题，你可以下看下获取accessToken的实现，有没有把agentId加入token的存储里面。这个企业微信多应用的支持还不够好

**Comment by zainlu** [comment]
这个问题应该是你accessToken没区分应用的问题，你可以下看下获取accessToken的实现，有没有把agentId加入token的存储里面。这个企业微信多应用的支持还不够好
