### ISSUE TITLE
MP4.0版本调用所有接口都报{"errcode":72029,"errmsg":"invoice never set auth field hint: [hp.Rka0781e653]"}

### ISSUE THREAD

**Issue by metamorphosis-lu** [Wechat-Group/WxJava#1948]
### 简要描述
MP4.0版本调用所有接口都会去调用下面的这个接口报错。。。
https://api.weixin.qq.com/card/invoice/setbizattr?action=get_auth_field
都报{"errcode":72029,"errmsg":"invoice never set auth field hint: [hp.Rka0781e653]"}

### 模块版本情况
* WxJava 模块名: 4.0.0
* WxJava 版本号:4.0.0

### 详细描述
MP4.0版本调用所有接口都会去调用下面的这个接口报错。。。
https://api.weixin.qq.com/card/invoice/setbizattr?action=get_auth_field
都报{"errcode":72029,"errmsg":"invoice never set auth field hint: [hp.Rka0781e653]"}

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by binarywang** [comment]
你确定代码没问题？这个接口看起来像是发票的接口

**Comment by metamorphosis-lu** [comment]
我昨天也看着发票的接口，我这都没调用这个接口，现在是只要调用微信的接口都会去自动调用这个接口




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/WxJava"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 上午10:17
收件人:&nbsp;"Wechat-Group/WxJava"<WxJava@noreply.github.com&gt;;
抄送:&nbsp;"忘记"<285684890@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] MP4.0版本调用所有接口都报{"errcode":72029,"errmsg":"invoice never set auth field hint: [hp.Rka0781e653]"} (#1948)





 
你确定代码没问题？这个接口看起来像是发票的接口

**Comment by binarywang** [comment]
明显是你代码有问题，另外如果你觉得不放心，可以去尝试跑下单元测试中的代码，或者运行demo去验证下

**Comment by metamorphosis-lu** [comment]
好的，感谢，我这边再看看
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/WxJava"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 上午10:37
收件人:&nbsp;"Wechat-Group/WxJava"<WxJava@noreply.github.com&gt;;
抄送:&nbsp;"忘记"<285684890@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] MP4.0版本调用所有接口都报{"errcode":72029,"errmsg":"invoice never set auth field hint: [hp.Rka0781e653]"} (#1948)





 
明显是你代码有问题，另外如果你觉得不放心，可以去尝试跑下单元测试中的代码，或者运行demo去验证下
