### ISSUE TITLE
微信多公众号网页授权， appId获取问题

### ISSUE THREAD

**Issue by EliLiu-YF** [Wechat-Group/WxJava#1949]
请问在多公众号开发情况下，微信网页授权获取用户信息如何获取到当前公众号的 appId，

之前调用 mp包中的方法进行拼接 url发现内部得到的 apIId都是 properties配置文件中配置的多个微信信息的最后一条的 appId

**Comment by binarywang** [comment]
使用新版本还发现有此问题吗？如果有问题，请指出，也欢迎直接提供PR修复代码

**Comment by binarywang** [comment]
看你在gitee上的评论，还是不清楚你适合调用的，如果觉得有问题欢迎直接指出问题所在

**Comment by EliLiu-YF** [comment]
我是想在MsgHandler中根据当前公众号的appId去查找公众号的回复的关键字信息，但是现在就是不清楚如何获取当前公众号的appId

**Comment by binarywang** [comment]
handler里跟据message不能获取到发送方的id吗，那不就是appid吗？

**Comment by EliLiu-YF** [comment]
fromUserName好像是公众号的微信号，不是appId

**Comment by binarywang** [comment]
> fromUserName好像是公众号的微信号，不是appId

是吗，那可能是我记错了，通过service获取config，然后getappid，也不行吗？

**Comment by binarywang** [comment]
要么就是你没有switchover公众号，导致获取的是错误的帐号

**Comment by EliLiu-YF** [comment]
已解决，感谢感谢，
是公众号配置出了问题，一直没发现

**Comment by hbuxzy** [comment]
> 请问在多公众号开发情况下，微信网页授权获取用户信息如何获取到当前公众号的 appId，
> 
> 之前调用 mp包中的方法进行拼接 url发现内部得到的 apIId都是 properties配置文件中配置的多个微信信息的最后一条的 appId

请问在多公众号的情况下，你是怎么获取当前请求对应的AppId的？
