### ISSUE TITLE
企业微信更新通讯录里系统自动生成的人员userid时WxCpUser对象里没有new_userid字段

### ISSUE THREAD

**Issue by yezw1506** [Wechat-Group/WxJava#1953]
WxCpUser对象里没有new_userid字段，需要自己项目里创建包含new_userid字段的对象，能否把这个字段添加到WxCpUser对象里，谢谢！

### 官方文档地址
https://work.weixin.qq.com/api/doc/90000/90135/90197

**Comment by binarywang** [comment]
关了？

**Comment by yezw1506** [comment]
嗯嗯，需求较急，自己新建了个对象来完成功能需求，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/WxJava"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月31日(星期四) 下午4:11
收件人:&nbsp;"Wechat-Group/WxJava"<WxJava@noreply.github.com&gt;;
抄送:&nbsp;"叶智伟"<827862654@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] 企业微信更新通讯录里系统自动生成的人员userid时WxCpUser对象里没有new_userid字段 (#1953)





 
关了？

**Comment by binarywang** [comment]
那也不用关闭啊，你可以直接提交PR代码的

**Comment by binarywang** [comment]
请问楼主是加在哪里的？官方文档写得很模糊，只是简单的一句：`特别地，如果userid由系统自动生成，则仅允许修改一次。新值可由new_userid字段指定。`
可否自行提交经过测试有效的代码，PR上来？

**Comment by yezw1506** [comment]
没拉代码，我是在自己的项目里改的，下面这样加应该就可以
1、`WxCpUser`对象里加个`new_userid`字段
```
package me.chanjar.weixin.cp.bean;
...
public class WxCpUser implements Serializable {

    private static final long serialVersionUID = -5696099236344075582L;

    ...
    private String newUserId;
    ...
}
```
2、`WxCpUserGsonAdapter`对象里的`serialize`方法实现里添加`new_userid`属性
```
package me.chanjar.weixin.cp.util.json;
...
public class WxCpUserGsonAdapter implements JsonDeserializer<WxCpUser>, JsonSerializer<WxCpUser> {
    ...
    public JsonElement serialize(WxCpUser user, Type typeOfSrc, JsonSerializationContext context) {
        JsonObject o = new JsonObject();
        ...
        if (user.getNewUserId() != null) {
            o.addProperty("new_userid", user.getNewUserId());
        }
        ...
        return o;
    }

}
```
