### ISSUE TITLE
微信支付接口现在已经启用v3版了，请问微信支付接口这块有没有增加v3版下单接口的计划？

### ISSUE THREAD

**Issue by as365** [Wechat-Group/WxJava#1962]
### 简要描述
微信支付接口v3版下单接口api封装有没有计划增加，下单接口已经不推荐使用v2版的统一接口了

### 官方文档地址
https://pay.weixin.qq.com/wiki/doc/apiv3/index.shtml

**Comment by binarywang** [comment]
暂未有计划，如果有需求，建议自行实现，调试无误后可以提交PR
