### ISSUE TITLE
关于xstream单例使用问题

### ISSUE THREAD

**Issue by xxsheng** [Wechat-Group/WxJava#1963]
### 简要描述
me.chanjar.weixin.common.util.xml.XStreamInitializer#getInstance 请问这个方法构造xstream对象的时候是否能够使用单例，我阅读了xstream指南，说是可以使用单例，不清楚这里为何没有使用单例，有什么特别的原因吗？

### 模块版本情况
最新版本

**Comment by binarywang** [comment]
看下getInstance方法的使用场景，不就是相当于单例使用吗？
不要太纠结去使用经典的单例模式。
