### ISSUE TITLE
access_token有缓存吗？

### ISSUE THREAD

**Issue by zyw976532735** [Wechat-Group/WxJava#1964]
个人水平有限，跟了下代码，没有看到access_token缓存，是不是每次发送请求都会请求新的access_token?望指点一下

**Comment by binarywang** [comment]
看对应的configstorage实现，默认可以使用基于内存的缓存，当然还可以使用基于redis的

**Comment by zyw976532735** [comment]
@binarywang 非常感谢您的回复，就是希望走内存缓存，那我就放心了，我怕没有缓存造成一些问题。我看看configstorage实现，再次感谢
