### ISSUE TITLE
小程序刷新AssessToken的默认分布式锁实现jedis-lock并发场景下存在严重性能问题

### ISSUE THREAD

**Issue by ctck1995** [Wechat-Group/WxJava#1966]
### 简要描述
jedis-lock中的acquire()和release()均实现了synchronized对象锁，并发场景下刷新accessToken导致一个线程获取不到对象锁从而无法unlock()，另一个线程无法lock()导致一直占用对象锁，最终并发接口的响应时间都大于获取分布式锁的超时时间

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号: 3.7.0

### 日志
![QQ截图20210113112020](https://user-images.githubusercontent.com/31645728/104402709-df4e4680-5591-11eb-8d73-a7b09430fb71.png)
![QQ截图20210113112227](https://user-images.githubusercontent.com/31645728/104402717-e2493700-5591-11eb-9ea2-bcefb9f08717.png)

**Comment by ctck1995** [comment]
更新版本使用redisson的实现或自行实现

**Comment by binarywang** [comment]
jedis-lock组件确实比较老 ，长时间没维护，不建议使用

**Comment by wangjia2016** [comment]
> 更新版本使用redisson的实现或自行实现

哪个版本用了redisson的实现啊

**Comment by ctck1995** [comment]
> > 更新版本使用redisson的实现或自行实现
> 
> 哪个版本用了redisson的实现啊

3.8.0就有，我是直接升到了3.9.0

**Comment by wangjia2016** [comment]
> > > 更新版本使用redisson的实现或自行实现
> > 
> > 
> > 哪个版本用了redisson的实现啊
> 
> 3.8.0就有，我是直接升到了3.9.0

我用的是3.9.4.B的版本，默认的实现还是是用的jedis-lock

**Comment by binarywang** [comment]
你看到的默认的，只是你之前用的吧，并不是一定是合适的，你自己更换新的实现即可
