### ISSUE TITLE
微信支付有支持类似于微信公众号的switchover方法来切换不同的商户号

### ISSUE THREAD

**Issue by qeprwjcgya** [Wechat-Group/WxJava#1968]

**Comment by binarywang** [comment]
暂时没有

**Comment by qeprwjcgya** [comment]
后面版本会提供吗？如果提供,就暂时不封装了.也是临时想到多商户号切换


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/WxJava"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月13日(星期三) 下午5:31
收件人:&nbsp;"Wechat-Group/WxJava"<WxJava@noreply.github.com&gt;;
抄送:&nbsp;"_Bean.Woo"<158921300@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] 微信支付有支持类似于微信公众号的switchover方法来切换不同的商户号 (#1968)





 
暂时没有

**Comment by binarywang** [comment]
暂时没时间，如果你有兴趣和时间，欢迎自行实现，如果觉得代码对其他人有帮助，也非常欢迎你提交PR
