### ISSUE TITLE
企业微信第三方应用获取登录用户信息接口的方法里的令牌获取错误

### ISSUE THREAD

**Issue by tanyun1111** [Wechat-Group/WxJava#1969]
public WxTpLoginInfo getLoginInfo(String authCode) throws WxErrorException {
    JsonObject jsonObject = new JsonObject();
    jsonObject.addProperty("auth_code", authCode);
    jsonObject.addProperty("access_token", configStorage.getAccessToken(authCode));
    String responseText = post(configStorage.getApiUrl(GET_LOGIN_INFO), jsonObject.toString());
    return WxTpLoginInfo.fromJson(responseText);
  }

 jsonObject.addProperty("access_token", configStorage.getAccessToken(authCode));
这行的获取令牌应该是
 jsonObject.addProperty("access_token", configStorage.getProviderAccessToken());

**Comment by binarywang** [comment]
欢迎直接提交PR
