### ISSUE TITLE
wx-java-miniapp-spring-boot-starter生产环境无法启动

### ISSUE THREAD

**Issue by zhww9206** [Wechat-Group/WxJava#1973]
### 简要描述
依赖wx-java-miniapp-spring-boot-starter，打包后无法启动

### 模块版本情况
* WxJava wx-java-miniapp-spring-boot-starter: 
* WxJava 版本号: 4.0.0

### 详细描述
项目依赖：SpringCloud Alibaba 2.2.3.RELEASE + SpringCloud Hoxton.SR8
 + spring boot 2.3.3.RELEASE

依赖wx-java-miniapp-spring-boot-starter，打包后无法启动。
在idea中可以正常启动，打包后无法启动
java.lang.IllegalStateException: Error processing condition on com.binarywang.spring.starter.wxjava.miniapp.config.WxMaAutoConfiguration.wxMaConfig

配置文件：
![image](https://user-images.githubusercontent.com/16043021/104818104-73edc880-5860-11eb-8704-d14d7e3191a4.png)

![image](https://user-images.githubusercontent.com/16043021/104818120-8c5de300-5860-11eb-9102-3b7c399cd755.png)
![image](https://user-images.githubusercontent.com/16043021/104818136-9bdd2c00-5860-11eb-9034-93ffbf6fb2a1.png)

idea正常启动：
![image](https://user-images.githubusercontent.com/16043021/104818182-f4142e00-5860-11eb-8bf8-dd2f90535be7.png)
生产环境启动异常：
![image](https://user-images.githubusercontent.com/16043021/104818199-13ab5680-5861-11eb-9720-147122a0e4ec.png)

### 日志
https://paste.ubuntu.com/p/Vw8J7nyQ2S/

**Comment by binarywang** [comment]
错误信息是如此的明确：
```
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/pool2/impl/GenericObjectPoolConfig
```

**Comment by binarywang** [comment]
建议参考下 https://github.com/binarywang/wx-java-miniapp-demo 这个demo

**Comment by tangmingze7280** [comment]
打包后 才报错  就很奇怪
