### ISSUE TITLE
企业付款功能，返回接口字段未映射，怀疑微信api设计问题

### ISSUE THREAD

**Issue by ztgoto** [Wechat-Group/WxJava#1975]
### 简要描述
企业付款失败和成功返回字段不一致，有字段在文档中也没有描述

### 模块版本情况
* WxJava 模块名:  weixin-java-pay
* WxJava 版本号: 4.0.0

### 详细描述
企业付款接口
https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_2
成功返回
```
<return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[]]></return_msg>
......
```
失败返回
```
<return_code><![CDATA[FAIL]]></return_code>
<retmsg><![CDATA[请确认请求参数是否正确param mch_id invalid]]></retmsg>
<retcode><![CDATA[1]]></retcode>
```
retmsg retcode 并未映射，官方文档也没有描述，导致现有的EntPayResult WxPayException 取不到错误描述

**Comment by binarywang** [comment]
欢迎直接提交PR
