### ISSUE TITLE
关于公众号（mp）管理员扫开放平台(open)授权二维码，然后通过开放平台调用公众号接口的问题

### ISSUE THREAD

**Issue by kkkangke** [Wechat-Group/WxJava#1977]
第三方开放平台和公众号结合使用，由于是用户扫码授权的公众号，open模块只能拿到appid，拿不到公众号的secret等参数。那么AccessToken.getAccessToken()获取access_token会出错。请问一下通过开放平台调用公众号接口需要做哪些修改？

**Comment by chrissun951** [comment]
为什么没有留下解决办法就close了呀
