### ISSUE TITLE
新增putV3、deleteV3方法

### ISSUE THREAD

**Issue by weitangli** [Wechat-Group/WxJava#1980]
### 简要描述
微信支付API v3是遵循RESTful风格设计的HTTP API。

当执行修改和删除操作时，需要使用put和delete方式。

### 官方文档地址

修改操作: https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/tool/merchant-service/chapter3_4.shtml

删除操作: https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/tool/merchant-service/chapter3_5.shtml

**Comment by binarywang** [comment]
欢迎直接提供PR代码
