### ISSUE TITLE
微信公众号/服务号新增订阅通知接口，模板消息即将下架

### ISSUE THREAD

**Issue by NBTim** [Wechat-Group/WxJava#1983]
### 简要描述
微信官方为向小程序靠拢，微信公众号/服务号的模板消息也将下架，新上架的订阅通知接口正在灰度测试。
网传可能微信公众号/服务号的模板消息可能与2021-04-30下线
https://mp.weixin.qq.com/s/AmbTo_B3GUCu5NIxRc908A
### 官方文档地址
https://developers.weixin.qq.com/doc/offiaccount/Subscription_Messages/api.html

**Comment by wuyachao** [comment]
功能还在开发，突然模板消息没了

**Comment by branchen** [comment]
这个框架会支持 新增的订阅通知接口吗

**Comment by NBTim** [comment]
@branchen 是新增的订阅通知接口

**Comment by xiaoguolong** [comment]
![image](https://user-images.githubusercontent.com/33684988/106232702-981db200-622f-11eb-9ac5-ae5a657a92ba.png)
这个框架会开发发送订阅消息功能吗

**Comment by binarywang** [comment]
会尽快支持的

**Comment by binarywang** [comment]
最新版本4.0.4.B已增加

**Comment by code33** [comment]
很多时候订阅通知拿来做关键的业务消息推送的,如果微信不支持的化.就得想其它办法了
