### ISSUE TITLE
微信支付商户号分账接口功能不完善

### ISSUE THREAD

**Issue by tianxiajiangshan** [Wechat-Group/WxJava#1984]
你好，分账功能中查询订单待分账金额，完结订单，分账动账通知接口暂时还没有，3.6上线分账到4.0发布，依然还没有加，建议及时加上，谢谢

**Comment by binarywang** [comment]
如果有需要建议先自己实现，并提交PR，如果你有账号，其实实现起来还是很简单的

**Comment by tianxiajiangshan** [comment]
> 如果有需要建议先自己实现，并提交PR，如果你有账号，其实实现起来还是很简单的

你好，自行已实现，只是建议更新版本的时候加上，要不然总感觉调api接口的时候有自己写一套单独的调用微信

**Comment by binarywang** [comment]
> > 如果有需要建议先自己实现，并提交PR，如果你有账号，其实实现起来还是很简单的
> 
> 你好，自行已实现，只是建议更新版本的时候加上，要不然总感觉调api接口的时候有自己写一套单独的调用微信

欢迎有空的时候提交PR
