### ISSUE TITLE
企业微信机器人webhookUrl地址问题

### ISSUE THREAD

**Issue by adogcode** [Wechat-Group/WxJava#1985]
### 简要描述
企业微信机器人webhookUrl地址无法在调用接口中设置，WxCpGroupRobotServiceImpl

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号:4.0.0

### 详细描述
  @Override
  public void sendNews(String webhookUrl, List<NewArticle> articleList) throws WxErrorException {
    this.cpService.postWithoutToken(this.getWebhookUrl(), new WxCpGroupRobotMessage()
      .setMsgType(GroupRobotMsgType.NEWS)
      .setArticles(articleList).toJson());
  }
### 日志
无法在接口中设置url地址：
![image](https://user-images.githubusercontent.com/9071923/106405706-1b2e4a80-6472-11eb-9db5-3cff6ee8ecbd.png)

**Comment by adogcode** [comment]
另外咨询下，如果我想用机器人发送一个不带picurl的news消息应该怎么处理？picurl设置为null的话不行。

**Comment by binarywang** [comment]
顶楼提到的确实是疏忽导致，会稍后修复的


> 另外咨询下，如果我想用机器人发送一个不带picurl的news消息应该怎么处理？picurl设置为null的话不行。


不行的意思是什么？
