### ISSUE TITLE
微信公众号订阅通知功能，是否有开发计划

### ISSUE THREAD

**Issue by BendyXu** [Wechat-Group/WxJava#1986]
如题，谢谢，现在在纠结自己写这部分功能。

**Comment by binarywang** [comment]
最新测试版本已加入，请注意关注公众号，及时查看版本发布记录

**Comment by jtMook** [comment]
测试用例怎么在哪，我拉下来发现sendSubscribeMsg这个方法没用过

**Comment by binarywang** [comment]
你看的是小程序的吧，注意别看错代码了，另外注意版本要一致。
另外方法如何使用，自己构建请求对象，参考对应字段注释填写即可，如果还有问题，看下官方文档就行了。

> 测试用例怎么在哪，我拉下来发现sendSubscribeMsg这个方法没用过
