### ISSUE TITLE
企业微信第三方应用获取授权方的access_token问题

### ISSUE THREAD

**Issue by kkkangke** [Wechat-Group/WxJava#1988]
在授权方获取token时
 @Override
  public String getAccessToken(boolean forceRefresh) throws WxErrorException {
    if (!this.configStorage.isAccessTokenExpired() && !forceRefresh) {
      return this.configStorage.getAccessToken();
    }
    //access token通过第三方应用service获取
    //corpSecret对应企业永久授权码
    WxAccessToken accessToken = wxCpTpService.getCorpToken(this.configStorage.getCorpId(), this.configStorage.getCorpSecret());

    this.configStorage.updateAccessToken(accessToken.getAccessToken(), accessToken.getExpiresIn());
    return this.configStorage.getAccessToken();
  }
永久授权码应该是permanent_code，这里用了CorpSecret，和官方文档不符合

**Comment by binarywang** [comment]
如果觉得有问题，欢迎直接修改，调试没问题后直接提交PR即可

**Comment by zhanp0304** [comment]
我自己初始化的时候设置了永久授权码传入corpSecret这里。可以参考一下~~
// corpSecret要设置永久授权码(从数据库里读）
String permanentCode = wechatCache.getPermanentCode(corpId, agentId, "", tpService.getWxCpTpConfigStorage().getSuiteId());
config.setCorpSecret(permanentCode);
cpService.setWxCpConfigStorage(config);

**Comment by yangtiao** [comment]
> 我自己初始化的时候设置了永久授权码传入corpSecret这里。可以参考一下~~
> // corpSecret要设置永久授权码(从数据库里读）
> String permanentCode = wechatCache.getPermanentCode(corpId, agentId, "", tpService.getWxCpTpConfigStorage().getSuiteId());
> config.setCorpSecret(permanentCode);
> cpService.setWxCpConfigStorage(config);

它这里的configStorage是企业微信的，不是第三方应用的呀，那你岂不是每一个授权企业都要去set一次configStorage？

**Comment by zhanp0304** [comment]
@yangtiao 我自己设计的是这样的：每个企业一个WxCpService，所以每一个授权企业都初始化set一次configStorage应该是没有问题的.

**Comment by Jc826** [comment]
官方上明确说明了，服务商 获取了 企业的授权后拿到了 企业ID 和 应用Secret 就用自建应用的API去获取accessToken 然后完成相应的api调用，所以我这里和[zhanp0304](https://github.com/zhanp0304) 处理方式一样的
