### ISSUE TITLE
createTmpFile这个创建的临时文件夹能加个删除吗

### ISSUE THREAD

**Issue by gap1994** [Wechat-Group/WxJava#1989]
现在服务器堆了好多这种临时文件夹

**Comment by binarywang** [comment]
临时文件夹是放在系统临时目录下的，按说是系统会自动去处理的，除非你自己关闭了相关配置

**Comment by gap1994** [comment]
我也不知道为啥，那些空文件夹就放在tomcat的temp文件夹下，都好久了，我服务器是winserver的

**Comment by binarywang** [comment]
请自行处理，使用代码或者借助工具
