### ISSUE TITLE
企业微信第三方应用suite_ticket在redis中的缓存时间不应该为10分钟，应该设置为30分钟

### ISSUE THREAD

**Issue by zhanp0304** [Wechat-Group/WxJava#1990]
### 简要描述
__简单概括描述下你所遇到的问题。__
1. 企业微信第三方应用suite_ticket在redis中的缓存时间不应该为10分钟，应该设置为30分钟。
2. 根据文档描述：有效期为三十分钟，并且能容忍2次的失败。
3. 我亲自测试过了，在快过期前延长时间，并且停掉服务不接收suite_ticket。然后再打开，用旧的suite_ticket依然有效，可获取
suite_access_token。
4.为什么不能设置为10分钟？我的个人理解是：如果我在10分钟快过期的时候，停掉了服务（更新服务），下次再打开，Redis里面就没了，而且也没有做suite_ticket的持久化，所以我认为应该设置为30分钟。预防这种情况。
5.私以为企业微信更新他那边服务器的suite_ticket的依据是【我成功响应suite_ticket事件，返回"success"】或者【连续超过两次没有响应则判断为失效】

### 模块版本情况
* WxJava 模块名:  cp/tp模块 企业微信第三方应用
* WxJava 版本号: 4.0.0

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__
![image](https://user-images.githubusercontent.com/38825329/106578517-8bc08e80-657a-11eb-8600-048346427685.png)

**Comment by binarywang** [comment]
建议直接修改代码，测试通过后直接提交PR

**Comment by binarywang** [comment]
无回复，暂时关闭
