### ISSUE TITLE
自定义token

### ISSUE THREAD

**Issue by Kirno7** [Wechat-Group/WxJava#1992]
我们公司自定义了获取微信的token接口,openId和密钥我们不知道,请问这种情况该怎么使用WxJava

**Comment by binarywang** [comment]
看过此方法吗？
`me.chanjar.weixin.mp.api.impl.WxMpServiceHttpClientImpl#getAccessToken`

看懂前几行代码 就知道该怎么做了

**Comment by binarywang** [comment]
提示更明确些的话：
```
    final WxMpConfigStorage config = this.getWxMpConfigStorage();
    if (!config.isAccessTokenExpired() && !forceRefresh) {
      return config.getAccessToken();
    }
```
也就是你自己编写 `WxMpConfigStorage` 的 实现类，保证 `isAccessTokenExpired()`方法 返回 `false`，并且让 `getAccessToken()`方法返回你想要的东西。
