### ISSUE TITLE
【公众号】公众号的订阅通知有计划跟进吗

### ISSUE THREAD

**Issue by benzfungus** [Wechat-Group/WxJava#1993]
### 简要描述
公众号模板消息和一次性订阅消息要换成订阅通知，有计划什么时候更新订阅通知的功能吗

### 官方文档地址
https://developers.weixin.qq.com/doc/offiaccount/Subscription_Messages/intro.html
https://developers.weixin.qq.com/community/minihome/doc/000a4e1df800d82acb9b7fb5e5b001

**Comment by binarywang** [comment]
请注意关注公众号版本日志通知，已经发布了最新的测试版了
