### ISSUE TITLE
WxCpGroupRobotServiceImpl.sendImage  webhookUrl 赋值无效

### ISSUE THREAD

**Issue by xujoy** [Wechat-Group/WxJava#1994]
me.chanjar.weixin.cp.api.impl.WxCpGroupRobotServiceImpl 类

  @Override
  public void sendImage(**String webhookUrl**, String base64, String md5) throws WxErrorException {
    this.cpService.postWithoutToken(**this.getWebhookUrl()**, new WxCpGroupRobotMessage()
      .setMsgType(GroupRobotMsgType.IMAGE)
      .setBase64(base64)
      .setMd5(md5).toJson());
  }

参数 webhookUrl 没有使用，实际使用的this.getWebhookUrl()

**Comment by xujoy** [comment]
cp 模块。4.0.0版本

**Comment by binarywang** [comment]
重复 https://github.com/Wechat-Group/WxJava/issues/1985
请关注近期即将发布的新版本
