### ISSUE TITLE
CharMatcher.whitespace() 方法不存在？

### ISSUE THREAD

**Issue by wangchangkang** [Wechat-Group/WxJava#1999]
![image](https://user-images.githubusercontent.com/32864125/107324603-502a4500-6ae3-11eb-9de9-96b7c6d07362.png)

**Comment by binarywang** [comment]
你这个问题明显是jar包冲突导致版本不一致，建议看下wiki常见问题

**Comment by CodeGather** [comment]
https://github.com/Wechat-Group/WxJava/issues/2369  你可以看看这个方案
