### ISSUE TITLE
使用模板消息，微信收到没有格式化

### ISSUE THREAD

**Issue by kmath163** [Wechat-Group/WxJava#2001]
WxMpTemplateMessage wxMpTemplateMessage = new WxMpTemplateMessage();
        wxMpTemplateMessage.setTemplateId(template_id);
        wxMpTemplateMessage.setToUser(openId);
        wxMpTemplateMessage.setUrl(url);
        wxMpTemplateMessage.setData(templateDataList);
       wxMpService.switchoverTo(appId).getTemplateMsgService().sendTemplateMsg(wxMpTemplateMessage);
       微信接收到消息内容没有进行格式化；
       https://user-images.githubusercontent.com/8296005/108326512-4ac8ab00-7205-11eb-8108-42de9b4ba4be.jpg

**Comment by binarywang** [comment]
看起来像是微信自己的bug
