### ISSUE TITLE
企业微信 如何获取access_token ，需要考虑过期的期限么

### ISSUE THREAD

**Issue by steadyliu** [Wechat-Group/WxJava#2009]
在用cp模块，需要自己取请求获取access_token然后记录期限进行判断来处理access_token么。我是在做扫码登录，还有就是我通过js的方式拉取二维码，扫描后能够获取到code。我能够直接用WxCpOauth2UserInfo userInfo = wxCpService.getOauth2Service().getUserInfo(code);获取到userId。为何我用这个方式`WxCpUser cpUser = this.wxCpService.getUserService().getById(userId);`就获取不到Wxcpuser呢。

**Comment by tingyugetc520** [comment]
不需要，sdk里面已经处理了access token的过期刷新问题
