### ISSUE TITLE
有企业微信第三方应用 部门 相关的api 吗 

### ISSUE THREAD

**Issue by Bleoo** [Wechat-Group/WxJava#2011]
### 简要描述
对企业微信 的 部门操作，用 WxCpDepartmentServiceImpl ，那企业微信第三方应用的 部门操作 ，有 api 吗？ 好像 没有 WxCpTpDepartmentServiceImpl 类

### 官方文档地址
https://open.work.weixin.qq.com/api/doc/90001/90143/90344

**Comment by tingyugetc520** [comment]
接口地址是一样的呀，可以直接拿过来用

**Comment by tingyugetc520** [comment]
是不是第三方应用企业微信会自己判断的

**Comment by Bleoo** [comment]
只能每次都new 一个新 WxCpTpService 来调用吗？ 相似问题 #1876

**Comment by tingyugetc520** [comment]
[me.chanjar.weixin.cp.tp.service.impl.WxCpTpDepartmentServiceImpl](https://github.com/Wechat-Group/WxJava/blob/develop/weixin-java-cp/src/main/java/me/chanjar/weixin/cp/tp/service/impl/WxCpTpDepartmentServiceImpl.java)
有这个的

**Comment by Bleoo** [comment]
嗯，看到新版本有这个类了。但是很多问题。
1 该使用缓存的 accessToken 的地方很多都是直接去微信获取的
2 还有 很多 直接去缓存拿不考虑过期后 null 的

**Comment by binarywang** [comment]
> 嗯，看到新版本有这个类了。但是很多问题。
> 1 该使用缓存的 accessToken 的地方很多都是直接去微信获取的
> 2 还有 很多 直接去缓存拿不考虑过期后 null 的

具体是什么问题，欢迎直接提交PR进行修复

**Comment by tingyugetc520** [comment]
> 嗯，看到新版本有这个类了。但是很多问题。
> 1 该使用缓存的 accessToken 的地方很多都是直接去微信获取的
> 2 还有 很多 直接去缓存拿不考虑过期后 null 的

你说的这几个问题没有呀，accessToken是从缓存拿的，并且也判断了是否过期，你说的具体是哪些呢

**Comment by Bleoo** [comment]
简单说一个地方：
https://github.com/Wechat-Group/WxJava/blob/e46c6c1995450e958f7f199f1018f90304e10814/weixin-java-cp/src/main/java/me/chanjar/weixin/cp/tp/service/impl/WxCpTpUserServiceImpl.java#L71
这里的 getAccessToken() 实现如果是 https://github.com/Wechat-Group/WxJava/blob/e46c6c1995450e958f7f199f1018f90304e10814/weixin-java-cp/src/main/java/me/chanjar/weixin/cp/config/impl/WxCpRedissonConfigImpl.java

那么它的实现是直接去 redis 中拿的，如果过期了就是 null，并不判断过期后去微信api重新获取
https://github.com/Wechat-Group/WxJava/blob/e46c6c1995450e958f7f199f1018f90304e10814/weixin-java-cp/src/main/java/me/chanjar/weixin/cp/config/impl/WxCpRedissonConfigImpl.java#L88

**Comment by Bleoo** [comment]
这种直接去 redis 里面拿的 问题 修复了吗？

**Comment by binarywang** [comment]
> 这种直接去 redis 里面拿的 问题 修复了吗？

基于标题所说问题的讨论已结束，暂时关闭。

至于你提到的新问题，如果你已知道如何修复，建议直接提交PR来解决，否则就请单独提issue。
