### ISSUE TITLE
 SEND_SUBSCRIBE_MESSAGE_URL("https://api.weixin.qq.com", "/cgi-bin/message/subscribe/bizsend"),

### ISSUE THREAD

**Issue by en-o** [Wechat-Group/WxJava#2014]
### 简要描述
发送订阅消息调用地址有问题
 SEND_SUBSCRIBE_MESSAGE_URL("https://api.weixin.qq.com", "/cgi-bin/message/subscribe/bizsend"),

### 模块版本情况
* WxJava 模块名:  weixin-java-mp
* WxJava 版本号:  4.0.5.B

### 详细描述
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/subscribe-message/subscribeMessage.send.html
官方文档中接口名为： send
你的的enum中写的是：bizsend

### 日志
【请求地址】: https://api.weixin.qq.com/cgi-bin/message/subscribe/bizsend?access_token=
【请求参数】：{"touser"
【错误信息】：错误代码：48001, 错误信息：api 功能未授权，请确认公众号已获得该接口，可以在公众平台官网 - 开发者中心页中查看接口权限，微信原始报文：{"errcode":48001,"errmsg":"api unauthorized rid: 60376992-721dd380-5461afa4"}
me.chanjar.weixin.common.error.WxErrorException: 错误代码：48001, 错误信息：api 功能未授权，请确认公众号已获得该接口，可以在公众平台官网 -

**Comment by binarywang** [comment]
https://developers.weixin.qq.com/doc/offiaccount/Subscription_Messages/api.html#send%E5%8F%91%E9%80%81%E8%AE%A2%E9%98%85%E9%80%9A%E7%9F%A5

你到底是要用小程序，还是公众号？

确定看的是正确的文档？或者是调用的不是正确的接口？
