### ISSUE TITLE
引用第三方平台sdk4.0.0版本中工具类FileUtils的createTmpFile创建临时文件方法问题

### ISSUE THREAD

**Issue by hub-chen** [Wechat-Group/WxJava#2019]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: weixin-java-open
* WxJava 版本号: 4.0.0

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__
微信第三方开放平台

调用获取小程序体验版二维码接口：https://api.weixin.qq.com/wxa/get_qrcode
进行转换图片时图片访问不到，创建临时文件后又把文件给删除了，查看代码发现是被删除了，辛苦看看是不是这样的。
![image](https://user-images.githubusercontent.com/74441129/109462902-24c1c700-7a9f-11eb-916c-b6c588903b3b.png)

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by hub-chen** [comment]
已debug进行排除，发现就是这段删除的文件的问题导致的，麻烦辛苦查看一下

**Comment by hub-chen** [comment]
close

**Comment by binarywang** [comment]
这个是临时生成的文件，建议自行存储到自己专有的文件系统进行保存
