### ISSUE TITLE
获取图文群发总数据（getarticletotal）接口   缺少参数url 能否加上

### ISSUE THREAD

**Issue by hairtil** [Wechat-Group/WxJava#2028]
图文分析数据接口
https://developers.weixin.qq.com/doc/offiaccount/Analytics/Graphic_Analysis_Data_Interface.html
其中获取图文群发总数据（getarticletotal）接口
https://api.weixin.qq.com/datacube/getarticletotal?access_token=ACCESS_TOKEN
{
	"list": [{
			"ref_date": "2021-02-22",
			"msgid": "2247483654_1",
			"title": "标题",
			"user_source": 0,
			"details": [{	}],
"url": "文章地址" //此处有返回文章地址参数
		}
	}]
}
接口用WxDataCubeArticleTotalDetail这个类接收返回，但是没有url这个参数来接收返回的结果，能否加上此参数。

**Comment by binarywang** [comment]
建议直接提交PR

**Comment by binarywang** [comment]
> 接口用WxDataCubeArticleTotalDetail这个类接收返回，但是没有url这个参数来接收返回的结果，能否加上此参数。

说错了吧，应该是这个类： `WxDataCubeArticleTotal`
