### ISSUE TITLE
JedisDistributedLock 可能引起死锁问题

### ISSUE THREAD

**Issue by yungaoxing** [Wechat-Group/WxJava#2029]
* WxJava 模块名:  me.chanjar.weixin.common.util.locks.JedisDistributedLock 
* WxJava 版本号:3.5.8.B

### 详细描述
代码： try (Jedis jedis = jedisPool.getResource()) {
      if (!lock.acquire(jedis)) {
        throw new WxRuntimeException("acquire timeouted");
      }
    } catch (InterruptedException e) {
      throw new WxRuntimeException("lock failed", e);
    }
  }

 @Override
  public void unlock() {
    try (Jedis jedis = jedisPool.getResource()) {
      lock.release(jedis);
    }
  }

两个方法都使用了自动释放资源功能  try (Jedis jedis = jedisPool.getResource()) ，当一个线程获取链接对资源进行加锁之后此时进行了redis链接释放回收。如果链接池中的资源都被其他想要获取锁权限的线程获取到，并持有（即使超时释放也可能被新线程获取）将可能一直等待加锁线程进行释放。这时此线程将无法获取链接资源执行释放锁。造成锁死 只能等待一分钟超时。会有大量请求阻塞，造成死锁。
### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by binarywang** [comment]
这个用到了JedisLock过期组件，不建议使用，可更换其他组件

**Comment by yungaoxing** [comment]
OK 谢谢

**Comment by JimmyLincole** [comment]
@yungaoxing 
哥们，请问一下，你是如何优雅解决这问题呀？谢谢

**Comment by jacobwwang** [comment]
@yungaoxing 
哥们，请问一下，你是如何优雅解决这问题呀？谢谢

我的项目依赖的是 jedis2.x，用的集团框架，无法升级 jedis，因此只能使用 WxJava3.8.0，无法使用 WxMpRedissonConfigImpl。
一时半会找不到好的解决办法。

**Comment by clickear** [comment]
> @yungaoxing 哥们，请问一下，你是如何优雅解决这问题呀？谢谢
> 
> 我的项目依赖的是 jedis2.x，用的集团框架，无法升级 jedis，因此只能使用 WxJava3.8.0，无法使用 WxMpRedissonConfigImpl。 一时半会找不到好的解决办法。

有个思路，可以在JedisDistributedLock的lock方法加上 synchronized。这样就可以保证同一时刻只有1个线程进行lock操作，也就不会有太多线程进行getResource操作。
  ``` java
@Override
  public synchronized void lock() {
    try (Jedis jedis = jedisPool.getResource()) {
      if (!lock.acquire(jedis)) {
        throw new RuntimeException("acquire timeouted");
      }
    } catch (InterruptedException e) {
      throw new RuntimeException("lock failed", e);
    }
  }```
