### ISSUE TITLE
微信第三方平台 使用版本weixin-java-open：4.0.0，小程序订阅消息设置缺少发送订阅消息接口，望辛苦实现

### ISSUE THREAD

**Issue by hub-chen** [Wechat-Group/WxJava#2039]
微信第三方平台 使用版本weixin-java-open：4.0.0，小程序订阅消息设置缺少发送订阅消息接口，望辛苦实现

文档地址：https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Mini_Programs/subscribe_template/subscribeMessage.send.html

**Comment by binarywang** [comment]
在消息管理相关类里，你搜索接口地址就能找到了

**Comment by hub-chen** [comment]
你好 我是已经搜索过了 订阅消息的其他接口是有的 唯独缺少了这个发送的接口。



------------------------------------------------------------------
发件人：Binary Wang ***@***.***>
发送时间：2021年3月15日(星期一) 11:08
收件人：Wechat-Group/WxJava ***@***.***>
抄　送：陈荣 ***@***.***>; Author ***@***.***>
主　题：Re: [Wechat-Group/WxJava] 微信第三方平台 使用版本weixin-java-open：4.0.0，小程序订阅消息设置缺少发送订阅消息接口，望辛苦实现 (#2039)

在消息管理相关类里，你搜索接口地址就能找到了

**Comment by binarywang** [comment]
确定搜索过？https://github.com/Wechat-Group/WxJava/search?q=message%2Fsubscribe%2Fsend

**Comment by hub-chen** [comment]
这个不是weixin-java-miniapp里面的么 ,
我用的是weixin-java-open：4.0.0


------------------------------------------------------------------
发件人：Binary Wang ***@***.***>
发送时间：2021年3月15日(星期一) 11:21
收件人：Wechat-Group/WxJava ***@***.***>
抄　送：陈荣 ***@***.***>; Author ***@***.***>
主　题：Re: [Wechat-Group/WxJava] 微信第三方平台 使用版本weixin-java-open：4.0.0，小程序订阅消息设置缺少发送订阅消息接口，望辛苦实现 (#2039)

确定搜索过？https://github.com/Wechat-Group/WxJava/search?q=message%2Fsubscribe%2Fsend

**Comment by hub-chen** [comment]
我错了。。 原来放到消息发送这边了 sorry，我以为是在消息订阅那个实现一起的。


------------------------------------------------------------------
发件人：Binary Wang ***@***.***>
发送时间：2021年3月15日(星期一) 11:21
收件人：Wechat-Group/WxJava ***@***.***>
抄　送：陈荣 ***@***.***>; Author ***@***.***>
主　题：Re: [Wechat-Group/WxJava] 微信第三方平台 使用版本weixin-java-open：4.0.0，小程序订阅消息设置缺少发送订阅消息接口，望辛苦实现 (#2039)

确定搜索过？https://github.com/Wechat-Group/WxJava/search?q=message%2Fsubscribe%2Fsend
