### ISSUE TITLE
小程序直播间创建接口响应参数封装不太合理

### ISSUE THREAD

**Issue by onlyonezhongjinhui** [Wechat-Group/WxJava#2042]
### 简要描述
小程序直播间创建接口响应参数封装不太合理，当主播微信号未实名认证的时候，errcode不等于0，框架中抛出了异常WxErrorException，导致WxMaCreateRoomResult中没有填入微信响应参数qrcode_url，必须从WxErrorException中获取

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号:4.0.0

### 日志
【错误信息】：错误代码：300036, 错误信息：anchorWechat has no realName, please open the codeUrl and scan the code for certification rid: 60502398-542eda6d-61ba9e09，微信原始报文：{"errmsg":"anchorWechat has no realName, please open the codeUrl and scan the code for certification rid: 60502398-542eda6d-61ba9e09","qrcode_url":"https://res.wx.qq.com/op_res/9rSix1dhHfK4rR049JL0PHJ7TpOvkuZ3mE0z7Ou_Etvjf-w1J_jVX0rZqeStLfwh","errcode":300036}

**Comment by binarywang** [comment]
建议提供优化代码，直接PR即可

**Comment by binarywang** [comment]
这个问题只能说微信不按常规出牌，随意更改已经默认的接口规则，确实很操蛋
