### ISSUE TITLE
微信小商店功能准备支持吗?

### ISSUE THREAD

**Issue by borisbao** [Wechat-Group/WxJava#2048]
### 简要描述
微信小商店功能准备支持吗?

### 官方文档地址
https://developers.weixin.qq.com/doc/ministore/minishopopencomponent/Introduction.html

**Comment by binarywang** [comment]
暂无计划。你如果有帐号和相关权限，建议自行先实现，然后提交PR供他人参考并一起完善

**Comment by futurexiong** [comment]
> 暂无计划。你如果有帐号和相关权限，建议自行先实现，然后提交PR供他人参考并一起完善

是否可以通过service的get post或者execute请求url来调用小商店服务端api？

**Comment by binarywang** [comment]
完全可以，预留这两个接口就是方便扩展的

> > 暂无计划。你如果有帐号和相关权限，建议自行先实现，然后提交PR供他人参考并一起完善
> 
> 是否可以通过service的get post或者execute请求url来调用小商店服务端api？
