### ISSUE TITLE
Jedis 版本冲突

### ISSUE THREAD

**Issue by 872588448** [Wechat-Group/WxJava#2050]
![image](https://user-images.githubusercontent.com/27331568/112090324-4dd10580-8bce-11eb-8387-05a05e633f0c.png)
这个在配置文件里引用传入JedisPool  我试了好多版本 未发现在jedis.util.pool
![image](https://user-images.githubusercontent.com/27331568/112090621-d8196980-8bce-11eb-98e8-689d81ecdca0.png)
大佬们咋解决的

**Comment by taneg** [comment]
<groupId>redis.clients</groupId>
<artifactId>jedis</artifactId>

**Comment by taneg** [comment]
![image](https://user-images.githubusercontent.com/30307000/112437922-7568cf00-8d82-11eb-923b-179c37b6d159.png)

**Comment by taneg** [comment]
SpringBoot1 单独引包
![image](https://user-images.githubusercontent.com/30307000/112442175-89aecb00-8d86-11eb-90e7-b77e1093be07.png)

**Comment by binarywang** [comment]
就按楼上所说
