### ISSUE TITLE
BaseWxMpServiceImpl类型里面的execute方法中如果设置了最大的重试次数为0的话所抛出的异常不对

### ISSUE THREAD

**Issue by zainlu** [Wechat-Group/WxJava#2054]
![image](https://user-images.githubusercontent.com/28281414/112453929-211a1b00-8d93-11eb-9f8a-6e32a5ef01b2.png)
重试调用接口的话，会有一定的概率导致消息重发。如果我将最大的重试次数maxRetryTimes设置为0的时候。
图中抛出异常会在第一次调用接口出现任何的报错的时候进行抛出异常，而不是第一次调用超时时候抛出异常。
会导致后面对异常的处理，出现错误。

![image](https://user-images.githubusercontent.com/28281414/112454993-3fcce180-8d94-11eb-9274-6d24a4ea1016.png)

**Comment by binarywang** [comment]
欢迎直接提供PR
