### ISSUE TITLE
企业微信网页授权获取用户信息(非企业用户)时,字段缺失external_userid

### ISSUE THREAD

**Issue by sishuiyunyan** [Wechat-Group/WxJava#2061]
简要描述
网页授权登录 返回字段不全 当非企业用户时无external_userid 字段

模块版本情况
WxJava 模块名: weixin-java-cp
WxJava 版本号: 4.0.0
详细描述
网页授权登录时,根据code获取访问者的身份,官方https://open.work.weixin.qq.com/api/doc/90000/90135/91023
用户为非企业成员时,官方有返回external_userid 字段: {
"errcode": 0,
"errmsg": "ok",
"OpenId":"OPENID",
"DeviceId":"DEVICEID",
"external_userid":"EXTERNAL_USERID"
}
调用咱jar中提供的方法
WxCpOauth2UserInfo userInfo = cpService.getOauth2Service().getUserInfo(code);

返回的结果中没有 external_userid字段

public class WxCpOauth2UserInfo {
private String openId;
private String deviceId;
private String userId;
private String userTicket;
private String expiresIn;
}

**Comment by binarywang** [comment]
没有看下最新版本吗？建议关注下版本更新日志，关注下WxJava公众号

**Comment by sishuiyunyan** [comment]
你好,我用的是weixin-java-cp 4.0.0的版本  github上4.0.7B测试版 我也看了确实没有相关字段 您的实体类WxCpOauth2UserInfo  中没有external_userid 字段更不可能返回了,
请您在核实一下 !
原问题 如下:
简要描述
网页授权登录 返回字段不全 当非企业用户时无external_userid 字段
模块版本情况
WxJava 模块名: weixin-java-cp
WxJava 版本号: 4.0.0
详细描述
网页授权登录时,根据code获取访问者的身份,官方https://open.work.weixin.qq.com/api/doc/90000/90135/91023
用户为非企业成员时,官方有返回external_userid 字段: {
"errcode": 0,
"errmsg": "ok",
"OpenId":"OPENID",
"DeviceId":"DEVICEID",
"external_userid":"EXTERNAL_USERID"
}
调用咱jar中提供的方法
WxCpOauth2UserInfo userInfo = cpService.getOauth2Service().getUserInfo(code);
返回的结果中没有 external_userid字段
public class WxCpOauth2UserInfo {
private String openId;
private String deviceId;
private String userId;
private String userTicket;
private String expiresIn;
}

**Comment by binarywang** [comment]
建议直接提交PR

**Comment by sishuiyunyan** [comment]
你好:

    OK,已提交PR



***@***.***
 
发件人： Binary Wang
发送时间： 2021-03-31 10:32
收件人： Wechat-Group/WxJava
抄送： sishuiyunyan; Author
主题： Re: [Wechat-Group/WxJava] 企业微信网页授权获取用户信息(非企业用户)时,字段缺失external_userid (#2061)
建议直接提交PR
