### ISSUE TITLE
创建直播间报错：parameter anchorImg must no be null

### ISSUE THREAD

**Issue by Camio1945** [Wechat-Group/WxJava#2065]
调用 WxMaLiveService.createRoom 创建直播间报错 parameter anchorImg must no be null

### 日志
【错误信息】：错误代码：200002, 错误信息：parameter anchorImg must no be null rid: 6069705e-6d2207ef-19ddbd3b，微信原始报文：{"errmsg":"parameter anchorImg must no be null rid: 6069705e-6d2207ef-19ddbd3b","errcode":200002}

### 参考
https://developers.weixin.qq.com/community/minihome/doc/000e2ad8c84800f8afeb35c4651400

**Comment by binarywang** [comment]
到底是怎么解决的？

**Comment by erhu1999** [comment]
anchorImg

**Comment by Camio1945** [comment]
WxMaLiveRoomInfo 类中需要增加 anchorImg 字段。
这是微信接口的问题吧，在[创建直播间](https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Mini_Programs/live_player/studio-api.html#1)接口里，有一个字段叫`anchorImg`，但是在[编辑直播间](https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Mini_Programs/live_player/studio-api.html#6)接口里，没有这个字段了，变成了`feedsImg`字段。

**Comment by binarywang** [comment]
欢迎直接提交PR，保证测试通过没问题

**Comment by Camio1945** [comment]
OK，已经PR了，没改什么东西，只是加了一个字段，改了一下注释。
