### ISSUE TITLE
希望添加订阅通知事件支持

### ISSUE THREAD

**Issue by forwujinwei** [Wechat-Group/WxJava#2067]
微信文档：https://developers.weixin.qq.com/doc/offiaccount/Subscription_Messages/api.html#%E4%BA%8B%E4%BB%B6%E6%8E%A8%E9%80%81

**Comment by binarywang** [comment]
消息类有个专门的属性：allFieldsMap，你可以用它来获取微信推送消息里的所有内容。
因为事件太多，来不及一个个针对性增加字段，当然如果你有兴趣，可以自行修改增加相关属性，并提交PR。
