### ISSUE TITLE
微信小程序更新wx.getUserProfile，无法获取到小程序用户信息

### ISSUE THREAD

**Issue by maple2012** [Wechat-Group/WxJava#2069]
微信小程序更新了。wx.getUserProfile(Object object)。
后端在使用wxMaService.getUserService().getUserInfo获取不到用户的 openid和 union了。

**Comment by TerryGuan** [comment]
遇到同样的问题啊，要怎样解决啊

**Comment by junjiex123** [comment]
框架是否对这个问题做了更新？

**Comment by binarywang** [comment]
那能得到什么东西？

**Comment by junjiex123** [comment]
@binarywang   
![image](https://user-images.githubusercontent.com/44934686/113966930-92ad9b00-9862-11eb-8cbb-73d38da6372b.png)

**Comment by binarywang** [comment]
这个图片我知道，我是问现在用getUserInfo方法得到的是什么？

**Comment by binarywang** [comment]
按照官方文档描述，接口不需要调整，只是数据变了而已

**Comment by rpdict** [comment]
同样的问题，感觉是加密encryptedData的时候没包含openid，所以解密出来也没有openid。。

**Comment by TerryGuan** [comment]
1、wx.login拿到code，服务端换openid,unionid，本地记录登陆的token
2、wx.getUserProfile拿到的encryptedData，iv值里面比之前是少了openid,unionid的，只有头像和昵称。。。
3、通过之前登陆的token获取当前登陆的openid更新头像和昵称

**Comment by rpdict** [comment]
> 1、wx.login拿到code，服务端换openid,unionid，本地记录登陆的token
> 2、wx.getUserProfile拿到的encryptedData，iv值里面比之前是少了openid,unionid的，只有头像和昵称。。。
> 3、通过之前登陆的token获取当前登陆的openid更新头像和昵称

是的，现在要拉个人信息要像之前获取手机号一样写了，先用userInfo获取openid，再用userProfile获取详情更新上去。
官方示例代码不推荐使用getUserInfo获取用户信息，我这边好多同事都理解成getUserInfo废弃了，这是不对的。

**Comment by PanPanda** [comment]
> > 1、wx.login拿到code，服务端换openid,unionid，本地记录登陆的token
> > 2、wx.getUserProfile拿到的encryptedData，iv值里面比之前是少了openid,unionid的，只有头像和昵称。。。
> > 3、通过之前登陆的token获取当前登陆的openid更新头像和昵称
> 
> 是的，现在要拉个人信息要像之前获取手机号一样写了，先用userInfo获取openid，再用userProfile获取详情更新上去。
> 官方示例代码不推荐使用getUserInfo获取用户信息，我这边好多同事都理解成getUserInfo废弃了，这是不对的。

getUserInfo获取用户信息现在nickname做了处理拿不到用户的昵称了

**Comment by gongming1982** [comment]
这个预计多久会更新呀？

**Comment by binarywang** [comment]
> 这个预计多久会更新呀？

更新啥，早就更新了
