### ISSUE TITLE
一个mchId下绑定多个appId，这种情况下该怎么设置WxPayConfig？

### ISSUE THREAD

**Issue by mostcool** [Wechat-Group/WxJava#2074]
@binarywang 你好，我现在遇到的问题是一个mchId下绑定了多个不同的appId。看到WxJava BaseWxPayServiceImpl中configMap是用mchId作为key的，不允许重复。这种场景下，我该怎么处理呢？

**Comment by binarywang** [comment]
@cloudX2019

**Comment by cloudX2019** [comment]
需要使用多个appId支付的场景可在 WxPayConfig中配置默认的appId（也可不配置），在实际调用支付的时候传入实际使用的appId

**Comment by mostcool** [comment]
thx，已经知道是这么操作的了

**Comment by linyongfu2013** [comment]
@mostcool 具体怎么操作，能分享一下吗？

**Comment by mostcool** [comment]
> @mostcool 具体怎么操作，能分享一下吗？

构建请求的Request对象时，把appId设置进去。

WxPayUnifiedOrderRequest.setAppid(appId);
