### ISSUE TITLE
小程序授权encryptedData解密，返回结果错误。

### ISSUE THREAD

**Issue by TinChi0818** [Wechat-Group/WxJava#2076]
### 简要描述
小程序授权，对encryptedData进行解密，获取头像、昵称，返回结果并不是用户实际的昵称和头像。

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号: 3.8.0

### 详细描述
解析结果:{"avatar":"https://thirdwx.qlogo.cn/mmopen/vi_32/POgEwh4mIHO4nibH0KlMECNjjGxQUq24ZEaGT4poC6icRiccVGKSyXwibcPq4BWmiaIGuG1icwxaQX6grC9VemZoJ8rg/132","nickName":"微信用户"}

**Comment by tookbra** [comment]
看起来像这个 https://developers.weixin.qq.com/community/develop/doc/000cacfa20ce88df04cb468bc52801?highLine=login

**Comment by lyh92** [comment]
这个是前端返回的，好像微信改了，开发工具前端获取的昵称就是微信用户和白色头像

**Comment by TinChi0818** [comment]
> 这个是前端返回的，好像微信改了，开发工具前端获取的昵称就是微信用户和白色头像
