### ISSUE TITLE
企业微信服务商weixin-java-cp 通讯录搜索

### ISSUE THREAD

**Issue by OrangeBadBad** [Wechat-Group/WxJava#2080]
### 简要描述
企业微信服务商开发 通讯录搜索接口失败

### 模块版本情况
* WxJava 模块名: weixin-java-cp 
* WxJava 版本号:4.0.7.B

### 详细描述
```
 mainService.post(mainService.getWxCpTpConfigStorage().getApiUrl(CONTACT_SEARCH) + "?provider_access_token=" + mainService.getWxCpTpConfigStorage().getCorpSecret(), wxCpTpContactSearch.toJson());
```
这里不应该是传corpSecret 应该改为
```
mainService.post(mainService.getWxCpTpConfigStorage().getApiUrl(CONTACT_SEARCH) + "?provider_access_token=" + mainService.getWxCpProviderToken(), wxCpTpContactSearch.toJson());
```
@RequiredArgsConstructor
public class WxCpTpContactServiceImpl implements WxCpTpContactService {

  private final WxCpTpService mainService;

  @Override
  public WxCpTpContactSearchResp contactSearch(WxCpTpContactSearch wxCpTpContactSearch) throws WxErrorException {
    String responseText =
      mainService.post(mainService.getWxCpTpConfigStorage().getApiUrl(CONTACT_SEARCH) + "?provider_access_token=" + mainService.getWxCpTpConfigStorage().getCorpSecret(), wxCpTpContactSearch.toJson());
    return WxCpTpContactSearchResp.fromJson(responseText);
  }
}
```


### 日志

**Comment by binarywang** [comment]
欢迎直接提交PR
