### ISSUE TITLE
未配置V3信息时，WxPayConfig.toString()报错。

### ISSUE THREAD

**Issue by mostcool** [Wechat-Group/WxJava#2087]
### 简要描述
在未配置V3信息时，进行WxPayConfig.toString()报错。
什么情况下，BaseWxPayServiceImpl中configMap中的配置会被remove掉？现在我这边遇到了这种情况：启动后，configMap中有2个配置，运行一会后，就只剩下一个了，另外一个找不到了。
![image](https://user-images.githubusercontent.com/2172570/115665838-66237400-a376-11eb-86a2-72835410487e.png)

### 模块版本情况
* WxJava 模块名:  weixin-java-pay
* WxJava 版本号: 4.0.8.B

### 详细描述
在未配置V3信息时，进行WxPayConfig.toString()报错：
请确保privateKeyPath已设置
请确保privateCertPath已设置
请确保apiV3Key值已设置
（因为toString会调用getVerifier()方法）

同时，在使用BaseWxPayServiceImpl.switchoverTo(mchId)时，有报找不到配置的情况，怀疑跟这个也有关系。但具体原因在哪里还未知，只是重写了WxPayConfig的toString()方法后就正常了。

```java
/**
 * 微信支付自动配置
 */
@Configuration
public class WxPayAutoConfiguration {

    @Autowired
    private WxPayProperties wxPayProperties;

    /**
     * 构造微信支付服务对象.
     */
    @Bean
    @ConditionalOnMissingBean(WxPayService.class)
    public WxPayService wxPayService() {
        List<WxPayProperties.WxPay> configList = wxPayProperties.getConfigs();

        Map<String, WxPayConfig> configMap = configList.stream()
                .map(config -> {
                    WxPayConfig payConfig = new WxPayConfig();
                    payConfig.setMchId(StringUtils.trimToNull(config.getMchId()));
                    payConfig.setMchKey(StringUtils.trimToNull(config.getMchKey()));
                    payConfig.setKeyPath(StringUtils.trimToNull(config.getKeyPath()));
                    return payConfig;
                })
                .collect(Collectors.toMap(WxPayConfig::getMchId, Function.identity()));

        WxPayServiceImpl wxPayService = new WxPayServiceImpl();
        wxPayService.setMultiConfig(configMap);

        return wxPayService;
    }
}`

**Comment by mostcool** [comment]
@binarywang @cloudX2019

**Comment by mostcool** [comment]
```java
  @Override
  public void setMultiConfig(Map<String, WxPayConfig> wxPayConfigs, String defaultMchId) {
    this.configMap = Maps.newHashMap(wxPayConfigs);
    WxPayConfigHolder.set(defaultMchId);
  }
`
这里直接 this.configMap = wxPayConfigs 或者 用ConcurrentHashMap是不是更好一点？

**Comment by cloudX2019** [comment]
1.只有手动调用  removeConfig(mchId) 方法才会删除配置
2.toString() 方法在未配置V3信息时确实有问题，后续可以调整一下

**Comment by mostcool** [comment]
> 1.只有手动调用 removeConfig(mchId) 方法才会删除配置
> 2.toString() 方法在未配置V3信息时确实有问题，后续可以调整一下

可以确定，业务中没有任何地方调用过removeConfig方法。但确实遇到了configMap信息丢失的情况，这大概会是什么原因星期的呢？

**Comment by mostcool** [comment]
@binarywang @cloudX2019 多线程下configMap数据丢失的问题有解决方法吗？

**Comment by mostcool** [comment]
大概知道原因了。
应用启动时，在WxPayAutoConfiguration里通过
wxPayService.setMultiConfig(configMap);
此时，configMap里有多个config。

后面在支付\退款结果回调时，因为要切换不同的配置，又进行
wxPayService.setConfig(wxPayConfig);
此时，原来的configMap就被替换为新的了，所以造成数据丢失。

setMultiConfig这个方法需要改一下。
```java
  @Override
  public void setMultiConfig(Map<String, WxPayConfig> wxPayConfigs, String defaultMchId) {
    this.configMap = Maps.newHashMap(wxPayConfigs);
    WxPayConfigHolder.set(defaultMchId);
  }
`

**Comment by cloudX2019** [comment]
> 大概知道原因了。
> 应用启动时，在WxPayAutoConfiguration里通过
> wxPayService.setMultiConfig(configMap);
> 此时，configMap里有多个config。
> 
> 后面在支付\退款结果回调时，因为要切换不同的配置，又进行
> wxPayService.setConfig(wxPayConfig);
> 此时，原来的configMap就被替换为新的了，所以造成数据丢失。
> 
> setMultiConfig这个方法需要改一下。
> 
> ```java
>   @Override
>   public void setMultiConfig(Map<String, WxPayConfig> wxPayConfigs, String defaultMchId) {
>     this.configMap = Maps.newHashMap(wxPayConfigs);
>     WxPayConfigHolder.set(defaultMchId);
>   }
> `
> ```

在切换不同的配置时如果是新增的配置请使用 addConfig(mchId, wxPayConfig) ，如果是已存在的配置则使用switchoverTo(mchId)。 如果不确定是否存在可使用switchover(mchId) 判断

**Comment by mostcool** [comment]
> > 大概知道原因了。
> > 应用启动时，在WxPayAutoConfiguration里通过
> > wxPayService.setMultiConfig(configMap);
> > 此时，configMap里有多个config。
> > 后面在支付\退款结果回调时，因为要切换不同的配置，又进行
> > wxPayService.setConfig(wxPayConfig);
> > 此时，原来的configMap就被替换为新的了，所以造成数据丢失。
> > setMultiConfig这个方法需要改一下。
> > ```java
> >   @Override
> >   public void setMultiConfig(Map<String, WxPayConfig> wxPayConfigs, String defaultMchId) {
> >     this.configMap = Maps.newHashMap(wxPayConfigs);
> >     WxPayConfigHolder.set(defaultMchId);
> >   }
> > `
> > ```
> 
> 在切换不同的配置时如果是新增的配置请使用 addConfig(mchId, wxPayConfig) ，如果是已存在的配置则使用switchoverTo(mchId)。 如果不确定是否存在可使用switchover(mchId) 判断

在回调接口处理时，遇到要切换mchId和appId时，要怎么处理才合适？我现在是如下处理的。
```java
WxPayConfig wxPayConfig = wxPayService.switchoverTo(mchId).getConfig();
wxPayConfig.setAppId(appId);
wxPayService.setConfig(wxPayConfig);
orderNotifyResult = wxPayService.parseOrderNotifyResult(xmlData);
`

**Comment by mostcool** [comment]
> > > 大概知道原因了。
> > > 应用启动时，在WxPayAutoConfiguration里通过
> > > wxPayService.setMultiConfig(configMap);
> > > 此时，configMap里有多个config。
> > > 后面在支付\退款结果回调时，因为要切换不同的配置，又进行
> > > wxPayService.setConfig(wxPayConfig);
> > > 此时，原来的configMap就被替换为新的了，所以造成数据丢失。
> > > setMultiConfig这个方法需要改一下。
> > > ```java
> > >   @Override
> > >   public void setMultiConfig(Map<String, WxPayConfig> wxPayConfigs, String defaultMchId) {
> > >     this.configMap = Maps.newHashMap(wxPayConfigs);
> > >     WxPayConfigHolder.set(defaultMchId);
> > >   }
> > > `
> > > ```
> > 
> > 
> > 在切换不同的配置时如果是新增的配置请使用 addConfig(mchId, wxPayConfig) ，如果是已存在的配置则使用switchoverTo(mchId)。 如果不确定是否存在可使用switchover(mchId) 判断
> 
> 在回调接口处理时，遇到要切换mchId和appId时，要怎么处理才合适？我现在是如下处理的。
> `java 
WxPayConfig wxPayConfig = wxPayService.switchoverTo(mchId).getConfig(); wxPayConfig.setAppId(appId); wxPayService.setConfig(wxPayConfig); orderNotifyResult = wxPayService.parseOrderNotifyResult(xmlData);
 `

**Comment by cloudX2019** [comment]
据我所知微信支付通知不需要appId，只要商户号配置就行了。
wxPayService.switchoverTo(mchId).parseOrderNotifyResult(xmlData);  应该就行了

**Comment by mostcool** [comment]
> 据我所知微信支付通知不需要appId，只要商户号配置就行了。
> wxPayService.switchoverTo(mchId).parseOrderNotifyResult(xmlData); 应该就行了

好的，我试试
