### ISSUE TITLE
同时启动多个java实例，但是access_token不能共享的问题

### ISSUE THREAD

**Issue by cloud0072** [Wechat-Group/WxJava#2089]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
同一份应用，同时启动多个java实例，获取的access_token只能保存在本地java虚拟机，
现在希望在开发的时候能够多个人同时开发，但是各自启动一个项目会导致 access_token频发刷新。
能否加一个共享access_token的获取源 例如 redis 或者 mysql 或者url 等等

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by jaymie9019** [comment]
我也想问这个问题

**Comment by binarywang** [comment]
自己实现config，从同一个redis读取存储的token

**Comment by binarywang** [comment]
redis的实现不是有吗？

**Comment by jaymie9019** [comment]
这个问题我解决了
WxMpConfigStorage 有不同的实现类 

        WxMpDefaultConfigImpl configStorage = new WxMpRedisConfigImpl(new RedisTemplateWxRedisOps(stringRedisTemplate), "你想要存redis的前缀");
