### ISSUE TITLE
服务商模式没有关闭订单接口吗？

### ISSUE THREAD

**Issue by wheatguppy** [Wechat-Group/WxJava#2094]
接口地址：https://api.mch.weixin.qq.com/v3/pay/partner/transactions/out-trade-no/{out_trade_no}/close
这个服务商模式关闭订单有提供接口可供我们使用吗？

**Comment by binarywang** [comment]
可以参考queryPartnerTransactions实现一下，欢迎提交PR

**Comment by wheatguppy** [comment]
大佬你好，请问分账动账通知结果解析目前是否还没有此方法，我好像没有找到对应的结果解析接口，目前只有支付回调解析，是否也需要我再实现呢？感谢回复

**Comment by binarywang** [comment]
可能是没实现，源码都在里面的
