### ISSUE TITLE
WxCpXmlMessage的id是Long型，但企业微信客户标签变更事件的消息中，id是个字符串

### ISSUE THREAD

**Issue by jackinsan** [Wechat-Group/WxJava#2095]
解密后的原始xml消息内容：<xml><ToUserName><![CDATA[ww2f9cccc6aaf9b5b]]></ToUserName><FromUserName><![CDATA[abc]]></FromUserName><CreateTime>1619417005</CreateTime><MsgType><![CDATA[event]]></MsgType><Event><![CDATA[change_external_tag]]></Event><ChangeType><![CDATA[delete]]></ChangeType><Id><![CDATA[etF1bDDAAA6yLInsyCaC3Dbs_M5vR28g]]></Id><TagType><![CDATA[tag_group]]></TagType></xml>

---- Debugging information ----
cause-exception     : java.lang.NumberFormatException
cause-message       : For input string: "etF1bDDAAA6yLInsyCaC3Dbs_M5vR28g"
class               : java.lang.Long
required-type       : java.lang.Long
converter-type      : com.thoughtworks.xstream.converters.SingleValueConverterWrapper
wrapped-converter   : com.thoughtworks.xstream.converters.basic.LongConverter
line number         : 1
class[1]            : me.chanjar.weixin.cp.bean.message.WxCpXmlMessage
required-type[1]    : me.chanjar.weixin.cp.bean.message.WxCpXmlMessage
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
version             : not available

**Comment by jackinsan** [comment]
`解密后的原始xml消息内容：<xml><ToUserName><![CDATA[123]]></ToUserName><FromUserName><![CDATA[abc]]></FromUserName><CreateTime>1619417005</CreateTime><MsgType><![CDATA[event]]></MsgType><Event><![CDATA[change_external_tag]]></Event><ChangeType><![CDATA[delete]]></ChangeType><Id><![CDATA[etF1bDDAAA6yLInsyCaC3Dbs_M5vR28g]]></Id><TagType><![CDATA[tag_group]]></TagType></xml>`

**Comment by binarywang** [comment]
这个已经修改，请使用最新版本
