### ISSUE TITLE
添加服务号的订阅通知消息发送功能

### ISSUE THREAD

**Issue by tuke-code** [Wechat-Group/WxJava#2103]
### 简要描述
公众号发送订阅通知消息
### 官方文档地址
https://developers.weixin.qq.com/doc/offiaccount/Subscription_Messages/api.html

**Comment by binarywang** [comment]
这个不是早就有了吗

**Comment by tuke-code** [comment]
我没有在文档中找到这个接口文档，麻烦给个链接，谢谢

**Comment by binarywang** [comment]
看javadoc，不要只看wiki上的文档

**Comment by binarywang** [comment]
或者你在源码里搜索你要的接口地址关键字

**Comment by tuke-code** [comment]
好的

**Comment by tuke-code** [comment]
目前的javadoc的接口是一次性订阅的，https://developers.weixin.qq.com/doc/offiaccount/Message_Management/One-time_subscription_info.html
还有个订阅通知的没有

**Comment by tuke-code** [comment]
https://developers.weixin.qq.com/doc/offiaccount/Subscription_Messages/api.html#send%E5%8F%91%E9%80%81%E8%AE%A2%E9%98%85%E9%80%9A%E7%9F%A5

**Comment by binarywang** [comment]
看最新测试版，正式版还没发布

**Comment by tuke-code** [comment]
好的

**Comment by leechenqi** [comment]
@binarywang 订阅通知的 微信发过来的事件消息， subscribe_msg_popup_event、subscribe_msg_change_event 和 subscribe_msg_sent_event 目前还没有在WxConsts.EventType 中定义，另外这几个对应的xml也没有对应的对象类与之对应吧？

**Comment by binarywang** [comment]
> @binarywang 订阅通知的 微信发过来的事件消息， subscribe_msg_popup_event、subscribe_msg_change_event 和 subscribe_msg_sent_event 目前还没有在WxConsts.EventType 中定义，另外这几个对应的xml也没有对应的对象类与之对应吧？

新的那些消息字段你可以在map字段里自行解析，或者你自行实现并PR亦可。
