### ISSUE TITLE
企业微信-OA-审批-提交审批申请，假勤组件的参数结构错误

### ISSUE THREAD

**Issue by lovelive1024** [Wechat-Group/WxJava#2107]
### 简要描述
文档地址：https://work.weixin.qq.com/api/doc/90000/90135/91853
企业微信-OA-审批-提交审批申请，假勤组件的参数结构错误

### 模块版本情况
* WxJava 模块名: weixin-java-cp-4.0.8.B
* WxJava 版本号: weixin-java-cp-4.0.8.B
* 类: me.chanjar.weixin.cp.bean.oa.applydata.ContentValue

### 详细描述
假勤组件-请假组件（control参数为Vacation）
现在的结构为：contents-value-selector&attendance
需要的结构为：contents-value-vacation-selector&attendance

现在的结构数据：
{
	"creator_userid": "xxx",
	"template_id": "xxx",
	"use_template_approver": 1,
	"apply_data": {
		"contents": [{
			"control": "Vacation",
			"id": "vacation-1563793073898",
			"value": {
				"selector": {
					"type": "single",
					"options": [{
						"key": "3",
						"value": [{
							"text": "病假",
							"lang": "zh_CN"
						}]
					}],
					"exp_type": 0
				},
				"attendance": {
					"date_range": {
						"type": "hour",
						"new_begin": 1568077200,
						"new_end": 1568368800,
						"new_duration": 291600
					},
					"type": 1
				}
			}
		}, {
			"control": "Number",
			"id": "Number-1620724086302",
			"value": {
				"new_number": "13333333333"
			}
		}, {
			"control": "Textarea",
			"id": "item-1497581399901",
			"value": {
				"text": ""
			}
		}]
	}
}

实际需要的结构数据：
{
	"creator_userid": "xxx",
	"template_id": "xxx",
	"use_template_approver": 1,
	"apply_data": {
		"contents": [{
				"control": "Vacation",
				"id": "vacation-1563793073898",
				"value": {
					"vacation": {
						"selector": {
							"type": "single",
							"options": [{
								"key": "3",
								"value": [{
									"text": "病假",
									"lang": "zh_CN"
								}]
							}],
							"exp_type": 0
						},
						"attendance": {
							"date_range": {
								"type": "hour",
								"new_begin": 1568077200,
								"new_end": 1568368800,
								"new_duration": 291600
							},
							"type": 1
						}
					}
				}
			},
			{
				"control": "Number",
				"id": "Number-1620724086302",
				"value": {
					"new_number": "13333333333"
				}
			},
			{
				"control": "Textarea",
				"id": "item-1497581399901",
				"value": {
					"text": "测试"
				}
			}
		]
	}
}

**Comment by Gyv12345** [comment]
是有变动吗

**Comment by lovelive1024** [comment]
> 是有变动吗

@Gyv12345 不清楚是不是变动过，我是现在才使用这个接口，然后提交一直提示出错，联系微信的客服后才发现是结构有问题

**Comment by Gyv12345** [comment]
ContentValue 这个类里增加一个新的属性吧，之前没有假勤组件的

**Comment by lovelive1024** [comment]
> ContentValue 这个类里增加一个新的属性吧，之前没有假勤组件的

@Gyv12345 
原来是有一个attendance属性的
现在应该需要是增加一个vacation属性，然后vacation需要有selector和attendance属性，原来的attendance暂时没有发现在其它地方有使用

**Comment by binarywang** [comment]
楼主描述了半天，其实你可以直接修改并提交PR的
