### ISSUE TITLE
weixin-java-miniapp4.0.0 文字内容审核接口报错 

### ISSUE THREAD

**Issue by gongming1982** [Wechat-Group/WxJava#2110]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号: 4.0.0

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__
weixin-java-miniapp模块中

wxMaService.getSecCheckService().checkMessage(）方法请求超时，其他接口没有发现此问题。这个问题不定期出现，不是一直超时，目前还没有发现规律和导致问题的原因
同一台开发机器，用postman请求相同地址，相同参数没有问题。可以成功返回。
【请求地址】: https://api.weixin.qq.com/wxa/msg_sec_check?access_token=45_p7V2P3RaQNgBdl0Tld881smHIDYyOFf06NNLIFBXL3a04lHKXWb3TQc-KgBD2eBwxnPKCt8ihz4RrqSmMHM-PoDrjHfH4baRbf_IuU-PNeiYsoGhF_HcYNOmU50DAsn0iObhUVEBisbSti-WQZIhAGAMVE
【请求参数】：{"content":"o4x5y5"}
【异常信息】：Read timed out

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by binarywang** [comment]
超时参数设置问题，自己参考wiki文档进行修改
