### ISSUE TITLE
请求升级代金券接口，旧接口官方提示可能不再维护

### ISSUE THREAD

**Issue by asog** [Wechat-Group/WxJava#2112]
**微信支付代金券API已经全面升级，点击查看全新文档。本接口文档未来将不再维护，请已经基于本文档开发的商户尽快升级至新接口。**
![image](https://user-images.githubusercontent.com/13364274/118237207-9cfa2f00-b4c9-11eb-8661-c55a4846e01c.png)

**新接口**

![image](https://user-images.githubusercontent.com/13364274/118237273-bbf8c100-b4c9-11eb-8717-20a096d9dc84.png)

**Comment by binarywang** [comment]
暂无计划，如果楼主有帐号，可自行实现并提交PR

**Comment by chutian0124** [comment]
微信支付代金券V3版可以用这个吧WxPayService.getMarketingFavorService().createFavorStocksV3(FavorStocksCreateRequest request)
