### ISSUE TITLE
服务商模式下进件缺少 小微商户 类型

### ISSUE THREAD

**Issue by plumekanade** [Wechat-Group/WxJava#2114]
### 简要描述
服务商模式下 商户进件 除了 个体、企业、党政机关、其他组织之外，还有一个小微商户类型
调用的是同个接口进件，请求参数不同

### 官方文档地址
https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/tool/applyment/chapter3_1.shtml

**Comment by binarywang** [comment]
欢迎自行实现并提交PR
