### ISSUE TITLE
微信分账服务类是否考虑增加v3接口，目前是v2，谢谢

### ISSUE THREAD

**Issue by 155311616123** [Wechat-Group/WxJava#2120]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by huayanYu** [comment]
可以PR哇~

**Comment by binarywang** [comment]
如果想让别人实现，就请给出文档，否则就自行实现提交PR，目前来说后者最快
