### ISSUE TITLE
群发图文消息，报empty news data问题。

### ISSUE THREAD

**Issue by gzlboy** [Wechat-Group/WxJava#2126]
### 简要描述
群发图文消息，已经给了图文的mediaId，但接口报empty news data，看了一下post的数据，序列化没有把news的mediaId序列化进去。

### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号:3.5.0

### 详细描述
代码：
`WxMpMassTagMessage message = new WxMpMassTagMessage();
            message.setMsgType(result.getType());
            message.setMediaId(result.getMediaId());
            message.setContent(result.getMediaId());
            message.setTagId(hasTag.getId());

            WxMpMassSendResult sendResult = helper.getMassMessageService().massGroupMessageSend(message);`

调试，可以看到mediaId是有传的，但message序列化后，并没有添加到post请求数据中：
![image](https://user-images.githubusercontent.com/1492060/119067287-4da98680-ba14-11eb-8be8-2718ba777c5a.png)

所以微信服务器返回错误：

“上传推文异常，ex:{"errcode":44003,"errmsg":"empty news data rid: 60a70896-0d6063dd-7ad6f498"}”

**Comment by binarywang** [comment]
是不是你用的版本太老导致的，也许这个问题早就修复了
