### ISSUE TITLE
使用weixin-java-mp 4.0.0 版本 

### ISSUE THREAD

**Issue by gongxm0412** [Wechat-Group/WxJava#2127]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
在整合过程中 遇到 
```
java: 无法访问me.chanjar.weixin.common.service.WxService
  找不到me.chanjar.weixin.common.service.WxService的类文件
```

### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号: 4.0.0

### 详细描述
 
![image](https://user-images.githubusercontent.com/11432636/119086879-c589a800-ba38-11eb-8837-37c625a252ab.png)

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by binarywang** [comment]
common包版本问题，这个很明显，不一致导致的

**Comment by gongxm0412** [comment]
感谢 感谢

**Comment by gongxm0412** [comment]
在监听 公众号事件的时候 提示 
```
Request method 'POST' not supported
```

**Comment by binarywang** [comment]
> 在监听 公众号事件的时候 提示
> 
> ```
> Request method 'POST' not supported
> ```

完全不知道啥意思，你这描述太简单了
