### ISSUE TITLE
公众号自动回复同步改成异步无法回复消息

### ISSUE THREAD

**Issue by yuanhh11** [Wechat-Group/WxJava#2131]
[公众号自动回复同步改成异步无法回复消息，但如果用同步的话微信端会超时5s导致报错该公众号提供的服务出现故障，请稍后再试。实际是有回复的，但是这个提示信息很尴尬。请问下各位大佬如何处理的。
![1621589401(1)](https://user-images.githubusercontent.com/76681336/119116006-65a3f900-ba5a-11eb-8ba9-385ffe246779.jpg)

**Comment by binarywang** [comment]
参考demo，不管同步异步，如果handler返回null，你就给微信返回个空字符串

**Comment by yuanhh11** [comment]
z

> 参考demo，不管同步异步，如果handler返回null，你就给微信返回个空字符串

加了还是不可以的，同步的话还是会提示该公众号提供的服务出现异常，请稍后再试

**Comment by binarywang** [comment]
> z
> 
> > 参考demo，不管同步异步，如果handler返回null，你就给微信返回个空字符串
> 
> 加了还是不可以的，同步的话还是会提示该公众号提供的服务出现异常，请稍后再试

同步会提示？你确定吗
