### ISSUE TITLE
企业微信第三方 redis keyPrefix,多个suite 共用了同样的key,很严重

### ISSUE THREAD

**Issue by momosv** [Wechat-Group/WxJava#2134]
### 简要描述
没法设置keyPrefix,但是有没有拼上如 suiteId 这样的唯一标识,导致redis 的数据串了，provider 也是这问题，虽说provider 也许只有一个造成影响不大，但是会有隐患。

### 模块版本情况
* WxJava 模块名: cp，cptp
* WxJava 版本号:4.0.9.B 

### 详细描述
![image](https://user-images.githubusercontent.com/33799449/119916740-ae4a3d80-bf97-11eb-8bd9-fc6cc316c034.png)

### 日志
![image](https://user-images.githubusercontent.com/33799449/119916960-2284e100-bf98-11eb-8814-55f254f89031.png)

**Comment by binarywang** [comment]
欢迎自行优化代码，实现你的需求，并提交PR
