### ISSUE TITLE
小程序获取 URL Link接口实现

### ISSUE THREAD

**Issue by cranehe** [Wechat-Group/WxJava#2135]
### 官方文档地址
__ [小程序获取URL Link地址接口](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/url-link.html)

微信最近更新支持小程序获取URL Link接口，这个接口使用场景比较多，还望可以尽快实现

**Comment by binarywang** [comment]
欢迎自行实现，并提交PR。现阶段这是最快的实现方式
