### ISSUE TITLE
企业微信服务商模式缺少外部联系人openid转换

### ISSUE THREAD

**Issue by ezsky** [Wechat-Group/WxJava#2147]
### 企业微信服务商模式缺少外部联系人openid转换

企业和服务商可通过此接口，将微信外部联系人的userid（如何获取?）转为微信openid，用于调用支付相关接口。暂不支持企业微信外部联系人（ExternalUserid为wo开头）的userid转openid。

请求方式：POST（HTTPS）
请求地址：https://qyapi.weixin.qq.com/cgi-bin/externalcontact/convert_to_openid?access_token=ACCESS_TOKEN

### 官方文档地址
https://open.work.weixin.qq.com/api/doc/90001/90143/92292

**Comment by binarywang** [comment]
这个接口看起来很简单，欢迎楼主参考现有源码有余力的情况下，实现该接口并提交PR
