### ISSUE TITLE
什么时候能支持微信（公众号和小程序）订阅消息

### ISSUE THREAD

**Issue by zouchao** [Wechat-Group/WxJava#2149]
### 简要描述
目前微信公众号和小程序相继开放了订阅消息的能力，订阅通知是一个用户主动订阅、服务号按需下发的通知能力。

### 官方文档地址
小程序：https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/subscribe-message.html
公众号：https://developers.weixin.qq.com/doc/offiaccount/Subscription_Messages/intro.html

**Comment by binarywang** [comment]
早支持了，你没看更新日志？
