### ISSUE TITLE
企业微信客户联系接口缺少

### ISSUE THREAD

**Issue by 13535148742** [Wechat-Group/WxJava#2150]
### 简要描述
企业微信客户联系接口缺少

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号:4.1.0

### 详细描述
* 缺少【在职继承-分配在职员工】：https://work.weixin.qq.com/api/doc/90000/90135/92125
* 缺少【在职继承-查询客户接替状态】：https://work.weixin.qq.com/api/doc/90000/90135/94088
* 缺少【离职继承-分配离职成员的客户】：https://work.weixin.qq.com/api/doc/90000/90135/94081
* 缺少【离职继承-查询客户接替状态】：https://work.weixin.qq.com/api/doc/90000/90135/94082
* 缺少【离职继承-分配离职成员的客户群】：https://work.weixin.qq.com/api/doc/90000/90135/92127

**Comment by binarywang** [comment]
麻烦给出具体文档，而不是接口地址。

另外如果你急需这些接口，欢迎自行参考现有代码实现并提交PR，否则可能等待时间会有点长

**Comment by 13535148742** [comment]
缺少【在职继承-分配在职员工】：https://work.weixin.qq.com/api/doc/90000/90135/92125
缺少【在职继承-查询客户接替状态】：https://work.weixin.qq.com/api/doc/90000/90135/94088
缺少【离职继承-分配离职成员的客户】：https://work.weixin.qq.com/api/doc/90000/90135/94081
缺少【离职继承-查询客户接替状态】：https://work.weixin.qq.com/api/doc/90000/90135/94082
缺少【离职继承-分配离职成员的客户群】：https://work.weixin.qq.com/api/doc/90000/90135/92127
