### ISSUE TITLE
分布式环境下的公众号数据如何存储访问？

### ISSUE THREAD

**Issue by zhoubang85** [Wechat-Group/WxJava#2152]
有一个问题一直想问一下，对于分布式系统环境，公众号的数据如何维护管理？比如在管理系统中添加一个公众号配置后，通过wxMpService.addConfigStorage将数据加载到内存里面，如果后端接口服务部署在N台机器实例上（微服务分布式部署），如何做到公众号的数据同步？或者统一管理？
我目前看到的，好像是token以及verify_ticket相关数据可以通过redis存储。但是对于普通的公众号的数据，不知道如何操作。
由于刚接触wxJava框架，很多还不太了解，对于以上的问题，不知道框架是否有支持？还是说目前不支持分布式存储？thanks

**Comment by Sailboats** [comment]
问得好，兄弟，我也想问这个问题，运行时动态增加一个公众号配置的话，从目前看来只在新增的那台机器上有这个新增的公众号配置，其它机器的数据不会更新

**Comment by gadfly3173** [comment]
不是有个me.chanjar.weixin.mp.config.WxMpConfigStorage的接口和me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl抽象类么，自己再做一个能存配置的redis的实现类就可以了吧

**Comment by justwu** [comment]
自己广播一下?
