### ISSUE TITLE
在调用微信授权登录接口时会零星出现api.weixin.qq.com:443 failed to respond 的问题

### ISSUE THREAD

**Issue by zhouyf14** [Wechat-Group/WxJava#2153]
https://juejin.cn/post/6865277186438496269

1383 Wrapped by: me.chanjar.weixin.common.error.WxRuntimeException: org.apache.http.NoHttpResponseException: api.weixin.qq.com:443 failed to respond
1384         at me.chanjar.weixin.open.api.impl.WxOpenServiceAbstractImpl.execute(WxOpenServiceAbstractImpl.java:60)
1385         at me.chanjar.weixin.open.api.impl.WxOpenServiceApacheHttpClientImpl.get(WxOpenServiceApacheHttpClientImpl.java:60)
1386         at me.chanjar.weixin.open.api.impl.WxOpenComponentServiceImpl.get(WxOpenComponentServiceImpl.java:186)
1387         at me.chanjar.weixin.open.api.impl.WxOpenComponentServiceImpl.get(WxOpenComponentServiceImpl.java:178)
1388         at me.chanjar.weixin.open.api.impl.WxOpenComponentServiceImpl.oauth2getAccessToken(WxOpenComponentServiceImpl.java:399)
1389         at com.uxseeing.service.impl.TracMountWebServiceImpl.mountMpOpenId(TracMountWebServiceImpl.java:92)
1390         at com.uxseeing.service.impl.TracMountWebServiceImpl.mountRequest(TracMountWebServiceImpl.java:61)
1391         at com.uxseeing.service.impl.TracParserServiceImpl.mountSingleVo(TracParserServiceImpl.java:197)
1392         at com.uxseeing.service.impl.TracParserServiceImpl.mountAndCheckRequest(TracParserServiceImpl.java:86)
1393         at com.uxseeing.controller.TracController.track(TracController.java:116)
1394         at com.uxseeing.controller.TracController.trackerAsyn(TracController.java:95)
1395         at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source)
1396         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
1397         at java.lang.reflect.Method.invoke(Method.java:498)
1398         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
1399         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
1400         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
1401         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
1402         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
1403         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
1404         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
1405         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
1406         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
1407         at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
1408         at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
1409         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
1410         at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
1411         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
1412         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
1413         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
1414         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
1415         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
1416         at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
1417         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
1418         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
1419         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
1420         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
1421         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
1422         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
1423         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
1424         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
1425         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
1426         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
1427         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
1428         at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
1429         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
1430         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
1431         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
1432         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
1433         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
1434         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
1435         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
1436         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
1437         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
1438         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
1439         at java.lang.Thread.run(Thread.java:748)

**Comment by binarywang** [comment]
这应该是网络问题，自己尝试调整http请求参数值

**Comment by zhouyf14** [comment]
> 这应该是网络问题，自己尝试调整http请求参数值

https://juejin.cn/post/6865277186438496269

**Comment by zhouyf14** [comment]
![image](https://user-images.githubusercontent.com/31618029/121648796-76c8ae80-caca-11eb-9999-320a8e1876bd.png)

**Comment by binarywang** [comment]
这篇文章也说的是超时参数的设置问题，参考wiki设置即可

**Comment by zhouyf14** [comment]
> 这篇文章也说的是超时参数的设置问题，参考wiki设置即可

非常感谢
