### ISSUE TITLE
企业微信欢迎语不支持视频类型的欢迎语

### ISSUE THREAD

**Issue by zhangyu1197** [Wechat-Group/WxJava#2155]

**Comment by binarywang** [comment]
可以详细些吗？是因为企业微信官方不支持吗？

**Comment by zhangyu1197** [comment]
> 可以详细些吗？是因为企业微信官方不支持吗？
不是，我发现在 me.chanjar.weixin.cp.bean.external.msg   只有  Image  Link  MiniProgram   Text   这4种消息类型

**Comment by binarywang** [comment]
其实你发下文档地址就很容易看明白了，
不过我自己找了下，你说的可能是这个：
https://work.weixin.qq.com/api/doc/90000/90135/92137

**Comment by zhangyu1197** [comment]
> 其实你发下文档地址就很容易看明白了，
> 不过我自己找了下，你说的可能是这个：
> https://work.weixin.qq.com/api/doc/90000/90135/92137

对的，少video类型

**Comment by binarywang** [comment]
欢迎自己提交PR代码，这是目前最快的办法

**Comment by binarywang** [comment]
咋关了？

**Comment by binarywang** [comment]
新代码已修复
