### ISSUE TITLE
wx.miniapp.config-storage 如果配置为redistemplate, 要求项目必须注入StringRedisTemplate 问题

### ISSUE THREAD

**Issue by Carlosplng** [Wechat-Group/WxJava#2156]
### 简要描述
wx.miniapp.config-storage 如果配置为redistemplate, 要求项目必须注入StringRedisTemplate 问题

### 模块版本情况
* WxJava 模块名: miniapp
* WxJava 版本号: 4.1.0

### 详细描述
wx.miniapp.config-storage 如果配置为redistemplate, 要求项目必须注入StringRedisTemplate 问题，
这个是否对序列化限制的太死了？

代码如下：
private WxMaRedisBetterConfigImpl getWxMaInRedisTemplateConfigStorage() {
        StringRedisTemplate redisTemplate = (StringRedisTemplate)this.applicationContext.getBean(StringRedisTemplate.class);
        WxRedisOps redisOps = new RedisTemplateWxRedisOps(redisTemplate);
        return new WxMaRedisBetterConfigImpl(redisOps, this.properties.getConfigStorage().getKeyPrefix());
    }

**Comment by binarywang** [comment]
你有什么好的修改建议？欢迎直接提供优化方案

**Comment by Carlosplng** [comment]
RedisTemplate redisTemplate = this.applicationContext.getBean(RedisTemplate.class);
这样既兼容StringRedisTemplate，应用程序Redis序列化可以灵活控制

**Comment by binarywang** [comment]
> RedisTemplate redisTemplate = this.applicationContext.getBean(RedisTemplate.class);

欢迎楼主自行PR，我看涉及的不止这个一个地方，其他地方也需要重构

**Comment by linyongfu2013** [comment]
+1

**Comment by StringKe** [comment]
> > RedisTemplate redisTemplate = this.applicationContext.getBean(RedisTemplate.class);
> 
> 欢迎楼主自行PR，我看涉及的不止这个一个地方，其他地方也需要重构

是否可以考虑抽取一个简单 JSON 的通用接口，底层实现根据具体引入依赖指定？
类似 https://github.com/xkcoding/simple-json 这种。

整个包通过序列化工具进行转换后存取，这样就不会导致 StringRedisTemplate 序列化解析错误了。

我现在的项目统一使用 jackson 来进行解析，我默认的 StringRedisTemplate 也配置了这个，这样就导致 WxMpConfigStorage 存取数据解析错误。（这里也有一个我比较疑惑的问题，默认存是没有问题的，取的时候好像进行序列化。）

**Comment by china0402** [comment]
RedisTemplateSimpleDistributedLock中这个地方
![image](https://user-images.githubusercontent.com/11327535/144572534-8065f1f5-6477-4a2c-9a42-e3b2d866b554.png)
用
![image](https://user-images.githubusercontent.com/11327535/144572793-15fc8b96-bdd2-45fa-9780-8e6ec5e1b1c9.png)
这种方式灵活一点吧，pipeline设置值大坑
