### ISSUE TITLE
企业微信提交审批新增关联单字段

### ISSUE THREAD

**Issue by cst799926407** [Wechat-Group/WxJava#2160]
### 简要描述
提交审批时缺少关联审批单控件字段

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__
https://work.weixin.qq.com/api/doc/90000/90135/91853 见附14

**Comment by binarywang** [comment]
按文档所述，看来少的不止是这一个字段，还有：
### 附13 位置控件（control参数为Location，且value参数为location）

```
{
    "location": {
        "latitude": "30.547239",
        "longitude": "104.063291",
        "title": "腾讯科技(成都)有限公司(腾讯成都大厦)",
        "address": "四川省成都市武侯区天府三街198号腾讯成都大厦A座",
        "time": 1605690460
    }
}
```

参数	说明
latitude	纬度，精确到6位小数
longitude	经度，精确到6位小数
title	地点标题
address	地点详情地址
time	选择地点的时间


### 附14 关联审批单控件（control参数为RelatedApproval，且value参数为related_approval）
```
{
    "related_approval": [
        {
            "sp_no": "202011180001"
        }
    ]
}
```
参数	说明
sp_no	关联审批单的审批单号

### 附15 公式控件（control参数为Formula，且value参数为formula）
```
{
   "formula": {
        "value": "5.0"
    }
}
```
参数	说明
value	公式的值，提交表单时无需填写，后台自动计算


### 附14 时长组件（control参数为DateRange，且value参数为date_range）
```
{
    "date_range": {
        "new_begin": 1570550400,
        "new_end": 1570593600,
        "new_duration": 86400
    }
}
```
参数	说明
new_begin	开始时间,unix时间戳
new_end	结束时间，unix时间戳
new_duration	时长范围， 单位秒

**Comment by binarywang** [comment]
欢迎楼主先按自己所需添加所需字段，并提交PR
