### ISSUE TITLE
增加微信订阅消息

### ISSUE THREAD

**Issue by jev001** [Wechat-Group/WxJava#2166]
# 增加微信订阅消息修改详情字段

### 简要描述

* 目前 `WxMaMessage` 缺少订阅消息修改的详情

* 微信订阅消息回调: 
   * 增加订阅消息修改详情

### 官方文档地址
https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/subscribe-message.html
![image](https://user-images.githubusercontent.com/10397378/123363751-bf419b00-d5a5-11eb-9007-3cc9535a7b6a.png)

**Comment by yhan219** [comment]
你说的是`cn.binarywang.wx.miniapp.api.WxMaMsgService#sendSubscribeMsg`方法
和`cn.binarywang.wx.miniapp.api.WxMaSubscribeService#sendSubscribeMsg`方法
吧

**Comment by binarywang** [comment]
楼上跟楼主说的不是同一个问题，楼主的标题有误导嫌疑

**Comment by binarywang** [comment]
楼主如果有迫切的解析需求，建议先自行实现并提交PR
