### ISSUE TITLE
'创建企业群发'接口升级

### ISSUE THREAD

**Issue by liujinmu** [Wechat-Group/WxJava#2168]
### 简要描述
官网'创建企业群发'接口已升级，并废弃旧版接口，请问是否有跟进计划？

### 官方文档地址
旧版本接口：https://open.work.weixin.qq.com/api/doc/27708
新版本接口：https://open.work.weixin.qq.com/api/doc/90001/90143/92698

**Comment by binarywang** [comment]
暂无计划，如果有紧急需求，欢迎自行参考现有代码实现并提交PR
