### ISSUE TITLE
项目配置找不到 WxMpInMemoryConfigStorage.class 类

### ISSUE THREAD

**Issue by william-abel** [Wechat-Group/WxJava#2172]
### 简要描述
在项目配置 WxMp AppId时找不到 WxMpInMemoryConfigStorage.class 类

### 模块版本情况
* WxJava 模块名: wx-java-mp
* WxJava 版本号: 4.0.0

### 详细描述
在项目配置 WxMp AppId时找不到 WxMpInMemoryConfigStorage.class 类

![image](https://user-images.githubusercontent.com/45378809/123510835-3ebb9100-d6b0-11eb-91ef-a2ad08527125.png)
![image](https://user-images.githubusercontent.com/45378809/123510838-43804500-d6b0-11eb-809f-8c05740e29f6.png)
![image](https://user-images.githubusercontent.com/45378809/123510841-47ac6280-d6b0-11eb-90a1-593a9f607f42.png)

**Comment by binarywang** [comment]
早就重构了，请参考wiki说明
