### ISSUE TITLE
weixin-java-cp-demo中怎么修改weixin-java-cp中的WxCpApiPathConsts的DEFAULT_CP_BASE_URL

### ISSUE THREAD

**Issue by wuzhike666** [Wechat-Group/WxJava#2174]
### 简要描述
进行企业微信私有化部署的时候，去调用api,发现需要修改DEFAULT_CP_BASE_URL为公司的企业微信私有化路径。

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号:4.1

### 详细描述
进行企业微信私有化部署的时候，去调用api,发现需要修改DEFAULT_CP_BASE_URL为公司的企业微信私有化路径。

### 日志
无

**Comment by binarywang** [comment]
重复
