### ISSUE TITLE
希望第三方开放平台的codeCommit函数能增加一个上传代码包含组件的功能

### ISSUE THREAD

**Issue by xyh-994** [Wechat-Group/WxJava#2175]
### 简要描述
希望第三方开放平台的codeCommit函数的WxMaOpenCommitExtInfo 能增加个plugins(组件)的上传控制或者允许添加其他跟ext同级内容的函数...

### 官方文档地址
https://developers.weixin.qq.com/miniprogram/dev/devtools/ext.html

**Comment by binarywang** [comment]
欢迎先自行实现你所需功能，并提交PR
