### ISSUE TITLE
升级4.1.0后，项目启动报错，读取到空的 WxMaServiceAutoConfiguration， 请问是哪里配置的问题

### ISSUE THREAD

**Issue by zhouyufei8** [Wechat-Group/WxJava#2177]
### 简要描述
升级4.1.0后，项目启动报错，读取到空的 WxMaServiceAutoConfiguration， 请问是哪里配置的问题

### 模块版本情况
* WxJava  wx-java-mp-spring-boot-starter
* WxJava 4.1.0:

### 详细描述
引用版本
`    
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>wx-java-miniapp-spring-boot-starter</artifactId>
            <version>${wxjava.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>wx-java-pay-spring-boot-starter</artifactId>
            <version>${wxjava.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>wx-java-mp-spring-boot-starter</artifactId>
            <version>${wxjava.version}</version>
        </dependency>`

yml 配置文件内容如下 

wx:
  mp:
    useRedis: false
    configs:
        - appid: xxxxx
          secret: xxxxx
  miniapp:
    configs:
        - appid: xxxxx
          secret: xxxxx
#          token:
#          aesKey: #微信小程序消息服务器配置的EncodingAESKey
          msgDataFormat: JSON
  pay:
    # 微信公众号或者小程序等的appid
    appId: xxxxx
    # 微信支付商户号
    mchId: xxxxx
    # 微信支付商户密钥
    mchKey: xxxxx
    #服务商模式下的子商户公众账号ID
    subAppId:
    #服务商模式下的子商户号
    subMchId:

项目中使用到了小程序，公众号，以及支付
所以引用了3个starter, 起初用的版本是3,7.0 ， 后来为了新增一个公众号小消息相关，看到这部分有升级，于是就升级到了4.1.0
启动后报错

大概日志 ：
Caused by: java.lang.NullPointerException: null key in entry: null={"accessTokenLock":{"sync":{"state":0}},"expiresTime":0,"httpProxyPort":0,"retrySleepMillis":1000,"maxRetryTimes":5,"jsapiTicketExpiresTime":0,"cardApiTicketExpiresTime":0,"jsapiTicketLock":{"sync":{"state":0}},"cardApiTicketLock":{"sync":{"state":0}}}
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:30) ~[guava-29.0-jre.jar:?]
	at com.google.common.collect.SingletonImmutableBiMap.<init>(SingletonImmutableBiMap.java:42) ~[guava-29.0-jre.jar:?]
	at com.google.common.collect.ImmutableBiMap.of(ImmutableBiMap.java:71) ~[guava-29.0-jre.jar:?]
	at com.google.common.collect.ImmutableMap.of(ImmutableMap.java:124) ~[guava-29.0-jre.jar:?]

具体日志 ： 
https://paste.ubuntu.com/p/884sHcj6RQ/

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/p/884sHcj6RQ/) 或者其他地方，并将其url地址贴在这里__

**Comment by zzzmhcn** [comment]
同问，我也是一样的情况一样的问题
3.7.0 升级到 4.1.0 配置文件和代码都是照抄的demo
启动就报这个错 一模一样

**Comment by binarywang** [comment]
key为空，你看下报错的位置就知道了

**Comment by zhouyufei8** [comment]
appid 为空，但是我的配置文件中该配置的都配置了。
这个配置在3.7.0 的版本是能够使用的。除了这几个还有其他的地方需要配吗？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/WxJava"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月28日(星期一) 下午4:19
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] 升级4.1.0后，项目启动报错，读取到空的 WxMaServiceAutoConfiguration， 请问是哪里配置的问题 (#2177)





 
key为空，你看下报错的位置就知道了

**Comment by zzzmhcn** [comment]
> key为空，你看下报错的位置就知道了

能否麻烦说下是哪里的key

**Comment by zzzmhcn** [comment]
```
logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug
wx:
  miniapp:
    configs:
        - appid: #微信小程序的appid
          secret: #微信小程序的Secret
          token: #微信小程序消息服务器配置的token
          aesKey: #微信小程序消息服务器配置的EncodingAESKey
          msgDataFormat: JSON
```

我是参照这个配置文件例子配置的，里面有的尽量都填了

**Comment by binarywang** [comment]
> > key为空，你看下报错的位置就知道了
> 
> 能否麻烦说下是哪里的key

看你代码报错对应的行，建议debug代码去看

**Comment by zhouyufei8** [comment]
我是有自己实现的各个配置的，但是不应该会读取到，&nbsp;WxMaServiceAutoConfiguration，
感觉问题出现在这里







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/WxJava"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月28日(星期一) 下午4:24
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] 升级4.1.0后，项目启动报错，读取到空的 WxMaServiceAutoConfiguration， 请问是哪里配置的问题 (#2177)





 logging:   level:     org.springframework.web: info     com.github.binarywang.demo.wx.miniapp: debug     cn.binarywang.wx.miniapp: debug wx:   miniapp:     configs:         - appid: #微信小程序的appid           secret: #微信小程序的Secret           token: #微信小程序消息服务器配置的token           aesKey: #微信小程序消息服务器配置的EncodingAESKey           msgDataFormat: JSON  
我是参照这个配置文件例子配置的，里面有的尽量都填了

**Comment by zhouyufei8** [comment]
我自己重写了 ，&nbsp;WxMaProperties  WxMaConfiguration， 是不是不应该去使用工具自带的  WxMaServiceAutoConfiguration ？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/WxJava"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月28日(星期一) 下午4:19
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] 升级4.1.0后，项目启动报错，读取到空的 WxMaServiceAutoConfiguration， 请问是哪里配置的问题 (#2177)





 
key为空，你看下报错的位置就知道了

**Comment by zzzmhcn** [comment]
楼主如果调试出来的话麻烦和我说一声，谢谢，我这边努力一天了，真的没办法了

**Comment by zzzmhcn** [comment]
补充一个报错信息 看看有没有帮助
https://paste.ubuntu.com/p/m4tNCCNNV9/

**Comment by zhouyufei8** [comment]
暂时将版本降低到&nbsp; 3.8.0 就可以了，
我试了，就改个版本号，3.9.0 的也不行
<wxjava.version&gt;3.8.0</wxjava.version&gt;
目前我就么用。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/WxJava"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月28日(星期一) 下午4:46
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] 升级4.1.0后，项目启动报错，读取到空的 WxMaServiceAutoConfiguration， 请问是哪里配置的问题 (#2177)





 
楼主如果调试出来的话麻烦和我说一声，谢谢，我这边努力一天了，真的没办法了

**Comment by 18121259693** [comment]
今天早上一行行读源码，发现了华点
https://github.com/Wechat-Group/WxJava/blob/develop/spring-boot-starters/wx-java-miniapp-spring-boot-starter/src/main/java/com/binarywang/spring/starter/wxjava/miniapp/properties/WxMaProperties.java

**Comment by zzzmhcn** [comment]
今天早上一行行读源码，发现了华点
https://github.com/Wechat-Group/WxJava/blob/develop/spring-boot-starters/wx-java-miniapp-spring-boot-starter/src/main/java/com/binarywang/spring/starter/wxjava/miniapp/properties/WxMaProperties.java
这个文件决定了 WxMaServiceAutoConfiguration -> public WxMaService wxMaService(WxMaConfig wxMaConfig) 的 wxMaConfig的值
而WxMaProperties的读取路径方式居然是wx.miniapp.appid .......于是我改成下面这样，启动就正常了，特地来告诉楼主
```yml
wx:
  miniapp:
    appid: xxxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    msgDataFormat: JSON
```

**Comment by zzzmhcn** [comment]
对了，我还把demo对应的config也删了。就引入4.1.0 pom依赖，然后直接用，只配置了yml这5行，我水平有限如果说错勿怪
@zhouyufei8

**Comment by binarywang** [comment]
> 今天早上一行行读源码，发现了华点
> https://github.com/Wechat-Group/WxJava/blob/develop/spring-boot-starters/wx-java-miniapp-spring-boot-starter/src/main/java/com/binarywang/spring/starter/wxjava/miniapp/properties/WxMaProperties.java
> 这个文件决定了 WxMaServiceAutoConfiguration -> public WxMaService wxMaService(WxMaConfig wxMaConfig) 的 wxMaConfig的值
> 而WxMaProperties的读取路径方式居然是wx.miniapp.appid .......于是我改成下面这样，启动就正常了，特地来告诉楼主
> 
> ```yaml
> wx:
>   miniapp:
>     appid: xxxxxxxxxxxxxxxxxxxx
>     secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>     msgDataFormat: JSON
> ```

这么说来是你们自己把demo的配置跟starter的配置搞混了，其实仔细一些就好了

**Comment by zzzmhcn** [comment]
> > 今天早上一行行读源码，发现了华点
> > https://github.com/Wechat-Group/WxJava/blob/develop/spring-boot-starters/wx-java-miniapp-spring-boot-starter/src/main/java/com/binarywang/spring/starter/wxjava/miniapp/properties/WxMaProperties.java
> > 这个文件决定了 WxMaServiceAutoConfiguration -> public WxMaService wxMaService(WxMaConfig wxMaConfig) 的 wxMaConfig的值
> > 而WxMaProperties的读取路径方式居然是wx.miniapp.appid .......于是我改成下面这样，启动就正常了，特地来告诉楼主
> > ```yaml
> > wx:
> >   miniapp:
> >     appid: xxxxxxxxxxxxxxxxxxxx
> >     secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> >     msgDataFormat: JSON
> > ```
> 
> 这么说来是你们自己把demo的配置跟starter的配置搞混了，其实仔细一些就好了

其实我昨天就猜到我配置文件和正确的不一样了
但我实在找不到正确的是什么样的，我一点点找readme，看wiki，但凡能点进去的我都看了，我确实没找到一个正确的配置文件的例子。也许是有的，但我确实找了没找到。唯一一个能参考的就是demo。。。。包括这个问题我发现这个项目的issues还有其他人也遇到了，估计也是这个问题

**Comment by zhouyufei8** [comment]
两个确实搞混了，
我看了一下starter 的配置
wx.mp.appId=appId
***@***.***
***@***.***
***@***.***Key但是这个配置怎么支持多个公众号呢 ？是不是starter 不支持多个？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/WxJava"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月29日(星期二) 上午10:17
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] 升级4.1.0后，项目启动报错，读取到空的 WxMaServiceAutoConfiguration， 请问是哪里配置的问题 (#2177)





  
今天早上一行行读源码，发现了华点
 https://github.com/Wechat-Group/WxJava/blob/develop/spring-boot-starters/wx-java-miniapp-spring-boot-starter/src/main/java/com/binarywang/spring/starter/wxjava/miniapp/properties/WxMaProperties.java
 这个文件决定了 WxMaServiceAutoConfiguration -&gt; public WxMaService wxMaService(WxMaConfig wxMaConfig) 的 wxMaConfig的值
 而WxMaProperties的读取路径方式居然是wx.miniapp.appid .......于是我改成下面这样，启动就正常了，特地来告诉楼主
 wx:   miniapp:     appid: xxxxxxxxxxxxxxxxxxxx     secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     msgDataFormat: JSON
  
这么说来是你们自己把demo的配置跟starter的配置搞混了，其实仔细一些就好了

**Comment by binarywang** [comment]
> 两个确实搞混了， 我看了一下starter 的配置 wx.mp.appId=appId ***@***.*** ***@***.*** ***@***.***Key但是这个配置怎么支持多个公众号呢 ？是不是starter 不支持多个？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Wechat-Group/WxJava" ***@***.***&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 上午10:17 ***@***.***&gt;; 抄送:&nbsp;" ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Wechat-Group/WxJava] 升级4.1.0后，项目启动报错，读取到空的 WxMaServiceAutoConfiguration， 请问是哪里配置的问题 (#2177) 今天早上一行行读源码，发现了华点 https://github.com/Wechat-Group/WxJava/blob/develop/spring-boot-starters/wx-java-miniapp-spring-boot-starter/src/main/java/com/binarywang/spring/starter/wxjava/miniapp/properties/WxMaProperties.java 这个文件决定了 WxMaServiceAutoConfiguration -&gt; public WxMaService wxMaService(WxMaConfig wxMaConfig) 的 wxMaConfig的值 而WxMaProperties的读取路径方式居然是wx.miniapp.appid .......于是我改成下面这样，启动就正常了，特地来告诉楼主 wx: miniapp: appid: xxxxxxxxxxxxxxxxxxxx secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx msgDataFormat: JSON 这么说来是你们自己把demo的配置跟starter的配置搞混了，其实仔细一些就好了 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

starter目前不支持，是为了快速接入公众号做的

**Comment by zhouyufei8** [comment]
但是我用的starter 版本 3.8 及以下的是可以的 。3.8没用到starter 的特性？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/WxJava"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月30日(星期三) 下午4:07
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] 升级4.1.0后，项目启动报错，读取到空的 WxMaServiceAutoConfiguration， 请问是哪里配置的问题 (#2177)





  
两个确实搞混了， 我看了一下starter 的配置 wx.mp.appId=appId @.*** @.*** @.Key但是这个配置怎么支持多个公众号呢 ？是不是starter 不支持多个？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Wechat-Group/WxJava" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 上午10:17 @.&gt;; 抄送:&nbsp;" @.@.***&gt;; 主题:&nbsp;Re: [Wechat-Group/WxJava] 升级4.1.0后，项目启动报错，读取到空的 WxMaServiceAutoConfiguration， 请问是哪里配置的问题 (#2177) 今天早上一行行读源码，发现了华点 https://github.com/Wechat-Group/WxJava/blob/develop/spring-boot-starters/wx-java-miniapp-spring-boot-starter/src/main/java/com/binarywang/spring/starter/wxjava/miniapp/properties/WxMaProperties.java 这个文件决定了 WxMaServiceAutoConfiguration -&gt; public WxMaService wxMaService(WxMaConfig wxMaConfig) 的 wxMaConfig的值 而WxMaProperties的读取路径方式居然是wx.miniapp.appid .......于是我改成下面这样，启动就正常了，特地来告诉楼主 wx: miniapp: appid: xxxxxxxxxxxxxxxxxxxx secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx msgDataFormat: JSON 这么说来是你们自己把demo的配置跟starter的配置搞混了，其实仔细一些就好了 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
starter目前不支持，是为了快速接入公众号做的

**Comment by binarywang** [comment]
> 但是我用的starter 版本 3.8 及以下的是可以的 。3.8没用到starter 的特性？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Wechat-Group/WxJava" ***@***.***&gt;; 发送时间:&nbsp;2021年6月30日(星期三) 下午4:07 ***@***.***&gt;; 抄送:&nbsp;" ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Wechat-Group/WxJava] 升级4.1.0后，项目启动报错，读取到空的 WxMaServiceAutoConfiguration， 请问是哪里配置的问题 (#2177) 两个确实搞混了， 我看了一下starter 的配置 wx.mp.appId=appId @.*** @.*** @.Key但是这个配置怎么支持多个公众号呢 ？是不是starter 不支持多个？ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Wechat-Group/WxJava" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 上午10:17 @.&gt;; 抄送:&nbsp;" @.@.***&gt;; 主题:&nbsp;Re: [Wechat-Group/WxJava] 升级4.1.0后，项目启动报错，读取到空的 WxMaServiceAutoConfiguration， 请问是哪里配置的问题 (#2177) 今天早上一行行读源码，发现了华点 https://github.com/Wechat-Group/WxJava/blob/develop/spring-boot-starters/wx-java-miniapp-spring-boot-starter/src/main/java/com/binarywang/spring/starter/wxjava/miniapp/properties/WxMaProperties.java 这个文件决定了 WxMaServiceAutoConfiguration -&gt; public WxMaService wxMaService(WxMaConfig wxMaConfig) 的 wxMaConfig的值 而WxMaProperties的读取路径方式居然是wx.miniapp.appid .......于是我改成下面这样，启动就正常了，特地来告诉楼主 wx: miniapp: appid: xxxxxxxxxxxxxxxxxxxx secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx msgDataFormat: JSON 这么说来是你们自己把demo的配置跟starter的配置搞混了，其实仔细一些就好了 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. starter目前不支持，是为了快速接入公众号做的 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

自己看下源码就清楚了，做过一次重构

**Comment by tiger-ye** [comment]
![image](https://user-images.githubusercontent.com/12395748/130549232-f2440955-85f6-46f8-8bee-b72b430069fb.png)
额 又加了一些。。。 这样可以的

**Comment by zhouyufei8** [comment]
参考springboot-starter 的demo的配置写法，stater和普通的配置不一样，


这个是我的配置 ：&nbsp;
wx:
&nbsp; mp:
&nbsp; &nbsp; useRedis: false
&nbsp; &nbsp; configs:
&nbsp; &nbsp; &nbsp; &nbsp; - appid: xxxxxxx
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; secret: xxxxxxx
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; token: xxxxxxx_token # 接口配置里的Token值
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; aesKey: xxxxxxx# 接口配置里的EncodingAESKey值
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; # 开发测试订阅号
&nbsp; &nbsp; &nbsp; &nbsp; - appid: xxxxxxx
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; secret: xxxxxxx
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; token: xxxxxxx# 接口配置里的Token值
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; aesKey: xxxxxxx# 接口配置
&nbsp; miniapp:
&nbsp; &nbsp; configs:
&nbsp; &nbsp; &nbsp; &nbsp; - appid: xxxxxxx
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; secret: xxxxxxx





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/WxJava"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月24日(星期二) 中午11:05
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] 升级4.1.0后，项目启动报错，读取到空的 WxMaServiceAutoConfiguration， 请问是哪里配置的问题 (#2177)





 

 额 又加了一些。。。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tiger-ye** [comment]
> 参考springboot-starter 的demo的配置写法，stater和普通的配置不一样， 这个是我的配置 ：&nbsp; wx: &nbsp; mp: &nbsp; &nbsp; useRedis: false &nbsp; &nbsp; configs: &nbsp; &nbsp; &nbsp; &nbsp; - appid: xxxxxxx &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; secret: xxxxxxx &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; token: xxxxxxx_token # 接口配置里的Token值 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; aesKey: xxxxxxx# 接口配置里的EncodingAESKey值 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; # 开发测试订阅号 &nbsp; &nbsp; &nbsp; &nbsp; - appid: xxxxxxx &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; secret: xxxxxxx &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; token: xxxxxxx# 接口配置里的Token值 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; aesKey: xxxxxxx# 接口配置 &nbsp; miniapp: &nbsp; &nbsp; configs: &nbsp; &nbsp; &nbsp; &nbsp; - appid: xxxxxxx &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; secret: xxxxxxx
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Wechat-Group/WxJava" ***@***.***&gt;; 发送时间:&nbsp;2021年8月24日(星期二) 中午11:05 ***@***.***&gt;; 抄送:&nbsp;" ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Wechat-Group/WxJava] 升级4.1.0后，项目启动报错，读取到空的 WxMaServiceAutoConfiguration， 请问是哪里配置的问题 (#2177) 额 又加了一些。。。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我直接复制的 demo ,这样报错的
