### ISSUE TITLE
【小程序直播商品】添加异常

### ISSUE THREAD

**Issue by bubble2121** [Wechat-Group/WxJava#2183]
### 简要描述
调用小程序直播添加商品，出现
{"errmsg":"url must not be empty rid: 60dc072a-739b8415-6a62d4ce","errcode":200002}
实际已经传入url

### 模块版本情况
 <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>wx-java-miniapp-spring-boot-starter</artifactId>
            <version>4.1.0</version>
  </dependency>

### 详细描述
查看日志已经传入URL，本地通过postman调用上传商品没有问题

### 日志
2021-06-30 13:56:17.304 ERROR 22224 --- [http-nio-8516-exec-4] c.b.w.m.api.impl.BaseWxMaServiceImpl     : 
【请求地址】: https://api.weixin.qq.com/wxaapi/broadcast/goods/add?access_token=48_yiRYpJKJGVN_sekXaMii0J7kjLgHD1taBR0_tUSZjkQ3WBKPlKRGArCq1RZ7aJBp_lh9AxHWfUe0ax_9wgrx-SELS_jX1_pNq3c8rsh_Is6SCidy3H4NNBkIPTn_5hltBnqrLqGz8XRo76B7KOPcAFARVW
【请求参数】：{"goodsInfo":"WxMaLiveGoodInfo(goodsId=null, coverImgUrl=ray7qi0bxllaAARM8uB9AI8B4uSl9BVTkR78f4UUxe4PoviVlyM4R5WjPZbm2edB, url=pages/shop/GoodsCon/index?id=955, priceType=1, price=28, price2=28, name=绿族 古色生香, thirdPartyTag=null)"}
【错误信息】：错误代码：200002, 错误信息：url must not be empty rid: 60dc0781-123acfde-21131d8c，微信原始报文：{"errmsg":"url must not be empty rid: 60dc0781-123acfde-21131d8c","errcode":200002}

**Comment by binarywang** [comment]
确实是个bug
