### ISSUE TITLE
cp模块中WxCpTpRedissonConfigImpl redis key设置问题

### ISSUE THREAD

**Issue by chenzuotan** [Wechat-Group/WxJava#2184]
版本是4.1.0
private final String suiteTicketKey = ":suiteTicketKey:";
@Override
  public void updateSuiteTicket(String suiteTicket, int expiresInSeconds) {
    wxRedisOps.setValue(keyWithPrefix(suiteTicketKey), suiteTicket, expiresInSeconds, TimeUnit.SECONDS);
  }

private String keyWithPrefix(String key) {
    return keyPrefix + ":" + suiteId + ":" + key;
  }
结果就导致redis key 就是 ww93f******1146ca3::suiteTicketKey:
中间会有2个冒号，结尾也有个冒号

**Comment by binarywang** [comment]
貌似问题也不大，多一个冒号，请问是影响到什么地方了吗？
