### ISSUE TITLE
直播商品无法添加的问题

### ISSUE THREAD

**Issue by imtaoist** [Wechat-Group/WxJava#2191]
### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号:4.1.1.B

### 详细描述
src/main/java/cn/binarywang/wx/miniapp/bean/live/WxMaLiveGoodInfo.java 
下面这个类的代码好像跟腾讯最新的文档不一致了，麻烦看看哈
/**
 * 直播商品信息
 */
@Data
public class WxMaLiveGoodInfo implements Serializable {
  private static final long serialVersionUID = 5769245932149287574L;
  private Integer goodsId;
  private String coverImgUrl;
  private String url;
  private Integer priceType;
  private String price;
  private String price2;
  private String name;
  /**
   * 1, 2：表示是为api添加商品，否则是在MP添加商品
   */
  private String thirdPartyTag;
}

**Comment by binarywang** [comment]
请明确下问题，到底是什么地方不同，另外请贴出文档地址，如果你觉得自己可以修复，欢迎直接PR

**Comment by imtaoist** [comment]
你好！
腾讯开发文档更新过了。
https://developers.weixin.qq.com/miniprogram/dev/framework/liveplayer/commodity-api.html







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/WxJava"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月6日(星期二) 中午1:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] 直播商品无法添加的问题 (#2191)





 
请明确下问题，到底是什么地方不同，另外请贴出文档地址，如果你觉得自己可以修复，欢迎直接PR

**Comment by binarywang** [comment]
如果说的是price和price2的类型问题，那已经是修复过了的
