### ISSUE TITLE
微信支付模块可否支持服务商模式的V3接口

### ISSUE THREAD

**Issue by liu-haiying** [Wechat-Group/WxJava#2196]
V3版本的服务商模式相关接口是否支持

官方文档地址 https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter4_5_1.shtml

**Comment by junetigerlee** [comment]
补充一下官方文档地址：
JSAPI 支付，API列表
https://pay.weixin.qq.com/wiki/doc/apiv3_partner/open/pay/chapter2_4.shtml
APP支付，API列表
https://pay.weixin.qq.com/wiki/doc/apiv3_partner/open/pay/chapter2_5_3.shtml
H5支付，API列表
https://pay.weixin.qq.com/wiki/doc/apiv3_partner/open/pay/chapter2_6_3.shtml
Native支付，API列表
https://pay.weixin.qq.com/wiki/doc/apiv3_partner/open/pay/chapter2_7_3.shtml

**Comment by binarywang** [comment]
看代码早已支持，你是否看过源码？
