### ISSUE TITLE
安全风控接口

### ISSUE THREAD

**Issue by radcat1987** [Wechat-Group/WxJava#2198]
### 简要描述
请添加微信小程序根据提交的用户信息数据获取用户的安全等级 risk_rank接口实现

### 官方文档地址
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/safety-control-capability/riskControl.getUserRiskRank.html

**Comment by binarywang** [comment]
暂无计划，如果不想等太久的话，欢迎先自行实现

**Comment by binarywang** [comment]
看起来接口很简单
