### ISSUE TITLE
企业微信扫码登录目前没有集成build二维码链接么

### ISSUE THREAD

**Issue by peterzhangnull** [Wechat-Group/WxJava#2207]
### 简要描述
企业微信扫码登录目前没有集成build二维码链接

### 官方文档地址
https://work.weixin.qq.com/api/doc/90000/90135/90988

**Comment by binarywang** [comment]
这个看起来是很简单的字符拼接吧，如果真希望有这么一个方法，欢迎先自行实现提交PR。
