### ISSUE TITLE
本地可以调试支付接口吗？createOrder接口

### ISSUE THREAD

**Issue by youc3576** [Wechat-Group/WxJava#2212]
本地如何调试createOrder接口呢？还是说必须部署到有域名的地址上调试呢？谢谢

**Comment by binarywang** [comment]
你试试不就知道了吗？代码里还有单元测试可以跑

**Comment by binarywang** [comment]
配置正确的情况下，之前跑单元测试是完全没问题的，现在不知道微信服务器是否有限制
