### ISSUE TITLE
微信支付 APP统一下单接口v3，缺少sign参数

### ISSUE THREAD

**Issue by evanweng666** [Wechat-Group/WxJava#2216]
### 简要描述
微信支付 APP统一下单接口v3，缺少sign参数

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号: 4.1.0

### 详细描述
WxPayUnifiedOrderV3Result.getPayInfo构建APP支付信息时没有签名
官方文档：https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_2_4.shtml
签名示例：SignUtils.sign(String.format("%s\n%s\n%s\n%s\n", appid, timestamp, noncestr, prepayid), wxPayService.getConfig().getPrivateKey())

**Comment by aboutZZ** [comment]
牛逼嗷，代码不测试就直接发版`4.1.0`了，全靠免费测试员给测bug。
