### ISSUE TITLE
EntPayRedpackQueryResult 类里面的属性类型定义错误

### ISSUE THREAD

**Issue by MicroCountry** [Wechat-Group/WxJava#2224]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
EntPayRedpackQueryResult 类里面的属性类型定义错误

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号: 4.1.3

### 详细描述
EntPayRedpackQueryResult 类里面的属性类型定义错误
目前包里面
@XStreamAlias("reason")
    private Integer reason;

 @XStreamAlias("rcv_time")
    private Integer rcvTime;
两个字段，但是官方 https://pay.weixin.qq.com/wiki/doc/api/tools/cash_coupon.php?chapter=13_6&index=5 ，
![image](https://user-images.githubusercontent.com/16758768/127455098-94e3ab2a-f69f-474b-be78-db912a889038.png)

reason 应该为String ,rcvTime也应该为String，但是代码中定义为了Integer

**Comment by MicroCountry** [comment]
@XStreamAlias("sender_name")
    private Integer senderName;
    @XStreamAlias("sender_header_media_id")
    private Integer senderHeaderMediaId;
    
    这两个字段应为String，但是定义为了Integer

**Comment by binarywang** [comment]
欢迎直接贡献PR代码来修复问题
