### ISSUE TITLE
请问企业微信直播的接口哪里能找到？

### ISSUE THREAD

**Issue by zjxpcyc** [Wechat-Group/WxJava#2225]
我在 CP 模块里面没有找到。在 miniapp 里面发现了一些，但是 miniapp 里面的应该是小程序的，不是企业微信的吧？

**Comment by binarywang** [comment]
企业微信直播接口暂未实现，如果急需这些接口，欢迎直接贡献代码。

**Comment by binarywang** [comment]
不过如果希望别人帮你实现，至少也得留一下文档地址吧？直接就关了吗？

**Comment by zjxpcyc** [comment]
不太懂开源社区的套路。我以为及时关闭，对你们是比较负责的态度。   地址是这个  [https://work.weixin.qq.com/api/doc/90000/90135/93632](https://work.weixin.qq.com/api/doc/90000/90135/93632)
