### ISSUE TITLE
大佬，我有一言，不知当讲不当讲

### ISSUE THREAD

**Issue by coldsmirk** [Wechat-Group/WxJava#2227]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
WxPay模块中，WxPayConfig的设计拓展性不够，还不如 WxCp和Mp的配置做的好，提供了 ConfigStorage的接口用作应用程序自己拓展，就拿WxPayConfig中configMap来说吧，虽然做了 configMap，但是有以下问题：
* 第一，逻辑写的太死，初始化第一个配置的时候，map的key用的mchId，我们知道微信商户可以有很多子商户，那么这些子商户的mchId都是同一个主商户，必然是一样的，只有subMchId是不一样的，显然这里设计是不合理的。
* 第二，有时候，多机构用户，可能每个机构一个配置，这些配置的key用户更希望是以 orgId为 map 的key来存储配置，而不是 mchId，局限性显而易见
* 第三，不统一，微信公众平MP和企业微信CP配置均遵守了相同的接口约定。让正真有需求的用户自定义实现配置管理，我觉着这个就是很棒，至少我可以实现一个类似 CompositeWxCpConfig 的实现，然后里面存放多个 WxCpConfigImpl的实现动态管理，这个应用程序自己想怎么定义就怎么定义了，这点很棒的，可以微信支付和小程序模块并没有提供支持
* 第四，微信支付和小程序的多配置除了依赖它类中的configMap 还依赖 ThreadLocal 动态的设值来改变要使用那个一个配置，这显然对于多线程执行的（请求过程中可能会切换线程执行）程序来说就不那么友好了，还要自己做各种适配和统一管理，如果提供配置接口的话，显然这个自定义就更棒了

以上乃个人愚见，纯属真实项目场景需求！希望可以得到改进

**Comment by binarywang** [comment]
你的想法很重要，毕竟是真实项目需求而来。
不过既然有这么多想法，你肯定也有自己想修改的替代代码吧。
欢迎直接PR，一个个解决你所说的问题。

**Comment by huayanYu** [comment]
@Venus-WXP  大佬说的好，我也很需要，把你的代码贡献出来吧。。

**Comment by huayanYu** [comment]
![image](https://user-images.githubusercontent.com/16700837/129663783-b3db5822-8580-4275-939b-921e8d9ec065.png)
@Venus-WXP  看起来似乎虽然命名是mchId，但是没有限制必须用mchId啊

**Comment by coldsmirk** [comment]
> ![image](https://user-images.githubusercontent.com/16700837/129663783-b3db5822-8580-4275-939b-921e8d9ec065.png)
> @Venus-WXP 看起来似乎虽然命名是mchId，但是没有限制必须用mchId啊

<img width="1368" alt="WX20210817-130138@2x" src="https://user-images.githubusercontent.com/18739624/129666504-b8206bf4-5de4-4d01-8e06-ba0312fe8af6.png">
