### ISSUE TITLE
使用客服功能时候,消息全部进入了待接入

### ISSUE THREAD

**Issue by tianjiangtao** [Wechat-Group/WxJava#2230]
我使用的jdk版本是:
![image](https://user-images.githubusercontent.com/20277431/127631572-7449200e-fc4f-45af-b121-ec9778900cc1.png)
问题截图:
![image](https://user-images.githubusercontent.com/20277431/127631962-3418f6ec-d9e3-4d64-ae8c-ec166a8659c5.png)
如果点击接入,在没有给微信服务器返回MsgType为transfer_customer_service的消息的情况下，
用户发的所有消息，都进入到了客服系统。
这样的话，公众号官方文档中的“消息转发到客服”就变得没有意义，
开发者也无法控制什么情况下转接客服。
请问各位是否有类似问题？期待回复！

**Comment by binarywang** [comment]
我估计点击接入按钮的功能就相当于转发的动作。据我所知，之前是没有这个按钮的，应该是后来加的

**Comment by tianjiangtao** [comment]
这个按钮是我们自己做的菜单,公众号的截图如下:
![image](https://user-images.githubusercontent.com/20277431/127834608-5e56bdfd-8ca0-41f1-b899-2c4cf1daa3f2.png)

当时的设计是点菜单就进客服,但是发现一个问题,如果用户在公众号里说话,这个消息会全部发送到那个待处理里,那不是说,如果有客服功能,那就不能在公众号里面说话?
这个问题,有人遇到过么?
