### ISSUE TITLE
WxMaMessageRouter#isMsgDuplicated 在某些特定场景下会出现丢消息的情况

### ISSUE THREAD

**Issue by 1yus2yus3** [Wechat-Group/WxJava#2231]
### 简要描述
在小程序内容安全版本 security.mediaCheckAsync ，调用此方法后，微信服务器会推送消息到业务服务器，进而调用消息路由，由绑定的handler处理消息，消息处理时必须经过除重逻辑，问题就在这个除重逻辑，会导致并发回调时间相同的时候，丢消息的情况

### 模块版本情况
* WxJava 模块名: miniapp
* WxJava 版本号:  本人引用的是3.9的项目版本 但是我看最新版本这里也没有找到处理方案

### 详细描述
返回的消息结构：
![image](https://user-images.githubusercontent.com/10860713/127952280-0ba96078-9584-43a9-869d-4adf8420b51e.png)

![image](https://user-images.githubusercontent.com/10860713/127952438-e3df826e-b629-48a3-b9af-8a832637460c.png)

实际微信返回
![image](https://user-images.githubusercontent.com/10860713/127952524-8401bf34-a9f7-4b5c-88ef-b3fa51ac3414.png)

目前我的解决方案是自己实现了一个 WxMessageDuplicateChecker 固定返回true 然后在业务里面处理 消息重复的问题，不知道目前有没有其他的解决方案，或者我没有理解这个场景下的其他处理

**Comment by 1yus2yus3** [comment]
内容审查的消息通知 如果可以按照返回的属性 traceid 是 合适的，但是key值的生成是在router里面的私有方法，如果key值的生成能和WxMessageDuplicateChecker 判断 一起 暴露给我们自己实现 这样会不会更方便一些

**Comment by binarywang** [comment]
> 内容审查的消息通知 如果可以按照返回的属性 traceid 是 合适的，但是key值的生成是在router里面的私有方法，如果key值的生成能和WxMessageDuplicateChecker 判断 一起 暴露给我们自己实现 这样会不会更方便一些

这个想法很不错，如果你有已经现成的代码，欢迎直接PR上来以供参考
