### ISSUE TITLE
【企业微信 - 客户联系 - 标签】序号问题

### ISSUE THREAD

**Issue by qq626** [Wechat-Group/WxJava#2233]
### 简要描述
【企业微信 - 客户联系 - 标签】序号问题，字段对应的是：标签排序的次序值，order值大的排序靠前。有效的值范围是[0, 2^32)
文档地址：https://open.work.weixin.qq.com/api/doc/90000/90135/92117

### 模块版本情况
* WxJava 模块名: cp
* WxJava 版本号: 4.1.0

### 详细描述
代码里是 Integer

**Comment by binarywang** [comment]
你现在都用到了最大值？

**Comment by binarywang** [comment]
准备更改为long
