### ISSUE TITLE
严重BUG - BaseWxPayResult add a field named signType  

### ISSUE THREAD

**Issue by 7777-ouyang** [Wechat-Group/WxJava#2237]
### 简要描述
BaseWxPayResult   新增 signType字段，与 WxPayOrderNotifyResult 类中 signType 重复，导致回调 XML 序列化出错。

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号: 4.1.4.B

### 详细描述
---- Debugging information ----
cause-exception     : java.lang.IllegalArgumentException
cause-message       : Multiple entries with same key: sign_type=private java.lang.String com.github.binarywang.wxpay.bean.result.BaseWxPayResult.signType and sign_type=private java.lang.String com.github.binarywang.wxpay.bean.notify.WxPayOrderNotifyResult.signType. To index multiple values under a key, use Multimaps.index.
class               : com.github.binarywang.wxpay.bean.notify.WxPayOrderNotifyResult
required-type       : com.github.binarywang.wxpay.bean.notify.WxPayOrderNotifyResult
converter-type      : com.github.binarywang.wxpay.converter.WxPayOrderNotifyResultConverter
line number         : 1
version             : not available
-------------------------------
com.thoughtworks.xstream.converters.ConversionException:

**Comment by binarywang** [comment]
谢谢及时指出，已回滚相关代码
