### ISSUE TITLE
开放平台网页授权通过code获取accessToken，请求报空指针

### ISSUE THREAD

**Issue by mxker** [Wechat-Group/WxJava#2239]
### 简要描述
开放平台网页授权通过code获取accessToken，请求报空指针！！！

### 模块版本情况
* WxJava 模块名: wx_open
* WxJava 版本号: 4.1.0  和 4.1.4.B 都有问题

### 详细描述
获取accesToken方法：oAuth2Service.getAccessToken(request.getCode())，报空指针。问题追溯，组装的路由是正常的，单独提出来访问，能收到微信的返回。但是，到execute的时候，this.requestHttp.getRequestHttpProxy() 出现空指针，this.requestHttp该参数确实没有RequestHttpProxy参数。

**Comment by binarywang** [comment]
oAuth2Service 是如何定义的

**Comment by mxker** [comment]
OAuth2Configuration oAuth2Service = new OAuth2Configuration(openProperties.getAppId(),openProperties.getAppSecret());
WxOAuth2AccessToken accessToken = oAuth2Service.getAccessToken(request.getCode());

直接new的，获取二维码地址也是这样的，是正常的。

**Comment by binarywang** [comment]
`OAuth2Configuration oAuth2Service` 这个是什么鬼？你确定都是使用sdk的代码，没做过改造？

**Comment by mxker** [comment]
继承的这个： WxOpenOAuth2ServiceImpl

**Comment by mxker** [comment]
更改后：
        WxOpenOAuth2ServiceImpl oAuth2Service = new WxOpenOAuth2ServiceImpl(openProperties.getAppId(), openProperties.getAppSecret());
        WxOAuth2AccessToken accessToken = oAuth2Service.getAccessToken(request.getCode());

错误信息：
java.lang.NullPointerException: null
	at me.chanjar.weixin.common.util.http.apache.ApacheSimpleGetRequestExecutor.execute(ApacheSimpleGetRequestExecutor.java:40) ~[weixin-java-common-4.1.4.B.jar:na]
	at me.chanjar.weixin.common.util.http.apache.ApacheSimpleGetRequestExecutor.execute(ApacheSimpleGetRequestExecutor.java:21) ~[weixin-java-common-4.1.4.B.jar:na]
	at me.chanjar.weixin.open.api.impl.WxOpenServiceAbstractImpl.execute(WxOpenServiceAbstractImpl.java:48) ~[weixin-java-open-4.1.4.B.jar:na]

**Comment by binarywang** [comment]
`me.chanjar.weixin.open.api.impl.WxOpenOAuth2ServiceImplTest` 你可以尝试用源码里的这个单元测试调试下看看，问题到底出在哪里

**Comment by mxker** [comment]
报错文件：ApacheSimpleGetRequestExecutor.java  
行数：34行
代码：if (this.requestHttp.getRequestHttpProxy() != null) {
原因：this.requestHttp该对象没有requestHttpProxy 属性，所以报空指针了。

**Comment by binarywang** [comment]
这个问题还没找到原因？

**Comment by yimik** [comment]
确实遇到了，跟了下代码，发现WxOpenServiceApacheHttpClientImpl这个类里面的httpClient是在initHttp()方法中实例化的，initHttp()方法是在setWxOpenConfigStorage(WxOpenConfigStorage wxOpenConfigStorage)方法中调用的；
而WxOpenOAuth2ServiceImpl的构造方法只有appId和appSecret，并不主动调用setWxOpenConfigStorage()，导致httpClient并没有被实例化

**Comment by yimik** [comment]
之前做的开放平台网站授权的时候查了查issues，找到了这个#864，于是就一直用的公众号的sdk，没有出现问题

**Comment by binarywang** [comment]
> 确实遇到了，跟了下代码，发现WxOpenServiceApacheHttpClientImpl这个类里面的httpClient是在initHttp()方法中实例化的，initHttp()方法是在setWxOpenConfigStorage(WxOpenConfigStorage wxOpenConfigStorage)方法中调用的；
> 而WxOpenOAuth2ServiceImpl的构造方法只有appId和appSecret，并不主动调用setWxOpenConfigStorage()，导致httpClient并没有被实例化

看来确实是这样，其实也不是问题，单元测试中其实有init方法，楼主可能没仔细去看，也不愿意去看。

**Comment by bushkarl** [comment]
还是不太好用啊
