### ISSUE TITLE
第三方平台-小程序-提审素材上传接口

### ISSUE THREAD

**Issue by shuaidawang** [Wechat-Group/WxJava#2240]
### 简要描述
第三方平台》小程序审核接口》提审素材上传接口介绍
这个接口没有封装

### 官方文档地址
https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/2.0/api/code/submit_audit.html

截图
https://gitee.com/shuaidawang/notepic/raw/master/20210804154501.png

**Comment by binarywang** [comment]
你确定没有封装？在代码里可以搜到的 `wxa/submit_audit`

**Comment by shuaidawang** [comment]
> 你确定没有封装？在代码里可以搜到的 `wxa/submit_audit`

是提审素材上传接口，在文档下面
这个接口 https://api.weixin.qq.com/wxa/uploadmedia?access_token=ACCESS_TOKEN

**Comment by binarywang** [comment]
哦，是我看错了

**Comment by binarywang** [comment]
建议先自行实现，仿照现有代码，实现起来应该很简单吧

**Comment by shuaidawang** [comment]
> 建议先自行实现，仿照现有代码，实现起来应该很简单吧

嗯嗯，现在是自己实现的，参考了MediaUploadRequestExecutor

**Comment by binarywang** [comment]
欢迎直接PR上来吧
