### ISSUE TITLE
如何通过企业微信第三方应用（WxCpTpService）访问企业内部开发（WxCpService）的接口

### ISSUE THREAD

**Issue by ZhengChuan6415** [Wechat-Group/WxJava#2241]
第三方应用和业内部开发都用共同访问的接口
例如：获取客户列表
https://qyapi.weixin.qq.com/cgi-bin/externalcontact/list?access_token=ACCESS_TOKEN&userid=USERID

项目中已经维护了WxCpTpService实例，但是该类没有ExternalContact相关接口。
如果根据WxCpTpService能拿到一个WxCpService实例，进行相关接口的访问？

**Comment by xiaoliangtang** [comment]
大哥，有无解决

**Comment by wuzhike666** [comment]
你是怎么将WxCpTpService注入使用的呢
