### ISSUE TITLE
微信支付 V3 支持合并订单支付

### ISSUE THREAD

**Issue by lixunhui** [Wechat-Group/WxJava#2259]
实际开发过程中合并订单支付是很实际的业务场景，希望能够支持微信支付 V3合并订单支付

### 官方文档地址
https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter5_1_4.shtml

**Comment by binarywang** [comment]
欢迎先自行参考现有代码实现，毕竟有参照代码，并且你有账号可以调试，实现起来会更快些，否则你可能要等很久。

**Comment by fangzy17** [comment]
com.github.binarywang.wxpay.bean.ecommerce.RefundsRequest 的构造函数为啥是私有，我创建不了实例

**Comment by binarywang** [comment]
该类的作者自己做了限制，你用builder方法构建实例即可
