### ISSUE TITLE
希望支持“扣费服务”功能，很多场景可以用到自动扣费、续费功能

### ISSUE THREAD

**Issue by hyhlmy** [Wechat-Group/WxJava#2262]
https://pay.weixin.qq.com/wiki/doc/api/wxpay_v2/pages/jiekouguize.shtml
1、扣费服务-直连模式
2、扣费服务-服务商模式

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/issues/1253  建议参考下这里的说明
