### ISSUE TITLE
WxMpRedisConfigImpl 分布式锁的实现问题

### ISSUE THREAD

**Issue by daiyun169** [Wechat-Group/WxJava#2265]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号: 4.0.9.B

### 详细描述
类：WxMpServiceHttpClientImpl
方法：
public String getAccessToken(boolean forceRefresh) throws WxErrorException {
    final WxMpConfigStorage config = this.getWxMpConfigStorage();
    if (!config.isAccessTokenExpired() && !forceRefresh) {
      return config.getAccessToken();
    }

    Lock lock = config.getAccessTokenLock();
    boolean locked = false;
    try {
      do {
        locked = lock.tryLock(100, TimeUnit.MILLISECONDS);
        if (!forceRefresh && !config.isAccessTokenExpired()) {
          return config.getAccessToken();
        }
      } while (!locked);

      String url = String.format(GET_ACCESS_TOKEN_URL.getUrl(config), config.getAppId(), config.getSecret());
      try {
        HttpGet httpGet = new HttpGet(url);
        if (this.getRequestHttpProxy() != null) {
          RequestConfig requestConfig = RequestConfig.custom().setProxy(this.getRequestHttpProxy()).build();
          httpGet.setConfig(requestConfig);
        }
        try (CloseableHttpResponse response = getRequestHttpClient().execute(httpGet)) {
          return this.extractAccessToken(new BasicResponseHandler().handleResponse(response));
        } finally {
          httpGet.releaseConnection();
        }
      } catch (IOException e) {
        throw new WxRuntimeException(e);
      }
    } catch (InterruptedException e) {
      throw new WxRuntimeException(e);
    } finally {
      if (locked) {
        lock.unlock();
      }
    }
  }

疑问：这段代码是单机的锁，在分布式环境会不会存在问题？

比如两台机器的线程同时请求了 access_token，在调用 extractAccessToken 保存到 redis 的时候完全不知道先后顺序，可能出现先申请的 access_token 覆盖了后申请的 access_token 导致失效。(后申请的应该是最新有效的)。

WxMpRedisConfigImpl.updateTicket 这个类提示开发人员使用分布式锁，可是在这个地方即使加了分布式锁也是没用的，因为无法知道那个线程先获取到 redis 分布式锁。

假设我的提的问题成立，那么请问我改如何解决这个问题呢？

**Comment by einsitang** [comment]
我看到上面有一段逻辑
```
do {
    locked = lock.tryLock(100, TimeUnit.MILLISECONDS);
    if (!forceRefresh && !config.isAccessTokenExpired()) {
      return config.getAccessToken();
    }
  } while (!locked);
```
表明在取锁失败之后会重新尝试读取config的accessToken，如果你是分布式系统的话，这个config的实现应该是读取缓存（redis）。
所以确保 `WxMpConfigStorage` 的实现是读取缓存（`WxMpRedisConfigImpl`），而分布式锁后也写入缓存，则**你的问题不成立**

**Comment by daiyun169** [comment]
> 我看到上面有一段逻辑
> 
> ```
> do {
>     locked = lock.tryLock(100, TimeUnit.MILLISECONDS);
>     if (!forceRefresh && !config.isAccessTokenExpired()) {
>       return config.getAccessToken();
>     }
>   } while (!locked);
> ```
> 
> 表明在取锁失败之后会重新尝试读取config的accessToken，如果你是分布式系统的话，这个config的实现应该是读取缓存（redis）。 所以确保 `WxMpConfigStorage` 的实现是读取缓存（`WxMpRedisConfigImpl`），而分布式锁后也写入缓存，则**你的问题不成立**

你好，我的意思是两台机器的线程都同时运行到了
String url = String.format(GET_ACCESS_TOKEN_URL.getUrl(config), config.getAppId(), config.getSecret());
这段代码，在更新 access_token 无法保证顺序

**Comment by einsitang** [comment]
> 
> 
> 
> 
> 
> 
> > 我看到上面有一段逻辑
> 
> > 
> 
> > ```
> 
> > do {
> 
> >     locked = lock.tryLock(100, TimeUnit.MILLISECONDS);
> 
> >     if (!forceRefresh && !config.isAccessTokenExpired()) {
> 
> >       return config.getAccessToken();
> 
> >     }
> 
> >   } while (!locked);
> 
> > ```
> 
> > 
> 
> > 表明在取锁失败之后会重新尝试读取config的accessToken，如果你是分布式系统的话，这个config的实现应该是读取缓存（redis）。 所以确保 `WxMpConfigStorage` 的实现是读取缓存（`WxMpRedisConfigImpl`），而分布式锁后也写入缓存，则**你的问题不成立**
> 
> 
> 
> 你好，我的意思是两台机器的线程都同时运行到了
> 
> String url = String.format(GET_ACCESS_TOKEN_URL.getUrl(config), config.getAppId(), config.getSecret());
> 
> 这段代码，在更新 access_token 无法保证顺序

这段代码不正在lock中吗

**Comment by zhaoleiDev** [comment]
> > 我看到上面有一段逻辑
> > ```
> > do {
> >     locked = lock.tryLock(100, TimeUnit.MILLISECONDS);
> >     if (!forceRefresh && !config.isAccessTokenExpired()) {
> >       return config.getAccessToken();
> >     }
> >   } while (!locked);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 表明在取锁失败之后会重新尝试读取config的accessToken，如果你是分布式系统的话，这个config的实现应该是读取缓存（redis）。 所以确保 `WxMpConfigStorage` 的实现是读取缓存（`WxMpRedisConfigImpl`），而分布式锁后也写入缓存，则**你的问题不成立**
> 
> 你好，我的意思是两台机器的线程都同时运行到了 String url = String.format(GET_ACCESS_TOKEN_URL.getUrl(config), config.getAppId(), config.getSecret()); 这段代码，在更新 access_token 无法保证顺序

能执行到这段代码的前提是获取到锁，分布式锁不会两个线程同时获取到
