### ISSUE TITLE
企业微信新增了很多消息卡片接口，辛苦对接下

### ISSUE THREAD

**Issue by adogcode** [Wechat-Group/WxJava#2270]
### 简要描述
企业微信新增了很多消息卡片接口，辛苦对接下

### 官方文档地址
https://work.weixin.qq.com/api/doc/90000/90135/90236#%E6%A8%A1%E6%9D%BF%E5%8D%A1%E7%89%87%E6%B6%88%E6%81%AF

**Comment by binarywang** [comment]
欢迎自行实现提交PR，等待会很辛苦的
