### ISSUE TITLE
入群欢迎语目前还少一个file文件类型的支持呢，辛苦更新下

### ISSUE THREAD

**Issue by Horizon1123** [Wechat-Group/WxJava#2272]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
入群欢迎语目前还少一个file文件类型的支持呢

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__
https://work.weixin.qq.com/api/doc/90001/90143/92599

**Comment by binarywang** [comment]
欢迎直接PR

**Comment by binarywang** [comment]
最新版本已支持
