### ISSUE TITLE
请问什么时候加入实名认证的接口呢?

### ISSUE THREAD

**Issue by liandyao** [Wechat-Group/WxJava#2273]
微信官方开发文档
https://pay.weixin.qq.com/wiki/doc/api/realnameauth.php?chapter=60_2&index=3

**Comment by binarywang** [comment]
欢迎自行实现并提交PR，等待可能会很长时间

**Comment by binarywang** [comment]
期待有好心人可以提交PR代码上来，肯定有人实现了的吧
