### ISSUE TITLE
API网关地址（https://api.weixin.qq.com）是否可以改为动态传入？

### ISSUE THREAD

**Issue by liming1019** [Wechat-Group/WxJava#2274]
### 简要描述
<img width="837" alt="image" src="https://user-images.githubusercontent.com/19259449/130540111-4186ac91-b5ab-44a7-a9cf-dd243418498a.png">
以weixin-java-mini为例，API的网关地址“https://api.weixin.qq.com”目前是写在常量类WxMaApiUrlConstants里的，开发者改不了这个URL。目前我遇到的场景是，我司现有一个网关，希望对接任何第三方API都经过网关，便于日志、监控等，所以希望对于微信的API请求，能在网关层面上转发一次。
我的想法是，这个网关的前缀“https://api.weixin.qq.com”可以动态配置，为了兼容已有版本，可以设置默认值。

**Comment by binarywang** [comment]
你看下config里的是有相关方法可以设置的。

https://github.com/Wechat-Group/WxJava/blob/develop/weixin-java-miniapp/src/main/java/cn/binarywang/wx/miniapp/config/WxMaConfig.java

**Comment by liming1019** [comment]
> 你看下config里的是有相关方法可以设置的。
> 
> https://github.com/Wechat-Group/WxJava/blob/develop/weixin-java-miniapp/src/main/java/cn/binarywang/wx/miniapp/config/WxMaConfig.java

感谢，抱歉，没有认真看文档！
