### ISSUE TITLE
xstream是否可以提升一下版本

### ISSUE THREAD

**Issue by ahuai** [Wechat-Group/WxJava#2276]
\- com.github.binarywang:weixin-java-mp:jar:4.1.7.B:compile
    \- com.github.binarywang:weixin-java-common:jar:4.1.7.B:compile
       \- com.thoughtworks.xstream:xstream:jar:1.4.17:compile
目前xstream的jar包引入的是1.4.17版本 当前版本存在安全漏洞 是否可以提升xstream版本？
![image](https://user-images.githubusercontent.com/31682683/130600034-be64f034-5565-41ba-aee7-a0025ebb16b2.png)

**Comment by binarywang** [comment]
不要太依赖本SDK对依赖项的管理，你其实可以自己手动升级的，本SDK后续（也就是下一版本）依赖版本会升级的
