### ISSUE TITLE
微信订阅号菜单事件重写URL，拼接OPENID

### ISSUE THREAD

**Issue by shengwens** [Wechat-Group/WxJava#2277]
项目：
weixin-java-mp-demo-springboot
代码：
/**
 * @author Binary Wang(https://github.com/binarywang)
 */
@Component
public class MenuHandler extends AbstractHandler {

    @Override
    public WxMpXmlOutMessage handle(WxMpXmlMessage wxMessage,
                                    Map<String, Object> context, WxMpService weixinService,
                                    WxSessionManager sessionManager) {
        String msg = String.format("type:%s, event:%s, key:%s",
            wxMessage.getMsgType(), wxMessage.getEvent(),
            wxMessage.getEventKey());
        if (EventType.VIEW.equals(wxMessage.getEvent())) {
            return null;
        }
       String openId = wxMessage.getOpenId();
       //此处是否可以重写URL，拼写上OPENID
    }

}
微信订阅号想要在点击的菜单URL上带OPENID，
在EventType.VIEW时，是打开默认定义的URL
想要在打开URL前，重写URL，拼写OPENID到url，此处是否可实现呢？

**Comment by binarywang** [comment]
目前看来应该是无法实现
