### ISSUE TITLE
建议增加小程序加密网络通道支持

### ISSUE THREAD

**Issue by supreme94** [Wechat-Group/WxJava#2281]
### 简要描述
这个功能可以避免小程序与开发者后台通信时数据被截取和篡改

### 官方文档地址
https://developers.weixin.qq.com/minigame/dev/api-backend/open-api/internet/internet.getUserEncryptKey.html

**Comment by binarywang** [comment]
欢迎自行PR，看起来不复杂，参考现有代码实现即可
