### ISSUE TITLE
支持从别的地方拿token

### ISSUE THREAD

**Issue by Kirno7** [Wechat-Group/WxJava#2292]
我们公司有个项目组,appId,secret相关信息在他们服务里维护,他们提供了获取token的接口，每次调用微信api的时候 会去他们那拿token,但是WxJava对这些信息有要求必填,可以稍作改动支持这种场景吗？

**Comment by binarywang** [comment]
自定义config

**Comment by pingxin403** [comment]
自定义config是不行的，应该要继承WxCpServiceImpl（在weixin-java-cp中）或者别的Service，重写获取accessToken的逻辑
![image.png](https://i.loli.net/2021/09/14/EXlP6ACvucFh5iz.png)

**Comment by binarywang** [comment]
> 自定义config是不行的，应该要继承WxCpServiceImpl（在weixin-java-cp中）或者别的Service，重写获取accessToken的逻辑 ![image.png](https://camo.githubusercontent.com/d77db4f7cd8001ce2b872c12c1528ab9c1115127dd0e76ace2fb051f4df17e09/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30392f31342f45586c50364143767563466835697a2e706e67)

其实是可以的，你要保证你所展示的代码前面几行总是生效就可以了

**Comment by RefinedMe** [comment]
> 我们公司开项目组,appId,sec ret相关信息在他们服务里维护,他们提供了获取token的接口,每次调用微信api的时候会去要求那拿token,但是WxJava对这些信息有他们必填,可以做支持这种场景吗？

您好,您解决了么.您是怎么处理的
