### ISSUE TITLE
使用 addConfig 配置多个小程序；传入miniappId 未被使用；默认使用 appId 作为key

### ISSUE THREAD

**Issue by dianming** [Wechat-Group/WxJava#2315]
### 简要描述
使用 addConfig 配置多个小程序；传入miniappId 未被使用；默认使用 appId 作为key

### 模块版本情况
* WxJava 模块名: miniapp
* WxJava 版本号:4.1.0

### 详细描述
使用 addConfig 添加第一个；默认使用appId作为MAP key 不合理；我已经传miniappId，因为第一次configMap为空；就默认使用appId作为key，导致我在使用的时候 用miniappId获取不到；

**Comment by linyongfu2013** [comment]
借楼请教个问题
`wx-java-miniapp-spring-boot-starter` 支持配置多个小程序吗？还是得用代码手动添加？

**Comment by binarywang** [comment]
没太看明白问题，欢迎直接PR
