### ISSUE TITLE
服务号后台无法访问服务器URL

### ISSUE THREAD

**Issue by sh2sg** [Wechat-Group/WxJava#2316]
跟这个 SDK 没有直接的关系，本地测试运行良好。但是在部署到服务器后，在设置 URL 时发现的问题，询问一下看有没有类似的经验。

服务号后台设置，不管在服务器设置那里，还是在“微信公众平台接口调试工具”那里，保存 URL 时老是报错 
{"base_resp":{"ret":200302,"err_msg":"verify token fail"}}

而服务器的日志里根本没有收到微信传来的验证请求。

DNS，服务器配置，HTTPS 证书都没问题，用 curl 命令行或者 Postman 里都可以访问 URL 并且得到响应。

以为是域名备案的关系，但是用免费的 webhook 服务比如 https://webhook.site, 或者内网穿透服务比如 ngrok, localtunnel 都没问题，所以应该不是备案的关系。

困扰了很久，究竟是什么问题呢？

**Comment by binarywang** [comment]
你的问题说到底还是网络不通导致的问题，域名因素很大
