### ISSUE TITLE
企业微信客户联系-获取客户朋友圈全部的发表记录 接口目前没看到对接，可以新增吗

### ISSUE THREAD

**Issue by wukang666** [Wechat-Group/WxJava#2318]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
企业微信客户联系-获取客户朋友圈全部的发表记录 接口目前没看到对接，可以新增吗

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by wukang666** [comment]
获取企业全部的发表列表
企业和第三方应用可通过该接口获取企业全部的发表内容。

请求方式：POST(HTTPS)
请求地址：https://qyapi.weixin.qq.com/cgi-bin/externalcontact/get_moment_list?access_token=ACCESS_TOKEN

**Comment by wukang666** [comment]
朋友圈总共5个接口
获取客户朋友圈企业发表的列表
获取客户朋友圈发表时选择的可见范围
获取客户朋友圈发表后的可见客户列表
获取客户朋友圈的互动数据
获取企业全部的发表列表

**Comment by binarywang** [comment]
暂无计划，如果急需此功能，建议参考现有代码自行实现并提交PR，应该很容易实现的。
