### ISSUE TITLE
怎么注入使用WxCpTpService的功能

### ISSUE THREAD

**Issue by wuzhike666** [Wechat-Group/WxJava#2319]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
怎么注入使用WxCpTpService的功能

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号: 4.1.0

### 详细描述
怎么注入使用WxCpTpService的功能，有注入使用WxCpservice的功能，却不知道怎注入使用WxCpTpService的功能

**Comment by binarywang** [comment]
类似的，自己构建实例即可

**Comment by stephenson37** [comment]
同问。
1、WxCpTpDefaultConfigImpl的set方法都废弃了，怎么构造WxCpTpDefaultConfigImpl。
2、WxCpTpService和WxCpServiceOnTpImpl 有什么区别，使用哪个。
