### ISSUE TITLE
有没有代码生成啊，我用企业微信的时候没有

### ISSUE THREAD

**Issue by Ghaker** [Wechat-Group/WxJava#2323]
感觉微信开发就是做网站 ，网站的表多了，来个代码生成可以吗，天天 做增删改查挺烦的，官方出一个代码生成工具就好了
我现在要做小程序，个人微信的

**Comment by binarywang** [comment]
代码生成是其他工具要做的，这个sdk仅是提供微信常用功能和接口对接。

**Comment by Ghaker** [comment]
如果有后台接口就好了，毕竟应该做成平台，程序员都懒

**Comment by Ghaker** [comment]
错了，是后台管理界面

**Comment by Ghaker** [comment]
还是很感谢你的，可以 推荐一下 管理界面和代码生成工具吗？jfinal好像也没带，jeecg和boot带了，不知道jeecgwx-boot,带了没有

**Comment by binarywang** [comment]
请参考首页应用案例，里面有很多

**Comment by Ghaker** [comment]
谢谢啊，脑残了，你下次把最终产品让用户挑选一下吧

**Comment by binarywang** [comment]
选择是你自己的事情了，我无能为力，请记住这只是个SDK就好了。
