### ISSUE TITLE
使用WxJava4.1.0，在weixin-java-cp模块下，WxCpMessageSendResult 返回值缺省msgid字段

### ISSUE THREAD

**Issue by liupenggithub** [Wechat-Group/WxJava#2329]
### 问题：
* 我现在需要在企业微信应用中，将发送的消息，撤销。发现最新版本WxJava 4.1.0版本中，WxCpMessageSendResult 没有返回msgid字段
### 请问：
* 我使用的版本号不对，还是说WxJava不提供msgid字段呢？我看源码中WxCpMessageSendResult返回对象中是有msgid的

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号:WxJava4.1.0
### 下载的WxJava4.1.0
![image](https://user-images.githubusercontent.com/19922903/134856998-df5802dc-b06f-42e4-a4fb-7eb19d3f3432.png)
### 源码
![image](https://user-images.githubusercontent.com/19922903/134857308-1cf70427-74d1-4b2d-af70-6f93c88bd402.png)

**Comment by binarywang** [comment]
楼主看到的源码是最新版本的，还没发布新版本的代码，所以会跟你使用的发布版本有差异，很正常
