### ISSUE TITLE
企业微信第三方WxCpTpService怎么用

### ISSUE THREAD

**Issue by stephenson37** [Wechat-Group/WxJava#2330]
您好，请问：
1、WxCpTpDefaultConfigImpl的set方法都废弃了，怎么构造WxCpTpDefaultConfigImpl。
2、WxCpTpService和WxCpServiceOnTpImpl 有什么区别，使用哪个。
3、有没有企业微信第三方相关文档和示例

**Comment by lkjxzbp** [comment]
同样有这疑问，里面还有个 providerSecret 没有set方法。然后corpSecret这个字段都没有用到。   不行只能自己实现WxCpTpConfigStorage了

**Comment by kiwiflydream** [comment]
同样的问题
