### ISSUE TITLE
微信平台用户信息接口调整

### ISSUE THREAD

**Issue by BoolTrue** [Wechat-Group/WxJava#2331]
### 简要描述
微信平台获取用户信息的接口都变了，全平台都去掉了性别和地区信息。

### 官方文档地址
https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncement&announce_id=11632637451RQs8y

**Comment by shenyao2333** [comment]
如果不修改的话，性别字段是不是只是为空，如果没有使用这个字段做了其他业务，是不是不会报错。

**Comment by nadirvishun** [comment]
这里是更加详细的内容：[微信公众平台用户信息相关接口调整公告](https://developers.weixin.qq.com/community/develop/doc/00028edbe3c58081e7cc834705b801?highLine=%25E6%2580%25A7%25E5%2588%25AB)，对原有的应该不会造成影响：
![image](https://user-images.githubusercontent.com/5761981/137250454-cd69d620-5246-4476-9e38-bc08306c0a3d.png)
