### ISSUE TITLE
TagGroup的Order的类型不一致

### ISSUE THREAD

**Issue by Winson2018** [Wechat-Group/WxJava#2336]
### 字段类型不一致
WxCpUserExternalTagGroupInfo和WxCpUserExternalTagGroupList里的TagGroup的order字段类型不一致

![企业微信截图_16329044262034](https://user-images.githubusercontent.com/42804229/135233548-68e177fc-28a7-4a2e-b6ff-fcac1e29212e.png)

![企业微信截图_16329045002480](https://user-images.githubusercontent.com/42804229/135233583-49bdb663-6edb-423f-b239-3d551d97d65b.png)

**Comment by binarywang** [comment]
楼主其实可以直接提交PR修复这个问题

**Comment by binarywang** [comment]
最新版本已修复此问题
