### ISSUE TITLE
是否有对template_card的支持在http://binary.ac.cn/weixin-java-cp-javadoc/

### ISSUE THREAD

**Issue by CoreyZhou88** [Wechat-Group/WxJava#2341]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by CoreyZhou88** [comment]
需要使用https://open.work.weixin.qq.com/api/doc/90001/90143/90372#%E6%96%87%E6%9C%AC%E9%80%9A%E7%9F%A5%E5%9E%8B

**Comment by binarywang** [comment]
有支持的，看源码即可
