### ISSUE TITLE
现有功能不满足个人需求！！场景：saas系统中，每个客户都有自己的企微、微信小程序、公众号

### ISSUE THREAD

**Issue by huchuansai** [Wechat-Group/WxJava#2342]
我的场景是saas系统中，每个客户都有自己的企微，微信小程序公众号，所以我的appid,token,secret都不是固定的。
我把这些信息存放到数据库中，从每个请求中根据不同的企业id去获取不同的appid,token,secret，
然后再用此项目去走接下来的流程，但是目前项目里的这些参数都是写死且指定在yml文件里的。
请思考一下我的场景并适当性的提出解决方案，谢谢，如果我的issue描述的不清楚，请及时告知。

**Comment by xyh-994** [comment]
正常来说..
saas的系统  
要处理小程序、公众号你应该用开放平台的第三方平台去拿到他们的授权然后就可以管理
企微同理要用企微服务商去获取授权然后来管理。。。

应该不是要用户自动输入app、token、secret这些东西才对。。。

**Comment by huchuansai** [comment]
> 正常来说.. saas的系统 要处理小程序、公众号你应该用开放平台的第三方平台去拿到他们的授权然后就可以管理 企微同理要用企微服务商去获取授权然后来管理。。。
> 
> 应该不是要用户自动输入app、token、secret这些东西才对。。。

但是目前的springboot-starter的application.yml中appid这些东西都是必填的；
简而言之，这套sdk能用来做第三方平台或者服务商的开发吗？

**Comment by xyh-994** [comment]
> > 正常来说.. saas的系统 要处理小程序、公众号你应该用开放平台的第三方平台去拿到他们的授权然后就可以管理 企微同理要用企微服务商去获取授权然后来管理。。。
> > 应该不是要用户自动输入app、token、secret这些东西才对。。。
> 
> 但是目前的springboot-starter的application.yml中appid这些东西都是必填的； 简而言之，这套sdk能用来做第三方平台或者服务商的开发吗？

open的starter可以用来开发公众号跟小程序的授权获取。
pay的starter可以用来开发微信支付服务商的内容，不过普通服务商的需要自己再处理下
企微服务商没有starter包，接口的实现大部分都有了。得自己去模仿一下其他starter包，最好是open的去做一个注入

**Comment by springcloud-boot** [comment]
满足的. 我就是服务商开发. 你要稍微改一丢丢的.  刷新accesstoken的,初始化,accesstoken的 就行

**Comment by springcloud-boot** [comment]
for(多个公众号){
 map.put(appId,  WxMpService(自己去创建 继承BaseWxMpServiceImpl));
}

**Comment by xyh-994** [comment]
> 满足的. 我就是服务商开发. 你要稍微改一丢丢的. 刷新accesstoken的,初始化,accesstoken的 就行

顺带问句， 微信支付服务商的。是不是得自己重写部分内容啊。。然后用 v3的接口？

**Comment by springcloud-boot** [comment]
微信支付我没用这个包. 
这个包,我只用来做,获取openId,菜单啊,素材啊,推送 非支付的功能.

支付是按照微信商户平台的文档来写的

**Comment by tony2y** [comment]
@sai117 请问下，目前遇到和您同样的问题，微服务、多租户、读取数据库配置状态下 ，有解决方式了吗
