### ISSUE TITLE
关于服务商分账接口返回参数遗漏的问题

### ISSUE THREAD

**Issue by xiaozhou322** [Wechat-Group/WxJava#2346]
### 简要描述
服务商单次分账接口   https://api.mch.weixin.qq.com/secapi/pay/profitsharing   返回参数有遗漏， 比如：status 和  receivers
 
接口文档地址：https://pay.weixin.qq.com/wiki/doc/api/allocation_sl.php?chapter=25_1&index=1

### 模块版本情况
* WxJava 模块名:  服务商分账接口
* WxJava 版本号:  4.1.9.B

### 详细描述
微信服务商分账接口  字段有遗漏， 这边调用接口返回需要用到这两个参数
分账单状态：status 
分账接收方列表：receivers

**Comment by binarywang** [comment]
楼主其实可以自行PR，这个简单问题

**Comment by binarywang** [comment]
这两个参数最新版本已添加
