### ISSUE TITLE
微信加密问题

### ISSUE THREAD

**Issue by ryanfan219** [Wechat-Group/WxJava#2348]
### 简要描述
SHA1.gen 加密参数问题

### 模块版本情况
* WxJava 模块名: wexin-java-mp
* WxJava 版本号:4.1.9

### 详细描述
原始代码：加密字符串与微信给过来的加密串不匹配
String signature = SHA1.gen(this.token, timeStamp, nonce,encryptedXml);
修改后：
String signature = SHA1.gen(this.token, timeStamp, nonce)
可以匹配
我不太确定这是不是BUG,但我这里确实有这个问题

### 日志
me.chanjar.weixin.common.error.WxRuntimeException: 加密消息签名校验失败
	at me.chanjar.weixin.common.util.crypto.WxCryptUtil.decrypt(WxCryptUtil.java:225)
	at me.chanjar.weixin.mp.bean.message.WxMpXmlMessage.fromEncryptedXml(WxMpXmlMessage.java:713)

**Comment by ryanfan219** [comment]
已解决

**Comment by chenyuhua321** [comment]
> 已解决

你好，请问你是如何解决这个问题的呢
