### ISSUE TITLE
微信公众号拉取历史关注用户的时候,会丢失数据 V3.7.0

### ISSUE THREAD

**Issue by springcloud-boot** [Wechat-Group/WxJava#2351]
多线程 http请求超时时, 未有重试.导致池满失败.
BaseWxMpServiceImpl. 298行
源码--
 do {
      try {
        return this.executeInternal(executor, uri, data);
      } catch (WxErrorException e) {
        if (retryTimes + 1 > this.maxRetryTimes) {
          log.warn("重试达到最大次数【{}】", maxRetryTimes);
          //最后一次重试失败后，直接抛出异常，不再等待
          throw new RuntimeException("微信服务端异常，超出重试次数");
        }

        WxError error = e.getError();
        // -1 系统繁忙, 1000ms后重试 ************
      //**这里不可能是-1, 因为执行的代码没有存入errorcode**
        if (error.getErrorCode() == -1) {
          int sleepMillis = this.retrySleepMillis * (1 << retryTimes);
          try {
            log.warn("微信系统繁忙，{} ms 后重试(第{}次)", sleepMillis, retryTimes + 1);
            Thread.sleep(sleepMillis);
          } catch (InterruptedException e1) {
            throw new RuntimeException(e1);
          }
        } else {
          throw e;
        }
      }
    } while (retryTimes++ < this.maxRetryTimes);

**Comment by springcloud-boot** [comment]
目前解决办法,自己捕获,错误描述, 是http超时msg时,重试

**Comment by binarywang** [comment]
标题描述跟实际问题不一致？
