### ISSUE TITLE
【求助】请问下图中这种也是公众号模板消息吗？

### ISSUE THREAD

**Issue by edwards19900128** [Wechat-Group/WxJava#2355]
### 简要描述
下图所示,有红色标记的图，
为啥他的label能对齐,而且是灰色的 ？
第二就是那段灰色的文字是{{first.DATA}}内容吗？

### 示例图
![image](https://user-images.githubusercontent.com/11594850/138477089-45cb36d9-9b88-48d5-ba21-f4393a75e517.png )
![image](https://user-images.githubusercontent.com/11594850/138477251-84ae7ea9-5a58-4673-84a1-08c018b54f52.png)

**Comment by binarywang** [comment]
有可能是行业特殊配置

**Comment by edwards19900128** [comment]
> 有可能是行业特殊配置

好吧...查了半天文档和微信那边的文档说明....还以为是我哪里少设置了...
