### ISSUE TITLE
第三方平台获取用户信息接口的方法没有?

### ISSUE THREAD

**Issue by wankang189** [Wechat-Group/WxJava#2357]
如果网页授权作用域为 snsapi_userinfo，则此时开发者可以通过 access_token 和 openid 拉取用户信息了。

GET https://api.weixin.qq.com/sns/userinfo?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN

**Comment by binarywang** [comment]
必须有的。
自己搜索源码就知道在哪里了
