### ISSUE TITLE
关于外部依赖扩展的一点思考与建议

### ISSUE THREAD

**Issue by shinestmt** [Wechat-Group/WxJava#2358]
关于外部依赖扩展的一点思考与建议:
=========================================
## json序列化
可考虑提供一个 JsonCodec 的接口, 包含 encode 和 decode, 其具体实现按需选择即可.  
gson / jackson / fastjson 等常见的实现, WxJava 可考虑直接提供一二, 若不提供, 由使用者自行实现亦可.  
具体实现可自行选择, 也可自行定制具体的解析参数.  
当所选库存在漏洞需要解决时, 可轻易切换或定制修复, 而不依赖 WxJava  

## xml 序列化
提供一个 XmlCodec 接口, 包含 encode 和 decode, 其具体实现按需选择即可.  
dom / dom4j / sax 等常见的实现, WxJava 可考虑直接提供一二, 若不提供, 由使用者自行实现亦可  
具体实现可自行选择, 也可自行定制具体的解析参数.  
当所选库存在漏洞需要解决时, 可轻易切换或定制修复, 而不依赖 WxJava  

## http请求执行
我了解了一下相关的 RequestExecutor 接口, 其是否只需要以下方法:
```
    // 发起 get 请求
    String get(String uri, Map<String, String> queryMap);
    // 发起 post 请求
    String post(String uri, Map<String, String> queryMap, Object body);
    // 发起上传文件的请求
    String upload(String uri, Map<String, String> queryMap, File file);
    // 发起下载文件的请求, 提供文件流的 Consumer 
    void download(String uri, Map<String, String> queryMap, Object body, Consumer<InputStream> resultConsumer);
```
以上接口定义如果能满足要求, 依然是以上套路  
HttpURLConnection / HttpClient / OkHttp / RestTemplate 等常见的实现, WxJava 直接提供一二即可  
至于代理, 由其 client 自行实现, RequestExecutor 只负责执行请求 , 比如 HttpClientRequestExecutor  
```
public class HttpClientRequestExecutor {
    public (HttpClient httpClient, JsonCodec jsonCodec) {
        // httpClient 已经自己设有代理
    }
}
```

**Comment by langlan** [comment]
赞一个

**Comment by binarywang** [comment]
谢谢楼主的好建议，欢迎直接提交PR代码

**Comment by scruel** [comment]
WxMpXmlMessage 之类的生成只能 fromXml，而且不能指定自己的对象传到 route 是挺醉的。。。

**Comment by scruel** [comment]
后续看时间安排，调研后把 xml/json 部分的三方依赖库标为 optional，抽离当前的实现，支持常用的三方库解析。
调研了一下感觉不是很好实现，主要是有一些 POJO 需要注明专用的注解，后面看看有没有啥办法吧。

**Comment by shinestmt** [comment]
> 后续看时间安排，调研后把 xml/json 部分的三方依赖库标为 optional，抽离当前的实现，支持常用的三方库解析。 调研了一下感觉不是很好实现，主要是有一些 POJO 需要注明专用的注解，后面看看有没有啥办法吧。

我仔细看了一下, xml/json的序列化耦合太深, 可能很难处理了
http执行器, 处理起来工作量也非常大, 毕竟接口太多.
😂

**Comment by scruel** [comment]
> > 后续看时间安排，调研后把 xml/json 部分的三方依赖库标为 optional，抽离当前的实现，支持常用的三方库解析。 调研了一下感觉不是很好实现，主要是有一些 POJO 需要注明专用的注解，后面看看有没有啥办法吧。
> 
> 我仔细看了一下, xml/json的序列化耦合太深, 可能很难处理了 http执行器, 处理起来工作量也非常大, 毕竟接口太多. 😂

我忙别的暂时放弃了，确实有点难整了，所以一个良好的基本代码级别架构也很重要啊，要不：
“当前仓库已存档，请大家点击访问船新 WxJava-Better”😂
