### ISSUE TITLE
使用微信公众平台测试号进行接口测试开发，网页授权报48001错误

### ISSUE THREAD

**Issue by lirunsheng** [Wechat-Group/WxJava#2359]
### 简要描述
使用网页授权功能，构建网页授权url，构建后的api接口域名错误

### 模块版本情况
* WxJava 模块名: wx-java-mp-spring-boot-starter
* WxJava 版本号: 4.1.0

### 详细描述
使用wx-java-mp-spring-boot-starter模块进行微信公众号开发，本人使用微信公众平台测试号进行本地开发，配置好以后，使用该模块可以与微信服务器进行通讯，包括用户关注、发送消息都可以进行响应，但是使用网页授权时，提示api未授权

微信公众平台配置格式
`wx:
    mp:
        app-id : 
        secret : 
        token : 
        aes-key :
        config-storage:
            type : redistemplate
            key-prefix : wx
            redis :
                host : 192.168.1.252
                port : 6379
            http-client-type : httpclient
            http-proxy-host :
            http-proxy-port :
            http-proxy-username :
            http-proxy-password :`

这是构建授权url
`@PassToken
    @GetMapping("/authorization/url")
    public String test() throws WxErrorException {
        String redirectUrl  = "http://hhht.free.idcfengye.com/api/callback";
        String s = mpService.getOAuth2Service().buildAuthorizationUrl(redirectUrl,  WxConsts.OAuth2Scope.SNSAPI_BASE, null);
        return "<script type=\"text/javascript\">window.location.href=\""+s+"\"</script>";
    }`

构建后的url是
`https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxc8bd13ceb94dbb9c&redirect_uri=http%3A%2F%2Fhhht.free.idcfengye.com%2Fapi%2Fcallback&response_type=code&scope=snsapi_base&state=&connect_redirect=1#wechat_redirect`

这是授权回调接口
`@PassToken
@GetMapping("/callback")
    public String callback(@RequestParam("code") String code){
        WxOAuth2AccessToken accessToken = null;
        try {
            accessToken = mpService.getOAuth2Service().getAccessToken(code);
            System.out.println(mpService.getWxMpConfigStorage().getAppId());
            System.out.println(accessToken);
            System.out.println("=================");
            WxOAuth2UserInfo userInfo = mpService.getOAuth2Service().getUserInfo(accessToken, null);
            if (userInfo != null){
                System.out.println(userInfo.getOpenid());
            }else{
                System.out.println("未获取到数据");
            }
            return accessToken.getOpenId();
        } catch (WxErrorException e) {
            e.printStackTrace();
            return e.getMessage();
        }
    }`
调取接口后报错
`错误代码：48001, 错误信息：api 功能未授权，请确认公众号已获得该接口，可以在公众平台官网 - 开发者中心页中查看接口权限，微信原始报文：{"errcode":48001,"errmsg":"api unauthorized, rid: 61791374-5d255eb5-67f84bb7"}`

使用PHP调用接口无此问题可以获取用户信息

**Comment by binarywang** [comment]
确定是同样的参数和接口？

**Comment by lirunsheng** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/WxJava"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月31日(星期天) 晚上11:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] 使用微信公众平台测试号进行接口测试开发，网页授权报48001错误 (Issue #2359)





 
确定是同样的参数和接口？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.&nbsp;




我确认 ，希望能够匹配微信的沙盒模式
