### ISSUE TITLE
视频号下单异常

### ISSUE THREAD

**Issue by xiehn** [Wechat-Group/WxJava#2362]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
视频号下单异常，原因是 ：WxMaShopOrderDetail.WxMaShopPayInfo.payMethod,,,字段和微信文档表述不一致。
问题1：微信的文档是 pay_method_type，不是pay_method
问题2：微信的文档pay_method_type是number类型，不是string

### 模块版本情况
<artifactId>weixin-java-pay</artifactId>
<version>4.1.9.B</version>

### 详细描述
视频号下单错误，是支付方式字段和微信的文档不一致。pay_method_type，请在下个版本里修复一下。

**Comment by binarywang** [comment]
这个其实最新代码已经修复
