### ISSUE TITLE
WxCpUserExternalGroupChatInfo.class缺少字段

### ISSUE THREAD

**Issue by Winson2018** [Wechat-Group/WxJava#2366]
WxCpUserExternalGroupChatInfo.GroupMember少了group_nickname和name两个字段
![企业微信截图_1635772777594](https://user-images.githubusercontent.com/42804229/139678037-9a5d465b-4126-49dc-a45d-6d68e2ab82a3.png)

**Comment by binarywang** [comment]
#2209 已添加
