### ISSUE TITLE
WxOAuth2UserInfo为何删除了city等字段？

### ISSUE THREAD

**Issue by yeluowuhen52** [Wechat-Group/WxJava#2368]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: weixin-java-common
* WxJava 版本号:4.2.0

### 详细描述
4.2.0的发布版中，WxOAuth2UserInfo删除了city等字段，但是我查阅了微信服务号官方的文档，发现并没有删除
https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html#3
![Dingtalk_20211102143842](https://user-images.githubusercontent.com/5179916/139798470-fe84c225-024e-4410-98df-21417f8a5b03.jpg)
![Dingtalk_20211102143805](https://user-images.githubusercontent.com/5179916/139798551-74c350f4-83e6-400d-a44a-0ebca033d2c4.jpg)

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by binarywang** [comment]
注意看文档，这些字段已置空，属于无效字段

**Comment by binarywang** [comment]
https://developers.weixin.qq.com/community/develop/doc/00028edbe3c58081e7cc834705b801?highLine=%25E6%2580%25A7%25E5%2588%25AB

**Comment by yeluowuhen52** [comment]
感谢回复
