### ISSUE TITLE
调用微信支付V3查询订单关闭订单等接口报错

### ISSUE THREAD

**Issue by cuixiren** [Wechat-Group/WxJava#2369]
报错信息：
java.lang.NoSuchMethodError: com.google.common.base.CharMatcher.whitespace()Lcom/google/common/base/CharMatcher;
调用接口：
WxPayOrderQueryV3Result queryOrderV3(WxPayOrderQueryV3Request var1) throws WxPayException;
void closeOrderV3(WxPayOrderCloseV3Request var1) throws WxPayException;
模块名：
<weixin-java-pay.version>4.2.0</weixin-java-pay.version>
JDK版本：
1.8

谢谢帮助

**Comment by binarywang** [comment]
很明显是你的guava版本问题，请参考wiki常见问题进行修复

**Comment by cuixiren** [comment]
> 很明显是你的guava版本问题，请参考wiki常见问题进行修复

好的，感谢回复

**Comment by cuixiren** [comment]
问题可能是swagger內部的guava依赖冲突，排除后报错消失
![image](https://user-images.githubusercontent.com/60409684/139811278-b3ad94c3-6182-4a8b-8313-3728bc4eeb49.png)
