### ISSUE TITLE
调用微信支付createOrderV3接口，带下划线命名的参数丢失

### ISSUE THREAD

**Issue by cuixiren** [Wechat-Group/WxJava#2371]
传入json：
{
        "out_trade_no": "1217752501201407033233368318",
	"description": "QQ公仔",
	"notify_url": "https://weixin.qq.com/",
	"amount": {
		"total": 1,
		"currency": "CNY"
	},
	"payer": {
		"openid": "7777777UGa12B2Hz18m9Gz"
	}
}
报错信息：
outTradeNo=null,notifyUrl=null,
【异常信息】：输入源“/body/out_trade_no”映射到字段“商户订单号”必填性规则校验失败，此字段为必填项
传入参数
调用接口：
<T> T createOrderV3(TradeTypeEnum tradeType, WxPayUnifiedOrderV3Request request) throws WxPayException;
模块名：
<weixin-java-pay.version>4.2.0</weixin-java-pay.version>
JDK版本：
1.8

在wiki中没找到相关问题

**Comment by binarywang** [comment]
你的json是怎么传入request对象的？

**Comment by cuixiren** [comment]
> 你的json是怎么传入request对象的？

直接将json传入body，用WxPayUnifiedOrderV3Request这个类做接收。
  @PostMapping("/createOrderV3")
  public <T> T createOrderV3(@RequestBody WxPayUnifiedOrderV3Request request) throws WxPayException {
    System.out.println("测试数据"+request);
    return this.wxService.createOrderV3(JSAPI,request);
  }

**Comment by wuchubuzai2018** [comment]
不建议直接用WxPayUnifiedOrderV3Request对象作为参数接收条件，可以自己自定义一个业务参数对象，然后增加JSON字段映射的注解进行实现

**Comment by binarywang** [comment]
楼上说的对
