### ISSUE TITLE
企业号的创建企业群发接口已升级，求更新

### ISSUE THREAD

**Issue by honeybeeChu** [Wechat-Group/WxJava#2381]
# 企业号的创建企业群发接口（https://qyapi.weixin.qq.com/cgi-bin/externalcontact/add_msg_template?access_token=ACCESS_TOKEN）已升级，希望接口代码升级。

### 官方文档地址
https://work.weixin.qq.com/api/doc/90000/90135/92135

**Comment by binarywang** [comment]
麻烦给下具体升级信息，方便更新。或者如果楼主更清楚，欢迎直接PR进行更新

**Comment by azouever** [comment]
develop上面代码已经有了
here:https://github.com/Wechat-Group/WxJava/pull/2391#issue-1055844504
close吧

**Comment by azouever** [comment]
> 麻烦给下具体升级信息，方便更新。或者如果楼主更清楚，欢迎直接PR进行更新

develop上面已经有代码了
here:https://github.com/Wechat-Group/WxJava/pull/2391#issue-1055844504
close吧
