### ISSUE TITLE
微信支付-服务商模式时，子商户在自身的小程序内支付时的问题

### ISSUE THREAD

**Issue by hjshiwbd** [Wechat-Group/WxJava#2383]
4.2.0版本完善了很多新东西，更方便了，大大们真给力！

我在用这个版本做服务商支付的时候遇到点问题，特来请教一下哈。

调用的接口是
https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter4_1_1.shtml

配置初始化、请求参数等等的先略过，应该和本次问题无关。

支付场景是
签约了服务商的子商户在自身关联的小程序内拉起支付

我调用的sdk方法是WxPayService.getEcommerceService().partnerTransactions()，接口调用成功。
再用返回的PayInfo去微信小程序内拉起js支付的时候报错说签名失败
代码如下
`
TransactionsResult.JsapiResult result2 = payService.getEcommerceService().partnerTransactions(TradeTypeEnum.JSAPI, request);
`

个人解决：
更换使用sdk的另一个方法，然后手动计算签名，得到payinfo，再用这个payinfo去小程序端进行js支付，支付成功。
核心区别就是在getPayInfo签名时的第二个参数，我用subAppId替换了原来partnerTransactions()方法内的第二个参数spAppId
代码如下
`
TransactionsResult result = payService.getEcommerceService().partner(TradeTypeEnum.JSAPI, request);
TransactionsResult.JsapiResult payInfo = result.getPayInfo(TradeTypeEnum.JSAPI, request.getSubAppid(),
                    request.getSpMchid(), payService.getConfig().getPrivateKey());
`

所以请问EcommerceService类的partner()和partnerTransactions()方法的区别是什么呢

**Comment by lnynj** [comment]
微信文档上-小程序调起支付API->写了 “若下单时候传了sub_appid,须为sub_appid的值。”

**Comment by heyucong** [comment]
TransactionsResult transactionsResult = payService.getEcommerceService().partner(TradeTypeEnum.JSAPI, request);

            TransactionsResult.JsapiResult result = transactionsResult.getPayInfo(TradeTypeEnum.JSAPI ,request.getSubAppid(), request.getSubMchid() , payService.getConfig().getPrivateKey());

V3的接口，我们前段时间都切换过来了，也花了点时间研究工具里的方法，一开始也遇到签名失败，后来也解决了，现在稳定使用了一段时间了
上边那边代码是可以正常使用的

**Comment by chengAndcheng** [comment]
> 



> ```
>         TransactionsResult transactionsResult = payService.getEcommerceService().partner(TradeTypeEnum.JSAPI, request);
> 
>         TransactionsResult.JsapiResult result = transactionsResult.getPayInfo(TradeTypeEnum.JSAPI ,request.getSubAppid(), request.getSubMchid() , payService.getConfig().getPrivateKey());
> ```
> 
> V3的接口，我们前段时间都切换过来了，也花了点时间研究工具里的方法，一开始也遇到签名失败，后来也解决了，现在稳定使用了一段时间了 上边那边代码是可以正常使用的

别的接口正常，就这个签名失败。麻烦你怎么解决的？
