### ISSUE TITLE
jar包里面缺少WxOpenMaPrivacyService

### ISSUE THREAD

**Issue by aouwuu** [Wechat-Group/WxJava#2388]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: weixin-java-open
* WxJava 版本号:4.2.0

### 详细描述
阿里云下载的weixin-java-open 缺少WxOpenMaPrivacyService

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by binarywang** [comment]
请确认下你要的东西是不是该版本的
