### ISSUE TITLE
默认使用的ApacheHttpClient，不能配置重试策略

### ISSUE THREAD

**Issue by haoyanbing** [Wechat-Group/WxJava#2390]
默认使用的ApacheHttpClient，不能配置重试策略么，遇到调用微信接口，偶尔报 443:failed to responsed错误，想加个重试策略，发现好像加不了。
![image](https://user-images.githubusercontent.com/20509387/142129805-6ab2ca66-3003-4d24-b9bf-e6896af276e9.png)

**Comment by binarywang** [comment]
其实你可以提供个PR代码
