### ISSUE TITLE
依赖的是4.2版本 但是jar包缺少 增加为小程序设置用户隐私指引的相关接口 相关实现类

### ISSUE THREAD

**Issue by yujiain2008** [Wechat-Group/WxJava#2393]
### 简要描述
依赖的是4.2版本 但是jar包缺少 增加为小程序设置用户隐私指引的相关接口 相关实现类

### 模块版本情况
* WxJava 模块名: weixin-java-open
* WxJava 版本号:4.2.0

### 详细描述
依赖的是4.2版本 但是jar包缺少 增加为小程序设置用户隐私指引的相关接口 相关实现类
WxOpenMaPrivacyService.java 相关实现类没有，依赖引用4.2版本

**Comment by binarywang** [comment]
最新版本已实现
