### ISSUE TITLE
企业微信接口更新

### ISSUE THREAD

**Issue by yuner523** [Wechat-Group/WxJava#2398]
# 希望更新企业微信相关接口

### 比如[获取客户群列表](https://work.weixin.qq.com/api/doc/90000/90135/92120)
- 4.1.1版本使用offset+limit分页，企业微信将不再支持这种方案
> 旧版接口以offset+limit分页，要求offset+limit不能超过50000，该方案将废弃，请改用cursor+limit分页

**Comment by huayanYu** [comment]
何不提交PR~
