### ISSUE TITLE
weixin-java-miniapp 4.1.0版本中 WxMaMessage 没有TemplateId、SubscribeStatusString等相关属性

### ISSUE THREAD

**Issue by jiangxiulong** [Wechat-Group/WxJava#2400]
只有这些信息{"ToUserName":"gh_d0fbe457547","FromUserName":"o1TAR5TYAtcIYI8765yyudfhfghwe","CreateTime":1637563412,"MsgType":"event","Event":"subscribe_msg_popup_event"}
不能确定允许了什么模版
请问是有其他方式获取还是就没有 谢谢

**Comment by binarywang** [comment]
欢迎直接提交PR，有的属性可能是后面加的
