### ISSUE TITLE
依赖优化

### ISSUE THREAD

**Issue by jobmission** [Wechat-Group/WxJava#2402]
建议对依赖lib进行优化处理，引入后打出的包直接增加了好几MB，在k8s环境中不占优势，被迫瘦身。

**Comment by binarywang** [comment]
其实之前版本已经做过多次优化了，不过还是非常欢迎你直接PR，优化你认为可以精简的依赖。

**Comment by wangqinggo** [comment]
> 其实之前版本已经做过多次优化了，不过还是非常欢迎你直接PR，优化你认为可以精简的依赖。

你好，我还发现有些依赖冲突，我可以pr吗？

**Comment by wangqinggo** [comment]
> 其实之前版本已经做过多次优化了，不过还是非常欢迎你直接PR，优化你认为可以精简的依赖。



> 其实之前版本已经做过多次优化了，不过还是非常欢迎你直接PR，优化你认为可以精简的依赖。

使用maven-helper查看模块的结果
![image](https://user-images.githubusercontent.com/31787562/143431556-c291a334-9137-49a6-ab2f-0d29b23c47e0.png)
