### ISSUE TITLE
4.2.0 企业微信 获取企业的全部群发记录接口有误  WxCpExternalContactServiceImpl

### ISSUE THREAD

**Issue by hjaaa** [Wechat-Group/WxJava#2404]
![image](https://user-images.githubusercontent.com/37679630/143367374-08bb0129-42b5-4307-8342-2fc774d7e7c9.png)

![image](https://user-images.githubusercontent.com/37679630/143367022-8ba3c935-23b7-4f95-b1ca-555cea163b6a.png)
![image](https://user-images.githubusercontent.com/37679630/143367107-86f78dfc-0e18-4fdb-8f49-fa002863ca83.png)

**Comment by binarywang** [comment]
为啥不直接提交PR进行修复呢？

**Comment by binarywang** [comment]
最新代码其实已经修复
