### ISSUE TITLE
功能优化：分析了一下各个模块的依赖告警，存在一些未使用的但声明的依赖

### ISSUE THREAD

**Issue by wangqinggo** [Wechat-Group/WxJava#2406]
优化依赖 #2402 

### 详细描述
分析报告如下：的确存在一些优化点
![unused1](https://user-images.githubusercontent.com/31787562/143439359-6d27a159-9e7e-45c0-bd8e-ff5602932da6.png)
![unsed2](https://user-images.githubusercontent.com/31787562/143439462-ec0e5f00-1061-45e7-a52e-74d6a5cbd9e9.png)

**Comment by wangqinggo** [comment]
如果有需要我可以提个PR优化各个模块，然后通过测试用例再PR

**Comment by binarywang** [comment]
非常欢迎提交PR

**Comment by binarywang** [comment]
楼主可以继续了
