### ISSUE TITLE
wx-java-mp-starter无法使用默认的JedisPool?

### ISSUE THREAD

**Issue by shaoguanlee** [Wechat-Group/WxJava#2407]
小白不懂求问,以下代码似乎无法使用SpringContext里的JedisPool

WxMpStorageAutoConfiguration.java
```
  @Value("${wx.mp.config-storage.redis.host:")
  private String redisHost; 

  private WxMpConfigStorage jedisConfigStorage() {
    JedisPoolAbstract jedisPool;
    if (StringUtils.isNotEmpty(redisHost) || StringUtils.isNotEmpty(redisHost2)) {
      jedisPool = getJedisPool();
    } else {
      jedisPool = applicationContext.getBean(JedisPool.class);
    }
    WxRedisOps redisOps = new JedisWxRedisOps(jedisPool);
    WxMpRedisConfigImpl wxMpRedisConfig = new WxMpRedisConfigImpl(redisOps,
        wxMpProperties.getConfigStorage().getKeyPrefix());
    setWxMpInfo(wxMpRedisConfig);
    return wxMpRedisConfig;
  }
```

这个地方`redisHost`恒等于`${wx.mp.config-storage.redis.host:`
是不是应该写成`${wx.mp.config-storage.redis.host:}`或者修改以下代码

https://github.com/Wechat-Group/WxJava/blob/95d130d92790ed0f4dc6554d9f9193cbe54a5b51/spring-boot-starters/wx-java-mp-spring-boot-starter/src/main/java/com/binarywang/spring/starter/wxjava/mp/config/WxMpStorageAutoConfiguration.java#L84

StringUtils.isNotEmpty(redisHost)
==>
StringUtils.isNotEmpty(wxMpProperties.getConfigStorage().getRedis().getHost())

**Comment by binarywang** [comment]
确实是写错了，欢迎直接PR进行修复
