### ISSUE TITLE
4.2版本升级到jdk17会报SAXNotRecognizedException 

### ISSUE THREAD

**Issue by stepjacky** [Wechat-Group/WxJava#2409]
### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号:（4.2.0)

### 详细描述
微信公众号解析用户消息,xml格式会出错,问题出在XmlUtils 类
`saxReader.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);`
这一行,原因升级到java17后jdk后台实现方式有变化,
具体异常
`me.chanjar.weixin.common.error.WxRuntimeException: org.xml.sax.SAXNotRecognizedException: unrecognized feature http://apache.org/xml/features/disallow-doctype-decl
	, me.chanjar.weixin.common.util.XmlUtils.xml2Map(XmlUtils.java:45)
	, me.chanjar.weixin.mp.bean.message.WxMpXmlMessage.fromXml(WxMpXmlMessage.java:693)`

切换到jdk8就没问题.

**Comment by binarywang** [comment]
>目前本SDK最新版本要求的JDK最低版本是8，使用7的同学可以使用WxJava 3.8.0及以前版本，而还在使用JDK6的用户请参考【此项目】 ，而其他更早的JDK版本则需要自己改造实现。

请参考下首页的这段说明，jdk旧版本已不再支持。

**Comment by binarywang** [comment]
java17有点太新了，如果你确实需要使用，欢迎提供可行的修复代码，暂时没有环境去实验修复

**Comment by stepjacky** [comment]
这问题即使在java11也存在，解决了这个问题，在java9+版本就无大碍了，解决方案很容易啦，重写XmlUtils类的xml2map方法让他能兼容新版本jdk即可。

**Comment by binarywang** [comment]
> 这问题即使在java11也存在，解决了这个问题，在java9+版本就无大碍了，解决方案很容易啦，重写XmlUtils类的xml2map方法让他能兼容新版本jdk即可。

欢迎PR

**Comment by jiewang-2023** [comment]
加入这个依赖 implementation("xerces:xercesImpl:2.12.2")
启动main方法设置系统属性  System.setProperty("javax.xml.parsers.SAXParserFactory", "com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl");

jdk17版本目前正常使用
