### ISSUE TITLE
调用wxMaService.getUserService().getSessionInfo(jsCode)报错

### ISSUE THREAD

**Issue by xswby** [Wechat-Group/WxJava#2410]
### 简要描述
@Bean
	public WxMaConfig wxMaConfig() {
		WxMaDefaultConfigImpl config = new WxMaDefaultConfigImpl();
		config.setAppid(properties.getAppid());
		config.setSecret(properties.getSecret());
		return config;
	}

	@Bean
	public WxMaService wxMaService(WxMaConfig maConfig) {
		WxMaService service = new WxMaServiceImpl();
		service.setWxMaConfig(maConfig);
		return service;
	}

WxMaJscode2SessionResult js = wxMaService.getUserService().getSessionInfo(jsCode);

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号:4.2.0

### 详细描述
WxMaJscode2SessionResult js = wxMaService.getUserService().getSessionInfo(jsCode);

### 日志
Illegal character in query at index 224: https://api.weixin.qq.com/sns/jscode2session?access_token=51_iDCQ9NiydyUXy06eWVJE68P8AQyQiAbQRQHur-rnz7BRs49XuunxXQzSBlWDVptSmun8gzz58xZhwMxHKO8DyuxkPRL5A3gMyY9cTzDp9A8I2Pdm6X8Dsv5tA5drtJa2vr0M2VT8mvft05auUQLgAGACYT&js_code={"jsCode":"053zwEkl2yAQb84Wz6ol29kGKm0zwEke"}&secret=123123&grant_type=authorization_code&appid=123

**Comment by binarywang** [comment]
你的jsCode为什么要传个json字符串？
