### ISSUE TITLE
mp公众号模块，无法使用JedisPool

### ISSUE THREAD

**Issue by wsc17** [Wechat-Group/WxJava#2418]
### 简要描述
mp公众号模块，无法使用JedisPool

### 模块版本情况
* WxJava 模块名:  weixin-java-mp
* WxJava 版本号: 4.2.0

### 详细描述
我使用了4.2.0版本的公众号开发模块，但是无法使用JedisPool。JedisWxRedisOps类中导入的Pool好像也不对。

1、这个是我的maven：
        

        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-mp</artifactId>
            <version>4.2.0</version>
        </dependency>

        
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-common</artifactId>
            <version>3.8.0</version>
        </dependency>

        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>3.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.jedis-lock</groupId>
            <artifactId>jedis-lock</artifactId>
            <version>1.0.0</version>
        </dependency>

2、这个是报错代码（这行代码会报错）：

        WxMpRedisConfigImpl wxMpRedisConfigImpl = new WxMpRedisConfigImpl(new JedisWxRedisOps(jedisPool), "ttt");

3、这个是JedisWxRedisOps类中引入的Pool的路径：

        import redis.clients.util.Pool;

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by binarywang** [comment]
报什么错？

**Comment by wsc17** [comment]
> 报什么错？

可以了，我把wx-java-common的版本也改成4.2.0，就没问题了。

**Comment by wsc17** [comment]
.
