### ISSUE TITLE
使用WxMaRedisBetterConfigImpl实例化时报错，但是不影响项目启动

### ISSUE THREAD

**Issue by sliu170** [Wechat-Group/WxJava#2435]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。

### 模块版本情况
* WxJava 模块名:  weixin-java-miniapp
* WxJava 版本号:  4.2.0

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__

 实例化WxMaRedisBetterConfigImpl会报一个没有tostring方法的错，但是不会中断程序启动,对使用有影响吗？
code:
    @Autowired
    private StringRedisTemplate stringRedisTemplate;

    @Bean
    public WxMaConfig wxMaConfig() {
        RedisTemplateWxRedisOps redisTemplateWxRedisOps = new RedisTemplateWxRedisOps(stringRedisTemplate);
        WxMaRedisBetterConfigImpl wxMaRedisBetterConfig = new WxMaRedisBetterConfigImpl(redisTemplateWxRedisOps,"xx");
        wxMaRedisBetterConfig.setAppid(properties.getAppId());
        wxMaRedisBetterConfig.setSecret(properties.getAppSecret());
        return wxMaRedisBetterConfig;
    }
### 日志

Method threw 'java.lang.IllegalArgumentException' exception. Cannot evaluate cn.binarywang.wx.miniapp.config.impl.WxMaRedisBetterConfigImpl.toString()

**Comment by sliu170** [comment]
版本是最新版本4.2.0

**Comment by binarywang** [comment]
具体是哪里报的错，第三方插件？

**Comment by sliu170** [comment]
![飞书20211213-140625](https://user-images.githubusercontent.com/72956933/145761082-2a67a237-dcf0-470f-9189-ebfeac75f35e.png)
如图所示,因为在demo工程里没看到最新的样例，所以自己写了一个简单的，按照参数要求传入一个stringRedisTemplate和prefxi，在注入的时候报错，但是能正常启动

**Comment by binarywang** [comment]
启动没问题，按说没事，看你截图你是debug时报的东西，不影响使用就行。

**Comment by wenhaiLi-HappyPD** [comment]
> 启动没问题，按说没事，看你截图你是debug时报的东西，不影响使用就行。

有事，问题很大，影响到登录了，获取这个实例化的时候直接会抛出异常。

**Comment by binarywang** [comment]
> > 启动没问题，按说没事，看你截图你是debug时报的东西，不影响使用就行。
> 
> 有事，问题很大，影响到登录了，获取这个实例化的时候直接会抛出异常。

欢迎直接PR修复代码，这块既然你用到了，应该知道怎么解决吧
