### ISSUE TITLE
调用微信接口重复!

### ISSUE THREAD

**Issue by Concealed0** [Wechat-Group/WxJava#2437]
### 简要描述
获取群发成员发送任务列表
wxCpService.getExternalContactService().getGroupMsgTask(）
获取企业群发成员执行结果表
wxCpService.getExternalContactService().getGroupMsgSendResult(）

以上两个接口调用相同地址。调用相同地址为：【/cgi-bin/externalcontact/get_groupmsg_send_result】

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号: 4.2

**Comment by binarywang** [comment]
这个最新版本其实已经修复了

**Comment by Concealed0** [comment]
我在develop分支里面全局搜含有【/get_groupmsg_task】关键词的微信接口，截止目前，仍未搜到。
请核查微信如下两个微信接口是否存在在CP模块
【/cgi-bin/externalcontact/get_groupmsg_send_result】
【/cgi-bin/externalcontact/get_groupmsg_task】

**Comment by Concealed0** [comment]
> 这个最新版本其实已经修复了

请核查微信如下两个微信接口是否存在在CP模块
【/cgi-bin/externalcontact/get_groupmsg_send_result】
【/cgi-bin/externalcontact/get_groupmsg_task】

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/blob/develop/weixin-java-cp/src/main/java/me/chanjar/weixin/cp/constant/WxCpApiPathConsts.java 请查看此类，不要太依赖搜索结果

**Comment by Concealed0** [comment]
> https://github.com/Wechat-Group/WxJava/blob/develop/weixin-java-cp/src/main/java/me/chanjar/weixin/cp/constant/WxCpApiPathConsts.java 请查看此类，不要太依赖搜索结果

感谢，已找到！
