### ISSUE TITLE
更新到 4.x.x 后， Wiki 文档似乎没有更新

### ISSUE THREAD

**Issue by jiatiejun** [Wechat-Group/WxJava#2440]
### 简要描述
更新到 4.x.x 后， Wiki 文档似乎没有更新，例如：
MP_OAuth2网页授权
获得access token
当用户同意授权后，会回调所设置的url并把authorization code传过来，然后用这个code获得access token，其中也包含用户的openid等信息

WxMpOAuth2AccessToken wxMpOAuth2AccessToken = wxMpService.getOAuth2Service().getAccessToken(code);

似乎 4.x.x. 中已经删除了 WxMpOAuth2AccessToken 定义

请问哪里有适用于 4.x.x 的开发文档？ 谢谢

### 模块版本情况
* WxJava 模块名:  weixin-java-mp 和 wx-java-mp-spring-boot-starter 都尝试过
* WxJava 版本号:  4.2.0

**Comment by binarywang** [comment]
等空了更新下wiki即可，其实你也可以自己看源码，然后帮忙完善修复文档

**Comment by scruel** [comment]
@jiatiejun WxMpOAuth2AccessToken  -> WxOAuth2AccessToken

**Comment by scruel** [comment]
@binarywang 已订正
