### ISSUE TITLE
微信公众号  对话能力缺少回调参数

### ISSUE THREAD

**Issue by ZzzHekmatyar** [Wechat-Group/WxJava#2445]
### 简要描述
 接入微信公众号回调接口，没有顾客扫导购二维码后回调的字段

**Comment by binarywang** [comment]
麻烦请先使用allFieldsMap这个属性获取所有回调数据。
因为由于微信回调数据众多，所以无法一一支持，如果确实需要单独支持，请本地fork后修改实现代码直接提交PR，谢谢。
