### ISSUE TITLE
MerchantInvoicePlatformInfo

### ISSUE THREAD

**Issue by Debenson** [Wechat-Group/WxJava#2446]
### 简要描述
MerchantInvoicePlatformInfo缺少@Data或getter, setter

### 模块版本情况
* WxJava 模块名: 
* WxJava 版本号: 4.2.0

### 详细描述
漏加@Data, 导致类无法设值 

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by binarywang** [comment]
其实你可以直接PR代码的
