### ISSUE TITLE
CP_主动发送消息,建议支持markdown

### ISSUE THREAD

**Issue by nxt5656** [Wechat-Group/WxJava#2447]
markdown格式能在推送消息内容较多的时候,用比较好看的方式展示出来,建议添加

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__
https://open.work.weixin.qq.com/api/doc/90000/90135/90250#markdown%E6%B6%88%E6%81%AF

**Comment by binarywang** [comment]
你确定现在不支持吗？麻烦看下源码吧，这个是很早就支持的功能
