### ISSUE TITLE
V3模式，普通小程序支付，privateKeyPath等参数无法获取到。

### ISSUE THREAD

**Issue by lee-john0087** [Wechat-Group/WxJava#2448]
### 简要描述
V3模式，普通小程序支付，privateKeyPath等参数无法获取到

### 模块版本情况
* WxJava 模块名: pay
* WxJava 版本号:（4.2.0）

### 详细描述
controller： WxPayMpOrderResult wxPayMpOrderResult = wxPayService.createOrderV3(TradeTypeEnum.JSAPI,orderRequest);

yml：
wx:
  pay:
    appId: *************** #appId
    mchId: *************** #微信支付商户号
    mchKey: ***************  #微信支付商户密钥
    subAppId: #服务商模式下的子商户公众账号ID
    subMchId: #服务商模式下的子商户号
    keyPath: classpath:../cert/wxpay/apiclient_cert.p12 #p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
    notifyURL: http://localhost:8080/api/wechat/payment/callback
    privateKey: classpath:cert/wxpay/apiclient_key.pem
    privateKeyPath: classpath:cert/wxpay/apiclient_key.pem
    privateCertPath: classpath:cert/wxpay/apiclient_cert.pem
    apiv3Key: ***************
    payScoreNotifyUrl: http://localhost:8080/api/wechat/payment/callback
    certSerialNo: ***************

### 日志
 - 微信支付失败！订单号：LS202112161035481639622148433,原因:请确保privateKeyPath已设置
WxPayException(customErrorMsg=请确保privateKeyPath已设置, returnCode=null, returnMsg=null, resultCode=null, errCode=null, errCodeDes=null, xmlString=null)

**Comment by lee-john0087** [comment]
appId、mchId、mchKey、keyPath、notifyURL这些都能获取到，其他的都获取不到，在WxPayConfig getConfig（）的时候。

**Comment by binarywang** [comment]
你的配置类是自己写的？
