### ISSUE TITLE
自行配置error日志

### ISSUE THREAD

**Issue by tcxiaotudou** [Wechat-Group/WxJava#2449]
现在项目接入了企业微信的模块，一些接口获取外部联系人信息的时候或其他数据时，经常会记录error日志 （但这些是可容忍的，比方说：双方并不是好友关系或者其他情况），导致error日志暴增。我想可以自行配置这些error日志的发生情况，请问一下有什么好的解决办法吗？

**Comment by tcxiaotudou** [comment]
![image](https://user-images.githubusercontent.com/17454614/146305685-48278f2a-c85b-4e77-a2ea-850a1abe10f2.png)

**Comment by tcxiaotudou** [comment]
![image](https://user-images.githubusercontent.com/17454614/146305848-e76da7fe-c45b-4a5f-8c37-05b3e375e47a.png)

**Comment by scruel** [comment]
日志文件中针对 `me.chanjar.weixin.*", "cn.binarywang.wx.*", "com.github.binarywang.*` 设置级别，使用什么框架就去查什么文档。

**Comment by binarywang** [comment]
楼上说的对，自己设置日志level即可，没啥技术难度
