### ISSUE TITLE
微信公众号新增了草稿箱功能，请同步实现该功能

### ISSUE THREAD

**Issue by UsrLi** [Wechat-Group/WxJava#2453]
微信公众号新增了草稿箱功能，请更新该功能相关接口实现

**Comment by UsrLi** [comment]
现有产品需要用到草稿箱功能，希望大神能尽快实现，谢谢！

**Comment by binarywang** [comment]
草稿箱功能已经添加了，请注意阅读最新各个版本发布日志，关注公众号接受相关消息

**Comment by binarywang** [comment]
> 现有产品需要用到草稿箱功能，希望大神能尽快实现，谢谢！

另外可不要指望所谓的大神来帮助你实现，最好的办法是你自己主动实现，测试没问题直接提交PR

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/pull/2356
