### ISSUE TITLE
获取手机号

### ISSUE THREAD

**Issue by godamia** [Wechat-Group/WxJava#2455]
phonenumber.getPhoneNumber

### 简要描述
code换取用户手机号。 每个code只能使用一次，code的有效期为5min

### 官方文档地址
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/phonenumber/phonenumber.getPhoneNumber.html

**Comment by binarywang** [comment]
欢迎先自行实现，并提交测试好的代码上来

**Comment by mr-xiaoyu** [comment]
这个方法吗   wxMaService.getUserService().getPhoneNoInfo()

**Comment by binarywang** [comment]
看起来不一样
