### ISSUE TITLE
微信公众号用户信息接口调整

### ISSUE THREAD

**Issue by kids1994** [Wechat-Group/WxJava#2456]
### 简要描述

UnionID机制说明：

开发者可通过OpenID来获取用户基本信息。特别需要注意的是，如果开发者拥有多个移动应用、网站应用和公众帐号，可通过获取用户基本信息中的unionid来区分用户的唯一性，因为只要是同一个微信开放平台帐号下的移动应用、网站应用和公众帐号，用户的unionid是唯一的。换句话说，同一用户，对同一个微信开放平台下的不同应用，unionid是相同的。

**请注意： 20年6月8日起，用户关注来源“微信广告（ADD_SCENE_WECHAT_ADVERTISEMENT）”从“其他（ADD_SCENE_OTHERS）”中拆分给出，2021年12月27日之后，不再输出头像、昵称信息。**

### 官方文档地址
https://developers.weixin.qq.com/doc/offiaccount/User_Management/Get_users_basic_information_UnionID.html#UinonId

**Comment by scruel** [comment]
已处理
Thanks
