### ISSUE TITLE
weixin-java-pay 一个商户号，同时需要微信支付、小程序支付，多个config无法配置

### ISSUE THREAD

**Issue by lujiamingzZ** [Wechat-Group/WxJava#2457]
### 简要描述

我是普通模式， 我有一个mchid，两个appid，同时在一个后端服务中都需要下单。
`

 

    @Bean
    @ConditionalOnMissingBean
    public WxPayService wxService() {

      WxPayConfig payConfig = new WxPayConfig();
      payConfig.setAppId(StringUtils.trimToNull(this.properties.getAppId()));
      payConfig.setMchId(StringUtils.trimToNull(this.properties.getMchId()));
      payConfig.setMchKey(StringUtils.trimToNull(this.properties.getMchKey()));
      payConfig.setSubAppId(StringUtils.trimToNull(this.properties.getSubAppId()));
      payConfig.setSubMchId(StringUtils.trimToNull(this.properties.getSubMchId()));
      payConfig.setKeyPath(StringUtils.trimToNull(this.properties.getKeyPath()));

      // 可以指定是否使用沙箱环境
      payConfig.setUseSandboxEnv(false);

      WxPayService wxPayService = new WxPayServiceImpl();

      // **此处若使用 wxPayService.setMultiConfig(); 需要两个mchid，我并没有。但是我有两个appid。**
      wxPayService.setConfig(payConfig);

      return wxPayService;

    }

`

wxPayService.setMultiConfig(); 的源码中mchid是作为map key 去使用的，但是我只有一个mchid，有两个appid，分别是app以及小程序。
此时就无法配置两个支付应用。导致wxService.createOrder(request);只用到一个appid，另外一个无法实现。

**Comment by wuchubuzai2018** [comment]
我是用了2个service去处理的，建议用2个service处理，每个里面维护一个config
