### ISSUE TITLE
小程序的授权资料变更功能

### ISSUE THREAD

**Issue by dingchengyuan** [Wechat-Group/WxJava#2458]
### 简要描述
小程序的授权资料变更无法通过WxMaMessage来实现，需要新增RevokeInfo和OpenID等字段。

### 官方文档地址
(https://developers.weixin.qq.com/miniprogram/dev/framework/security.html#%E6%8E%88%E6%9D%83%E7%94%A8%E6%88%B7%E8%B5%84%E6%96%99%E5%8F%98%E6%9B%B4)

**Comment by binarywang** [comment]
欢迎直接PR，添加你需要的字段
