### ISSUE TITLE
你好，微信27号更新了获取手机号码的方式，请问你们什么时候会更新呢？

### ISSUE THREAD

**Issue by yigenmala** [Wechat-Group/WxJava#2472]
你好，微信27号更新了获取手机号码的方式，请问你们什么时候会更新呢？

### 官方文档地址

https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/getPhoneNumber.html

**Comment by binarywang** [comment]
#2455 重复请求，近期版本会实现

**Comment by yigenmala** [comment]
Thank you. Your email is received and will be handled as soon as possible.
