### ISSUE TITLE
分账接口支持不全，分账结果和查询分账缺少detail_id

### ISSUE THREAD

**Issue by hugo2017** [Wechat-Group/WxJava#2478]
微信支付分账接口，V3版本，4.2.0版本。

按官方文档，申请分账和查询分账结果两个接口，返回值中接收方数据有个"detail_id"。由于分账订单有多个接收方，分账金额提现在接收方中。查单后需要区分接收方，记录资金变动明细，需要一个ID，detail_id貌似比较合适。

**Comment by binarywang** [comment]
欢迎直接PR
