### ISSUE TITLE
【建议】支持风险合规接口调用

### ISSUE THREAD

**Issue by hp88yx** [Wechat-Group/WxJava#2482]
### 简要描述
weixin-java-pay缺少风险合规接口调用支持，希望大佬未来规划这个功能

### 官方文档地址

https://pay.weixin.qq.com/wiki/doc/apiv3/open/pay/chapter6_2_3.shtml

**Comment by binarywang** [comment]
欢迎直接提交PR代码，这是开源项目，需要大家的支持
