### ISSUE TITLE
在线上高并发环境下，发送公众号模板通知后出现大量线程阻塞

### ISSUE THREAD

**Issue by wuyuancai** [Wechat-Group/WxJava#2484]
### 简要描述
在线上高并发环境下，发送公众号模板通知后出现线程阻塞

### 模块版本情况
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>wx-java-mp-spring-boot-starter</artifactId>
            <version>4.2.0</version>
        </dependency>

### 详细描述
在线上高并发环境下，发送公众号模板通知后出现线程一直没有释放，一直累积，一直阻塞

**Comment by wuyuancai** [comment]
测试中发现使用http请求的都会有线程阻塞的情况，相当于每发一次http 请求后一直阻塞，不会释放

**Comment by scruel** [comment]
是否有 demo 项目？没有的话，能否提供下具体情况执行 jmap 等分析指令后的结果如何？

**Comment by wuyuancai** [comment]
> 是否有 demo 项目？没有的话，能否提供下具体情况执行 jmap 等分析指令后的结果如何？

![3f1c9f8c36622c7c9a5e091a49be44d](https://user-images.githubusercontent.com/19992054/148338359-844b3bfb-51de-419e-9edb-19bda508d8ee.png)
此处一直在循环

**Comment by scruel** [comment]
> 此处一直在循环

这里循环是正常的，代码来看的话也只会起一个线程处理清理任务。
所以应该不是这个的问题，对于大量线程的阻塞这个情况，能提供看一下分析的结果吗？
当然这里如果 `msgId2Timestamp` 中的数据太多的话，会一直占用 CPU 进行检查，您看看是不是这个问题。

**Comment by wuyuancai** [comment]
> > 此处一直在循环
> 
> 这里循环是正常的，代码来看的话也只会起一个线程处理清理任务。 所以应该不是这个的问题，对于大量线程的阻塞这个情况，能提供看一下分析的结果吗？ 当然这里如果 `msgId2Timestamp` 中的数据太多的话，会一直占用 CPU 进行检查，您看看是不是这个问题。


```
"WxMpMessageRouter-pool-1" Id=15054 cpuUsage=0.0% deltaTime=0ms time=0ms WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@83f668e
    at sun.misc.Unsafe.park(Native Method)
    -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@83f668e
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
    at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
    at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)


"Thread-7475" Id=15055 cpuUsage=0.0% deltaTime=0ms time=2ms TIMED_WAITING
    at java.lang.Thread.sleep(Native Method)
    at me.chanjar.weixin.common.api.WxMessageInMemoryDuplicateChecker.lambda$checkBackgroundProcessStarted$0(WxMessageInMemoryDuplicateChecker.java:67)
    at me.chanjar.weixin.common.api.WxMessageInMemoryDuplicateChecker$$Lambda$1112/877132986.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:748)


"Thread-7476" Id=15056 cpuUsage=0.0% deltaTime=0ms time=1ms TIMED_WAITING
    at java.lang.Thread.sleep(Native Method)
    at me.chanjar.weixin.common.api.WxMessageInMemoryDuplicateChecker.lambda$checkBackgroundProcessStarted$0(WxMessageInMemoryDuplicateChecker.java:67)
    at me.chanjar.weixin.common.api.WxMessageInMemoryDuplicateChecker$$Lambda$1112/877132986.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:748)


"Thread-7477" Id=15057 cpuUsage=0.0% deltaTime=0ms time=2ms TIMED_WAITING
    at java.lang.Thread.sleep(Native Method)
    at me.chanjar.weixin.common.api.WxMessageInMemoryDuplicateChecker.lambda$checkBackgroundProcessStarted$0(WxMessageInMemoryDuplicateChecker.java:67)
    at me.chanjar.weixin.common.api.WxMessageInMemoryDuplicateChecker$$Lambda$1112/877132986.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by scruel** [comment]
> > > 此处一直在循环
> > 
> > 
> > 这里循环是正常的，代码来看的话也只会起一个线程处理清理任务。 所以应该不是这个的问题，对于大量线程的阻塞这个情况，能提供看一下分析的结果吗？ 当然这里如果 `msgId2Timestamp` 中的数据太多的话，会一直占用 CPU 进行检查，您看看是不是这个问题。
> 
> ```
> "WxMpMessageRouter-pool-1" Id=15054 cpuUsage=0.0% deltaTime=0ms time=0ms WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@83f668e
>     at sun.misc.Unsafe.park(Native Method)
>     -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@83f668e
>     at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
>     at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
>     at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
>     at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>     at java.lang.Thread.run(Thread.java:748)
> 
> 
> "Thread-7475" Id=15055 cpuUsage=0.0% deltaTime=0ms time=2ms TIMED_WAITING
>     at java.lang.Thread.sleep(Native Method)
>     at me.chanjar.weixin.common.api.WxMessageInMemoryDuplicateChecker.lambda$checkBackgroundProcessStarted$0(WxMessageInMemoryDuplicateChecker.java:67)
>     at me.chanjar.weixin.common.api.WxMessageInMemoryDuplicateChecker$$Lambda$1112/877132986.run(Unknown Source)
>     at java.lang.Thread.run(Thread.java:748)
> 
> 
> "Thread-7476" Id=15056 cpuUsage=0.0% deltaTime=0ms time=1ms TIMED_WAITING
>     at java.lang.Thread.sleep(Native Method)
>     at me.chanjar.weixin.common.api.WxMessageInMemoryDuplicateChecker.lambda$checkBackgroundProcessStarted$0(WxMessageInMemoryDuplicateChecker.java:67)
>     at me.chanjar.weixin.common.api.WxMessageInMemoryDuplicateChecker$$Lambda$1112/877132986.run(Unknown Source)
>     at java.lang.Thread.run(Thread.java:748)
> 
> 
> "Thread-7477" Id=15057 cpuUsage=0.0% deltaTime=0ms time=2ms TIMED_WAITING
>     at java.lang.Thread.sleep(Native Method)
>     at me.chanjar.weixin.common.api.WxMessageInMemoryDuplicateChecker.lambda$checkBackgroundProcessStarted$0(WxMessageInMemoryDuplicateChecker.java:67)
>     at me.chanjar.weixin.common.api.WxMessageInMemoryDuplicateChecker$$Lambda$1112/877132986.run(Unknown Source)
>     at java.lang.Thread.run(Thread.java:748)
> ```

只有三个吗，是否除了公众号服务还有注册其他的？

**Comment by wuyuancai** [comment]
> 



> 

只是部分，Thread-xxxx 的占了几万的数量

**Comment by wuyuancai** [comment]
> 

只是部分 ，"Thread-xxx" 这样的线程名称一共有几万个

**Comment by scruel** [comment]
@wuyuancai 了解，我这边定位看一下，谢谢

**Comment by wuyuancai** [comment]
> @wuyuancai 了解，我这边定位看一下，谢谢

谢谢，有没有暂时的解决方案

**Comment by scruel** [comment]
@wuyuancai 可以在自己代码中写一个 `WxMpMessageRouter` 子类（或者直接复制之类），bean 中生成自定义的子类对象，暂时移除其中重复监测的相关方法（`isMsgDuplicated`）。

**Comment by wuyuancai** [comment]
> > @wuyuancai 了解，我这边定位看一下，谢谢
> 
> 谢谢，有没有暂时的解决方案

复现场景，向公众号发送一条消息，就会生成一条线程，然后一直阻塞

**Comment by scruel** [comment]
> > > @wuyuancai 了解，我这边定位看一下，谢谢
> > 
> > 
> > 谢谢，有没有暂时的解决方案
> 
> 复现场景，向公众号发送一条消息，就会生成一条线程，然后一直阻塞

checker 本身是不会产生多条线程的，会不会是工程哪里有错误？

**Comment by wuyuancai** [comment]
> 


> 

不会的，我测试过，如果去掉route，就不会有线程增长的问题

**Comment by scruel** [comment]
是怎么写的 route 呢？

**Comment by wuyuancai** [comment]
> 是怎么写的 route 呢？
```

// aes加密的消息
            WxMpConfigStorage wxMpConfigStorage = wxMpService.getWxMpConfigStorage();
            WxMpXmlMessage inMessage = WxMpXmlMessage.fromEncryptedXml(requestBody, wxMpConfigStorage,
                    timestamp, nonce, msgSignature);
            WxMpXmlOutMessage outMessage = this.route(inMessage);
            if (outMessage == null) {
                return "";
            }

            out = outMessage.toEncryptedXml(wxMpConfigStorage);



    private WxMpXmlOutMessage route(WxMpXmlMessage message) {
        try {
            WxMpMessageRouter wxMpMessageRouter = new WxMpMessageRouter(wxMpService);
            return wxMpMessageRouter.rule().async(false).msgType("event").event(WxConsts.EventType.SUBSCRIBE).handler(subscribeHandle()).end()
                    .rule().async(true).msgType("event").event(WxConsts.EventType.SCAN).handler(scanHandle()).end()
                    .rule().async(true).msgType("event").event(WxConsts.EventType.UNSUBSCRIBE).handler(unsubscribeHandle()).end()
                    .rule().async(true).msgType("text").handler(textHandler()).end().route(message);
        } catch (Exception e) {
            log.error("路由消息时出现异常！", e);
        }
        return null;
    }
```

**Comment by scruel** [comment]
WxMpMessageRouter wxMpMessageRouter = new WxMpMessageRouter(wxMpService);
你一直在生成新的 Router 对象导致的，去参考下 wiki 的写法吧。
@binarywang Close

**Comment by binarywang** [comment]
楼主问题原因已经看清楚了是吧？直接关闭

**Comment by wuyuancai** [comment]
> 楼主问题原因已经看清楚了是吧？直接关闭

但是我把WxMpMessageRouter 改成单例，还是回增长，一次监听增加两个线程

**Comment by scruel** [comment]
> > 楼主问题原因已经看清楚了是吧？直接关闭
> 
> 但是我把WxMpMessageRouter 改成单例，还是回增长，一次监听增加两个线程

自查代码吧，不是项目的问题。

**Comment by wuyuancai** [comment]
> > > 楼主问题原因已经看清楚了是吧？直接关闭
> > 
> > 
> > 但是我把WxMpMessageRouter 改成单例，还是回增长，一次监听增加两个线程
> 
> 自查代码吧，不是项目的问题。

行吧
