### ISSUE TITLE
【企业微信】第三方服务商获取企业永久授权码接口返回的管理员信息没有 open_userid 字段

### ISSUE THREAD

**Issue by lbhfuture** [Wechat-Group/WxJava#2487]
### 简要描述
官方文档显示接口【获取企业永久授权码】有返回授权管理员的 `open_userid` 字段，即 `auth_user_info.open_userid`，但是 `v4.2.0` 中的 `WxCpTpPermanentCodeInfo.AuthUserInfo` 里没有该字段，麻烦添加一下。

### 官方文档地址
[文档地址](https://open.work.weixin.qq.com/api/doc/90001/90143/90603)

**Comment by binarywang** [comment]
@zp961466717 你的PR代码为啥close了？

**Comment by binarywang** [comment]
@lbhfuture 也非常欢迎楼主自行PR代码
