### ISSUE TITLE
V4.2.0 包与源码不一致

### ISSUE THREAD

**Issue by cbschina** [Wechat-Group/WxJava#2488]
cn.binarywang.wx.miniapp.bean.scheme.WxMaGenerateSchemeRequest
在4.2.0 版本里代码与源码不一致，缺少部分参数

**Comment by binarywang** [comment]
你看的源码确定是4.2.0的源码吗？

**Comment by cbschina** [comment]
我看的是TAG 4.2.0，和jar 包里反编译的对比的

**Comment by cbschina** [comment]
也和微信小程序的相关页面对比过，参数上有差异。GITEE和GITHUB 下的tag4.2.0的源码是没问题的，但是JAR 里的不对

**Comment by binarywang** [comment]
请具体说一下，到底是哪里不一样？

**Comment by cbschina** [comment]
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package cn.binarywang.wx.miniapp.bean.scheme;

import cn.binarywang.wx.miniapp.json.WxMaGsonBuilder;
import com.google.gson.annotations.SerializedName;

public class WxMaGenerateSchemeRequest {
    @SerializedName("jump_wxa")
    private WxMaGenerateSchemeRequest.JumpWxa jumpWxa;
    @SerializedName("is_expire")
    private Boolean isExpire;
    @SerializedName("expire_time")
    private Long expireTime;
    @SerializedName("env_version")
    private String envVersion = "release";

    public String toJson() {
        return WxMaGsonBuilder.create().toJson(this);
    }

    WxMaGenerateSchemeRequest(WxMaGenerateSchemeRequest.JumpWxa jumpWxa, Boolean isExpire, Long expireTime, String envVersion) {
        this.jumpWxa = jumpWxa;
        this.isExpire = isExpire;
        this.expireTime = expireTime;
        this.envVersion = envVersion;
    }

    public static WxMaGenerateSchemeRequest.WxMaGenerateSchemeRequestBuilder newBuilder() {
        return new WxMaGenerateSchemeRequest.WxMaGenerateSchemeRequestBuilder();
    }

    public WxMaGenerateSchemeRequest.JumpWxa getJumpWxa() {
        return this.jumpWxa;
    }

    public Boolean getIsExpire() {
        return this.isExpire;
    }

    public Long getExpireTime() {
        return this.expireTime;
    }

    public String getEnvVersion() {
        return this.envVersion;
    }

    public void setJumpWxa(WxMaGenerateSchemeRequest.JumpWxa jumpWxa) {
        this.jumpWxa = jumpWxa;
    }

    public void setIsExpire(Boolean isExpire) {
        this.isExpire = isExpire;
    }

    public void setExpireTime(Long expireTime) {
        this.expireTime = expireTime;
    }

    public void setEnvVersion(String envVersion) {
        this.envVersion = envVersion;
    }

    public boolean equals(Object o) {
        if (o == this) {
            return true;
        } else if (!(o instanceof WxMaGenerateSchemeRequest)) {
            return false;
        } else {
            WxMaGenerateSchemeRequest other = (WxMaGenerateSchemeRequest)o;
            if (!other.canEqual(this)) {
                return false;
            } else {
                label59: {
                    Object this$jumpWxa = this.getJumpWxa();
                    Object other$jumpWxa = other.getJumpWxa();
                    if (this$jumpWxa == null) {
                        if (other$jumpWxa == null) {
                            break label59;
                        }
                    } else if (this$jumpWxa.equals(other$jumpWxa)) {
                        break label59;
                    }

                    return false;
                }

                Object this$isExpire = this.getIsExpire();
                Object other$isExpire = other.getIsExpire();
                if (this$isExpire == null) {
                    if (other$isExpire != null) {
                        return false;
                    }
                } else if (!this$isExpire.equals(other$isExpire)) {
                    return false;
                }

                Object this$expireTime = this.getExpireTime();
                Object other$expireTime = other.getExpireTime();
                if (this$expireTime == null) {
                    if (other$expireTime != null) {
                        return false;
                    }
                } else if (!this$expireTime.equals(other$expireTime)) {
                    return false;
                }

                Object this$envVersion = this.getEnvVersion();
                Object other$envVersion = other.getEnvVersion();
                if (this$envVersion == null) {
                    if (other$envVersion != null) {
                        return false;
                    }
                } else if (!this$envVersion.equals(other$envVersion)) {
                    return false;
                }

                return true;
            }
        }
    }

    protected boolean canEqual(Object other) {
        return other instanceof WxMaGenerateSchemeRequest;
    }

    public int hashCode() {
        int PRIME = true;
        int result = 1;
        Object $jumpWxa = this.getJumpWxa();
        int result = result * 59 + ($jumpWxa == null ? 43 : $jumpWxa.hashCode());
        Object $isExpire = this.getIsExpire();
        result = result * 59 + ($isExpire == null ? 43 : $isExpire.hashCode());
        Object $expireTime = this.getExpireTime();
        result = result * 59 + ($expireTime == null ? 43 : $expireTime.hashCode());
        Object $envVersion = this.getEnvVersion();
        result = result * 59 + ($envVersion == null ? 43 : $envVersion.hashCode());
        return result;
    }

    public String toString() {
        return "WxMaGenerateSchemeRequest(jumpWxa=" + this.getJumpWxa() + ", isExpire=" + this.getIsExpire() + ", expireTime=" + this.getExpireTime() + ", envVersion=" + this.getEnvVersion() + ")";
    }

    public static class WxMaGenerateSchemeRequestBuilder {
        private WxMaGenerateSchemeRequest.JumpWxa jumpWxa;
        private Boolean isExpire;
        private Long expireTime;
        private String envVersion;

        WxMaGenerateSchemeRequestBuilder() {
        }

        public WxMaGenerateSchemeRequest.WxMaGenerateSchemeRequestBuilder jumpWxa(WxMaGenerateSchemeRequest.JumpWxa jumpWxa) {
            this.jumpWxa = jumpWxa;
            return this;
        }

        public WxMaGenerateSchemeRequest.WxMaGenerateSchemeRequestBuilder isExpire(Boolean isExpire) {
            this.isExpire = isExpire;
            return this;
        }

        public WxMaGenerateSchemeRequest.WxMaGenerateSchemeRequestBuilder expireTime(Long expireTime) {
            this.expireTime = expireTime;
            return this;
        }

        public WxMaGenerateSchemeRequest.WxMaGenerateSchemeRequestBuilder envVersion(String envVersion) {
            this.envVersion = envVersion;
            return this;
        }

        public WxMaGenerateSchemeRequest build() {
            return new WxMaGenerateSchemeRequest(this.jumpWxa, this.isExpire, this.expireTime, this.envVersion);
        }

        public String toString() {
            return "WxMaGenerateSchemeRequest.WxMaGenerateSchemeRequestBuilder(jumpWxa=" + this.jumpWxa + ", isExpire=" + this.isExpire + ", expireTime=" + this.expireTime + ", envVersion=" + this.envVersion + ")";
        }
    }

    public static class JumpWxa {
        @SerializedName("path")
        private String path;
        @SerializedName("query")
        private String query;

        JumpWxa(String path, String query) {
            this.path = path;
            this.query = query;
        }

        public static WxMaGenerateSchemeRequest.JumpWxa.JumpWxaBuilder newBuilder() {
            return new WxMaGenerateSchemeRequest.JumpWxa.JumpWxaBuilder();
        }

        public String getPath() {
            return this.path;
        }

        public String getQuery() {
            return this.query;
        }

        public void setPath(String path) {
            this.path = path;
        }

        public void setQuery(String query) {
            this.query = query;
        }

        public boolean equals(Object o) {
            if (o == this) {
                return true;
            } else if (!(o instanceof WxMaGenerateSchemeRequest.JumpWxa)) {
                return false;
            } else {
                WxMaGenerateSchemeRequest.JumpWxa other = (WxMaGenerateSchemeRequest.JumpWxa)o;
                if (!other.canEqual(this)) {
                    return false;
                } else {
                    Object this$path = this.getPath();
                    Object other$path = other.getPath();
                    if (this$path == null) {
                        if (other$path != null) {
                            return false;
                        }
                    } else if (!this$path.equals(other$path)) {
                        return false;
                    }

                    Object this$query = this.getQuery();
                    Object other$query = other.getQuery();
                    if (this$query == null) {
                        if (other$query != null) {
                            return false;
                        }
                    } else if (!this$query.equals(other$query)) {
                        return false;
                    }

                    return true;
                }
            }
        }

        protected boolean canEqual(Object other) {
            return other instanceof WxMaGenerateSchemeRequest.JumpWxa;
        }

        public int hashCode() {
            int PRIME = true;
            int result = 1;
            Object $path = this.getPath();
            int result = result * 59 + ($path == null ? 43 : $path.hashCode());
            Object $query = this.getQuery();
            result = result * 59 + ($query == null ? 43 : $query.hashCode());
            return result;
        }

        public String toString() {
            return "WxMaGenerateSchemeRequest.JumpWxa(path=" + this.getPath() + ", query=" + this.getQuery() + ")";
        }

        public static class JumpWxaBuilder {
            private String path;
            private String query;

            JumpWxaBuilder() {
            }

            public WxMaGenerateSchemeRequest.JumpWxa.JumpWxaBuilder path(String path) {
                this.path = path;
                return this;
            }

            public WxMaGenerateSchemeRequest.JumpWxa.JumpWxaBuilder query(String query) {
                this.query = query;
                return this;
            }

            public WxMaGenerateSchemeRequest.JumpWxa build() {
                return new WxMaGenerateSchemeRequest.JumpWxa(this.path, this.query);
            }

            public String toString() {
                return "WxMaGenerateSchemeRequest.JumpWxa.JumpWxaBuilder(path=" + this.path + ", query=" + this.query + ")";
            }
        }
    }
}

**Comment by cbschina** [comment]
jump_wxa 在代码里和腾讯api 都是三个参数，反编译4.2的jar 是两个参数
其他的参数也有不对的

**Comment by binarywang** [comment]
请仔细看代码，第三个参数是后来加的，你看下该文件的代码变更记录就知道了。如果想使用最新代码，建议更换最新版本

**Comment by cbschina** [comment]
expire_type expire_interval 这两个参数在jar 代码里没有,调用的时候会报参数不足

**Comment by binarywang** [comment]
你说的这两个参数，最新版本都还没添加，建议通过PR加一下，下一个版本发布后可以用

**Comment by cbschina** [comment]
了解了，那先不用这个接口，谢谢

**Comment by binarywang** [comment]
楼主描述有问题，实际情况是不存在不一致情况，只是有部分新字段还未及时更新到源码中，后续处理
