### ISSUE TITLE
企业微信下载素材，在linux下路径+文件名字超过255后，抛出异常”文件名过长“

### ISSUE THREAD

**Issue by leone-007** [Wechat-Group/WxJava#2490]
### 简要描述
企业微信下载素材，在linux下路径+文件名字超过255后，抛出异常”文件名过长“。

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号:（4.2.0）

### 详细描述
企业微信下载素材，在linux下路径+文件名字超过255后，抛出异常”文件名过长“。且无法正确下载文件。

### 日志
【请求地址】: https://qyapi.weixin.qq.com/cgi-bin/media/get?access_token=...
【请求参数】：media_id=...
【异常信息】：文件名过长

**Comment by binarywang** [comment]
此问题建议自行修改me.chanjar.weixin.cp.config.impl.WxCpDefaultConfigImpl#tmpDirFile参数，不要设置过长解决。代码层面暂不做调整，如果楼主有较好解决方案，欢迎直接提交PR代码
