### ISSUE TITLE
希望支持微信红包封面相关api

### ISSUE THREAD

**Issue by yang2048** [Wechat-Group/WxJava#2492]
微信红包封面 现在支持了吗？找了好久没看到相关api信息，如果没有是否考虑添加呢？

**Comment by binarywang** [comment]
暂无计划。
另外，请给出相关文档地址。
如果急用，欢迎自己参考现有代码实现，调试没问题可以直接PR，否则可能无限期等下去的

**Comment by yang2048** [comment]
[微信红包封面](https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/redpacketcover/redpacketcover.getAuthenticationUrl.html)
