### ISSUE TITLE
建议【统一下单】等接口内，增加“notifyUrl为空时，通过this.getConfig()读取notifyUrl”的几行代码

### ISSUE THREAD

**Issue by cxh1231** [Wechat-Group/WxJava#2500]
因为已经在`WxPayConfig`里配置了`notifyUrl`，所以建议在`BaseWxPayServiceImpl`方法中的下单等接口（如：https://github.com/Wechat-Group/WxJava/blob/4c781ee7ee424191244bba3d6261577878610a07/weixin-java-pay/src/main/java/com/github/binarywang/wxpay/service/impl/BaseWxPayServiceImpl.java#L695 ）增加几行代码：
```
    if (StringUtils.isBlank(request.getNotifyUrl())) {
      request.setNotifyUrl(this.getConfig().getNotifyUrl());
    }
```
使`request.getNotifyUrl()`为空时，默认从配置信息中读取回调通知地址。

如下图。
![https://img.cxh.life/FtzIFSQpry75n0N0g7zeOvBH4K2F](https://img.cxh.life/FtzIFSQpry75n0N0g7zeOvBH4K2F)

**Comment by binarywang** [comment]
非常欢迎直接提供PR代码
