### ISSUE TITLE
没有EncodingAESKey和Token的情况下无法使用

### ISSUE THREAD

**Issue by willcream** [Wechat-Group/WxJava#2502]
想跳过验签，我们只需要单向发消息的能力，当初建应用时就没有填写EncodingAESKey和Token，这个能做到吗？现在是启动就报错，
java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

**Comment by binarywang** [comment]
什么情况下报的错？

**Comment by willcream** [comment]
没事了，sdk的问题……换了个ibm的openjdk就好了，具体什么问题我也没搞清楚，原本用的是从oracle上下载的8
