### ISSUE TITLE
项目中配置logback-spring.xml、启动项目后报错

### ISSUE THREAD

**Issue by viclee11** [Wechat-Group/WxJava#2504]
在项目中添加了logback-spring.xml配置文件后、启动项目报错（无法初始化Logback配置）
1.项目为Gradle构建
2.依赖版本为4.2.0（implementation group: 'com.github.binarywang', name: 'weixin-java-pay', version: '4.2.0'）
3.删除依赖又启动成功
（不知道是不是依赖冲突的问题）
![image](https://user-images.githubusercontent.com/43262983/149117852-98a8bf1c-ee86-4a2e-aab2-08c5d3305fbd.png)

**Comment by viclee11** [comment]
![image](https://user-images.githubusercontent.com/43262983/149119399-fc8499c5-de83-48f4-adbc-23417dc48622.png)

**Comment by binarywang** [comment]
最后部分不是错误根源吗？

**Comment by yhan219** [comment]
确实启不起来，添加本项目依赖后，spring boot只要配置了 logback.xml 都启动不起来。以为是java版本问题，从11换成8也是启动不起来。spring boot2.4版本可以启动，2.6不行

**Comment by Sloaix** [comment]
springboot 2.6.2
java 13
gradle构建，只是添加依赖就会复现。

**Comment by kiddkyd2** [comment]
me too.
springboot 2.6.3

我找到了解决方案，只要导入这个包就可以
group: 'xerces', name: 'xercesImpl', version: '2.12.1'

**Comment by binarywang** [comment]
#2530 是同一个问题吗？

**Comment by binarywang** [comment]
拿demo做了简单测试，没发现问题，楼上的几位，能否给个必然出现问题的demo项目代码？

**Comment by yhan219** [comment]
是同一个问题，关闭吧，最新版可以使用了

**Comment by viclee11** [comment]
Demo-查收




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/WxJava"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月21日(星期一) 下午2:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] 项目中配置logback-spring.xml、启动项目后报错 (Issue #2504)





 
拿demo做了简单测试，没发现问题，楼上的几位，能否给个必然出现问题的demo项目代码？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
