### ISSUE TITLE
weixin-java-pay  getSandboxSignKey 没有存储功能，且setUseSandboxEnv(true)没有用沙箱Api秘钥进行签名

### ISSUE THREAD

**Issue by 1799246295** [Wechat-Group/WxJava#2505]
# weixin-java-pay  getSandboxSignKey 没有存储功能，且setUseSandboxEnv(true)没有用沙箱Api秘钥 进行签名， 
# 微信支付商户介入助手 文档地址 https://mp.weixin.qq.com/s/JEQnD_NmqNvYnCi5hCKW9g  	
## Q3 沙箱验证签名失败    注意：沙箱密钥过期，获取的沙箱密钥有效期为3天，过期请重新获取   ，

**Comment by binarywang** [comment]
自己进行存储吧，比如放到redis里
