### ISSUE TITLE
Native支付

### ISSUE THREAD

**Issue by lee-john0087** [Wechat-Group/WxJava#2509]
### 简要描述
Native支付

### 模块版本情况
* WxJava 模块名: pay
* WxJava 版本号:4.2（旧版本不予支持，谢谢配合）

### 详细描述
我看到扫码支付：String createScanPayQrcodeMode1(String productId)
这个应该是面向native的支付方式的，但是我在里面没有看到关于订单价格的相关描述，我想请教一下，这里面如何操作订单金额的，因为封装的接口入参只有产品ID（productId），我看到官方文档上面有提到关于amount的参数，这是关于交易金额的，但是我不知道如何对接到您这个支付接口里面操作，还麻烦指教，万分感谢！

**Comment by binarywang** [comment]
麻烦给出具体文档，目前代码参考的文档是这个：https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=6_4
