### ISSUE TITLE
WxCpRecordSpStatus 没有定义并支持 11-已回退状态 导致空指针

### ISSUE THREAD

**Issue by ltzhi** [Wechat-Group/WxJava#2518]
### 简要描述
当一个审批状态为11-已回退时，WxCpApprovalRecordDetail拿到的WxCpRecordSpStatus 将会是null

### 模块版本情况
* WxJava 模块名:  weixin-java-cp
* WxJava 版本号:4.2.0

### 详细描述
主动获取到：WxCpApprovalDetailResult 时，从里面取出审批记录，当获取审批记录的审批状态时，如果审批状态是11-已回退，则会返回null。
查看代码，发现WxCpRecordSpStatus 中为定义值为11的枚举。

**Comment by binarywang** [comment]
麻烦明确下，给个文档地址最好了
另外，其实你如果知道如何完善，欢迎直接PR
