### ISSUE TITLE
创建企业群发接口需要支持更多消息类型

### ISSUE THREAD

**Issue by binarywang** [Wechat-Group/WxJava#2520]
WxCpMsgTemplate 类 支持不全

文档地址：
https://work.weixin.qq.com/api/doc/90001/90143/92698

**Comment by binarywang** [comment]
已确认支持完整

**Comment by qq330496248** [comment]
大佬 WxCpMsgTemplate缺少allow_select参数，业务比较着急，麻烦帮忙看下
