### ISSUE TITLE
wxMpService.getDraftService().listDraft(page, pageSize) 获取到不到草稿

### ISSUE THREAD

**Issue by UsrLi** [Wechat-Group/WxJava#2523]
WxMpDraftList draftList = wxMpService.getDraftService().listDraft(page, pageSize) 获取到不到草稿，相应公众号明明有草稿，检查过相关参数都没错，就是获取到0条：draftList.getTotalCount()值为0

**Comment by azouever** [comment]
请问使用的版本是？我测试了最新版本v4.2.0是正常返回数据的

**Comment by UsrLi** [comment]
4.2.5.B

**Comment by UsrLi** [comment]
我试了下版本改成4.2.0也不行，是什么关键的地方没注意到吗，在草稿箱的文章就能获取的到吧？用wxMpService 是可以正常获取历史图文素材的，那说明wxMpService没问题吧

**Comment by azouever** [comment]
> 我试了下版本改成4.2.0也不行，是什么关键的地方没注意到吗，在草稿箱的文章就能获取的到吧？用wxMpService 是可以正常获取历史图文素材的，那说明wxMpService没问题吧

![image](https://user-images.githubusercontent.com/42696884/151705223-778c1022-d35e-4e58-b57d-2ec89f2ec46c.png)
是这里的内容吧，我用了
![image](https://user-images.githubusercontent.com/42696884/151705248-d0f53b24-c1ac-492f-ba43-88662e4df7a9.png)

跑了个单测，是可以获取到结果的

**Comment by binarywang** [comment]
楼主有结果没？

**Comment by UsrLi** [comment]
![image](https://user-images.githubusercontent.com/13633909/153142442-91b508a5-0165-4b43-9e72-77b240d4e518.png)
还是取到0条，没有报错

**Comment by UsrLi** [comment]
![image](https://user-images.githubusercontent.com/13633909/153142846-8ff1ec07-5dc0-4b95-841c-8ecafb4963eb.png)
这个地方也没问题

**Comment by azouever** [comment]
> ![image](https://user-images.githubusercontent.com/13633909/153142442-91b508a5-0165-4b43-9e72-77b240d4e518.png) 还是取到0条，没有报错
把你的代码弄个demo 仓库，我拉下来我来配置我的公众号信息，我跑一下

**Comment by UsrLi** [comment]
https://gitee.com/_liruijun/cuxiao-demo.git
ruoyi-system/src/main/java/com/ruoyi/system/controller/WechatController.java里的getDraftsList方法，
配置文件在 ruoyi-admin/src/main/resources/application.yml
你试一下吧，麻烦了

**Comment by azouever** [comment]
> https://gitee.com/_liruijun/cuxiao-demo.git ruoyi-system/src/main/java/com/ruoyi/system/controller/WechatController.java里的getDraftsList方法， 配置文件在 ruoyi-admin/src/main/resources/application.yml 你试一下吧，麻烦了

<img width="749" alt="image" src="https://user-images.githubusercontent.com/42696884/153576020-1b810212-9e85-45c2-b263-35c6252ee4a6.png">

<img width="513" alt="image" src="https://user-images.githubusercontent.com/42696884/153576132-dd64f63c-ab3f-466a-9fce-74bea79dfe48.png">

你这是给我了个航母啊，我改动了，可以查询到，没有问题;
不是sdk的问题

-- 
配置:
https://github.com/Wechat-Group/WxJava/tree/develop/spring-boot-starters/wx-java-mp-spring-boot-starter
微信文档:
https://developers.weixin.qq.com/doc/offiaccount/Draft_Box/Get_draft_list.html

**Comment by UsrLi** [comment]
已找到原因，还是配置的问题，谢谢了！！！
