### ISSUE TITLE
4.2.0 版本企业微信审核的时候可以添加多个附件，实体类类型不是集合，报错

### ISSUE THREAD

**Issue by tianbo-0319** [Wechat-Group/WxJava#2528]
### 简要描述
4.2.0 版本企业微信审核的时候可以添加多个附件，实体类类型不是集合，报错

### 模块版本情况
* WxJava 模块名:  weixin-java-cp
* WxJava 版本号: 4.2.0

### 详细描述
![image](https://user-images.githubusercontent.com/40235929/152930176-04af6861-827c-4fba-932a-8d4c0444867c.png)
![image](https://user-images.githubusercontent.com/40235929/152930234-cc752463-1159-45fa-9386-4419a1360ee9.png)

### 日志
![image](https://user-images.githubusercontent.com/40235929/152930259-f3ebddf7-1eb9-4fd6-a15e-761f1f37255b.png)

**Comment by binarywang** [comment]
这个有点坑

**Comment by binarywang** [comment]
暂时屏蔽该注解以免报错，
如果有可行的替代代码，欢迎随时PR。
