### ISSUE TITLE
WxMpFreePublishItem 缺少 updateTime 属性

### ISSUE THREAD

**Issue by JaynLau** [Wechat-Group/WxJava#2529]
### 简要描述
WxMpFreePublishItem 缺少 updateTime 属性

### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号: 4.2.5.B

### 详细描述
获取成功发布列表的返回属性里包含有 updateTime 属性，但是现在的模型类 WxMpFreePublishItem 里面没有该属性。

![image](https://user-images.githubusercontent.com/1670721/152956446-1730a2c8-77ca-493c-a8b9-7a58e67c2cae.png)

![image](https://user-images.githubusercontent.com/1670721/152957576-9f5eac15-e083-434e-a171-d4e6b68ee9a8.png)

**Comment by binarywang** [comment]
最新代码应该是已经加上了，还未发布版本
