### ISSUE TITLE
企微服务商 安装测试 回调agentId为空时报错

### ISSUE THREAD

**Issue by ZhouHGit** [Wechat-Group/WxJava#2532]
ERROR   : 
---- Debugging information ----
cause-exception     : java.lang.NumberFormatException
cause-message       : Zero length string
class               : java.lang.Integer
required-type       : java.lang.Integer
converter-type      : com.thoughtworks.xstream.converters.SingleValueConverterWrapper
wrapped-converter   : com.thoughtworks.xstream.converters.basic.IntConverter
line number         : 1
class[1]            : me.chanjar.weixin.cp.bean.message.WxCpXmlMessage
required-type[1]    : me.chanjar.weixin.cp.bean.message.WxCpXmlMessage
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
version             : not available
-------------------------------,  COST:31

**Comment by ZhouHGit** [comment]
接收微信请求：[signature=[d0f5dcd0d79c76f8a5f6f77bd4df7392c97633fb], timestamp=[1644808728], nonce=[1644827663], requestBody=[
<xml><ToUserName><![CDATA[ww5073a8a978f9ef81]]></ToUserName><Encrypt><![CDATA[bNKkxqjLUaSk9AtqvyMnGKJ/yxIM70Z1AWeGxJJzdlZnXDegWTSSZ6YNEmC7Lh/WIpUhZ+RXz5xKOYJdDDYu263ByI4rnn1EUqga6KOkOTub0FtYxzxA6k0+JXJhXX4Myo5hHOFOK2LGmxbisaLfQYkTOQslstECj9UHRQvGJAvwKbZ2S+Q9c5dNfg/smv+XNOZpayLg/xgLZWTM8hgJFbNxJE0LZjoXd9MDGnd9yCJFd8W5doM18iGVnJImDPPusWB9OwJFYm9NnlQZ6KQGZv1QBNO4GZillQ68u2LnNFLs6kic50u+1oLs+9EpBhlGGoyCFPzLsm1O9g29NZX5hZp0DeHbB1MfAbmepKt9xEwxup8sD3nPv1Q6Lc/wF+oM9lHh92spfh2VL8Bxf0q8/WGsdhwFC+PUu4NA4rHgLPM=]]></Encrypt><AgentID><![CDATA[]]></AgentID></xml>
]

**Comment by ZhouHGit** [comment]
requestBody `<xml><ToUserName><![CDATA[ww5073a8a978f9ef81]]></ToUserName><Encrypt><![CDATA[bNKkxqjLUaSk9AtqvyMnGKJ/yxIM70Z1AWeGxJJzdlZnXDegWTSSZ6YNEmC7Lh/WIpUhZ+RXz5xKOYJdDDYu263ByI4rnn1EUqga6KOkOTub0FtYxzxA6k0+JXJhXX4Myo5hHOFOK2LGmxbisaLfQYkTOQslstECj9UHRQvGJAvwKbZ2S+Q9c5dNfg/smv+XNOZpayLg/xgLZWTM8hgJFbNxJE0LZjoXd9MDGnd9yCJFd8W5doM18iGVnJImDPPusWB9OwJFYm9NnlQZ6KQGZv1QBNO4GZillQ68u2LnNFLs6kic50u+1oLs+9EpBhlGGoyCFPzLsm1O9g29NZX5hZp0DeHbB1MfAbmepKt9xEwxup8sD3nPv1Q6Lc/wF+oM9lHh92spfh2VL8Bxf0q8/WGsdhwFC+PUu4NA4rHgLPM=]]></Encrypt><AgentID><![CDATA[]]></AgentID></xml>`

**Comment by binarywang** [comment]
准备改成string，以避免此问题出现
