### ISSUE TITLE
jedis 不能使用  

### ISSUE THREAD

**Issue by liumiao007** [Wechat-Group/WxJava#2539]
WxRedisOps redisOps = new JedisWxRedisOps(jedisPool);
 这行代码有问题    JedisWxRedisOps  这个要传入一个 type 为 redis/clients/jedis/util/Pool    但是 实际传入的是 redis/clients/jedis/JedisPool   
   希望能 尽快优化    最好能给个push代码 的权限

**Comment by liumiao007** [comment]
我使用的版本是 4.2.0      starter里面  你的整合 是 jedis 3.3.0   我已经确认了我的版本与你starter 中的 jedis 版本一致

**Comment by binarywang** [comment]
为啥我要给你push代码的权限？
你要贡献代码的话，直接提交PR就可以的

**Comment by binarywang** [comment]
你的版本不一致问题，需要自己认真核对
