### ISSUE TITLE
最新版4.2.6.B WxOpenMaCodeTemplate 文件 sourceMiniProgramAppid/sourceMiniProgram 字段类型定义仍然存在问题

### ISSUE THREAD

**Issue by chenke91** [Wechat-Group/WxJava#2549]
最新版4.2.6.B WxOpenMaCodeTemplate 文件 sourceMiniProgramAppid/sourceMiniProgram 字段类型定义仍然存在问题
![微信截图_20220228161202](https://user-images.githubusercontent.com/6261549/155947583-53b39f13-9f7f-4bda-bad2-0c53d93c1cfd.png)

**Comment by binarywang** [comment]
这个版本确实存在问题，下一版本修复
