### ISSUE TITLE
新增草稿返回mediaId的String两头多了双引号

### ISSUE THREAD

**Issue by CodeingX** [Wechat-Group/WxJava#2553]
### 简要描述
WxMpDraftService.addDraft(WxMpAddDraft addDraft)方法返回的mediaId两头多了双引号

### 模块版本情况
* WxJava 模块名: mp
* WxJava 版本号: 4.2.0

### 详细描述
    String json = this.mpService.post(WxMpApiUrl.Draft.ADD_DRAFT, addDraft);
    return GsonParser.parse(json).get(MEDIA_ID).toString();
在将json转为对象并根据Key获取value时String的值会带有双引号

**Comment by gzlboy** [comment]
哈哈，我昨天被坑了一下午，太难注意到这个引号了

**Comment by rabbitlhf** [comment]
请问什么时候发版？ @binarywang
