### ISSUE TITLE
WxMpXmlMessage类的allFieldsMap取值问题

### ISSUE THREAD

**Issue by gzlboy** [Wechat-Group/WxJava#2554]
### 简要描述
微信事件通知的xml中有数组的情况下，存放所有属性的allFieldsMap对象只取到数组最后一个值，请问其他值怎么取？

### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号:4.2.0

### 详细描述
xml示例：
`<xml> 
  <ToUserName><![CDATA[gh_4d00ed8d6399]]></ToUserName>  
  <FromUserName><![CDATA[oV5CrjpxgaGXNHIQigzNlgLTnwic]]></FromUserName>  
  <CreateTime>1481013459</CreateTime>
  <MsgType><![CDATA[event]]></MsgType>
  <Event><![CDATA[PUBLISHJOBFINISH]]></Event>
  <PublishEventInfo>
    <publish_id>2247503051</publish_id>
    <publish_status>0</publish_status>
    <article_id><![CDATA[b5O2OUs25HBxRceL7hfReg-U9QGeq9zQjiDvy
WP4Hq4]]></article_id>
    <article_detail>
      <count>1</count>
      <item>
        <idx>1</idx>
        <article_url><![CDATA[ARTICLE_URL]]></article_url>
      </item>
      <item>
        <idx>2</idx>
        <article_url><![CDATA[ARTICLE_URL_2]]></article_url>
      </item>
    </article_detail>
  </PublishEventInfo>
</xml>`

article_detail下有两个item，但取allFieldsMap中的article_detail值，只取到最后一个item对象，第一个item数据丢了，请问怎么取全？

**Comment by binarywang** [comment]
看来是工具类方法对这种支持不好，也欢迎提供好的PR代码进行修复
