### ISSUE TITLE
微信支付申请支付账单结果WxPayApplyBillV3Result字段hash_value错误

### ISSUE THREAD

**Issue by itcrazy2019** [Wechat-Group/WxJava#2556]
简要描述
com.github.binarywang.wxpay.bean.result.WxPayApplyBillV3Result中的字段out_refund_no应该为字段hash_value

模块版本情况
WxJava 模块名: weixin-java-pay
WxJava 版本号:4.2.0（此版本未修复）
详细描述
/**

字段名：哈希值
变量名：hash_value
是否必填：是
类型：string[1,1024]
描述：
原始账单（gzip需要解压缩）的摘要值，用于校验文件的完整性。
示例值：79bb0f45fc4c42234a918000b2668d689e2bde04
*/
@SerializedName(value = "out_refund_no")
private String outRefundNo;

**Comment by papalian** [comment]
FYI

**Comment by binarywang** [comment]
这个最新版本其实早已修复

**Comment by itcrazy2019** [comment]
> 这个最新版本其实早已修复

最新版:4.2.0还是未修复哦

**Comment by binarywang** [comment]
最新版本并不是4.2.0，请看首页版本说明
