### ISSUE TITLE
企业微信第三方应用

### ISSUE THREAD

**Issue by xuthus83** [Wechat-Group/WxJava#2557]
除应用授权接口外,其他接口均使用access_token作为必传参,所以导致WxCpTpService下的service大多数接口没有携带企业的access_token请求失败

**Comment by binarywang** [comment]
你确定使用方式没问题？

**Comment by rexlin600** [comment]
version：4.1.0

企业微信部分接口从源码来看确实存在部分接口没有携带企业 access_token 的问题
![image](https://user-images.githubusercontent.com/23032549/160080034-335fb2be-a1af-4acc-9982-da21fa3676ee.png)

![image](https://user-images.githubusercontent.com/23032549/160080181-cf6c332c-fc9a-41f7-82db-8f91ce1b9573.png)

**Comment by tang226** [comment]
![image](https://user-images.githubusercontent.com/35478211/163911729-b3caf137-3a13-4cea-a0dd-e8bd3a00c683.png)
最后会拼接上accesstoken
