### ISSUE TITLE
缺少功能：小程序-手机号接口

### ISSUE THREAD

**Issue by blysin** [Wechat-Group/WxJava#2560]
### 简要描述
新版本的获取手机号接口

### 官方文档地址
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/phonenumber/phonenumber.getPhoneNumber.html#method-http

**Comment by fullee** [comment]
@binarywang 4.2.9什么时候能发布

**Comment by azouever** [comment]
develop中已添加接口(很早之前已经有人添加了)
关闭吧 不用加在4.2.9

**Comment by binarywang** [comment]
确实是有了，#2455
