### ISSUE TITLE
微信网页开发，网页授权查询用户信息问题

### ISSUE THREAD

**Issue by luqil** [Wechat-Group/WxJava#2561]
/weixin-java-common/src/main/java/me/chanjar/weixin/common/bean)/WxOAuth2UserInfo.java
内的属性不应该被删除。
根据 《微信公众平台用户信息相关接口调整公告》显示 网页授权的用户信息并没有删除用户信息。

![image](https://user-images.githubusercontent.com/33475522/158953212-655a7e59-4837-4b42-bef4-07ed80bda2bc.png)

### 模块版本情况
* WxJava 模块名: weixin-java-common
* WxJava 版本号: 4.2.0 及develop

### 详细描述
/weixin-java-common/src/main/java/me/chanjar/weixin/common/bean)/WxOAuth2UserInfo.java
内的属性不应该被删除。
根据 《微信公众平台用户信息相关接口调整公告》显示 网页授权的用户信息并没有删除用户信息。

网页授权文档连接：https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html
公告连接：https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncement&announce_id=11632637451RQs8y

**Comment by binarywang** [comment]
官方文档并没有及时更新，你确定现在还会返回这些信息吗？
即使返回空的信息，那你觉得还有用吗？

**Comment by l0702040115** [comment]
https://api.weixin.qq.com/sns/userinfo，现在这个接口确实能返回这些信息

**Comment by binarywang** [comment]
> https://api.weixin.qq.com/sns/userinfo，现在这个接口确实能返回这些信息

返回的非空信息吗？
