### ISSUE TITLE
如何配置代理服务器？

### ISSUE THREAD

**Issue by qcnuo** [Wechat-Group/WxJava#2564]
因公司网络需要配置代理才能请求到外网，内网不需要代理，所有里面请求  api.weixin.qq.com 的涉及代理问题如何解决？

**Comment by qcnuo** [comment]
设置如下全局代理，也不生效，api 也不生效
System.setProperty("http.proxyHost", "代理ip");
System.setProperty("http.proxyPort", "3128");
System.setProperty("https.proxyHost", "代理ip");
System.setProperty("https.proxyPort", "3128");

**Comment by qcnuo** [comment]
看了下源码 解决了，打扰了

**Comment by yidasanqian** [comment]
怎么解决的？

**Comment by JsonSong89** [comment]
nginx配置proxy 
```
       location /qyapi/ {
          proxy_set_header Host qyapi.weixin.qq.com;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass  https://qyapi.weixin.qq.com/;
          
       }
```

java端配置
 configStorage.setBaseApiUrl("{nginx_url}/qyapi/")

**Comment by nadirvishun** [comment]
@JsonSong89 
这两行的意思不是传递客户真实的IP过去吗？这样岂不是反而无法通过IP白名单？
```
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```
