### ISSUE TITLE
企业类型，服务商同步已安装企业的通讯录、家校通讯录等基础信息；

### ISSUE THREAD

**Issue by wangqinggo** [Wechat-Group/WxJava#2565]
### 简要描述
服务商基本都需要开发一个功能进行同步企微的基础用户信息，仔细找了文档，好像没有支持此功能，不知有没有计划？可否探讨一下

**Comment by binarywang** [comment]
请给出官方文档地址

**Comment by wangqinggo** [comment]
@binarywang 
通讯录：https://developer.work.weixin.qq.com/document/path/90967
家校通讯录：https://developer.work.weixin.qq.com/document/path/92032
服务商可以为自己的应用配置回调url，进行同步这些基础数据；安装时会全量同步，后续变更也会有事件回调；

**Comment by binarywang** [comment]
回调事件里的参数都可以通过allFieldsMap属性进行自行读取解析处理
