### ISSUE TITLE
WxPayUnifiedOrderV3Request没找到checkAndSign()方法

### ISSUE THREAD

**Issue by Jose-Guo** [Wechat-Group/WxJava#2571]
V3下单的请求类没有类似WxPayUnifiedOrderRequest中checkAndSign()的方法把WxPayConfig中的NotifyUrl填充到request中吗
请问必须手动设置WxPayUnifiedOrderV3Request的NotifyUrl？感谢！

**Comment by binarywang** [comment]
欢迎直接提供代码

**Comment by Jose-Guo** [comment]
非常感谢大佬提供的工具包，这两天顺利把微信登录和支付搞定了！
俺是菜鸡一枚，贡献代码还缺少一些修行哈哈，提出这个疑问单纯是好奇为啥没设置进去，没有深究到其中的原因，如果有冒犯到，还请见谅哈~

**Comment by binarywang** [comment]
贡献代码只是个态度问题，跟能力无关，其实想贡献就可以贡献的。
而我想说的是用代码表达可能会更有说服力些。
也许你在写代码的过程中就明白了怎么回事，也许就不会问这个问题了。
当然我只是猜测，有可能确实是代码不够完善。
因为这块代码我没用到过，其他人写的，所以也不清楚到底有没有可以优化的空间。

**Comment by Jose-Guo** [comment]
好的，明白您的意思了。
非常感谢您的回复，受益匪浅。我会再多了解一下源码，看看能不能找到问题的答案或者尝试自己写一下。
再次感谢！
