### ISSUE TITLE
企业微信获取企业全部的发表列表

### ISSUE THREAD

**Issue by KanagawaSurfing** [Wechat-Group/WxJava#2572]
![image](https://user-images.githubusercontent.com/86105771/161030790-7522c0a4-79fc-44a7-9dc2-45a2d1f254f4.png)
官方返回接口 image是个list 如下图
![image](https://user-images.githubusercontent.com/86105771/161031025-629c48da-efff-4fea-8ed9-96d41e1388a3.png)
wxJava返回WxCpGetMomentList->MomentInfo image是个对象 如下图
![1648721362(1)](https://user-images.githubusercontent.com/86105771/161031629-ae6740fd-07b4-4090-9a02-2db5265785df.jpg)
拿到官方返回结果json转换会出现报错

**Comment by binarywang** [comment]
欢迎直接PR修复，另外不建议贴截图，复制文字就可以

**Comment by binarywang** [comment]
另外你看的代码有点旧，最新代码早已经修复
