### ISSUE TITLE
企业微信通讯录新增biz_mail业务邮箱字段

### ISSUE THREAD

**Issue by justdoit-aaron** [Wechat-Group/WxJava#2584]
企业微信通讯录，新增和变更成员事件，增加企业邮箱BizMail字段

**Comment by binarywang** [comment]
事件里的消息字段可以通过那个map字段自行解析，如果你确实需要在外面获取，欢迎直接PR

**Comment by loong0306** [comment]
PR：https://github.com/Wechat-Group/WxJava/pull/2589
