### ISSUE TITLE
关于小程序wxService.getUserService().getUserInfo中的解密返回数据openid以及unionId为null

### ISSUE THREAD

**Issue by tuke-code** [Wechat-Group/WxJava#2585]
### 简要描述
关于小程序wxService.getUserService().getUserInfo中的解密返回数据openid以及unionId为null

### 模块版本情况
* WxJava 模块名:  weixin-java-miniapp
* WxJava 版本号:4.3.0

### 详细描述
关于小程序wxService.getUserService().getUserInfo中的解密返回数据openid以及unionId为null

**Comment by dinghu** [comment]
> ### 简要描述
> 关于小程序wxService.getUserService().getUserInfo中的解密返回数据openid以及unionId为null
> 
> ### 模块版本情况
> * WxJava 模块名:  weixin-java-miniapp
> * WxJava 版本号:4.3.0
> 
> ### 详细描述
> 关于小程序wxService.getUserService().getUserInfo中的解密返回数据openid以及unionId为null

我也出现了 请问这个您怎么解决的呢
