### ISSUE TITLE
apiclient_cert.p12 可以用base64 编码存储加载吗

### ISSUE THREAD

**Issue by jianchengwang** [Wechat-Group/WxJava#2586]
apiclient_cert.p12 可以用base64 编码存储加载吗，比较文件不好存储管理，

**Comment by binarywang** [comment]
你希望怎么存储，欢迎直接PR代码

**Comment by z-xiaohua** [comment]
使用以下代码获取p12证书的字节数组内容和Base64编码内容，供后来者参考

        
        File file = new File("D://apiclient_cert.p12");
        InputStream inputStream = new FileInputStream(file);
        // 获取p12证书文件内容的字节数组.
        byte[] keyContent = IOUtils.toByteArray(inputStream);

        // 获取p12证书base64编码
        String keyString = Base64.getEncoder().encodeToString(keyContent);
        System.out.println(keyString);

        // 检验Base64解密后是否相同
        byte[] configContent = Base64.getDecoder().decode(keyString);
        System.out.println(Arrays.equals(keyContent, configContent));

**Comment by binarywang** [comment]
请参考commit记录，代码里已经支持
