### ISSUE TITLE
CP_如何动态支持多个企业号

### ISSUE THREAD

**Issue by tang226** [Wechat-Group/WxJava#2594]
### 简要描述
在 **CP_如何支持多个企业号**的`wiki`中CP的基本配置信息（secret，token，aesKey）都是配置在配置文件中的，然后启动服务的时候直接生成了多个`WxCpService`然后存储在map中
```java
@PostConstruct
    public void initServices() {
        cpServices = this.properties.getAppConfigs().stream().map(a -> {
            val configStorage = new WxCpDefaultConfigImpl();
            configStorage.setCorpId(this.properties.getCorpId());
            configStorage.setAgentId(a.getAgentId());
            configStorage.setCorpSecret(a.getSecret());
            configStorage.setToken(a.getToken());
            configStorage.setAesKey(a.getAesKey());
            val service = new WxCpServiceImpl();
            service.setWxCpConfigStorage(configStorage);
            routers.put(a.getAgentId(), this.newRouter(service));
            return service;
        }).collect(Collectors.toMap(service -> service.getWxCpConfigStorage().getAgentId(), a -> a));
    }
```
### 问题
我的服务中有很多个CP的配置信息（100个）并且都存在数据库中，我感觉在项目启动的时候生成100个`WxCpService`非常不妥，并且这个配置信息还会动态递增（每接入一个CP用户，我就要在数据库中新增一条配置信息），请问有较好的方式解决这个问题吗。

就比如说我需要调用某个CP用户的接口，就根据数据库里面的配置信息为它生成一个`WxCpService`，主要的步骤就是每次都需要调用`setWxCpConfigStorage`把数据库存储的配置注入进去，但是`setWxCpConfigStorage`方法中有一个`initHttp()`，频繁的调用`initHttp()`会有性能影响吗

**Comment by didi12121** [comment]
我是写了一个根据租户id来生成不同的cpServices 的组件然后注入到spring
![image](https://user-images.githubusercontent.com/33095817/163763187-502ce911-ff22-430a-b4f2-56865f2e4621.png)
然后每次需要cpServices 的时候都通过这个方法拿到对应的cpServices

**Comment by tang226** [comment]
这样感觉可以；
请问每次去获取会很耗时吗

**Comment by didi12121** [comment]
目前看来不会

**Comment by izerui** [comment]
已经实现： https://github.com/Wechat-Group/WxJava/issues/2694

**Comment by nadirvishun** [comment]
可以参考本项目中微信公众号的解决方式，用`threadlocal`来解决，[demo](https://github.com/binarywang/weixin-java-mp-demo/blob/4ea5f12f037465db2a260c5fc24e9542a86bee62/src/main/java/com/github/binarywang/demo/wx/mp/config/WxMpConfiguration.java#L49-L78)，唯一麻烦点的是本身企业微信就是多个应用的，但如果再加上不同的企业的话话，相当于`agentId + corpId`才能确定唯一的应用。
