### ISSUE TITLE
第三方平台，缺少公众号关联小程序接口

### ISSUE THREAD

**Issue by allovine** [Wechat-Group/WxJava#2597]
涉及的接口如下：

获取公众号关联的小程序
关联小程序
解除已关联的小程序

### 官方文档地址

https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/2.0/api/Official__Accounts/Mini_Program_Management_Permission.html

**Comment by binarywang** [comment]
欢迎直接提交PR代码

**Comment by allovine** [comment]
> 欢迎直接提交PR代码

确实挺想加下提交，不过不知道怎么搞？是先拉下来WxJava项目，然后修改之后，push下，等着你这边审核，就行了吗？

**Comment by binarywang** [comment]
> > 欢迎直接提交PR代码
> 
> 确实挺想加下提交，不过不知道怎么搞？是先拉下来WxJava项目，然后修改之后，push下，等着你这边审核，就行了吗？

参考贡献指南，很简单
