### ISSUE TITLE
windows系统会话存档sdk中dll的加载因为会互相依赖所以是有顺序的，但是现在的代码里面是没有处理这个顺序的导致无法加载sdk

### ISSUE THREAD

**Issue by didi12121** [Wechat-Group/WxJava#2598]
windows系统会话存档sdk中dll的加载因为会互相依赖所以是有顺序的，但是现在的代码里面是没有处理这个顺序的导致无法加载sdk

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号:4.3.0

**Comment by 0katekate0** [comment]
自行配置一下对应的顺序？

windows:
<msgAuditLibPath>D:/WorkSpace/libcrypto-1_1-x64.dll,libssl-1_1-x64.dll,libcurl-x64.dll,WeWorkFinanceSdk.dll,libWeWorkFinanceSdk_Java.so</msgAuditLibPath>
linux:
<msgAuditLibPath>/www/osfile/work_msg_storage/libcrypto-1_1-x64.dll,libssl-1_1-x64.dll,libcurl-x64.dll,WeWorkFinanceSdk.dll,libWeWorkFinanceSdk_Java.so</msgAuditLibPath>

**Comment by 0katekate0** [comment]
> windows系统会话存档sdk中dll的加载因为会互相依赖所以是有顺序的，但是现在的代码里面是没有处理这个顺序的导致无法加载sdk
> 
> ### 模块版本情况
> * WxJava 模块名: weixin-java-cp
> * WxJava 版本号:4.3.0

自行配置一下对应的顺序？

windows:
D:/WorkSpace/libcrypto-1_1-x64.dll,libssl-1_1-x64.dll,libcurl-x64.dll,WeWorkFinanceSdk.dll,libWeWorkFinanceSdk_Java.so
linux:
/www/osfile/work_msg_storage/libcrypto-1_1-x64.dll,libssl-1_1-x64.dll,libcurl-x64.dll,WeWorkFinanceSdk.dll,libWeWorkFinanceSdk_Java.so

**Comment by didi12121** [comment]
我自己的项目里处理了，但是也许这个能加到Finance类里加载系统类库的方法？

**Comment by 0katekate0** [comment]
> 我自己的项目里处理了，但是也许这个能加到Finance类里加载系统类库的方法？

直接把lib开头的放在最前面？说一下你的想法？

**Comment by 0katekate0** [comment]
> 我自己的项目里处理了，但是也许这个能加到Finance类里加载系统类库的方法？

我可以去改下源码
