### ISSUE TITLE
微信签约预扣费通知接口，委托代扣协议ID(contractId)参数请求重复问题

### ISSUE THREAD

**Issue by 18891999885** [Wechat-Group/WxJava#2599]
### 简要描述
微信签约预扣费通知接口，委托代扣协议ID(contractId)参数重复传递
![image](https://user-images.githubusercontent.com/40842744/163970743-557fdcbf-1e59-468b-953a-ff1bd1f028b6.png)
导致如下报错
![lALPJw1WR1GKP73NAu3NBtk_1753_749](https://user-images.githubusercontent.com/40842744/163970965-e6caefd4-0312-4c7a-9ce8-def751b7e196.png)

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号: 4.3.0

### 详细描述
接口参数配置如下图:
![image](https://user-images.githubusercontent.com/40842744/163971808-1aad9306-7da3-48e4-a91e-a43cf9f9a105.png)

debug过程中，手动取消委托代扣协议ID(contractId)该参数，请求正常
未剔除contractId参数之前，如下图
![image](https://user-images.githubusercontent.com/40842744/163971323-58cb6048-5b55-4203-837b-23ee1fa7f13a.png)
剔除contractId参数参数之后，请求正常通过，如下图
![image](https://user-images.githubusercontent.com/40842744/163971555-8abd9c7a-02f2-4def-aadb-9c773d9a9aff.png)
![image](https://user-images.githubusercontent.com/40842744/163971615-2635daaf-cbde-4c21-95b7-c5b54ad4efd9.png)

注：第一次提issues，如果不对的地方还请见谅

**Comment by binarywang** [comment]
欢迎直接提交PR修复代码

**Comment by 18891999885** [comment]
> 欢迎直接提交PR修复代码

不知是我调用接口传参有问题，还是代码问题，还望大佬指点解决修复，谢谢~

**Comment by 18891999885** [comment]
有人来处理下这个问题吗~~

**Comment by binarywang** [comment]
@chanlyang 麻烦一起看下这个问题

**Comment by chanlyang** [comment]
经过测试传入contract_id并无问题，我这边代码在生产环境持续稳定运行。
解决方案：1.  联系对接的微信技术询问该报错原因。2. 在构造WxPreWithholdRequest对象时不给contractId字段赋值。
请勿直接修改源码将contract_id给remove掉。

![image](https://user-images.githubusercontent.com/36494934/164189772-398d4fdc-9912-4bc5-95f1-db2739a6b678.png)
该contract_id字段在微信支付文档中依然存在，但请求示例中却没有该字段。此问题已反馈微信。

**Comment by 18891999885** [comment]
> 经过测试传入contract_id并无问题，我这边代码在生产环境持续稳定运行。 解决方案：1. 联系对接的微信技术询问该报错原因。2. 在构造WxPreWithholdRequest对象时不给contractId字段赋值。 请勿直接修改源码将contract_id给remove掉。
> 
> ![image](https://user-images.githubusercontent.com/36494934/164189772-398d4fdc-9912-4bc5-95f1-db2739a6b678.png) 该contract_id字段在微信支付文档中依然存在，但请求示例中却没有该字段。此问题已反馈微信。




您好，请问不给contractId字段赋值，那该如何传递呢？接口怎么知道通过发送给谁？
刚测试了下，不给contractId字段赋值，会导致校验未通过
![image](https://user-images.githubusercontent.com/40842744/164195666-3babbf55-539b-4354-9827-edfa5f043b5e.png)

**Comment by chanlyang** [comment]
确实会有问题，稍后修复。
