### ISSUE TITLE
wx-java-miniapp-spring-boot-starter  这个dome运行不起来

### ISSUE THREAD

**Issue by moshuiqing** [Wechat-Group/WxJava#2601]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~

### 简要描述
__简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: 
* WxJava 版本号:（旧版本不予支持，谢谢配合）

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__

### 日志
__如果日志不多，直接使用md代码引用格式贴在此处，否则如果太长，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，然后将其url地址贴在这里__
```
日志请写于此处
```
Field maService in com.binarywang.demo.wx.miniapp.WxMiniappDemoApplication required a bean of type 'cn.binarywang.wx.miniapp.api.WxMaService' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

The following candidates were found but could not be injected:
	- Bean method 'wxMaService' in 'WxMaServiceAutoConfiguration' not loaded because @ConditionalOnBean (types: cn.binarywang.wx.miniapp.config.WxMaConfig; SearchStrategy: all) did not find any beans of type cn.binarywang.wx.miniapp.config.WxMaConfig

Action:

Consider revisiting the entries above or defining a bean of type 'cn.binarywang.wx.miniapp.api.WxMaService' in your configuration.

**Comment by binarywang** [comment]
首先你说的只是个starter，不是dome，也不是demo。
请从 https://github.com/Wechat-Group/WxJava/blob/develop/demo.md 这里参考真正的demo
