### ISSUE TITLE
增加对配置中心的兼容能力及demo

### ISSUE THREAD

**Issue by BigQ517** [Wechat-Group/WxJava#2602]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
做微服务往往绕不开，配置中心。希望微信的一些参数配置可以支持配置中心的模式或者demo，比如Nacos。

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by binarywang** [comment]
如果愿意欢迎提供相应的demo代码供其他人参考，本sdk暂不考虑这些
