### ISSUE TITLE
weixin-java-cp项目审批模块

### ISSUE THREAD

**Issue by xiaweinixxw** [Wechat-Group/WxJava#2605]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
1、me.chanjar.weixin.cp.bean.message.WxCpXmlMessage.ApprovalInfo.Detail 审核意见附件：@XStreamAlias("Attach") private String attach; 因附件可能多个建议改成：@XStreamImplicit(itemFieldName="Attach")    private List<String> attach;
2、me.chanjar.weixin.cp.bean.message.WxCpXmlMessage.ApprovalInfo.Comment审核备注信息新增附件属性@XStreamImplicit(itemFieldName="Attach") private List<String> attach;

3、建议 me.chanjar.weixin.cp.bean.oa.WxCpApproval***与me.chanjar.weixin.cp.bean.message.WxCpXmlMessage.ApprovalInfo中的属性名称保持统一，例如审核意见附件，要么都用List<String> attach 要么都用List<String> mediaIds

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by binarywang** [comment]
你的建议都很不错，欢迎直接PR
