### ISSUE TITLE
weixin-java-cp模块用户实体缺少biz_mail字段

### ISSUE THREAD

**Issue by wf270906853** [Wechat-Group/WxJava#2606]
WxCpUser实体中缺少bizMail字段。导致企业微信添加邮箱时自动生成邮箱

**Comment by binarywang** [comment]
请给出具体文档

**Comment by wf270906853** [comment]
请明示，没有看到相关的处理。

**Comment by wf270906853** [comment]
我现在遇到的问题就是自定义的邮箱没发用，然后系统自动生成了一个其他的邮箱

**Comment by wf270906853** [comment]
https://developer.work.weixin.qq.com/document/path/90195?version=4.0.3.99066&platform=mac
文档地址
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/22044679/164368088-d435ba3f-fcf9-4237-92c0-c41abbde12a3.png">

**Comment by binarywang** [comment]
欢迎直接PR代码
