### ISSUE TITLE
weixin-java-open 模块 WxOpenAuthorizerInfo 实体缺少 account_status 字段

### ISSUE THREAD

**Issue by masteranthoneyd** [Wechat-Group/WxJava#2607]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
weixin-java-open 模块 WxOpenAuthorizerInfo 实体缺少 account_status 字段
![image](https://user-images.githubusercontent.com/23326293/164384199-4653e7f9-eac0-4cea-b008-fad702a51e31.png)

### 官方文档地址
[获取授权帐号详情](https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/2.0/api/ThirdParty/token/api_get_authorizer_info.html)

**Comment by binarywang** [comment]
欢迎直接PR代码

**Comment by masteranthoneyd** [comment]
已提PR [2608](https://github.com/Wechat-Group/WxJava/pull/2608)

**Comment by masteranthoneyd** [comment]
#2610
