### ISSUE TITLE
企微"获取客户群详情"缺少state返回值

### ISSUE THREAD

**Issue by linqunxun** [Wechat-Group/WxJava#2625]
### 简要描述
版本：4.3.0
模块：weixin-java-cp
接口：WxCpService.getExternalContactService().getGroupChat()
原因：当客户通过扫描群二维码进群时，可能会带有state返回值，目前没有该返回值。

### 官方文档地址
[官方文档说明](https://developer.work.weixin.qq.com/document/path/92229#%E9%99%84%E5%BD%95%EF%BC%9A%E8%8E%B7%E5%8F%96%E5%AE%A2%E6%88%B7%E7%BE%A4%E8%AF%A6%E6%83%85%EF%BC%8C%E8%BF%94%E5%9B%9Estate%E5%8F%82%E6%95%B0)

**Comment by binarywang** [comment]
欢迎直接PR代码

**Comment by linqunxun** [comment]
收到🫡



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Binary Wang ***@***.***&gt;
发送时间: 2022年4月27日 17:31
收件人: Wechat-Group/WxJava ***@***.***&gt;
抄送: linqunxun ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Wechat-Group/WxJava] 企微"获取客户群详情"缺少state返回值 (Issue #2625)





 
欢迎直接PR代码
