### ISSUE TITLE
小程序订单生成支付参数 接口缺失问题

### ISSUE THREAD

**Issue by ludifeixingyuan** [Wechat-Group/WxJava#2631]
官方接口 生成支付参数接口缺失
官方文档地址： https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/business-capabilities/ministore/minishopopencomponent2/API/order/getpaymentparams.html
如图
[![image](https://user-images.githubusercontent.com/50260606/165942222-3c465bdf-0eff-4f7d-849b-87d2ebd05d3e.png)](https://tva1.sinaimg.cn/large/e6c9d24ely1h1qusp1cjij216t0mnaek.jpg)

**Comment by binarywang** [comment]
看不到图片，请明确描述清楚，谢谢

**Comment by ludifeixingyuan** [comment]
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/50260606/167241655-8786ad8e-e3d5-4fae-b32d-83e9cc4e9213.png">

官网文档中，小程序 有一个接口【生成支付参数】 在wxJava中找不到
官网文档地址：https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/business-capabilities/ministore/minishopopencomponent2/API/order/getpaymentparams.html

**Comment by ludifeixingyuan** [comment]
@binarywang

**Comment by binarywang** [comment]
欢迎直接实现代码并提交PR
