### ISSUE TITLE
获取小程序access_token问题

### ISSUE THREAD

**Issue by xrbear** [Wechat-Group/WxJava#2636]
在项目中通过wxMaService.getAccessToken()来获取token值，并存入缓存中。
部署到集群中后，机器上有“即将重新获取新的access_token，错误代码：40001，错误信息：access_token 无效或 AppSecret 错”的报错日志。经分析，另一个接口有调用createQrCode这个接口，token过期会报错。该报错日志大概10分钟左右报一次，很有规律性。而createQrCode这个接口的调用频次很高。多个ip如何保证getAccessToken()接口返回的token不过期且相同

**Comment by i3587616** [comment]
wxMaService.getAccessToken() 里就有过期时期设置啊，你看下那个时间是多少，redis设置的过期时间要比它这个的小

**Comment by xrbear** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xrbear** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 0katekate0** [comment]
> 在项目中通过wxMaService.getAccessToken()来获取token值，并存入缓存中。 部署到集群中后，机器上有“即将重新获取新的access_token，错误代码：40001，错误信息：access_token 无效或 AppSecret 错”的报错日志。经分析，另一个接口有调用createQrCode这个接口，token过期会报错。该报错日志大概10分钟左右报一次，很有规律性。而createQrCode这个接口的调用频次很高。多个ip如何保证getAccessToken()接口返回的token不过期且相同

在集群当中，可以缓存accessToken共享到redis当中，可以参考demo配置：
https://github.com/binarywang/weixin-java-mp-demo/blob/master/src/main/java/com/github/binarywang/demo/wx/mp/config/WxMpConfiguration.java

**Comment by xrbear** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xrbear** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
