### ISSUE TITLE
jar包转osgi包的问题

### ISSUE THREAD

**Issue by lengkangkang1996** [Wechat-Group/WxJava#2640]
### 简要描述
我的项目是在aem中开发，需要用到osgi bundle才能使用，我在eclipse中按照网上的教程将weixin-java-mp-4.3和weixin-java-common-4.3转成了osgi bundle，manifest文件截图如下
![image](https://user-images.githubusercontent.com/105356383/167827952-6300fe3f-df3d-4fcc-8f79-6c21c0996269.png)
export 出来之后，放入我的aem中，运行代码会报Could not initialize class me.chanjar.weixin.mp.api.impl.WxMpCardServiceImpl异常
我看other中有一个2.6的osgi版本，请问如何使用？或者是否有更新版本的osgi包？感谢

**Comment by binarywang** [comment]
因为osgi很少有人用，后续版本就没有维护了，如果你有兴趣，可以帮忙维护起来
