### ISSUE TITLE
2022年6月1日起，微信支付进件入驻有变，请问是否有计划对应更新

### ISSUE THREAD

**Issue by PigPinv** [Wechat-Group/WxJava#2652]
### 简要描述
2022年6月1日起，微信支付进件入驻有变，请问是否有计划对应更新。
好像是所有的商户进件接口都有改动了，包括商户自行入驻，特约商户入驻等，之前的接口估计就不兼容了。

### 官方文档地址
原文：https://mp.weixin.qq.com/s/AqbUMe0Kdfagr5Dbkf97OQ

**Comment by binarywang** [comment]
建议如果有开发能力，直接贡献代码即可

**Comment by PigPinv** [comment]
1
