### ISSUE TITLE
电商收付通中的分账结果查询功能返回结果集中的分账接收方少一个字段：detail_id

### ISSUE THREAD

**Issue by gitzh18** [Wechat-Group/WxJava#2657]
weixin-java-pay
版本：4.3.4.B（最新版）
问题描述：
电商收付通中的分账结果查询功能返回结果集中的分账接收方少一个字段：detail_id（分账明细单号）
PS：分账结果查询结果类用的是分账请求结果类，查询结果集比分账请求结果集多一个分账明细单号字段（detail_id）

分账结果查询方法：ProfitSharingResult EcommerceService.queryProfitSharing(ProfitSharingQueryRequest request) ;
少字段的类：com.github.binarywang.wxpay.bean.ecommerce.ProfitSharingResult.Receiver

微信电商收付通分账查询API：https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter7_4_2.shtml

**Comment by binarywang** [comment]
欢迎直接提交PR代码进行修复
