### ISSUE TITLE
Host name 'qyapi.weixin.qq.com'

### ISSUE THREAD

**Issue by chaorenlai** [Wechat-Group/WxJava#2659]
企业号项目，使用版本3.1.0 因为公司只能通过反向代理访问外网。在消息推送时候，会出现以下错误

javax.net.ssl.SSLPeerUnverifiedException: Host name 'qyapi.weixin.qq.com' does not match the certificate subject provided by the peer (CN=*.xxx.cn, O=*****有限公司, L=广州市, ST=广东省, C=CN)

请问是否可以忽略SSL证书。或者有其他解决方式。

**Comment by binarywang** [comment]
欢迎自行尝试修改代码，测试没问题后PR代码

**Comment by chaorenlai** [comment]
@binarywang 

哈哈，我水平比较有限，只能提供一个思路。

研究几天后，发现默认HTTP访问类DefaultApacheHttpClientBuilder就提供注入SSLConnectionSocketFactory
的方式来忽略对证书的验证。这里提供一下思路。有相同问题的话，可以参考一下。

``` 
//我因为需要redis 集群的原因，这里实现了WxCpConfigStorage，大家按照自己情况来改，这里只提供一下思路

public class WxCpJedisClusterConfigStorage implements WxCpConfigStorage {
    private volatile ApacheHttpClientBuilder apacheHttpClientBuilder;

    public ApacheHttpClientBuilder getApacheHttpClientBuilder() {
        return   this.apacheHttpClientBuilder = DefaultApacheHttpClientBuilder.get().
                sslConnectionSocketFactory(this.getSSLConnectionSocketFactory());
    }

    public void setApacheHttpClientBuilder(ApacheHttpClientBuilder apacheHttpClientBuilder) {
        this.apacheHttpClientBuilder = apacheHttpClientBuilder;
    }

    /**
     * 增加 HTTPS 访问忽略证书验证
     * @return
     * @throws NoSuchAlgorithmException
     * @throws KeyManagementException
     */
    public SSLConnectionSocketFactory getSSLConnectionSocketFactory() throws NoSuchAlgorithmException, KeyManagementException {
        SSLContext ctx = SSLContext.getInstance(SSLConnectionSocketFactory.TLS);
        ctx.init(null, new TrustManager[]{new MyX509TrustManager()}, null);
        return  new SSLConnectionSocketFactory(ctx, NoopHostnameVerifier.INSTANCE);
    }
}


public class MyX509TrustManager implements X509TrustManager{
        
    @Override
    public void checkClientTrusted(X509Certificate[] chain, String authType) throws CertificateException {
    }  
        
    @Override
    public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {
    }  
        
    @Override
    public X509Certificate[] getAcceptedIssuers() {
        return null;  
    }

}
```

**Comment by Jiiiiiin** [comment]
@binarywang 针对于无法从应用服务器出向访问微信的场景来说，忽略证书是一个刚需，虽然面很小，但是有这种需求的企业一般都是长期使用，老师您这边有没有什么好的建议，可以先从哪里突破？

**Comment by Jiiiiiin** [comment]
```java
me .chanjar :weixin .common :error .WxRuntimeException: javax.net. ssl.sSL Exception: Unrec ognized sSL message, plaintext connection?
at cn.binarywang. wX. miniapp. api . impl. BaseWxMaServiceImpl. getAccessToken(Base
WxMaSe rviceImpL. java:175)
at cn .binarywang . wx . miniapp . api. impl . BaseWxMaServiceImpL. executeInternal(Bas
eWxMaServiceImpL. java: 261)
at cn. binarywang . WX . miniapp . api . impl. BaseWxMaServiceImpL. execute (BasewxMaSer
viceImpL. java:224)
at cn. binarywang . WX . miniapp. api. impl . BaseWxMaSe rviceImpl. get (BasewxMaSe rvice
ImpL. java: 193)
at cn . binarywang. WX. miniapp . api . impL. BaseWxMaServiceImpL. jsCode2SessionInfo(
BaseWxMaServiceImpL. j ava:127 )
at cn. binarywang. WX. miniapp . api . impl . WxMaUserServiceImpL. getSessionInfo (WxMa
Use rSe rviceImpl. java:33)
...
```
类似出现这个问题

**Comment by chaorenlai** [comment]
您遇见的问题和我类似么，我在上面提供了类似是思路。通过重写WxCpConfigStorage类，


替换掉作者的实现类即可。 


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/WxJava"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月24日(星期三) 上午10:52
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] Host name 'qyapi.weixin.qq.com' (Issue #2659)





 me .chanjar :weixin .common :error .WxRuntimeException: javax.net. ssl.sSL Exception: Unrec ognized sSL message, plaintext connection? at cn.binarywang. wX. miniapp. api . impl. BaseWxMaServiceImpl. getAccessToken(Base WxMaSe rviceImpL. java:175) at cn .binarywang . wx . miniapp . api. impl . BaseWxMaServiceImpL. executeInternal(Bas eWxMaServiceImpL. java: 261) at cn. binarywang . WX . miniapp . api . impl. BaseWxMaServiceImpL. execute (BasewxMaSer viceImpL. java:224) at cn. binarywang . WX . miniapp. api. impl . BaseWxMaSe rviceImpl. get (BasewxMaSe rvice ImpL. java: 193) at cn . binarywang. WX. miniapp . api . impL. BaseWxMaServiceImpL. jsCode2SessionInfo( BaseWxMaServiceImpL. j ava:127 ) at cn. binarywang. WX. miniapp . api . impl . WxMaUserServiceImpL. getSessionInfo (WxMa Use rSe rviceImpl. java:33) ...
 
类似出现这个问题
