### ISSUE TITLE
开放平台获取授权信信息不全的问题

### ISSUE THREAD

**Issue by tri5m** [Wechat-Group/WxJava#2660]
### 简要描述
微信开放平台 WxOpenAuthorizerInfo 类中获取的信息很有限，与官方文档中获取的信息数量有差距。

### 官方文档地址
https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/2.0/api/ThirdParty/token/api_get_authorizer_info.html

**Comment by tri5m** [comment]
缺少字段：account_status，basic_config，register_type

**Comment by binarywang** [comment]
欢迎直接提交PR
