### ISSUE TITLE
WxCpGroupJoinWayInfo.JoinWay#state  类型错误

### ISSUE THREAD

**Issue by gf3gf3** [Wechat-Group/WxJava#2670]
最新版本中 me.chanjar.weixin.cp.bean.external.WxCpGroupJoinWayInfo.JoinWay#state 应该是String类型，实际为 Integer
参考 me.chanjar.weixin.cp.bean.external.WxCpUserExternalGroupChatInfo.GroupMember#state 类型

**Comment by binarywang** [comment]
看你已经提交了PR，这是很正确的做法
