### ISSUE TITLE
属性错误，改下吧。。。

### ISSUE THREAD

**Issue by mahuidong** [Wechat-Group/WxJava#2675]
https://github.com/Wechat-Group/WxJava/blob/develop/weixin-java-open/src/main/java/me/chanjar/weixin/open/bean/ma/WxMaOpenCommitStandardExt.java

这个文件这一行改下吧
``` java 
  @SerializedName("create_time")
  private String extAppId;
```

改为

``` java 
  @SerializedName("extAppid")
  private String extAppId;
```

**Comment by binarywang** [comment]
欢迎直接PR，这是最快的办法
