### ISSUE TITLE
WxMpService 无法注入

### ISSUE THREAD

**Issue by a383359959** [Wechat-Group/WxJava#2677]
SpringBoot多模块下无法注入Service

![image](https://user-images.githubusercontent.com/9694877/171356018-369f250b-29ea-4d49-a4ed-86a0be294258.png)

![image](https://user-images.githubusercontent.com/9694877/171356071-b3a3867d-7be0-4631-91a2-b5e0164cda99.png)

![image](https://user-images.githubusercontent.com/9694877/171356156-ca3fe1e5-343f-4115-a36d-5737666ef140.png)

**Comment by a383359959** [comment]
![image](https://user-images.githubusercontent.com/9694877/171356250-8ea553df-f693-48fb-bbda-29e308d487de.png)

这里也加了

**Comment by binarywang** [comment]
请参考demo，并不是你加了包扫描就会自动注入，建议学习下spring基础知识
