### ISSUE TITLE
电商收付通退款结果GSON转换报错

### ISSUE THREAD

**Issue by gitzh18** [Wechat-Group/WxJava#2688]
**问题描述**
电商收付通退款方法报错，原因是微信返回的退款创建时间字段是[rfc3339]标准格式，而RefundsResult中是date格式，GSON无法将rfc3339格式转换为Date格式从而报错，解决办法是将createTime字段改为String类型（我看其他的对应有日期的都改成了String类型）
类路径：com.github.binarywang.wxpay.bean.ecommerce.RefundsResult

关于 提交PR：小问题下个版本就随手改了吧，就不提交PR了
**版本**
* WxJava 模块名: weixin-java-pay
* WxJava 版本号:最新版

**Comment by binarywang** [comment]
越是小问题，PR不是更容易吗？

**Comment by azouever** [comment]
gson date format https://stackoverflow.com/questions/6873020/gson-date-format
