### ISSUE TITLE
基于企业微信的spring boot starter 封装，支持cp多租户，支持tp按租户获取cpservice，并调用cp-sdk进行接口调用。支持tp、cp微信回调封装。（本项目为个人项目仅做参考，希望可以在官方版本中支持）

### ISSUE THREAD

**Issue by izerui** [Wechat-Group/WxJava#2694]
参考实现地址： https://github.com/izerui/work-weixin-spring-boot

**Comment by binarywang** [comment]
你可以直接贡献代码集成到本项目中

**Comment by izerui** [comment]
好，包名和模块名要跟主项目保持一致么

**Comment by izerui** [comment]
或者我可以直接修改原始的configstorage来支持默认和多租户。

**Comment by binarywang** [comment]
> 好，包名和模块名要跟主项目保持一致么

需要的，也可以直接修改

**Comment by izerui** [comment]
最近比较忙，计划十一抽时间整合进去。

**Comment by dofindme** [comment]
这个关注下。

**Comment by zDream** [comment]
请问下，已经集成进去了吗，

**Comment by foreveryang321** [comment]
可以参考该实现：https://github.com/Wechat-Group/WxJava/pull/3149
