### ISSUE TITLE
能不能新增企业微信家校沟通系列接口

### ISSUE THREAD

**Issue by taomor2022** [Wechat-Group/WxJava#2697]
家校沟通功能接口较多，能不能增加这些接口

**Comment by binarywang** [comment]
已添加部分

**Comment by 0katekate0** [comment]
【企业微信】家校沟通所有接口已全部支持，请等待下个版本发布

**Comment by 0katekate0** [comment]
> 家校沟通功能接口较多，能不能增加这些接口

有没有使用发送学校通知，企微发送学校通知接口好像收不到通知消息？

**Comment by taomor2022** [comment]
> 

行动迅速，赞，学校通知暂时没用到，有时间我测试一下
