### ISSUE TITLE
OA - 审批 - 获取审批详情的枚举类（WxCpRecordSpStatus）和企业微信官网给出的对比少两个状态

### ISSUE THREAD

**Issue by a782272323** [Wechat-Group/WxJava#2703]
### WxCpRecordSpStatus 这个枚举类少了个状态

![image](https://user-images.githubusercontent.com/54020908/174264743-20908ae6-dfa4-46ed-9dee-32c3473b4e39.png)

### 模块版本情况
```
<dependency>
	<groupId>com.github.binarywang</groupId>
        <artifactId>weixin-java-cp</artifactId>
	<version>4.3.0</version>
</dependency>
```

### 详细描述
官网的例子（对比了一下，少了12-已加签和13-已同意并加签）
![1655456214](https://user-images.githubusercontent.com/54020908/174264575-6ab29b6b-bc24-4241-93ec-550e6405d01b.jpg)

### 官方文档地址
https://developer.work.weixin.qq.com/document/path/91983

**Comment by binarywang** [comment]
这个最新代码其实已经加了，建议使用最新测试版查看最新代码
