### ISSUE TITLE
请问怎么配置可以支持多个小程序

### ISSUE THREAD

**Issue by lwxk** [Wechat-Group/WxJava#2709]
RT

**Comment by izerui** [comment]
参考： https://github.com/Wechat-Group/WxJava/issues/2694

**Comment by 0katekate0** [comment]
> RT

可以参考demo里面的配置：
https://github.com/binarywang/weixin-java-miniapp-demo/blob/master/src/main/java/com/github/binarywang/demo/wx/miniapp/config/WxMaConfiguration.java

**Comment by binarywang** [comment]
楼上正解
