### ISSUE TITLE
me.chanjar.weixin.common.error.WxErrorException: 错误代码：-99, 错误信息：平台签名验证错误

### ISSUE THREAD

**Issue by Kidwind** [Wechat-Group/WxJava#2714]
### 简要描述
小程序的即时配送接口在接入配送平台后，使用 addOrder 接口创建配送单时，提示 "me.chanjar.weixin.common.error.WxErrorException: 错误代码：-99, 错误信息：平台签名验证错误"

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号: 4.3.6.B

### 详细描述
查看 wxMaService.post 方法的执行解析 AddOrderRequest 对象的 json 中不含有 "delivery_sign" 参数，但查看 AddOrderRequest 的基类 WxMaDeliveryBaseRequest ，发现是含有 "delivery_sign" 参数的声明的，不明白是什么原因。
WxMaDeliveryBaseRequest 类中的 delivery_sign 参数是通过 getDeliverySign 方法返回的，该方法使用 shopid、shop_order_id、appSecret 参数加密，这几个参数均已提供，但却不生成  "delivery_sign" 。

### 日志
Caused by: me.chanjar.weixin.common.error.WxErrorException: 错误代码：-99, 错误信息：平台签名验证错误
	at cn.binarywang.wx.miniapp.api.impl.WxMaImmediateDeliveryServiceImpl.parse(WxMaImmediateDeliveryServiceImpl.java:213)
	at cn.binarywang.wx.miniapp.api.impl.WxMaImmediateDeliveryServiceImpl.addOrder(WxMaImmediateDeliveryServiceImpl.java:97)

**Comment by gxh0797** [comment]
请问此问题你解决了吗？

**Comment by zhurenkai** [comment]
遇到了同样的问题，WxMaDeliveryBaseRequest.getDeliverySign()并没有把值序列化给deliverySign

**Comment by BB86818BB** [comment]
MAVEN仓库里 4.3.8.B 下载的代码跟GITHUB这里的代码不一致，应该是上传jar包的时候代码不对吧

**Comment by binarywang** [comment]
> MAVEN仓库里 4.3.8.B 下载的代码跟GITHUB这里的代码不一致，应该是上传jar包的时候代码不对吧

这里看到的是最新代码，你要看对应tag的源码才一致
