### ISSUE TITLE
微信小程序关于error日志级别问题

### ISSUE THREAD

**Issue by TonySteven** [Wechat-Group/WxJava#2716]
# 微信小程序关于error日志级别建议.

### 小程序发送订阅消息时,微信返回错误如下图所示:43101用户没有订阅的错误,一天批量发送可能很多这类错误.
![](https://tva1.sinaimg.cn/large/e6c9d24ely1h3mweyjnaij21qs0u0k4w.jpg)

### 因这类错误本服务干预不了, 故建议用warn或info级别即可.

![](https://tva1.sinaimg.cn/large/e6c9d24ely1h3mwcvl2slj21gs0u0q9l.jpg)

![](https://tva1.sinaimg.cn/large/e6c9d24ely1h3mwl0cg08j215q0l6q7n.jpg)

**Comment by binarywang** [comment]
可以的
