### ISSUE TITLE
第三方应用开发，userid_to_openuserid 接口没有

### ISSUE THREAD

**Issue by zhaowei2530** [Wechat-Group/WxJava#2717]
第三方应用开发，userid_to_openuserid 接口没有：https://developer.work.weixin.qq.com/document/path/95603
![image](https://user-images.githubusercontent.com/13674210/175902369-f2c6b5f2-9db5-4759-a3b2-4197f5814972.png)

**Comment by binarywang** [comment]
如果急需此接口，欢迎先自行实现并提交PR
