### ISSUE TITLE
微信公众号redis配置是否可以支持集群，单机的如果redis坏了，那整个服务号就无法使用了

### ISSUE THREAD

**Issue by ghost** [Wechat-Group/WxJava#2720]
### 简要描述
微信公众号redis配置是否可以支持集群，单机的如果redis坏了，那整个服务号就无法使用了

**Comment by binarywang** [comment]
redis集群的支持需要自己参考现有config改造实现

**Comment by ghost** [comment]
好的。已经想到了解决方案。具体如下：
wx.mp.config-storage.redis.host
wx.mp.config-storage.redis.port
wx.mp.config-storage.redis.database  把这三个注释；
wx.mp.config-storage.type设置为RedisTemplate 即可。这样只要原项目配置支持集群，那就可以了。
