### ISSUE TITLE
希望能支持自定义 GET_ACCESS_TOKEN_URL

### ISSUE THREAD

**Issue by zhnzntix** [Wechat-Group/WxJava#2724]
### 简要描述
多环境需要accesstoken统一，能自定义GET_ACCESS_TOKEN_URL可以方便很多呢

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by binarywang** [comment]
没看明白，建议你直接提供PR代码来表达清楚你的意思

**Comment by mastcer** [comment]
完全没这个必要，多环境是指什么呢？是说多个小程序吗？如果多个小程序的话对应的是多个WxMaConfig，没必要放在一个WxMaConfig里去处理accesstoken
