### ISSUE TITLE
请问近期有发新版的计划吗？

### ISSUE THREAD

**Issue by gzlboy** [Wechat-Group/WxJava#2728]
由于要用到一些新的接口在新版本中才实现，所以想问下大概什么时候发新版![01071761](https://user-images.githubusercontent.com/1492060/177167735-dd8c2cc3-2f28-4ba3-b7a7-8e061beac3be.png)

**Comment by 0katekate0** [comment]
先用beta版

**Comment by gzlboy** [comment]
好的，多谢哈!

> 先用beta版
