### ISSUE TITLE
商户转帐到零钱接口v3/transfer/batches测试用例访问异常

### ISSUE THREAD

**Issue by hson08** [Wechat-Group/WxJava#2734]
![image](https://user-images.githubusercontent.com/40419401/177727928-b0c8c8c2-c234-4e21-8280-48f69e1f7178.png)

**Comment by zhongjun96** [comment]
调整一下测试用例的appid，openid，userName等字段为真实字段后再试一下。还不行就提供一下完整的请求参数

**Comment by hson08** [comment]
{"appid":"wxf636efh5xxxxx","out_batch_no":"1655447999520","batch_name":"测试批次","batch_remark":"测试批次备注","total_amount":100,"total_num":1,"transfer_detail_list":[{"out_detail_no":"1655447989156","transfer_amount":100,"transfer_remark":"测试转账","openid":"oX_7Jzr9gSZz4X_Xc9-_7HGf8XzI","user_name":"测试用户"}]}

**Comment by hson08** [comment]
我知道了，不过我觉得这个test是不是可改一改。顺便按照规则修正一下。
https://developers.weixin.qq.com/community/develop/doc/000c48f9a5407895340e22f7351c00?highLine=%25E8%25AF%25B7%25E7%25A1%25AE%25E8%25AE%25A4%25E5%25BE%2585%25E5%25A4%2584%25E7%2590%2586%25E7%259A%2584%25E6%25B6%2588%25E6%2581%25AF%25E6%2598%25AF%25E5%2590%25A6%25E4%25B8%25BA%25E5%258A%25A0%25E5%25AF%2586%25E5%2590%258E%25E7%259A%2584%25E5%25AF%2586%25E6%2596%2587

**Comment by zhongjun96** [comment]
@hson08 字段添加了加密注解，按理来说会自动处理加密那些，周末我再调试一下吧 <img width="553" alt="image" src="https://user-images.githubusercontent.com/18225577/177913369-0e27b8d6-b191-4896-bb1f-1067ba9c338b.png">
