### ISSUE TITLE
退款状态常量缺失

### ISSUE THREAD

**Issue by markeNick** [Wechat-Group/WxJava#2737]
### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号: V4.3.0

### 详细描述
退款查询V3接口，官方文档：https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_1_10.shtml，对应的退款状态中异常枚举为：【ABNORMAL：退款异常】
weixin-java-pay模块中的com.github.binarywang.wxpay.bean.result.WxPayRefundQueryV3Result的退款状态描述是和官方文档一致的，
但是com.github.binarywang.wxpay.constant.WxPayConstants中的退款状态RefundStatus异常却是CHANGE
/**
* <pre>
* 字段名：退款状态
* 变量名：status
* 是否必填：是
* 类型：string[1, 32]
* 描述：
*  退款到银行发现用户的卡作废或者冻结了，导致原路退款银行卡失败，可前往商户平台（pay.weixin.qq.com）-交易中心，手动处理此笔退款。
*  枚举值：
*  SUCCESS：退款成功
*  CLOSED：退款关闭
*  PROCESSING：退款处理中
*  ABNORMAL：退款异常
*  示例值：SUCCESS
* </pre>
*/
@SerializedName(value = "status")
private String status;

![WxPayConstants退款状态](https://user-images.githubusercontent.com/46391351/177900366-bc45b20d-7894-4ddd-9bf0-2e211f8422ae.png)

![微信支付文档描述](https://user-images.githubusercontent.com/46391351/177900374-5bc6b29e-2a57-4592-a988-6668f7c9acc4.png)

**Comment by binarywang** [comment]
常量里的可能是v2接口用的，至于v3的应该还没维护进这个里面，欢迎直接PR

**Comment by markeNick** [comment]
您好，您的邮件我已经收到了。

**Comment by markeNick** [comment]
您好，您的邮件我已经收到了。
