### ISSUE TITLE
微信改版，现在获取不到用户详情

### ISSUE THREAD

**Issue by jikoy** [Wechat-Group/WxJava#2740]
新申请的微信，增加了企业可信IP配置，且获取用户信息时，信息获取不全。userInfo获取不到，查了API，似乎有较大改变，但以前的旧的企业号，完全没有问题。请大神查一下，若有需要，可提供新申请企业号的相关信息。

### 模块版本情况
* WxJava 模块名: wx-java-cp
* WxJava 版本号: 4.3.0
* 
![image](https://user-images.githubusercontent.com/10125432/178085075-8fdfc576-82f0-4a52-b302-9d87c4d25162.png)

**Comment by jikoy** [comment]
![image](https://user-images.githubusercontent.com/10125432/178085334-3260de7b-3d45-4af1-85c0-a30ea61029b8.png)
![image](https://user-images.githubusercontent.com/10125432/178085379-5067644b-1d3c-474e-8fbb-3ac98a6aca15.png)
似乎一直都是用userId来换取详情的，现在改成了用user_ticket了？

**Comment by jikoy** [comment]
![image](https://user-images.githubusercontent.com/10125432/178085588-8d73d5de-c647-4f05-b7ea-b985b3e7ec10.png)

**Comment by jikoy** [comment]
![image](https://user-images.githubusercontent.com/10125432/178085923-f576bbcf-68f0-4981-b523-5ecabe911a02.png)

**Comment by 0katekate0** [comment]
参考官方文档：https://developer.work.weixin.qq.com/document/path/90196  用户id是用来获取成员详情的

**Comment by jikoy** [comment]
明白，但是新申请的企业微信，获取的用户详情，信息不完整。你可以看一下上面的日志，旧的企业号上是正常的

**Comment by 0katekate0** [comment]
那新申请的，请求之后，返回了哪些数据

**Comment by jikoy** [comment]
![image](https://user-images.githubusercontent.com/10125432/178101336-14bcc83e-f819-4b0b-99a7-71d296c8bb73.png)

**Comment by jikoy** [comment]
好多信息显示不全了。只有部分信息了，userId，name这些正常，图像，地址啥的都是null

**Comment by jikoy** [comment]
若有需要，可以提供AppId这些信息给大神测试。

**Comment by 0katekate0** [comment]
这些信息比较隐私，最好自行测试寻找问题，不要把这些信息放到评论区；如果实在找不到，进群沟通吧（技术交流2群），如果还不行，就放到评论区吧

**Comment by jikoy** [comment]
不行的，同样的代码经过N多次测试了，新申请的企业号就是不行。

**Comment by jikoy** [comment]
技术交流2群怎么加？

**Comment by jikoy** [comment]
技术交流2群怎么加？

**Comment by 0katekate0** [comment]
钉钉技术交流群：32206329（技术交流2群）;
有没有更新后的文档，也发一下

**Comment by nadirvishun** [comment]
还真的来着，坑爹的微信啊，6月20号发布公告，6月20灰度，6月28日全量应用。但貌似对旧的应用没影响：[自建及代开发应用安全性升级](https://developer.work.weixin.qq.com/community/announcement/detail?content_id=16334603338859177543)
对于本类库来说没有api的变动，只是个人开发的登录流程需要变动了，不能`静默授权`了要`手动授权`然后额外请求`getUserDetail`接口才能获取手机号等敏感数据。

最大的影响是需要固定IP了，没法随便部署到本地了然后映射出去了。

**Comment by jikoy** [comment]
是的，我也刚刚意识到这一点，看来要做新的调整了。

**Comment by 0katekate0** [comment]
wxService.getOauth2Service().getUserDetail()
