### ISSUE TITLE
地理位置隐私查询接口，apiLink字段取错了

### ISSUE THREAD

**Issue by stxpons** [Wechat-Group/WxJava#2751]
<img width="732" alt="image" src="https://user-images.githubusercontent.com/4133964/179465555-aef1b5ac-4d65-4cc4-a3c1-cf583d604d57.png">

**Comment by stxpons** [comment]
me.chanjar.weixin.open.bean.ma.privacy.GetPrivacyInterfaceResult.Interface 这个文件

**Comment by binarywang** [comment]
欢迎直接贡献代码

**Comment by binarywang** [comment]
麻烦提供下对应文档地址
