### ISSUE TITLE
企业微信审批详情缺少控件类型

### ISSUE THREAD

**Issue by ZzzHekmatyar** [Wechat-Group/WxJava#2762]
### 简要描述
企业微信审批模块 
package me.chanjar.weixin.cp.bean.oa.applydata.ContentValue 类
缺少类型
PunchCorrection-补卡
![EC157EED-FFDA-4a38-ADAE-63485FD48EC5](https://user-images.githubusercontent.com/31466645/181449790-92aa7064-150b-45cc-aed0-c04ce8b25316.png)

**Comment by binarywang** [comment]
欢迎直接提交PR修复
