### ISSUE TITLE
关于事件推送群发结果中的 MsgID

### ISSUE THREAD

**Issue by masteranthoneyd** [Wechat-Group/WxJava#2763]
### 简要描述
在群发的事件推送报文中，有一个 `MsgID`，代表群发任务的id
<img width="376" alt="image" src="https://user-images.githubusercontent.com/23326293/182313445-e17941f7-3eac-44e7-82b3-839a025569ce.png">

`WxMpXmlMessage` 中没有改字段的映射（只有 `MsgId`），这个字段可以加上吗。。。

### 官方文档地址
[事件推送群发结果](https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Batch_Sends_and_Originality_Checks.html#7)

**Comment by binarywang** [comment]
欢迎直接PR代码

**Comment by binarywang** [comment]
或者自己从allFieldsMap里解析读取

**Comment by masteranthoneyd** [comment]
@binarywang PR已提请查收~ https://github.com/Wechat-Group/WxJava/pull/2764
