### ISSUE TITLE
企业微信官方文档更新（6.20后针对新建应用不返回用户敏感信息）

### ISSUE THREAD

**Issue by wuyongfei-1** [Wechat-Group/WxJava#2765]
### 简要描述
官方文档针对6.20后，针对新建应用将不返回用户的个人信息，期待大佬兼容新接口，发布新版本，持续关注！！！

**Comment by binarywang** [comment]
首先请提供文档，另外欢迎先自行实现代码提交PR

**Comment by wuyongfei-1** [comment]
网页授权登录：https://developer.work.weixin.qq.com/document/path/91121
扫码授权登录：https://developer.work.weixin.qq.com/document/path/91125
以上接口有变动，请知晓！（不排除其他功能接口也有变动）

**Comment by 0katekate0** [comment]
> 网页授权登录：https://developer.work.weixin.qq.com/document/path/91121 扫码授权登录：https://developer.work.weixin.qq.com/document/path/91125 以上接口有变动，请知晓！（不排除其他功能接口也有变动）

你说的是第三方应用开发还是企业内部开发，对应的接口不都有吗？，  WxTpService.getLoginInfo()....

**Comment by wuyongfei-1** [comment]
第三方应用开发，这两个接口返回的数据结构变了，以前是一个接口直接可以拿到用户信息，现在得通过两个才能拿到。

**Comment by 0katekate0** [comment]
> 

是两个接口呀，源码里面，接口早就有了

**Comment by 0katekate0** [comment]
> 第三方应用开发，这两个接口返回的数据结构变了，以前是一个接口直接可以拿到用户信息，现在得通过两个才能拿到。

去找这两个接口：WxTpService.getUserDetail3rd()，WxTpService.getUserInfo3rd()

**Comment by wuyongfei-1** [comment]
好的，感谢大佬，我研究一下子
