### ISSUE TITLE
如何添加另一个小程序的配置

### ISSUE THREAD

**Issue by yaozuowei** [Wechat-Group/WxJava#2774]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by yaozuowei** [comment]
如何添加另一个小程序的配置

**Comment by 0katekate0** [comment]
参考demo项目，配置多个appConfig，初始化多个mpservice即可

**Comment by 0katekate0** [comment]
> # 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~
> ### 简要描述
> ### 官方文档地址
> **请提供所需功能对应的微信官方文档地址以便进行确认。**

参考此配置：
https://github.com/binarywang/weixin-java-miniapp-demo/blob/master/src/main/java/com/github/binarywang/demo/wx/miniapp/config/WxMaConfiguration.java
