### ISSUE TITLE
企业微信 家校应用健康上报获取用户填写答案接口

### ISSUE THREAD

**Issue by moran002** [Wechat-Group/WxJava#2792]
### 简要描述
属性转换名称拼写错误

### 模块版本情况
* WxJava 模块名: me.chanjar.weixin.cp.bean.school.health
* WxJava 版本号:  4.0.0

### 详细描述
me.chanjar.weixin.cp.bean.school.health 包中的 WxCpGetReportAnswer类中的@SerializedName("single_chose") 名称编写错误

```

**Comment by binarywang** [comment]
欢迎直接PR修复代码，你写这个issue的时间其实就可以完成PR了
