### ISSUE TITLE
ResourcesUtils中缺少类

### ISSUE THREAD

**Issue by MingxingYe** [Wechat-Group/WxJava#2794]
com.github.binarywang.wxpay.util.ResourcesUtils中缺少jodd.util.ClassUtil类，编译时不会报错，但是运行时调用到了get相关方法会导致java.lang.NoClassDefFoundError: jodd/util/ClassUtil异常。下了源码显示是有该类的，但是从maven仓库中拉取的没有会报错，于是我将下载的源码package后发现还是出现缺少类的问题。目前我只能在本地重新添加jodd的依赖解决，但是治标不治本希望处理一下该问题

**Comment by quruihang** [comment]
同希望 + 1

**Comment by binarywang** [comment]
这个代码确实可以优化，去掉jodd的依赖代码，欢迎有精力的朋友帮忙实现下
