### ISSUE TITLE
三方小程序模版开发，上传代码并生成体验版接口增加requiredPrivateInfos参数

### ISSUE THREAD

**Issue by fcyes** [Wechat-Group/WxJava#2798]
7.14后，在代码中使用的地理位置相关接口，第三方开发者均需要在 ext_json 参数中 requiredPrivateInfos 配置项中声明

官方文档地址
https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/miniprogram-management/code-management/commit.html
https://developers.weixin.qq.com/community/develop/doc/000a02f2c5026891650e7f40351c01

**Comment by binarywang** [comment]
欢迎直接提供PR代码进行完善
