### ISSUE TITLE
多台应用实例，获取token可能会有bug

### ISSUE THREAD

**Issue by waterlang** [Wechat-Group/WxJava#2803]
<img width="910" alt="图片" src="https://user-images.githubusercontent.com/9714046/187158879-4c704a59-8ffd-45c4-903e-156070e94582.png">

这里针对jvm的锁是没问题的，如果应用是多实例的话，这里可能会出现多次获取token，还有可能先发起请求获得的token晚于后发起请求获得的token，导致最新的token被老token覆盖掉。这是不是通过你配置存放token的方式来判断使用jvm锁还是分布式来处理更好一些。

**Comment by binarywang** [comment]
多实例的情况下，你需要借助于redis等来实现锁，sdk里我记得是提供了对应的实现
