### ISSUE TITLE
wxMaUserService.getSessionInfo(jsCode) 怎么才能让它不自动刷新微信accessToken？

### ISSUE THREAD

**Issue by purpleline888** [Wechat-Group/WxJava#2810]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~

### 简要描述
__请简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: 
* WxJava 版本号:（旧版本不予支持，谢谢配合）

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__

### 日志
__如果日志不多，直接使用md代码引用格式贴在此处，否则如果太长，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，然后将其url地址贴在这里__
```
日志请写于此处
```

**Comment by purpleline888** [comment]
11

**Comment by songxianglong** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/login/auth.code2Session.html

**Comment by purpleline888** [comment]
就是这个地方很奇怪的。明明没必要刷新这个token的。
