### ISSUE TITLE
自定义交易组件

### ISSUE THREAD

**Issue by daiyun169** [Wechat-Group/WxJava#2813]
### 简要描述

售后接口地址有变更

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__
https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/business-capabilities/ministore/minishopopencomponent2/API/aftersale/add.html

**Comment by binarywang** [comment]
欢迎直接PR修复

**Comment by liming1019** [comment]
这个并不是问题，WxJava SDK是正确的。
售后接口原来命名是/shop/aftersale/add，后来由于视频号的改版，此接口被官方修改为/shop/ecaftersale/add。并且旧版本接口，官方并没有更新原有链接的文档。包括其他的售后接口也是同样的道理。提醒开发者注意的同时，也深深地鄙视下微信官方的烂文档。

以下是最新的API：
https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/business-capabilities/ministore/minishopopencomponent2/API/aftersale/add_new.html
https://developers.weixin.qq.com/community/develop/article/doc/0004e049970bd07473cdb0e575b013
