### ISSUE TITLE
微信分创建订单时候传入分账参数应该不是boolean类型的是String类型的Y才是标记分账，传true标记不成功

### ISSUE THREAD

**Issue by pandazhang520** [Wechat-Group/WxJava#2816]
微信分创建订单时候传入分账参数应该不是boolean类型的是String类型的Y才是标记分账，传true标记不成功，后面分账时候调用接口出现非分账订单不支持分账，麻烦帮忙核实下谢谢

**Comment by pandazhang520** [comment]
是否指定服务商分账	profit_sharing	否	String(16)	Y	
Y-是，需要分账

N-否，不分账

字母要求大写，不传默认不分账

**Comment by pandazhang520** [comment]
有空帮忙看看哈

**Comment by pandazhang520** [comment]
急急急 有空帮忙看下哈 谢谢了

**Comment by binarywang** [comment]
请直接给出具体的代码位置和参考文档，确定你的理解没问题的话可以直接提交修复代码

**Comment by pandazhang520** [comment]
好的已提交代码

**Comment by binarywang** [comment]
已证实错误
