### ISSUE TITLE
自定义交易组件视频号付款通知

### ISSUE THREAD

**Issue by sunchenweb** [Wechat-Group/WxJava#2817]
### 简要描述
微信自定义交易组件视频号支付成功微信平台将发送一条通知到开发者服务器，内容如下：
```
<xml>     
     <ToUserName>gh_abcdefg</ToUserName> 
     <FromUserName>oABCD</FromUserName>      
     <CreateTime>12344555555</CreateTime>     
     <MsgType>event</MsgType>      
     <Event>open_product_order_pay</Event>
     <order_info>
          <out_order_id>123456</out_order_id>
          <order_id>1234567</order_id>
          <transaction_id>42000000123123</transaction_id>
          <pay_time>2021-12-30 22:31:00</pay_time>
          <amount>10</amount>
          <sp_openid>oNMZ-5C0SPGHUiKsTwnOXpSHzFvw</sp_openid>
     </order_info>
</xml>
```
- EventType缺少open_product_order_pay;
- WxMaMessage类中缺少order_info，导致fromEncryptedJson、fromXml无法读取到相应的属性
- 官网链接 https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/business-capabilities/ministore/minishopopencomponent2/callback/order_success.html#%E5%9B%9E%E5%8C%85%E7%A4%BA%E4%BE%8B

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp

**Comment by binarywang** [comment]
欢迎直接提交PR。
另外WxMaMessage类建议先试用里面有个map字段`allFieldsMap`来获取你想要的属性

**Comment by sunchenweb** [comment]
好的，已经fork，将与近几天修改此问题并尝试提交PR

**Comment by sunchenweb** [comment]
已合并分支
