### ISSUE TITLE
会话存档支持external_redpacket类型

### ISSUE THREAD

**Issue by jinxiaoyi** [Wechat-Group/WxJava#2818]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
会话存档类型中. 暂时还不支持互通红包消息..还有todo,vote类型

### 官方文档地址
https://developer.work.weixin.qq.com/document/path/91774#%E4%BA%92%E9%80%9A%E7%BA%A2%E5%8C%85%E6%B6%88%E6%81%AF

**Comment by 0katekate0** [comment]
互通红包消息是有的，共用redpacket，投票消息官网没有json数据，你这边有没有消息的json？

**Comment by jinxiaoyi** [comment]
我看了下日志. Vote和todo 我在本地测不出来.  
企业微信端发起了投票但是类型是link
{"msgid":"8397471766999629074_1663668409559_external","action":"send","send":null,"from":"jinxiaoyi","tolist":["wo3_d2DAAAI5DwancuqE_5WBJl8kOE9Q","fanqiang","chengxuyuan","ChunBaiXiaoNiangZi","xuchenchen","wanbin","yangcongcong","wm3_d2DAAAmQ1gzS0Gq0_zFV2CgNGxcw","wm3_d2DAAAVwxTlebsUo-iAyPAUC-sZw"],"roomid":"wr3_d2DAAAi9g6AVWSZf9rChgxSSpvxw","msgtime":1663668405625,"msgtype":"link","text":null,"image":null,"revoke":null,"agree":null,"disagree":null,"voice":null,"video":null,"card":null,"location":null,"emotion":null,"file":null,"link":{"title":"测试","description":"描述s s 123","link_url":"https://doc.weixin.qq.com/forms/v/AN8A9wd2AAwAA4AYAatADUEsJfcSPsRVv_group","image_url":"https://wwcdn.weixin.qq.com/node/wework/images/notification-tform.536d92a1bf.png"},"weapp":null,"chatrecord":null,"collect":null,"redpacket":null,"meeting":null,"time":null,"user":null,"doc":null,"info":null,"calendar":null,"mixed":null,"voiceid":null,"meeting_voice_call":null,"voipid":null,"voip_doc_share":null,"sphfeed":null}
微信端发起投票
***@***.***","displayname":"腾讯投票"}}

**Comment by 0katekate0** [comment]
getChatPlainText()

1、获取下明文，贴一下vote的json，这两种类型现在官网上是没注明的，估计企微还未完善
2、发起了投票但是类型是link，那就直接获取link吧
