### ISSUE TITLE
使用微信第三方平台接口，上传扫描普通二维码规则，请求参数使用Gson转json，出现乱码

### ISSUE THREAD

**Issue by gwxh** [Wechat-Group/WxJava#2822]
### 简要描述
使用微信第三方平台接口，上传扫描普通二维码规则，请求参数使用Gson转json，url中的等于被转义 \u003d

### 模块版本情况
* WxJava 模块名:  weixin-java-open
* WxJava 版本号: 4.3.0

**Comment by binarywang** [comment]
请尽量详细描述，如果已确认是问题，建议直接提交PR代码进行修复
