### ISSUE TITLE
分配在职成员的客户群

### ISSUE THREAD

**Issue by xslong** [Wechat-Group/WxJava#2823]
### 简要描述
你好，帮忙加上此接口的实现，谢谢

《企业内部开发-服务端API-客户联系-在职继承-分配在职成员的客户群》

### 官方文档地址
[分配在职成员的客户群](https://developer.work.weixin.qq.com/document/path/95703)

**Comment by binarywang** [comment]
欢迎自行实现提供PR，如果确实急需的话，不如自己动手写，仿照现有代码会很快

**Comment by xslong** [comment]
已提交

https://github.com/Wechat-Group/WxJava/pull/2825
