### ISSUE TITLE
建议统一使用参数校验工具

### ISSUE THREAD

**Issue by qurenneng** [Wechat-Group/WxJava#2826]
拉取项目后，发现了很多 import org.jetbrains.annotations.NotNull; 报红，并且我在项目中发现了 import lombok.NonNull; 校验工具，能否统一，参数校验工具。。
![image](https://user-images.githubusercontent.com/31475285/192186596-065cd0bb-7f8f-494a-8a01-f04018e445f2.png)

**Comment by binarywang** [comment]
这确实是个问题，每个贡献者习惯不同，jetbrain的应该去掉

**Comment by qurenneng** [comment]
我可以去做这件事情吗 ，去掉 jetbrain 替换成  lombok

**Comment by binarywang** [comment]
> 我可以去做这件事情吗 ，去掉 jetbrain 替换成 lombok

当然可以，不过好像已经有人做了，下次可以及早提交PR
