### ISSUE TITLE
上传临时文件接口

### ISSUE THREAD

**Issue by Ruby8888** [Wechat-Group/WxJava#2836]
### 模块版本情况
* WxJava 模块名: weixin-java-common
* WxJava 版本号: 4.2.0

### 详细描述
 上传文件的时候创建临时文件,程序结束后临时文件还没有删除.resultFile.deleteOnExit() 这个方法是等到jvm退出以后才执行删除操作,如果服务一直在运行就一直删除不了; 是不是应该改成resultFile.delete()
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/34910318/194809661-3e8f8b3b-42f7-4b34-9ea1-3a421c6ec023.png">

#
### 日志

```
日志请写于此处
```

**Comment by binarywang** [comment]
你是否做过尝试？当时就可以删除吗？

**Comment by Ruby8888** [comment]
> 你是否做过尝试？当时就可以删除吗？

有的服务上临时文件一直删不掉,每隔几天服务器就爆磁盘满了

**Comment by binarywang** [comment]
我的意思是你把代码改成delete，你试过吗？删不掉的吧。
临时目录里的文件还是需要你自己去管理的，让系统自动清理最好，程序最好不要过多干预。
