### ISSUE TITLE
公众号获取绑定小程序bug

### ISSUE THREAD

**Issue by Gkytbn** [Wechat-Group/WxJava#2839]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~

### 简要描述
__请简单概括描述下你所遇到的问题。__

文档在这：[https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/officalaccount-management/link-miniprogram/getLinkMiniprogram.html](url)

第三方代公众号运营中的获取绑定小程序列表接口 wxamplinkget 代码在 WxOpenMaService 中 ，这个应该是公众号接口 不是小程序的接口，
wxAmpUnLink wxAmpLink getWxAmpLink 三个接口应该在 WxOpenMpService 中

### 模块版本情况
* WxJava 模块名: weixin-java-open
* WxJava 版本号:4.4.0

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__

### 日志
__如果日志不多，直接使用md代码引用格式贴在此处，否则如果太长，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，然后将其url地址贴在这里__
```
日志请写于此处
```

**Comment by binarywang** [comment]
欢迎直接提供PR代码

**Comment by binarywang** [comment]
@zhongjun96 你有什么想法

**Comment by zhongjun96** [comment]
因为当时这个接口文档是放在小程序那边的，的确是考虑不周，晚上我提RP移动一下🫣
