### ISSUE TITLE
商户投诉，获取投诉协商历史记录报错

### ISSUE THREAD

**Issue by HHC0541** [Wechat-Group/WxJava#2841]
### 简要描述
获取商户投诉协商列表出现json转换报错

### 模块版本情况
* WxJava 模块名:  weixin-java-pay
* WxJava 版本号:  4.4.2.B

### 详细描述

请求数据返回关于协商记录部分：
【响应数据】：{"data":[{"image_list":[],"log_id":"300200020221017161086544121","operate_details":"不想要了，我想要退款","operate_time":"2022-10-17T16:31:56+08:00","operate_type":"USER_CREATE_COMPLAINT","operator":"投诉人"},{"image_list":[],"log_id":"300200020221017161086653517","operate_details":"用户已向微信支付投诉贵司，请于72小时内妥善处理用户投诉。","operate_time":"2022-10-17T16:31:58+08:00","operate_type":"USER_CREATE_COMPLAINT_SYSTEM_MESSAGE","operator":"系统"},
### {"complaint_media_list":{"media_type":"OPERATION_IMAGE","media_url":["https://api.mch.weixin.qq.com/v3/merchant-service/images/ChsyMDAwMDAwMjAyMjEwMTcxNjAwMzE5NzM3MTQSGzMwMDIwMDAyMDIyMTAxNzE2MTA4NjYwOTEwMRgAIKCUtZoGKAMwAjgB"]}
,"image_list":["http://qualitymgr-40010.sh.gfp.tencent-cloud.com/FBA3E91E-CCBD-C593-E71E-8D37C944B425_40d0fc2276e30767e7f32b87eb909df4?sign=q-sign-algorithm%3dsha1%26q-ak%3dJGrb4ACVFrZzpbSa6Fo0BcVK%26q-sign-time%3d1666009622%3b1666013232%26q-key-time%3d1666009622%3b1666013232%26q-header-list%3dhost%26q-url-param-list%3d%26q-signature%3d310ca5b8f4674b3af0eba79d77ffb9ee20beecd7"],"log_id":"300200020221017161086609101","operate_details":"您好，不知道您因为什么原因需要退款？","operate_time":"2022-10-17T16:49:14+08:00","operate_type":"MERCHANT_RESPONSE","operator":"商家"},{"image_list":[],"log_id":"300200020221017171086702640","operate_details":"不是很喜欢，所以不要了","operate_time":"2022-10-17T17:10:56+08:00","operate_type":"USER_RESPONSE","operator":"投诉人"}],"limit":10,"offset":0,"total_count":4}

### 报错原因：
关于complaint_media_list参数，应该是对象来的，但是实际上转换Object的时候NegotiationHistoryResult.NegotiationHistory内是private List complaintMediaList; 造成转换报错。报错内容为：java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 442 path $.data[2].complaint_media_list

**Comment by binarywang** [comment]
欢迎直接提供修复PR

**Comment by HHC0541** [comment]
您的来信已接收，感谢您的来信！

**Comment by HHC0541** [comment]
您的来信已接收，感谢您的来信！

**Comment by binarywang** [comment]
已修复
