### ISSUE TITLE
初始化V3客户端多余代码

### ISSUE THREAD

**Issue by whaon** [Wechat-Group/WxJava#2845]
版本为4.4.0
WxPayV3HttpClientBuilder里设置validator的方法有2个
  public WxPayV3HttpClientBuilder withWechatpay(List<X509Certificate> certificates) {
    this.validator = new WxPayValidator(new CertificatesVerifier(certificates));
    return this;
  }

  public WxPayV3HttpClientBuilder withValidator(Validator validator) {
    this.validator = validator;
    return this;

WxPayConfig里initApiV3HttpClient方法中初始化httpClient时有如下代码：
      WxPayV3HttpClientBuilder wxPayV3HttpClientBuilder = WxPayV3HttpClientBuilder.create()
        .withMerchant(mchId, certSerialNo, merchantPrivateKey)
        .withWechatpay(Collections.singletonList(certificate))
        .withValidator(new WxPayValidator(verifier));

总上2出代码
.withWechatpay(Collections.singletonList(certificate))这行是无用的，会被下面那行覆盖掉，而且必须覆盖掉，如果没有下面那行反而错了

另外privateCertPath和privateCertString这2个参数是不是没用的，应该是不需要这2个参数，但代码中有做校验

**Comment by binarywang** [comment]
欢迎直接提供修复代码

**Comment by binarywang** [comment]
看不懂你要表达的意思，麻烦直接提交修复代码来说明吧

**Comment by binarywang** [comment]
看不懂你要表达的意思，麻烦直接提交修复代码来说明吧

**Comment by whaon** [comment]
see #2864
