### ISSUE TITLE
AutoUpdateCertificatesVerifier 潜在空指针风险

### ISSUE THREAD

**Issue by imyzt** [Wechat-Group/WxJava#2847]
### 简要描述

使用微信支付V3版本，接口请求前需要更新证书，`com.github.binarywang.wxpay.v3.auth.AutoUpdateCertificatesVerifier` 存在可能的空指针风险。

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号: 4.4.0

### 详细描述

产生原因分析：未正确配置 `apiV3Key` 时，173 行证书更新失败，未做 `throw` 等阻断动作，导致 `verifier` 未赋值。
https://github.com/Wechat-Group/WxJava/blob/b08530917c79971d94ba570d733f810dba483717/weixin-java-pay/src/main/java/com/github/binarywang/wxpay/v3/auth/AutoUpdateCertificatesVerifier.java#L173

223 行直接使用 `verifier`，未对属性进行空值判断，造成了可能的空指针异常。
https://github.com/Wechat-Group/WxJava/blob/b08530917c79971d94ba570d733f810dba483717/weixin-java-pay/src/main/java/com/github/binarywang/wxpay/v3/auth/AutoUpdateCertificatesVerifier.java#L223

**Comment by binarywang** [comment]
欢迎直接提供PR修复代码
