### ISSUE TITLE
公众号获取模板消息行业getIndustry字段解析错误

### ISSUE THREAD

**Issue by Gkytbn** [Wechat-Group/WxJava#2848]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~

### 简要描述
__请简单概括描述下你所遇到的问题。__

公众号获取模板消息行业接口 返回 结果{"primary_industry":{"first_class":"IT科技","second_class":"互联网|电子商务"},"secondary_industry":{"first_class":"医疗护理","second_class":"护理美容"}}

其中 secondary_industry 字段对应不上  secondIndustry

```
public class WxMpTemplateIndustry implements Serializable {
  private static final long serialVersionUID = -7700398224795914722L;

  private WxMpTemplateIndustryEnum primaryIndustry;
  private WxMpTemplateIndustryEnum secondIndustry;

  public static WxMpTemplateIndustry fromJson(String json) {
    return WxMpGsonBuilder.create().fromJson(json, WxMpTemplateIndustry.class);
  }

```

### 模块版本情况
* WxJava 模块名: weixin-java-open
* WxJava 版本号: 4.4.0

**Comment by Gkytbn** [comment]
bug找到了，枚举中定义的是   CARE_AND_BEAUTY("医药护理", "护理美容", 23) ；返回的是  {"first_class":"医疗护理","second_class":"护理美容"}   找不到所以无法转换

**Comment by binarywang** [comment]
欢迎直接提供修复代码

**Comment by langlan** [comment]
刚好遇到这个问题，准备提个 issue，巧了

/**
 * 临时修复（WARN：Hacking Style）
 */
public abstract class Fix {
    /** 业务功能前仅调一次即可，FIX: "医药护理", "医药医疗", 22 ==> 实际为 ==>：{"first_class":"医疗护理","second_class":"医药医疗"} */
    public static void fixIndustry () throws RuntimeException {
        try {
            Field field = WxMpGsonBuilder.class.getDeclaredField("INSTANCE");
            field.setAccessible(true);
            GsonBuilder INSTANCE = (GsonBuilder) field.get(WxMpGsonBuilder.class);
            Objects.requireNonNull(INSTANCE).registerTypeAdapter(WxMpTemplateIndustry.class, new WxMpIndustryGsonAdapter());
        } catch (Throwable ex) {
            throw new RuntimeException("Hacking Fix Failed!");
        }
    }

    /** "医药护理", "医药医疗", 22 ==> 实际为 ==>：{"first_class":"医疗护理","second_class":"医药医疗"} */
    static class WxMpIndustryGsonAdapter extends me.chanjar.weixin.mp.util.json.WxMpIndustryGsonAdapter {
        @Override
        public WxMpTemplateIndustry deserialize(JsonElement jsonElement, Type type, JsonDeserializationContext context)
                throws JsonParseException {
            return new WxMpTemplateIndustry()
                    .setPrimaryIndustry(this.convertFromJson(jsonElement.getAsJsonObject().get("primary_industry").getAsJsonObject()))
                    .setSecondIndustry(this.convertFromJson(jsonElement.getAsJsonObject().get("secondary_industry").getAsJsonObject()));
        }

        private WxMpTemplateIndustryEnum convertFromJson(JsonObject json) {
            String firstClass = GsonHelper.getString(json, "first_class");
            String secondClass = GsonHelper.getString(json, "second_class");

            return convert(firstClass, secondClass);
        }

        private WxMpTemplateIndustryEnum convert(String firstClass, String secondClass) {
            final WxMpTemplateIndustryEnum industryEnum = WxMpTemplateIndustryEnum.findByClass(firstClass, secondClass);
            if (industryEnum != null) {
                return industryEnum;
            }

            if (secondClass.contains("|")) {
                secondClass = secondClass.split("\\|")[1];
                WxMpTemplateIndustryEnum ret = WxMpTemplateIndustryEnum.findByClass(firstClass, secondClass);
                if (ret != null) {
                    return ret;
                }
            }

            // 仅看次分类名称
            for (WxMpTemplateIndustryEnum e : WxMpTemplateIndustryEnum.values()) {
                if (e.secondClass.equals(secondClass)) {
                    return e;
                }
            }

            return null;
        }
    }
}

**Comment by langlan** [comment]
巧了（网不稳定，先不在 Pull Request 解决了），心急的可以用下我的临时方案：

```java
/**
 * 临时修复（WARN：Hacking Style）
 */
public abstract class Fix {
    /** 业务功能前仅调一次即可，FIX: "医药护理", "医药医疗", 22 ==> 实际为 ==>：{"first_class":"医疗护理","second_class":"医药医疗"} */
    public static void fixIndustry () throws RuntimeException {
        try {
            Field field = WxMpGsonBuilder.class.getDeclaredField("INSTANCE");
            field.setAccessible(true);
            GsonBuilder INSTANCE = (GsonBuilder) field.get(WxMpGsonBuilder.class);
            Objects.requireNonNull(INSTANCE).registerTypeAdapter(WxMpTemplateIndustry.class, new WxMpIndustryGsonAdapter());
        } catch (Throwable ex) {
            throw new RuntimeException("Hacking Fix Failed!");
        }
    }

    /** "医药护理", "医药医疗", 22 ==> 实际为 ==>：{"first_class":"医疗护理","second_class":"医药医疗"} */
    static class WxMpIndustryGsonAdapter extends me.chanjar.weixin.mp.util.json.WxMpIndustryGsonAdapter {
        @Override
        public WxMpTemplateIndustry deserialize(JsonElement jsonElement, Type type, JsonDeserializationContext context)
                throws JsonParseException {
            return new WxMpTemplateIndustry()
                    .setPrimaryIndustry(this.convertFromJson(jsonElement.getAsJsonObject().get("primary_industry").getAsJsonObject()))
                    .setSecondIndustry(this.convertFromJson(jsonElement.getAsJsonObject().get("secondary_industry").getAsJsonObject()));
        }

        private WxMpTemplateIndustryEnum convertFromJson(JsonObject json) {
            String firstClass = GsonHelper.getString(json, "first_class");
            String secondClass = GsonHelper.getString(json, "second_class");

            return convert(firstClass, secondClass);
        }

        private WxMpTemplateIndustryEnum convert(String firstClass, String secondClass) {
            final WxMpTemplateIndustryEnum industryEnum = WxMpTemplateIndustryEnum.findByClass(firstClass, secondClass);
            if (industryEnum != null) {
                return industryEnum;
            }

            if (secondClass.contains("|")) {
                secondClass = secondClass.split("\\|")[1];
                WxMpTemplateIndustryEnum ret = WxMpTemplateIndustryEnum.findByClass(firstClass, secondClass);
                if (ret != null) {
                    return ret;
                }
            }

            // 仅看次分类名称
            for (WxMpTemplateIndustryEnum e : WxMpTemplateIndustryEnum.values()) {
                if (e.secondClass.equals(secondClass)) {
                    return e;
                }
            }

            return null;
        }
    }
}
```

**Comment by langlan** [comment]
巧了，也刚好遇到这个问题，心急吃个凉豆腐：

```java
/**
 * 临时修复（WARN：Hacking Style）
 */
public abstract class Fix {
    /** 配置前（其实接口调用前就行）仅调一次即可，FIX: "医药护理", "医药医疗", 22 ==> 实际为 ==>：{"first_class":"医疗护理","second_class":"医药医疗"} */
    public static void fixIndustry () throws RuntimeException {
        try {
            Field field = WxMpGsonBuilder.class.getDeclaredField("INSTANCE");
            field.setAccessible(true);
            GsonBuilder INSTANCE = (GsonBuilder) field.get(WxMpGsonBuilder.class);
            Objects.requireNonNull(INSTANCE).registerTypeAdapter(WxMpTemplateIndustry.class, new WxMpIndustryGsonAdapter());
        } catch (Throwable ex) {
            throw new RuntimeException("Hacking Fix Failed!");
        }
    }

    /** "医药护理", "医药医疗", 22 ==> 实际为 ==>：{"first_class":"医疗护理","second_class":"医药医疗"} */
    static class WxMpIndustryGsonAdapter extends me.chanjar.weixin.mp.util.json.WxMpIndustryGsonAdapter {
        @Override
        public WxMpTemplateIndustry deserialize(JsonElement jsonElement, Type type, JsonDeserializationContext context)
                throws JsonParseException {
            return new WxMpTemplateIndustry()
                    .setPrimaryIndustry(this.convertFromJson(jsonElement.getAsJsonObject().get("primary_industry").getAsJsonObject()))
                    .setSecondIndustry(this.convertFromJson(jsonElement.getAsJsonObject().get("secondary_industry").getAsJsonObject()));
        }

        private WxMpTemplateIndustryEnum convertFromJson(JsonObject json) {
            String firstClass = GsonHelper.getString(json, "first_class");
            String secondClass = GsonHelper.getString(json, "second_class");

            return convert(firstClass, secondClass);
        }

        private WxMpTemplateIndustryEnum convert(String firstClass, String secondClass) {
            final WxMpTemplateIndustryEnum industryEnum = WxMpTemplateIndustryEnum.findByClass(firstClass, secondClass);
            if (industryEnum != null) {
                return industryEnum;
            }

            if (secondClass.contains("|")) {
                secondClass = secondClass.split("\\|")[1];
                WxMpTemplateIndustryEnum ret = WxMpTemplateIndustryEnum.findByClass(firstClass, secondClass);
                if (ret != null) {
                    return ret;
                }
            }

            // 尝试仅看次分类名称
            for (WxMpTemplateIndustryEnum e : WxMpTemplateIndustryEnum.values()) {
                if (e.secondClass.equals(secondClass)) {
                    return e;
                }
            }

            return null;
        }
    }
}
```

**Comment by binarywang** [comment]
感谢楼上的hacking代码，直接贡献代码就可以，hacking真的没必要
