### ISSUE TITLE
安全模式下加密返回的文本消息解密出来后原本的换行效果没了

### ISSUE THREAD

**Issue by Folgerjun** [Wechat-Group/WxJava#2862]
明文模式下 \n 换行是正常的，安全模式下后就失去了换行的效果。

请问是需要额外做什么处理操作吗？

明文模式：
![20221030221554](https://user-images.githubusercontent.com/24917694/198883409-d285b2d4-780f-4647-afcb-e95526cce8c3.jpg)

安全模式：
![20221030221430](https://user-images.githubusercontent.com/24917694/198883369-da017741-371d-4451-9f20-939253f5f3e7.jpg)

**Comment by binarywang** [comment]
估计是微信服务器做了处理的吧
