### ISSUE TITLE
为了解决本地部署和开发白名单问题是否有代理请求

### ISSUE THREAD

**Issue by liyuan0420** [Wechat-Group/WxJava#2863]
为了节约成本，我们只有一台中间服务器专门作为代理服务器。想请求微信接口是带上代理信息。我们之前一直都是自己对接微信接口的请求上是有这些的，现在刚了解这个不知道支不支持呢？或者怎么使用呢？

**Comment by binarywang** [comment]
是支持的，你可以看下配置相关类
