### ISSUE TITLE
开发，测试和生产环境的Redis都是独立的情况下access_token统一管理的方式

### ISSUE THREAD

**Issue by ctrl-alt-xxh** [Wechat-Group/WxJava#2867]
### 简要描述####
目前框架对于access_token的管理方式，虽然提供了基于Redis的集中式缓存管理，但是，如果开发，测试和生产环境的Redis都是独立的，这就可能会导致不同环境同时刷新access_token，导致接口调用失败。demo中没有提到对应的解决方案，这个情况之前也有开发者提出相似的issue，但是情况可能存在差异 #866

### 官方文档地址
无

**Comment by binarywang** [comment]
你使用分布式事务锁就可以了，网上很多教程

**Comment by ctrl-alt-xxh** [comment]
可能你理解错了，目前开发环境，测试环境和生产环境，都有独立的redis缓存。

目前这个问题已经解决了，采用的方式是重写了框架中的getAccessToken方法，里面根据环境区分获取逻辑，如果是开发和测试环境，就通过接口方式从生产环境拿accessToken
