### ISSUE TITLE
微信公众号的url已经支持了配置化，但是小程序还不支持，请问这个有计划支持配置吗

### ISSUE THREAD

**Issue by DadySu** [Wechat-Group/WxJava#2868]
背景：
公司k8s集群与外网网络不通，无法直接访问微信域名，如果走透明代理方式，透明代理本身的性能有问题，所以计划改成先访问ngxin，然后代理到微信的域名。发现微信公众号的url已经支持了配置化，但是小程序还不支持，请问这个有计划支持配置吗？

**Comment by binarywang** [comment]
如果需求比较强烈，而且自己有开发能力，欢迎自行尝试修改实现并贡献代码

**Comment by gll910802** [comment]
一样的问题，正打算说看看有没有想过issue。兄弟目前有做处理么？
