### ISSUE TITLE
获取指定开放平台小程序服务时不会更新开放平台配置信息

### ISSUE THREAD

**Issue by wangxianglei1996** [Wechat-Group/WxJava#2870]
在获取到小程序服务时因缓存问题导致ticket不能更新 后续调用通过ticket获取令牌时返回ticket 过期

weixin-java-open  4.4.0

源码截图
![image](https://user-images.githubusercontent.com/53414604/199456655-0bdfae2e-b25b-4515-8d43-f2c892bf1ecf.png)

调用方式截图
![image](https://user-images.githubusercontent.com/53414604/199457222-458a9cdd-bcaf-4b35-9f5f-76a37e8df6b6.png)

错误信息：
【请求地址】: https://api.weixin.qq.com/cgi-bin/component/api_component_token
【请求参数】：{"component_appid":"wx3caf699f3a9e9c74","component_appsecret":"e1af192aa140bc81c2a4e971dd266d13","component_verify_ticket":"ticket@@@L-Yc0dT1hjGIKr_N6PQNXDv9lWZtuLjTTzQtOlebrIs7qp34vigAJTizZQ7xG-0gvSQDwN85F6JBwziNNWU8AQ"}
【错误信息】：错误代码：61005, 错误信息：ticket 已过期，微信原始报文：{"errcode":61005,"errmsg":"component ticket is expired rid: 6361c31b-4102c873-4f4c3823"}

**Comment by binarywang** [comment]
如果你确定问题如何修复，欢迎直接提交PR
