### ISSUE TITLE
多环境accessToken 过期错乱的问题如何解决

### ISSUE THREAD

**Issue by slin1972** [Wechat-Group/WxJava#2871]
比如我有一个appId，怎么让生产环境从微信获取，而其他开发和测试环境从生产环境获取。

我知道从安全性上来说，这样肯定有很大安全风险，但是针对中小公司来说，一般不会开发，测试，生产多个环境分别申请不同的微信号

**Comment by binarywang** [comment]
如果各个环境无法互通，那就很难做分布式锁，那就是无解的

**Comment by binarywang** [comment]
你跟他是同一个问题吧？同一个团队的？
https://github.com/Wechat-Group/WxJava/issues/2867

**Comment by liming1019** [comment]
虽然可以通过重写getAccessToken方法来解决。但我觉得根本原因在于，可能sdk有些笨重了，sdk只暴露token参数就行了，token存取这种事，交给开发者自己管理。

**Comment by binarywang** [comment]
> 虽然可以通过重写getAccessToken方法来解决。但我觉得根本原因在于，可能sdk有些笨重了，sdk只暴露token参数就行了，token存取这种事，交给开发者自己管理。

你的建议很好，可以看看怎么改造实现呢？提供个单独的方法？

**Comment by slin1972** [comment]
已经解决了

**Comment by slin1972** [comment]
> 你跟他是同一个问题吧？同一个团队的？ #2867

哈哈，不是的

**Comment by slin1972** [comment]
重写了WxMaServiceImpl.doGetAccessTokenRequest来实现
但是源码里面这个类有点坑WxMaRedisBetterConfigImpl 它没有重新实现getExpiresTime() 而且他几乎不支持扩展，所以只好自己重新实现了一个
