### ISSUE TITLE
修改敏感词规则请求体与官方提供的请求体不一致

### ISSUE THREAD

**Issue by IceMake7** [Wechat-Group/WxJava#2872]
### 简要描述
修改敏感词沿用的新增敏感词的请求体，导致一些条件无法正常修改

### 模块版本情况
* WxJava 模块名: WxCpExternalContactService 外部联系人管理接口
* WxJava 版本号: 4.4.x版本

### 详细描述
官方文档请求体：
{
	"rule_id":"xxxx",
	"rule_name":"rulename",
	"word_list":[
	  "敏感词1","敏感词2"
	],
	"extra_rule":{
			"semantics_list":[1,2,3],
	},
	"intercept_type":1,
	"add_applicable_range":{
		"user_list":["zhangshan"],
		"department_list":[2,3]
	},
	"remove_applicable_range":{
		"user_list":["zhangshan"],
		"department_list":[2,3]
	}
}
SDK中的：
public class WxCpInterceptRuleResp {

  @SerializedName("rule_name")
  private String ruleName;
  @SerializedName("rule_id")
  private String ruleId;
  @SerializedName("word_list")
  private List<String> wordList;
  @SerializedName("semantics_list")
  private List<Integer> semanticsList;
  @SerializedName("intercept_type")
  private int interceptType;
  @SerializedName("applicable_range")
  private ApplicableRange applicableRange;

  @Data
  public static class ApplicableRange {
    @SerializedName("user_list")
    private List<String> userList;
    @SerializedName("department_list")
    private List<Integer> departmentList;
    public static ApplicableRange fromJson(String json) {
      return WxCpGsonBuilder.create().fromJson(json, ApplicableRange.class);
    }

    public String toJson() {
      return WxCpGsonBuilder.create().toJson(this);
    }
  }

  public static WxCpInterceptRuleResp fromJson(String json) {
    return WxCpGsonBuilder.create().fromJson(json, WxCpInterceptRuleResp.class);
  }

  public String toJson() {
    return WxCpGsonBuilder.create().toJson(this);
  }

}

**Comment by binarywang** [comment]
麻烦直接提交PR说明，看得更清楚

**Comment by binarywang** [comment]
仔细对比看了下官方文档，这块代码确实写的不够规范，欢迎楼主能够帮忙重构，因为你用到这部分接口，可以用自己账号更快的进行调试验证，验证没问题直接提交PR即可
