### ISSUE TITLE
请问下 wxjava-pay是否支持服务商下单啊？

### ISSUE THREAD

**Issue by huihui-hb** [Wechat-Group/WxJava#2875]
请问下 wxjava-pay是否支持服务商下单啊？
服务商接口均是v3接口，请问wx-java-pay全是v2吗？

**Comment by binarywang** [comment]
支持v3，你自己看下javadoc就清楚了

**Comment by huihui-hb** [comment]
> 支持v3，你自己看下javadoc就清楚了

看到了v3方法。但是服务商不支持的吧。请问后续是否有服务商支持计划啊。感谢大佬

**Comment by lqq357** [comment]
> > 支持v3，你自己看下javadoc就清楚了
> 
> 看到了v3方法。但是服务商不支持的吧。请问后续是否有服务商支持计划啊。感谢大佬

支持服务商下单，使用方法：wxPayService.getEcommerceService().partner() 或者 wxPayService.getEcommerceService().partnerTransactions();  app支付需要自己签名。
