### ISSUE TITLE
企业微信提交审批申请接口参数跟官网接口定义有不一致的地方

### ISSUE THREAD

**Issue by fengwx007** [Wechat-Group/WxJava#2878]
企业微信提交审批申请接口，参数跟官网接口相比少了choose_department。

能否在me.chanjar.weixin.cp.bean.oa.WxCpOaApplyEventRequest里追加下choose_department参数的定义

[https://developer.work.weixin.qq.com/document/path/91853](url)

**Comment by binarywang** [comment]
欢迎直接提交PR代码
