### ISSUE TITLE
cn.binarywang.wx.miniapp.bean.live.WxMaLiveSharedCode少了@Data注解

### ISSUE THREAD

**Issue by liao564** [Wechat-Group/WxJava#2881]
cn.binarywang.wx.miniapp.bean.live.WxMaLiveSharedCode少了@Data注解

**Comment by binarywang** [comment]
这个你完全可以自己提交PR的，很快速

**Comment by binarywang** [comment]
而且你提交PR的时候就会发现，原来这个问题早就修复了，所以你也就不会再来发这个issue了

**Comment by liao564** [comment]
开发版修复的

**Comment by liao564** [comment]
> 而且你提交PR的时候就会发现，原来这个问题早就修复了，所以你也就不会再来发这个issue了

开发分支修复的
