### ISSUE TITLE
服务商，商户进件authorize_letter_copy字段类型错误

### ISSUE THREAD

**Issue by email450999788** [Wechat-Group/WxJava#2889]
/**
       * 法定代表人说明函
       */
      @SerializedName("authorize_letter_copy")
      private IdTypeEnum authorizeLetterCopy;

实际所需类型是字符串类型

**Comment by binarywang** [comment]
欢迎直接提交PR代码进行修复

**Comment by email450999788** [comment]
已提

**Comment by email450999788** [comment]
#2891
