### ISSUE TITLE
unifiedOrderV3 方法把参数 WxPayUnifiedOrderV3Request.Amount 丢掉了

### ISSUE THREAD

**Issue by 1893945** [Wechat-Group/WxJava#2890]
### 简要描述
https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_4_1.shtml
Native下单API
订单金额 amount 参数必传，
我在WxPayUnifiedOrderV3Request构造里setAmount(new WxPayUnifiedOrderV3Request.Amount() {
                    }.setTotal(price).setCurrency("CNY"))；
然后调用 ：
String codeUrl = this.wxService.createOrderV3(TradeTypeEnum.valueOf("NATIVE"), v3Request);
在 unifiedOrderV3的方法里String response = this.postV3(url, GSON.toJson(request)); 的 
GSON.toJson(request) 执行后把Amount丢掉了，运行出来的requestStr里没有amount的值了，但是提交订单失败。

### 模块版本情况
* WxJava 模块名:  weixin-java-pay
* WxJava 版本号:4.4.0

【异常信息】：输入源“/body/amount”映射到字段“订单金额”必填性规则校验失败，此字段为必填项

**Comment by binarywang** [comment]
请问你为啥要用这么奇怪的写法：
```
new WxPayUnifiedOrderV3Request.Amount(){}
```
构造方法后面加个大括号？

另外请按照规则发文，移除无用内容，谢谢

**Comment by binarywang** [comment]
还有以后有问题，可以先看看单元测试自己对照下，比如参考这个：
```
com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImplTest#testUnifiedOrderV3
```

**Comment by 1893945** [comment]
我debug跟踪过了。
new WxPayUnifiedOrderV3Request.Amount(){} 这个写法没问题的
在this.postV3(url, GSON.toJson(request)) 这里，断点打印request里的内容都用amount对象，但GSON.toJson(request)后生成的字符串里就没有amount参数了

**Comment by binarywang** [comment]
你把大括号去掉试过没？

**Comment by 1893945** [comment]
晚点去试下，谢谢

**Comment by binarywang** [comment]
我已经帮你试了，问题很简单，就是这个地方的问题

**Comment by 1893945** [comment]
ok，确实是
