### ISSUE TITLE
普通商户商家转账到零钱，接口微信接口增加了字段，最新代码没有加上

### ISSUE THREAD

**Issue by fjwhp** [Wechat-Group/WxJava#2897]
### 简要描述
对接微信接口【普通商户商家转账到零钱】微信新增了字段transfer_scene_id，必填，最新代码还没添加
1. 微信接口地址 https://pay.weixin.qq.com/docs/merchant/apis/batch-transfer-to-balance/transfer-batch/initiate-batch-transfer.html【transfer_scene_id】

### 模块版本情况
* WxJava 模块名:  [weixin-java-pay](https://github.com/Wechat-Group/WxJava/tree/develop/weixin-java-pay)
* WxJava 版本号: 4.4.0

### 详细描述
weixin-java-pay 工程模块，https://github.com/Wechat-Group/WxJava/blob/release/weixin-java-pay/src/main/java/com/github/binarywang/wxpay/bean/transfer/TransferBatchesRequest.java

TransferBatchesRequest 实体缺少字段，transfer_scene_id
微信最新接口地址，增加了字段【transfer_scene_id】 https://pay.weixin.qq.com/docs/merchant/apis/batch-transfer-to-balance/transfer-batch/initiate-batch-transfer.html

**Comment by liuwenfeng554** [comment]
找了一圈确实没找到

**Comment by ixqbar** [comment]
+1

**Comment by binarywang** [comment]
说实话这么简单的需求楼主你直接提交PR就可以了，楼上做的就很好，直接提交了PR，感谢
