### ISSUE TITLE
WxMaMessageRouter中的ThreadPoolExecutor使用默认值100，能否提供配置或根据CPU核数进行适配

### ISSUE THREAD

**Issue by jnan88** [Wechat-Group/WxJava#2898]
### 简要描述
WxMaMessageRouter中的ThreadPoolExecutor使用默认值100，能否提供配置或根据CPU核数进行适配

### 官方文档地址
[WxMaMessageRouter](https://gitee.com/binary/weixin-java-tools/blob/develop/weixin-java-miniapp/src/main/java/cn/binarywang/wx/miniapp/message/WxMaMessageRouter.java)

**Comment by nadirvishun** [comment]
这里不是有个重载方法吗：
https://github.com/Wechat-Group/WxJava/blob/b35645ee67cb15d6984628ed2c4e69c4afce513c/weixin-java-miniapp/src/main/java/cn/binarywang/wx/miniapp/message/WxMaMessageRouter.java?_pjax=%23js-repo-pjax-container#L55-L64

**Comment by jnan88** [comment]
好的，谢谢，我用4.1.0版本没有支持，我升级一下版本
