### ISSUE TITLE
关于小程序订单中心页设置

### ISSUE THREAD

**Issue by heyucong** [Wechat-Group/WxJava#2902]
2022-12-01出了新的公告：
https://developers.weixin.qq.com/community/develop/doc/00046880140f2842cdee491545b801?blockType=1
需要设置小程序订单中心页的path

第三方开发者代设置 path 的方式
1、对于新注册或有版本迭代需求的小程序：可在提审时通过参数配置该商家小程序的订单中心页 path

新增参数为：order_path；
接口为：[submit_audit](https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/miniprogram-management/code-management/submitAudit.html)
2、对于无版本迭代需求的小程序：第三方开发者可通过以下接口代商家设置订单中心页 path
[applySetOrderPathInfo](https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/miniprogram-management/basic-info-management/applySetOrderPathInfo.html)：该接口可用于批量代商家小程序提交申请设置订单中心页 path

[getOrderPathInfo](https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/miniprogram-management/basic-info-management/getOrderPathInfo.html)：该接口可用于查询商家小程序订单中心页 path 信息

**Comment by binarywang** [comment]
欢迎直接提交PR

**Comment by binarywang** [comment]
最新版本其实已经实现
