### ISSUE TITLE
解密 密文时，WxCryptUtil#bytesNetworkOrder2Number 返回 很大的 int 值，导致后面 new String 申请了 2G 内存

### ISSUE THREAD

**Issue by Pirate5946** [Wechat-Group/WxJava#2913]
me.chanjar.weixin.common.util.crypto.WxCryptUtil#decrypt(java.lang.String)

入参：I8c1HFKaBAxo2HM8lxWNso6LIodlBBlOldGelSMTaDsUd4uH1dCJRGS7VN5m6aYhJtt8Wqh9OQPE+EkVvYwrnNs7nRcdA6csYdGrbUiv/RvlnvKZw/cDaMC8EFfJv12HLoD79nE6PubCG7Kbp3Z9HZJ2ejII/J1EzrNgQftXKpHpZLWEZ8v7fRaNBx8FYID6YJdCnBSSlRR1KP1Fr7PEOc7XNS4DsNggTVxqGR76JSxmmlrSzOuMEF5GS3AVJ948z7I4qZQS/xlm0GmhjUug/Qap0ko73ptwLmZc8rsOWGFihbf+S5UUR7iDkKmobfYh2b8S9kePlcTn+1dr8+OtkiD8C7/g3hgmySSrCpHLe7FA836OFKebPOYFidf9foAgeb51WCioCe0paIb1DtBSYHGO1L4kZOG1PqjOqVZ6OBU4fM5mZLwsuA66zXKpp0nF/6U+f/S1jv50dR9WH4iA+hcInonlhPVcsMB7bZR98rtOHGGHnc9lhxS/51CMxIjS9c4y+bCjEHpxCPHSuFBeHNULdgqz9HWCyUfulzVfTU5fwtL5onU1UG6wVmlOJbNeThku62Rc+C5xw++lz/qZaQ==

me.chanjar.weixin.common.util.crypto.WxCryptUtil#bytesNetworkOrder2Number

![image](https://user-images.githubusercontent.com/22493889/209941934-d875dab5-6182-4081-81d9-f92af273ae5c.png)

版本：
![image](https://user-images.githubusercontent.com/22493889/209942194-40ebcbe5-1686-4782-8c79-30ecbe46f525.png)

**Comment by Pirate5946** [comment]
破案了，秘钥配置错误，导致解密异常，导致new String 申请了很大的内存

**Comment by lj199117** [comment]
> 破案了，秘钥配置错误，导致解密异常，导致new String 申请了很大的内存

老哥，我也遇到了，请问是怎么解决的？
