### ISSUE TITLE
商户转账到零钱

### ISSUE THREAD

**Issue by UpdateCw** [Wechat-Group/WxJava#2917]
转账金额字段类型为什么是Interger ，如果转账0.01 怎么办 很难受啊。。。

**Comment by UpdateCw** [comment]
![image](https://user-images.githubusercontent.com/21016670/211279196-5c7a3ba9-d1f7-4e79-b836-446f8434a51c.png)
![image](https://user-images.githubusercontent.com/21016670/211279223-6cb7b3c6-dead-4773-a198-17c067d711ac.png)

**Comment by binarywang** [comment]
单位为分，这个很难理解吗？

**Comment by UpdateCw** [comment]
对哈 我的错 😓
