### ISSUE TITLE
第三方平台获取授权小程序的登录用户手机号

### ISSUE THREAD

**Issue by guangxian** [Wechat-Group/WxJava#2918]
### 简要描述
需求：第三方平台在授权小程序中获取登录用户的手机号
目前只使用了weixin-java-open包，但该包未含小程序phonenumber.getPhoneNumber 接口，是不是还需引入weixin-java-miniapp包去实现获取手机号

### 官方文档地址
https://developers.weixin.qq.com/miniprogram/dev/OpenApiDoc/user-info/phone-number/getPhoneNumber.html

**Comment by binarywang** [comment]
open模块已经自动依赖了miniapp模块，你看下依赖关系就清楚了

**Comment by cnscoo** [comment]
miniapp 模块中的 phonenumber.getPhoneNumber 接口应该是小程序自己开发时调用的，第三方服务商代替小程序获取登陆用户手机号确实没有提供

官方文档说明：

**第三方调用**

-  调用方式以及出入参和HTTPS相同，仅是调用的token不同
- 该接口所属的权限集id为：18
- 服务商获得其中之一权限集授权后，可通过使用[authorizer_access_token](https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/2.0/api/ThirdParty/token/api_authorizer_token.html)代商家进行调用

难道每次调用的时候，构建一个该小程序的WxMaService和WxMaUserService? 或者是有其他的写法？

**Comment by cnscoo** [comment]
看了源码才明白了，服务商代替小程序的实现有很多，需要获取代替小程序操作的服务。

```java
WxOpenMaService maService = wxOpenService.getWxOpenComponentService().getWxMaServiceByAppid(appid);
WxMaPhoneNumberInfo phoneInfo = maService.getUserService().getPhoneNoInfo(code);
```
