### ISSUE TITLE
特约商户进件提交申请单主体资料中的主体类型少了政府类型

### ISSUE THREAD

**Issue by zhengxueling009** [Wechat-Group/WxJava#2919]
特约商户进件提交申请单主体资料中的主体类型SubjectTypeEnum枚举少了政府类型SUBJECT_TYPE_GOVERNMENT

**Comment by binarywang** [comment]
欢迎直接PR，谢谢

**Comment by binarywang** [comment]
另外最好请给出对应文档地址方便参考

**Comment by zhengxueling009** [comment]
> https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter11_1_1.shtml

**Comment by zhengxueling009** [comment]
麻烦更新发布一下maven版本

**Comment by binarywang** [comment]
会尽快了
