### ISSUE TITLE
互联企业消息推送需要怎么实现

### ISSUE THREAD

**Issue by adogcode** [Wechat-Group/WxJava#2926]
### 简要描述
互联企业消息推送需要怎么实现，需要向关联企业进行消息推送，接口目前是分开的

### 官方文档地址
https://developer.work.weixin.qq.com/document/path/90250

**Comment by binarywang** [comment]
me.chanjar.weixin.cp.api.impl.WxCpMessageServiceImpl#sendLinkedCorpMessage  这个方法不是吗？
