### ISSUE TITLE
自定义交易组件升级为视频号交易组件

### ISSUE THREAD

**Issue by JRGavin** [Wechat-Group/WxJava#2927]
自定义交易组件已经升级为视频号交易组件，接口与原来的有差异。希望能有计划更新

### 官方文档地址
https://support.weixin.qq.com/cgi-bin/mmsupportacctnodeweb-bin/pages/VvcAWqpIqxzcqzBp
https://developers.weixin.qq.com/doc/channels/API/basics/getaccesstoken.html

**Comment by binarywang** [comment]
建议如果楼主急需相关功能，先自行实现，然后提交PR
