### ISSUE TITLE
阅读wxjava 源码一些问题

### ISSUE THREAD

**Issue by su6** [Wechat-Group/WxJava#2929]
比如  public class WxCpUserServiceImpl implements WxCpUserService {
  private final WxCpService mainService;

 @Override
  public void authenticate(String userId) throws WxErrorException {
    this.mainService.get(this.mainService.getWxCpConfigStorage().getApiUrl(USER_AUTHENTICATE + userId), null);
  }
}

mainService 实例是怎么拿到的，这块一直搞明白

**Comment by zhongjun96** [comment]
Lombok  的 `RequiredArgsConstructor` 注解

**Comment by su6** [comment]
Hi
  你好这是一封自动回复邮件，现在是10.1嗨皮七天乐的时间，稍后我会马上回复你的邮件的

**Comment by su6** [comment]
Hi
  你好这是一封自动回复邮件，现在是10.1嗨皮七天乐的时间，稍后我会马上回复你的邮件的
