### ISSUE TITLE
企业微信消息集成redission后,idea debug时发现WxCpRedissonConfigImpl存在栈溢出

### ISSUE THREAD

**Issue by jgf-93** [Wechat-Group/WxJava#2932]
### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号:4.4.0

### 详细描述
企业微信发送消息集成WxCpRedissonConfigImpl。 idea debug时发现该类调用存在粘溢出
具体错误信息
Method threw 'java.lang.StackOverflowError' exception. Cannot evaluate me.chanjar.weixin.cp.config.impl.WxCpRedissonConfigImpl.toString()

**Comment by binarywang** [comment]
欢迎直接提供修复代码

**Comment by ouzhangpeng** [comment]
可能是你没有配置appid或者secret导致的，gson tostring的时候会对账溢出
