### ISSUE TITLE
企业微信接口地址变动

### ISSUE THREAD

**Issue by jinxiaoyi** [Wechat-Group/WxJava#2933]
你好. 我现在使用的版本是4.4.0
我今天发现获取访问用户身份相关接口有变动. /auth  但是我看了源码还是访问是/user 后期有计划改动吗
![image](https://user-images.githubusercontent.com/34831856/218971727-b766c2d1-bcad-4626-82fd-27271e1af62f.png)
企业微信接口如下

https://developer.work.weixin.qq.com/document/path/91023
<img width="977" alt="image" src="https://user-images.githubusercontent.com/34831856/218971839-468f3c9d-d1e6-4ff3-85eb-43a3e10516ea.png">

https://developer.work.weixin.qq.com/document/path/95833
<img width="986" alt="image" src="https://user-images.githubusercontent.com/34831856/218971911-7c1fb645-8218-45a7-8c1a-f3b3f40847a4.png">

**Comment by binarywang** [comment]
你确定现有代码有问题？

**Comment by jinxiaoyi** [comment]
现在可用.就是官方文档没这个接口了. 但是能正常使用

**Comment by binarywang** [comment]
你可以尝试修改代码为新的接口地址，测试下如果没问题，可以提交个PR
