### ISSUE TITLE
企业微信中客户联系、上下游、通讯录、微信客服等功能一起开发时，WxCpService 对象如何定义

### ISSUE THREAD

**Issue by amwitx** [Wechat-Group/WxJava#2935]
我看了demo代码 key是 agentid，但是企微后台，除了上下游；客户联系、通讯录、微信客服都是没有AgentId这个配置项的
private static Map<Integer, WxCpService> cpServices = Maps.newHashMap();

    @PostConstruct
    public void initServices() {
        cpServices = this.properties.getAppConfigs().stream().map(a -> {
            val configStorage = new WxCpDefaultConfigImpl();
            configStorage.setCorpId(this.properties.getCorpId());
            configStorage.setAgentId(a.getAgentId());
            configStorage.setCorpSecret(a.getSecret());
            configStorage.setToken(a.getToken());
            configStorage.setAesKey(a.getAesKey());
            val service = new WxCpServiceImpl();
            service.setWxCpConfigStorage(configStorage);
            routers.put(a.getAgentId(), this.newRouter(service));
            return service;
        }).collect(Collectors.toMap(service -> service.getWxCpConfigStorage().getAgentId(), a -> a));
    }

**Comment by binarywang** [comment]
其他的agentid你可以随便定义
