### ISSUE TITLE
企业微信群机器人  

### ISSUE THREAD

**Issue by becage** [Wechat-Group/WxJava#2938]
### 简要描述
```https://github.com/Wechat-Group/WxJava/issues/1720``` 这里有添加新功能，
但是```https://github.com/Wechat-Group/WxJava/wiki```没有企业微信群机器人文档，
该如何使用？
能更新下文档吗？Thanks.

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by binarywang** [comment]
如果需要文档，可以自行更新wiki，谢谢，不过目前看来比较简单，自己看javadoc即可
