### ISSUE TITLE
企业微信 不同应用secret 获取access_token 问题

### ISSUE THREAD

**Issue by su6** [Wechat-Group/WxJava#2940]
针对不同 应用 secret，如何保存不同access_token 实例，代码里获取access_token 只支持一个应用

**Comment by nadirvishun** [comment]
demo中有演示啊：[weixin-java-cp-demo](https://github.com/binarywang/weixin-java-cp-demo)

**Comment by su6** [comment]
Hi
  你好这是一封自动回复邮件，现在是10.1嗨皮七天乐的时间，稍后我会马上回复你的邮件的

**Comment by su6** [comment]
Hi
  你好这是一封自动回复邮件，现在是10.1嗨皮七天乐的时间，稍后我会马上回复你的邮件的

**Comment by su6** [comment]
Hi
  你好这是一封自动回复邮件，现在是10.1嗨皮七天乐的时间，稍后我会马上回复你的邮件的
