### ISSUE TITLE
forked from chanjarster/weixin-java-tools

### ISSUE THREAD

**Issue by zyhui98** [Wechat-Group/WxJava#2943]
仓库可以换下吗，经常跳到老文档里面去了。

**Comment by binarywang** [comment]
完全没听懂你说的啥意思，什么仓库，什么文档

**Comment by zyhui98** [comment]
嗯，没说清楚。我是说这个仓库是fork forked from chanjarster/weixin-java-tools。

目前这个仓库的帮助文档里面有些链接，还是会跳到chanjarster/weixin-java-tools里面。

可以考虑一下切换一下。

**Comment by binarywang** [comment]
wiki文档其实是谁都可以编辑的，如果你发现有问题的链接，可以随手帮忙修复了
