### ISSUE TITLE
请求添加对lettuce的支持，

### ISSUE THREAD

**Issue by guangxian** [Wechat-Group/WxJava#2945]
springboot默认lettuce，适用范围较广，请求添加对lettuce的支持

**Comment by binarywang** [comment]
欢迎直接贡献代码，你应该对lettuce比较熟吧，其他人可能没用到，也不方便贡献代码

**Comment by zhaohanjiangit** [comment]
貌似不能直接提交代码吧？

**Comment by binarywang** [comment]
> 貌似不能直接提交代码吧？

请阅读下代码贡献指南，通过PR贡献代码

**Comment by foreveryang321** [comment]
使用 spring-boot 直接用 redisTemplate 即可，不需要考虑 spring-boot 使用的是 jedis 还是 lettuce 客户端
