### ISSUE TITLE
微信消费者投诉2.0详情接口升级导致接口处理失败

### ISSUE THREAD

**Issue by aammio** [Wechat-Group/WxJava#2947]
微信消费者投诉2.0详情接口升级，新增字段，字段类型修改，导致查询报错

**Comment by binarywang** [comment]
具体是什么问题，如果你知道哪里的问题，欢迎直接提交PR代码

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/pull/2946  难道是这个问题？

**Comment by aammio** [comment]
是的这个问题

**Comment by binarywang** [comment]
那请耐心等待新版本发布
