### ISSUE TITLE
小程序的“微信人脸核身接口能力”接口计划开发吗？

### ISSUE THREAD

**Issue by zhaohanjiangit** [Wechat-Group/WxJava#2949]
小程序的“微信人脸核身接口能力”接口计划开发吗？
官方文档地址：https://developers.weixin.qq.com/community/business/doc/000442d352c1202bd498ecb105c00d

**Comment by binarywang** [comment]
暂无计划，如果楼主亟需，建议自己动手丰衣足食，下一大版本马上要发布了，希望你能赶上

**Comment by jiangxinxian** [comment]
希望作者可以支持小程序“微信人脸核身接口能力”，自己动手还是太多BUG了

**Comment by binarywang** [comment]
首先得有时间，其次得有权限的账号可以验证吧，你们需要此功能的肯定都是具备这些条件的吧，赶快行动起来吧，不要等了
