### ISSUE TITLE
查询投诉单详情API可能存在一个bug

### ISSUE THREAD

**Issue by lalinking** [Wechat-Group/WxJava#2952]
### 简要描述
  投诉单详情可以获取到一个投诉资料列表，内容是图片链接地址，但我发现这个地址有时候含特殊字符会导致下载失败。
比如这个链接：https://api.mch.weixin.qq.com/v3/merchant-service/images/ChsyMDAwMDAwMjAyMzAzMTcxODAwNjk0NzQxMjYYBSCd/9CgBigBMAE4AQ==
包含了一个特殊字符 "/" 这种情况不管是否先进行转义得到的签名字符串都会是错的。（从文档看这种字符是不应该存在的）

**Comment by lalinking** [comment]
获取到的图片链接：https://api.mch.weixin.qq.com/v3/merchant-service/images/ChsyMDAwMDAwMjAyMzAzMTcxODAwNjk0NzQxMjYYBSCd/9CgBigBMAE4AQ%3D%3D

测试了转换成以下链接均下载失败：
https://api.mch.weixin.qq.com/v3/merchant-service/images/ChsyMDAwMDAwMjAyMzAzMTcxODAwNjk0NzQxMjYYBSCd/9CgBigBMAE4AQ==
https://api.mch.weixin.qq.com/v3/merchant-service/images/ChsyMDAwMDAwMjAyMzAzMTcxODAwNjk0NzQxMjYYBSCd%2F9CgBigBMAE4AQ%3D%3D
https://api.mch.weixin.qq.com/v3/merchant-service/images/ChsyMDAwMDAwMjAyMzAzMTcxODAwNjk0NzQxMjYYBSCd/9CgBigBMAE4AQ%3D%3D

**Comment by lalinking** [comment]
另一个正常的链接： https://api.mch.weixin.qq.com/v3/merchant-service/images/ChsyMDAwMDAwMjAyMzAzMDExNTAwNjUzMjkzMjIYASClw7CgBigBMAE4AQ%3D%3D

转码成 https://api.mch.weixin.qq.com/v3/merchant-service/images/ChsyMDAwMDAwMjAyMzAzMDExNTAwNjUzMjkzMjIYASClw7CgBigBMAE4AQ== 进行签名能正常下载图片。

另外还发现图片链接里还有 + 字符，和 / 一样都是url里面的特殊字符，链接里不应该包含这样的字符。

**Comment by binarywang** [comment]
这个问题楼主是否有修复办法？

**Comment by lalinking** [comment]
> 这个问题楼主是否有修复办法？

我没找到办法，所以到处提问
