### ISSUE TITLE
import org.apache.commons.lang3.RegExUtils;

### ISSUE THREAD

**Issue by 7757** [Wechat-Group/WxJava#2953]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~

### 简要描述
__请简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: wx-pay
* WxJava 版本号:4.4.0

### 详细描述
正则工具类不存在

### 日志
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/48285391/226167754-5eb11191-e0d7-4e4f-8076-ed83e60345e4.png">

```
日志请写于此处
```
java.lang.NoClassDefFoundError: org/apache/commons/lang3/RegExUtils

**Comment by binarywang** [comment]
是你的commons-lang3版本跟本SDK需要的不一致导致的，建议更换一致的版本
