### ISSUE TITLE
一些类包含内部静态类时，没有无参构造带来的问题

### ISSUE THREAD

**Issue by muyuto** [Wechat-Group/WxJava#2955]
检查过各个版本，个别类书写未包含无参构造，导致项目中定义feign调用参数候，执行时提示错误
Type definition error: [simple type, class cn.binarywang.wx.miniapp.bean.WxMaKefuMessage$KfLink];
nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: 
  Cannot construct instance of `cn.binarywang.wx.miniapp.bean.WxMaKefuMessage$KfLink` (no Creators, like default constructor, exist): 
    cannot deserialize from Object value (no delegate- or property-based Creator)
at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 92] (through reference chain: cn.binarywang.wx.miniapp.bean.WxMaKefuMessage[\"link\"])

WxMaUniformMessage包含有无参构造，使用中未出现类似问题。

**Comment by binarywang** [comment]
欢迎提供修复代码，并PR上来
