### ISSUE TITLE
多个小程序，多个appid,secret,如何设置

### ISSUE THREAD

**Issue by laochiangx** [Wechat-Group/WxJava#2956]
多个小程序，多个appid,secret,如何设置

**Comment by muyuto** [comment]
这个得自己开发了吧，框架提供的是一个公众号，一个小程序，一个开放平台的对接。

**Comment by Jimmey-Jiang** [comment]
> 

好的，谢谢，本来想多个小程序，公用一套登录逻辑，看来不得行了，那就部署多个端口试试

**Comment by nadirvishun** [comment]
demo里就有啊：[weixin-java-mp-demo](https://github.com/binarywang/weixin-java-mp-demo/blob/master/src/main/java/com/github/binarywang/demo/wx/mp/config/WxMpConfiguration.java)，`setMultiConfigs`相关方法。

**Comment by springcloud-boot** [comment]
这不简单,搞个Map , 你new的WxMpService作为值, appid作为key.  每次用去get出来,

**Comment by shuiyihan12** [comment]
也可以参考 [WxMaConfiguration](https://github.com/binarywang/weixin-java-miniapp-demo/blob/master/src/main/java/com/github/binarywang/demo/wx/miniapp/config/WxMaConfiguration.java) 的配置写Configuration和Properties,不要用wx-java-miniapp-spring-boot-starter依赖,直接用weixin-java-mp依赖就好

**Comment by Ryoui** [comment]
同问，这种场景是很常见的。而且appid和secret还可能是动态变更的，比如开始只有10个，后面通过页面操作新增了几个...

**Comment by JaneYork** [comment]
> 也可以参考 [WxMaConfiguration](https://github.com/binarywang/weixin-java-miniapp-demo/blob/master/src/main/java/com/github/binarywang/demo/wx/miniapp/config/WxMaConfiguration.java) 的配置写Configuration和Properties,不要用wx-java-miniapp-spring-boot-starter依赖,直接用weixin-java-mp依赖就好

wx-java-mp-spring-boot-starter不支持多个小程序配置吗？直接使用weixin-java-mp反而可以？ @nadirvishun @binarywang

**Comment by nadirvishun** [comment]
> > 也可以参考 [WxMaConfiguration](https://github.com/binarywang/weixin-java-miniapp-demo/blob/master/src/main/java/com/github/binarywang/demo/wx/miniapp/config/WxMaConfiguration.java) 的配置写Configuration和Properties,不要用wx-java-miniapp-spring-boot-starter依赖,直接用weixin-java-mp依赖就好
> 
> wx-java-mp-spring-boot-starter不支持多个小程序配置吗？直接使用weixin-java-mp反而可以？ @nadirvishun @binarywang

一直没用过`starter`的，刚看了下源码，确实不支持，直接参考[weixin-java-mp-demo](https://github.com/binarywang/weixin-java-mp-demo/blob/master/src/main/java/com/github/binarywang/demo/wx/mp/config/WxMpConfiguration.java)就好了。反而能更多了解如何配置。
