### ISSUE TITLE
特约商户进件-提交申请单接口入参错误

### ISSUE THREAD

**Issue by hf43hf** [Wechat-Group/WxJava#2966]
### 简要描述
* WxJava 模块名: weixin-java-pay
* WxJava 版本号: 4.4.0
特约商户进件-提交申请单接口入参错误

### 模块版本情况
* WxJava 模块名: 
* WxJava 版本号:（旧版本不予支持，谢谢配合）

### 详细描述
WxPayApplyment4SubCreateRequest对象中的IdentityInfo内部对象参数错误，idHolderType、authorizeLetterCopy字段类型错误

**Comment by binarywang** [comment]
其实你可以直接提交PR修复的

另外偷偷告诉你，最新版本是已经修复了的
