### ISSUE TITLE
xstream 存在安全漏洞

### ISSUE THREAD

**Issue by zcj-cool** [Wechat-Group/WxJava#2970]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~

### 简要描述
weixin-java-mp 最新版 4.4.0存在安全漏洞

### 模块版本情况
* WxJava 模块名: 
 weixin-java-mp
* WxJava 版本号:（旧版本不予支持，谢谢配合）
 4.4.0
### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__
使用了最新版的weixin-java-mp部署在腾讯云上 被扫描到xstream存在安全漏洞 发现定位到是 weixin-java-common引用了xstream
![image](https://user-images.githubusercontent.com/22487059/229914121-ec7c891a-24a9-47fb-9150-251d473b7463.png)
![image](https://user-images.githubusercontent.com/22487059/229913865-7668e179-2bc8-4018-876f-550205bf565d.png)

### 日志
__如果日志不多，直接使用md代码引用格式贴在此处，否则如果太长，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，然后将其url地址贴在这里__
```
日志请写于此处
```

**Comment by binarywang** [comment]
你可以自行升级旧版本到最新版本

**Comment by zcj-cool** [comment]
> 你可以自行升级旧版本到最新版本

4.4.0不是最新版本了吗？

**Comment by binarywang** [comment]
> > 你可以自行升级旧版本到最新版本
> 
> 4.4.0不是最新版本了吗？

首先WxJava的版本介绍在首页有说明，建议仔细阅读，其次xstream的版本在你自己的项目也是可以修改的

**Comment by zcj-cool** [comment]
但我查了下xstream最新版本也有漏洞 这有啥好的建议呢
![image](https://user-images.githubusercontent.com/22487059/230523164-b87a186a-6037-43f9-a00a-266b4a20c260.png)

**Comment by binarywang** [comment]
可以去看看官方的说明，可能官方还没来得及发布最新包，也许可以自己修复后重新打包
