### ISSUE TITLE
调用微信小程序登录信息错误

### ISSUE THREAD

**Issue by pluscare531** [Wechat-Group/WxJava#2972]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~

### 简要描述
微信小程序登录，根据code获取微信。使用方法为WxMaUserService中的getSessionInfo方法

### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号:（旧版本不予支持，谢谢配合）

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__
2)]-执行方法出现异
[异常信息] : Remote host terminated the handshake
[请求参数]: js code=
[请求地址]: https://api.weixin.qq.com/sns/jscode2sessio

### 日志
__如果日志不多，直接使用md代码引用格式贴在此处，否则如果太长，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，然后将其url地址贴在这里__
```nat cn.binarywang.wx.miniapp.api. impl.iceImpl.java:210) .[weixin-java-miniapp-4.1.0.jar!/:?]at cn.binarywang.wx.miniapp.api. impl.Bajava:289) ~[weixin-java-miniapp-4.1.0.jar!/:?]me.chanjar.weixin.commthe handshak
[esm-member][2023-04-0713:03:57.789][][puhuiod][f125538c0e00495c9909d841de7ce320][http-ec-8][ERROR][coning(202)]-执行方法出现异常
[异常信息] : Remote host terminated the[
请求参数]: js code=b37an@w33Fzp834Co1w3
[请求地址]: https://api.weXOGXWeAFALCBesm-member][2023-04-0713:03:57.7897/7
[puhuiap129.5.1.188-prod]rf12553887TERROR][cn.binarywangg.wx.miniapp .api.impl .BasewxMaServic.winia0e0Ss+0at0oost32071httoImpl.executeInternal(288)]-

日志请写于此处
```

**Comment by binarywang** [comment]
麻烦规范下发帖格式

**Comment by binarywang** [comment]
格式不规范，暂时关闭
