### ISSUE TITLE
小程序 获取url link的 参数expireTime应为long类型

### ISSUE THREAD

**Issue by gang2113920** [Wechat-Group/WxJava#2973]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~

### 简要描述
__请简单概括描述下你所遇到的问题。__
小程序获取url link的请求封装类GenerateUrlLinkRequest中expireTime属性应为Long，现在是Integer

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号:4.4.9.B

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__
小程序获取url link的请求封装类GenerateUrlLinkRequest中expireTime类型应为Long，现在是Integer
类：cn.binarywang.wx.miniapp.bean.urllink.GenerateUrlLinkRequest
![image](https://user-images.githubusercontent.com/10305840/230596311-1faf6ffb-2241-45b4-a2ae-ce1fe85be9fb.png)

![image](https://user-images.githubusercontent.com/10305840/230595993-3393f784-fbdf-47d3-9193-fd502a570b05.png)

### 日志
__如果日志不多，直接使用md代码引用格式贴在此处，否则如果太长，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，然后将其url地址贴在这里__
```
日志请写于此处
```

**Comment by binarywang** [comment]
欢迎直接提供PR代码
