### ISSUE TITLE
WxFastMaAccountBasicInfoResult 比官方少了字段数据。

### ISSUE THREAD

**Issue by raymondZhong** [Wechat-Group/WxJava#2977]
### 简要描述
WxFastMaAccountBasicInfoResult   数据和官方字段不同步。 少了字段。

credential	string	非个人主体时返回的是企业或者政府或其他组织的代号
customer_type	number	认证类型；如果未完成微信认证则返回0；不同枚举值对应的类型说明看下方

### 模块版本情况
* WxJava 模块名: 4.4.9.B
* WxJava 版本号:（旧版本不予支持，谢谢配合）

### 详细描述
 WxFastMaAccountBasicInfoResult accountBasicInfo1 = wxOpenService.getWxOpenComponentService().getWxMaServiceByAppid(appId).getBasicService().getAccountBasicInfo();

**Comment by binarywang** [comment]
欢迎直接贡献代码进行修复

**Comment by binarywang** [comment]
4.5.0已添加
