### ISSUE TITLE
签名/验签和工具生成不一样

### ISSUE THREAD

**Issue by ZhangShao-0203** [Wechat-Group/WxJava#2979]
![image](https://user-images.githubusercontent.com/62738656/231919671-519c6191-4609-43ab-87a5-67cbe6e6e229.png)
上面是系统底层的验证 这种方式转换后会多\r   但是官方的只有一个\n 所以导致签名一直不对

**Comment by binarywang** [comment]
欢迎直接提供修复代码，谢谢

**Comment by binarywang** [comment]
没看到你截图里涉及的是sdk里的那部分代码，麻烦明确下
