### ISSUE TITLE
Gson 解析问题

### ISSUE THREAD

**Issue by rui8420** [Wechat-Group/WxJava#2992]
企业微信 获取用户信息  有的用户会解析错误 我自己换成 fastjson 就可以了

<img width="855" alt="image" src="https://user-images.githubusercontent.com/64239140/233914755-a744d581-bf99-4c59-8ad8-03063a1e0b22.png">

**Comment by binarywang** [comment]
麻烦提供下微信原始报文

**Comment by binarywang** [comment]
空指针问题很容易定问问题，如果你有原始报文，很容易发现问题，就可以直接提供修复代码了
