### ISSUE TITLE
敏感词更新接口参数对不上

### ISSUE THREAD

**Issue by jinxiaoyi** [Wechat-Group/WxJava#2993]
### 简要描述
敏感词接口
### 模块版本情况
* WxJava 模块名:  weixin-java-cp
* WxJava 版本号:  4.5.0

### 详细描述
WxCpExternalContactServiceImpl::updateInterceptRule() 方法中 WxCpInterceptRule入参结构不对
public class WxCpInterceptRule implements Serializable, ToJson {
    private static final long serialVersionUID = 7161086545769110431L;
    @SerializedName("rule_name")
    private String ruleName;
    @SerializedName("rule_id")
    private String ruleId;
    @SerializedName("word_list")
    private List<String> wordList;
    @SerializedName("extra_rule")
    private ExtraRule extraRule;
    @SerializedName("intercept_type")
    private int interceptType;
    @SerializedName("applicable_range")
    private ApplicableRange applicableRange;
}

实际企业微信入参请求
{
	"rule_id":"xxxx",
	"rule_name":"rulename",
	"word_list":[
	  "敏感词1","敏感词2"
	],
	"extra_rule":{
			"semantics_list":[1,2,3],
	},
	"intercept_type":1,
	"add_applicable_range":{
		"user_list":["zhangshan"],
		"department_list":[2,3]
	},
	"remove_applicable_range":{
		"user_list":["zhangshan"],
		"department_list":[2,3]
	}
}

**Comment by binarywang** [comment]
应该是官方文档做了调整，欢迎楼主直接提供优化代码

**Comment by binarywang** [comment]
文档地址：https://developer.work.weixin.qq.com/document/path/95097#%E4%BF%AE%E6%94%B9%E6%95%8F%E6%84%9F%E8%AF%8D%E8%A7%84%E5%88%99
