### ISSUE TITLE
weixin-java-mp格式化错误

### ISSUE THREAD

**Issue by junbugwell** [Wechat-Group/WxJava#2996]
微信公众号模板消息设置行业为其他和另一个别的行业，在调用获取行业接口wxMpService.getTemplateMsgService().getIndustry()出现格式化错误，错误位置WxMpTemplateMsgServiceImpl类的getIndustry方法
错误截图如下：
![image](https://user-images.githubusercontent.com/131840212/234466123-34d36ee8-5103-401c-aa80-acc8449a93a9.png)

**Comment by binarywang** [comment]
你调试下代码，就知道问题在哪里了，空指针的问题，建议自己调试，如果是sdk代码问题，欢迎直接提供修复代码
