### ISSUE TITLE
从4.2.0直接升级到4.5.0会不会有什么影响？

### ISSUE THREAD

**Issue by Zlianxin** [Wechat-Group/WxJava#2997]
### 简要描述
因为现在的项目是在4.2.0的基础上进行开发了，在做后续内容的时候，发现有些接口4.2.0没有，4.5.0才有。
直接升级又怕把现有的业务搞坏，所以想问一下，从4.2.0直接升级到4.5.0会不会有影响。

目前主要用了，微信小程序、微信公众号和微信支付这三个模板。

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by binarywang** [comment]
任何软件版本的升级都无法保证绝对没问题，建议自己多测试，关键用例要覆盖全

**Comment by Zlianxin** [comment]
> 任何软件版本的升级都无法保证绝对没问题，建议自己多测试，关键用例要覆盖全

谢谢，知道了~
