### ISSUE TITLE
【小程序】获取稳定版接口调用凭据

### ISSUE THREAD

**Issue by FreeOfYou** [Wechat-Group/WxJava#2998]
**由于不同环境使用的是同一个appid，所以在刷新AccessToken时，会有不同环境频繁刷新的问题，所以建议提供新的稳定版的接口调用凭据**

[官方文档地址](https://developers.weixin.qq.com/miniprogram/dev/OpenApiDoc/mp-access-token/getStableAccessToken.html)

**Comment by FreeOfYou** [comment]
目前我的解决方案是，重写了 `cn.binarywang.wx.miniapp.api.impl.WxMaServiceOkHttpImpl#doGetAccessTokenRequest` 方法

**Comment by binarywang** [comment]
欢迎提交PR代码
