### ISSUE TITLE
4.5.0版本公众号消息异常

### ISSUE THREAD

**Issue by qianyingchao** [Wechat-Group/WxJava#3003]
![image](https://user-images.githubusercontent.com/45645626/236145435-bedf16fe-7143-425a-ba0b-d4c1be661a3f.png)
如图所示，跟踪了下代码，WxMpMessageRouter类上的问题。
WxMpXmlOutMessage route(final WxMpXmlMessage wxMessage, final Map<String, Object> context, WxMpService wxMpService)
这个方法中调用this.wxMpService.switchoverTo(appId);报错，wxMpServiceb变量是null.

**Comment by binarywang** [comment]
请先参考https://github.com/Wechat-Group/WxJava/issues/2995 进行特殊处理，这个问题后面版本会尽快做修复

**Comment by biubiubiu3971** [comment]
> ![image](https://user-images.githubusercontent.com/45645626/236145435-bedf16fe-7143-425a-ba0b-d4c1be661a3f.png) 如图所示，跟踪了下代码，WxMpMessageRouter类上的问题。 WxMpXmlOutMessage route(final WxMpXmlMessage wxMessage, final Map<String, Object> context, WxMpService wxMpService) 这个方法中调用this.wxMpService.switchoverTo(appId);报错，wxMpServiceb变量是null.

@qianyingchao 是不是初始化 WxMpMessageRouter 这个bean的时候设置的WxMpService为null对象呢？
