### ISSUE TITLE
【公众号】模板消息发送，缺少非必填字段client_msg_id

### ISSUE THREAD

**Issue by zhongjichuan** [Wechat-Group/WxJava#3006]
### 简要描述
模板消息发送微信官方还给出个参数client_msg_id，用于防止消息重复发送。4.5版本mp里WxMpTemplateMessage没有这个参数，望添加该功能。

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__
https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Template_Message_Interface.html#%E5%8F%91%E9%80%81%E6%A8%A1%E6%9D%BF%E6%B6%88%E6%81%AF

**Comment by binarywang** [comment]
欢迎直接提供PR代码

**Comment by zhongjichuan** [comment]
https://github.com/Wechat-Group/WxJava/pull/3008
