### ISSUE TITLE
服务商代开发应用是用CpTpService 还是 CpService

### ISSUE THREAD

**Issue by Git-YHAn** [Wechat-Group/WxJava#3007]
获取suite_ticket、secret等时需要用CpTpService
但是我创建用户时用CpTpService就会出现access_token获取不到，而是传递的suite_access_token，这里就很迷
还是说，我需要两个混合使用？

**Comment by li2go** [comment]
感觉要打一套组合拳。

代开发授权之后 把那个永久授权码给存数据库里面。然后从数据库里面来读取就好了。
代开发调接口就调那个cp的。
