### ISSUE TITLE
使用小程序getUserInfo接口获取用户信息时首次调用会报错问题

### ISSUE THREAD

**Issue by binarymei** [Wechat-Group/WxJava#3011]
项目中使用code进行getSessionInfo登陆后，利用sessionKey、encryptedData、iv通过getUserInfo获取用户信息时，报错com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
原因发生在对结果进行Json的转换时报错：cn.binarywang.wx.miniapp.bean.WxMaUserInfo.fromJson(WxMaUserInfo.java:29) ~[weixin-java-miniapp-4.5.0.jar!/:na]
嵌套异常为：cn.binarywang.wx.miniapp.api.impl.WxMaUserServiceImpl.getUserInfo(WxMaUserServiceImpl.java:39) ~[weixin-java-miniapp-4.5.0.jar!/:na]，使用的版本为weixin-java-miniapp(4.3.0)，初步估计有可能与新版本有关，提升依赖至4.5.0最新版本时，首次调用依旧会出错，第二次与后续则不会。

**Comment by binarywang** [comment]
麻烦先看下常见问题，或者置顶区的issue，看有没有帮助
