### ISSUE TITLE
服务商模式下消息路由报空指针异常

### ISSUE THREAD

**Issue by tonychenl** [Wechat-Group/WxJava#3014]
![image](https://github.com/Wechat-Group/WxJava/assets/2723016/2de09a56-239d-4002-80a2-8951f746e274)

问题如下图，通过WxOpenMessageRouter初始化时wxMpService=null，在路由消息时，使用了该变量引起了空指针异常。
![image](https://github.com/Wechat-Group/WxJava/assets/2723016/38ce763d-08c5-4185-bfe7-09199ae47c50)

![image](https://github.com/Wechat-Group/WxJava/assets/2723016/9a3fea9c-0f76-4531-8c1a-ac70d9d6105f)

![image](https://github.com/Wechat-Group/WxJava/assets/2723016/fd2a68db-1d71-4e10-bb08-50022ac0fd67)

**Comment by binarywang** [comment]
这个最新版本会修复，可以先看下其他人的解决办法

**Comment by panxiaochao** [comment]
目前搜罗了一圈，没有好的解决方案，自己也尝试了好多，解决不了楼主空指针的问题，不知道有没有什么现成临时的方案，比较急？

**Comment by springcloud-boot** [comment]
我改过了 已经处理了 你判断缓存是否存在的时候,如果存在set这个appid到这个类 WxMpConfigStorageHolder.set(appId);
他源码用了这个threadlocal 坑到我了
![image](https://github.com/Wechat-Group/WxJava/assets/39367636/6816b4aa-09da-45dc-b335-b8a1117f2541)

**Comment by springcloud-boot** [comment]
实际是因为route 取了threadlocal的对象作为appid, 他不同线程肯定拿不到

**Comment by springcloud-boot** [comment]
实际是因为route 取了threadlocal的get 获取appid,为空就报错了, 你每次在最外层set一下当前操作的appId也行. 这个类
me.chanjar.weixin.mp.util.WxMpConfigStorageHolder
