### ISSUE TITLE
4.5.0 微信支付报错 wxPayService.createOrderV3

### ISSUE THREAD

**Issue by raymondZhong** [Wechat-Group/WxJava#3017]
4.5.0
微信支付

Object order = wxPayService.createOrderV3(TradeTypeEnum.JSAPI,requestV3);

报错：
Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: jodd/util/ClassUtil

4.4.0 正常
4.4.9.B 也正常

@chanjarster 
@binarywang 
@007gzs

**Comment by binarywang** [comment]
楼主请不要at 无关人员，你的问题我们已经收到，会尽快查明原因

**Comment by binarywang** [comment]
麻烦提供完整出错信息，即异常堆栈完整文字谢谢

**Comment by Yuwotongle** [comment]
我也是遇到同样问题

**Comment by Yuwotongle** [comment]
> 4.5.0 微信支付
> 
> Object order = wxPayService.createOrderV3(TradeTypeEnum.JSAPI,requestV3);
> 
> 报错： Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: jodd/util/ClassUtil
> 
> 4.4.0 正常 4.4.9.B 也正常
> 
> @chanjarster @binarywang @007gzs

怎么解决的，哥们

**Comment by Yuwotongle** [comment]
> 4.5.0 微信支付
> 
> Object order = wxPayService.createOrderV3(TradeTypeEnum.JSAPI,requestV3);
> 
> 报错： Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: jodd/util/ClassUtil
> 
> 4.4.0 正常 4.4.9.B 也正常
> 
> @chanjarster @binarywang @007gzs

    <dependency>
      <groupId>org.jodd</groupId>
      <artifactId>jodd-util</artifactId>
      <version>6.0.0</version>
    </dependency>
加上这个依赖就好了

**Comment by binarywang** [comment]
楼上正解
