### ISSUE TITLE
confluence插件中如何使用weixin-java-cp

### ISSUE THREAD

**Issue by mjayeey** [Wechat-Group/WxJava#3018]
直接pom.xml中加入依赖，安装confluence时会报错
![e9d8b0325d8576403c9e05e20c29c16](https://github.com/Wechat-Group/WxJava/assets/19778254/61e92dc3-a2dd-4853-8b65-c993e0865286)

**Comment by binarywang** [comment]
你这是在干啥，完全没看懂

**Comment by mjayeey** [comment]
我想在confluence插件中使用weixin-java-cp库，向企微应用发消息，我是这样做的 
![image](https://github.com/Wechat-Group/WxJava/assets/19778254/2e74abfb-5933-4e8e-a949-23609d0ea1a2)
        出包能成功，但是安装插件包时，报错

**Comment by binarywang** [comment]
那不清楚了，不太了解confluence插件的相关知识，你需要自己再研究下了

**Comment by mjayeey** [comment]
confluence插件好像使用的是ogsi，我是否需要使用weixin-java-osgi
        这个库啊
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Binary ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年5月15日 20:56
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            Mao ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [Wechat-Group/WxJava] confluence插件中如何使用weixin-java-cp (Issue #3018)
        
      
    
  

那不清楚了，不太了解confluence插件的相关知识，你需要自己再研究下了
