### ISSUE TITLE
小程序类目

### ISSUE THREAD

**Issue by Molzx** [Wechat-Group/WxJava#3019]
### 简要描述
怎么没有**代商家管理小程序 /小程序类目管理 /获取不同类型主体可设置的类目**这个接口啊，难道是微信新增加的吗？

### 官方文档地址
[获取不同类型主体可设置的类目](https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/miniprogram-management/category-management/getAllCategoriesByType.html)

**Comment by binarywang** [comment]
有可能新增的，如果你急需，欢迎先自行实现贡献代码提交PR
