### ISSUE TITLE
支付回调报错

### ISSUE THREAD

**Issue by raymondZhong** [Wechat-Group/WxJava#3020]
支付回调报错，签名头部信息验证失败。

WxPayException(customErrorMsg=非法请求，头部信息验证失败, returnCode=null, returnMsg=null, resultCode=null, errCode=null, errCodeDes=null, xmlString=null)

版本 4.4.9.B

    @Autowired
    private WxPayUtil wxPayUtil;

    @ApiOperation(value = "支付回调通知处理")
    @PostMapping("/barberOrder/{appId}/{shopId}")
    public Result parseOrderNotifyResult(HttpServletRequest request,
                                         HttpServletResponse response,
                                         @PathVariable String appId,
                                         @PathVariable Long shopId,
                                         @RequestBody String notifyData) {

        System.out.println("parseOrderNotifyResult>>>"+appId+">>>>>"+shopId);
        // 获取请求头信息
        SignatureHeader signatureHeader = getSignatureHeader(request);
        // 将请求体json字符串转换为实体
        OriginNotifyResponse notifyResponse = new GsonBuilder().create().fromJson(notifyData, OriginNotifyResponse.class);

        // 支付成功通知
        if ("TRANSACTION.SUCCESS".equals(notifyResponse.getEventType())) {

            try {

                WxPayService wxPayService = wxPayUtil.getWxPayServiceV3(appId,shopId);

                // 解析支付结果通知
                WxPayOrderNotifyV3Result resultV3 = wxPayService.parseOrderNotifyV3Result(notifyData, signatureHeader);

                System.out.println(resultV3);
 
                return Result.ok();
            } catch (Exception e) {
                return Result.error().message("系统异常");
            }

        }

        // 返回失败标识
        return Result.error();

    }

    /**
     * 生成签名头
     * @param request
     * @return
     */
    private static SignatureHeader getSignatureHeader(HttpServletRequest request) {
        SignatureHeader signatureHeader = new SignatureHeader();
        signatureHeader.setSignature(request.getHeader("Wechatpay-Signature"));
        signatureHeader.setNonce(request.getHeader("Wechatpay-Nonce"));
        signatureHeader.setSerial(request.getHeader("Wechatpay-Serial"));
        signatureHeader.setTimeStamp(request.getHeader("Wechatpay-TimeStamp"));
        return signatureHeader;
    }

![image](https://github.com/Wechat-Group/WxJava/assets/1297621/c174e1e5-e6ff-4876-8dce-cc1cffe309a2)

@binarywang

**Comment by binarywang** [comment]
你为啥不把完整堆栈打印出来呢，这样完全看不到到底是哪里出的错

**Comment by raymondZhong** [comment]
@binarywang    你在看看，这样清楚了吗

**Comment by binarywang** [comment]
你这是完全另一个问题了？

**Comment by binarywang** [comment]
跟之前不是同一个错误

**Comment by raymondZhong** [comment]
把签名头重新弄了一下了，前面直接 new SignatureHeader() 。

**Comment by binarywang** [comment]
提示的挺清楚了吧，头部信息验证失败

**Comment by binarywang** [comment]
麻烦你把另一个issue的错误信息完善下吧

**Comment by raymondZhong** [comment]
这个头签名， 以前4.4.0 是正常运行的。  现在就报错了。也不知道怎么回事。

**Comment by raymondZhong** [comment]
能给一下解决方案吗 @binarywang

**Comment by raymondZhong** [comment]
已解决， 是我的签名验证，引起的。

**Comment by yuanjinzhong** [comment]
> 

哥,怎么解决;外婆遇到同样的问题

**Comment by Java-Zking-tan-shu** [comment]
怎么解决的？我也是报这个错误

**Comment by Java-Zking-tan-shu** [comment]
> > 
> 
> 哥，怎么解决；外婆遇到同样的问题

你解决了吗？怎么解决的？

**Comment by Java-Zking-tan-shu** [comment]
> 解决了，是我的签名已验证，引起的。

怎么解决的我也在报这个错误

**Comment by yuanjinzhong** [comment]
> 报

![image](https://github.com/Wechat-Group/WxJava/assets/13908993/e7911286-1648-41ad-b279-410932f5fa7d)


> > > 
> > 
> > 
> > 哥，怎么解决；外婆遇到同样的问题
> 
> 你解决了吗？怎么解决的？

![image](https://github.com/Wechat-Group/WxJava/assets/13908993/32d7236c-3bb3-44d0-90cc-5157910e0dd0)


兄弟们,这种方式接收回调参数(我是没按这种方式接收参数导致出错的)

**Comment by Java-Zking-tan-shu** [comment]
> > 报
> 
> ![image](https://user-images.githubusercontent.com/13908993/260625511-e7911286-1648-41ad-b279-410932f5fa7d.png)
> 
> > > > 
> > > 
> > > 
> > > 哥，怎么解决；外婆遇到同样的问题
> > 
> > 
> > 你解决了吗？怎么解决的？
> 
> ![image](https://user-images.githubusercontent.com/13908993/260625555-32d7236c-3bb3-44d0-90cc-5157910e0dd0.png)
> 
> 兄弟们,这种方式接收回调参数(我是没按这种方式接收参数导致出错的)

谢谢大哥
