### ISSUE TITLE
不能同事发送文本消息和图片吗

### ISSUE THREAD

**Issue by 123brl** [Wechat-Group/WxJava#3021]
不能同事发送文本消息和图片吗

**Comment by binarywang** [comment]
你这问题问的不清不楚的

**Comment by 123brl** [comment]
> 你这个问题问的不清不楚的

![image](https://github.com/Wechat-Group/WxJava/assets/29086664/edae6ccd-d464-4c00-b8f5-6721394af28f)
比如这里，我需要触发这两个handler，一个文本信息，一个是照片，这里虽然这样写了，但是永远只执行最后一个handler

**Comment by 123brl** [comment]
> 你这问题问的不清不楚的

大佬，求指教

**Comment by binarywang** [comment]
只能一个handler，其他的使用客服消息接口发送，在handler里的返回语句前面实现

**Comment by 123brl** [comment]
> 只能一个handler，其他的使用客服消息接口发送，在handler里的返回语句前面实现

好的，谢谢。客服接口当天给单个用户发送信息有次数限制吗

**Comment by binarywang** [comment]
自己看官方文档说明吧，可能有过调整
