### ISSUE TITLE
WxTerminationContractResult缺少注释

### ISSUE THREAD

**Issue by hollisho** [Wechat-Group/WxJava#3022]
### 简要描述
WxTerminationContractResult缺少@XStreamAlias("xml")注解

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号: 4.5.0

### 详细描述
WxTerminationContractResult缺少@XStreamAlias("xml")注解，导致解析xml报错XStream CannotResolveClassException

**Comment by binarywang** [comment]
欢迎直接提交PR
