### ISSUE TITLE
企业微信三方应用管理企业标签

### ISSUE THREAD

**Issue by cococa** [Wechat-Group/WxJava#3026]
# 企业微信三方应用管理企业标签

### 简要描述
看了代码，企业内部应用可以调用WxCpExternalContactService 来实现管理企业标签的功能，但是第三方应用开发的包下 me.chanjar.weixin.cp.tp.service 没有实现管理标签的功能，是否有办法来兼容，或者是在 cp.tp.service 包下增加新的service 的来实现。

### 官方文档地址
[__添加企业客户标签__](https://developer.work.weixin.qq.com/document/path/92696)

**Comment by binarywang** [comment]
欢迎直接贡献代码
