### ISSUE TITLE
inputStream 一直获取不到，本地用别的工具测试能获取到，classpath 路径正常

### ISSUE THREAD

**Issue by wmt-git** [Wechat-Group/WxJava#3033]
![image](https://github.com/Wechat-Group/WxJava/assets/52341819/9aced5f1-2590-412d-a0e5-7d21514a4f93)

**Comment by wmt-git** [comment]
由于报了 Exception in thread "main" java.lang.NoClassDefFoundError: jodd/util/ClassUtil，我尝试增加依赖解决
<dependency>
    <groupId>org.jodd</groupId>
    <artifactId>jodd-util</artifactId>
    <version>6.0.0</version>
</dependency>
结果报 inputStream null 问题

**Comment by chxiaowu** [comment]
@WUMEITING 是不是打成可执行jar包了，然后获取不到呢？

**Comment by WUMEITING** [comment]
我看 idea target 目录下也没有呢

**Comment by wmt-git** [comment]
> @WUMEITING 是不是打成可执行jar包了，然后获取不到呢？

还未打包，本地main执行都找不到此文件

**Comment by wmt-git** [comment]
import jodd.util.ClassUtil; 
找不到这个类

**Comment by wmt-git** [comment]
线上报错 Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: jodd/util/ClassUtil

**Comment by lingxiaoplus** [comment]
解决了么，一样的问题。。现在暂时用的绝对路径，用classpath不行

**Comment by einsitang** [comment]
你们的classpath上是否有这个文件(证书)，比如IDEA上resources里头是否有

**Comment by binarywang** [comment]
> ClassUtil

你这是两个问题，没有关联，不知道你在纠结啥子

**Comment by binarywang** [comment]
新版本已自动把jodd-util依赖加入

**Comment by WUMEITING** [comment]
> 解决了么，一样的问题。。现在暂时用的绝对路径，用classpath不行

**Comment by wmt-git** [comment]
> 解决了么，一样的问题。。现在暂时用的绝对路径，用classpath不行

已解决，通过加入 jodd-util 依赖和修改maven配置解决，用classpath可行呢

**Comment by wmt-git** [comment]
> 你们的classpath上是否有这个文件（证书），比如IDEA上resources里头是否有

排查后发现是没把秘钥文件打包和无 jodd-util导致的问题
