### ISSUE TITLE
第三方应用-审批应用回调

### ISSUE THREAD

**Issue by MoonightsZ** [Wechat-Group/WxJava#3037]
简要描述
第三方应用开发中，审批申请状态变化回调通知没有相应的Model，目前只有审核流程引擎回调的Model

模块版本情况
WxJava 模块名: weixin-java-cp
WxJava 版本号: 4.5.0

详细描述
第三方应用开发中，有审核应用回调和审核流程引擎回调，目前WxCpTpXmlMessage只有审核流程引擎回调的Model，而审核应用回调的model只存在WxCpXmlMessage中，而WxCpTpMessageHandler无法使用WxCpXmlMessage。

第三方应用开发>服务端API>审批>审批申请状态变化回调通知
[文档地址](https://gitee.com/link?target=https%3A%2F%2Fdeveloper.work.weixin.qq.com%2Fdocument%2Fpath%2F92633)
第三方应用开发>服务端API>审批>审批流程引擎#第三方应用审批状态变化通知回调
[文档地址](https://gitee.com/link?target=https%3A%2F%2Fdeveloper.work.weixin.qq.com%2Fdocument%2Fpath%2F93798%233%25E7%25AC%25AC%25E4%25B8%2589%25E6%2596%25B9%25E5%25BA%2594%25E7%2594%25A8%25E5%25AE%25A1%25E6%2589%25B9%25E7%258A%25B6%25E6%2580%2581%25E5%258F%2598%25E5%258C%2596%25E9%2580%259A%25E7%259F%25A5%25E5%259B%259E%25E8%25B0%2583)

**Comment by binarywang** [comment]
欢迎直接提供修复代码并提交PR
