### ISSUE TITLE
提现商户号非法

### ISSUE THREAD

**Issue by UpdateCw** [Wechat-Group/WxJava#3038]
【请求地址】：https://api.mch.weixin.qq.com/xdc/apiv2sandbox/v3/transfer/batches
【请求数据】：XXXXXXXXXXXXXXXXXXXX
【响应数据】：
```<xml>
  <return_code><![CDATA[FAIL]]></return_code>
  <return_msg><![CDATA[商户号非法]]></return_msg>
</xml>
```

新注册的商户号 有大佬帮忙看看呢

**Comment by UpdateCw** [comment]
商户号非法

**Comment by binarywang** [comment]
不应该是检查下商户号的问题吗？

**Comment by shuiyihan12** [comment]
**V3 接口, 目前没有提供沙箱环境**,你用的v3接口,走的v2的沙箱
