### ISSUE TITLE
微信h5支付异常信息， trade_type参数格式错误

### ISSUE THREAD

**Issue by ghost** [Wechat-Group/WxJava#3042]
接口： https://api.mch.weixin.qq.com/v3/pay/transactions/h5
入参： {"appid":"321321","mchid":"32131","description":"test","out_trade_no":"1666635486746828800","notify_url":"http://localhost:8081/order/notify/1666635486746828800","amount":{"total":1099900,"currency":"CNY"},"scene_info":{"payer_client_ip":"127.0.0.1","h5_info":{"type":"Wap"}}}

【异常信息】：trade_type参数格式错误

看官方文档 微信支付的h5支付接口是没有trade_type参数的， 这个参数是统一支付中才有， 改问题是什么原因？

**Comment by binarywang** [comment]
错误信息原始报文有吗？
