### ISSUE TITLE
请问下weixin-java-open模块有没有提供移动应用授权登录的接口呢？没有找到

### ISSUE THREAD

**Issue by sk8breeze** [Wechat-Group/WxJava#3044]
简要描述 请问下weixin-java-open模块有没有提供移动应用授权登录的接口呢？没有找到
![image](https://github.com/Wechat-Group/WxJava/assets/43592374/74df4714-1470-4622-8972-f687c2d1191f)

官方文档地址: https://developers.weixin.qq.com/doc/oplatform/Mobile_App/WeChat_Login/Development_Guide.html

**Comment by binarywang** [comment]
这块代码比较老，早期存在于mp模块里，请参考  https://github.com/Wechat-Group/WxJava/wiki/MP_OAuth2%E7%BD%91%E9%A1%B5%E6%8E%88%E6%9D%83

**Comment by sk8breeze** [comment]
好的谢谢
