### ISSUE TITLE
调用企业获取打卡记录数据接口，月底那日下班时间超过晚上12点，无法取得下班打卡记录？

### ISSUE THREAD

**Issue by honestno1** [Wechat-Group/WxJava#3046]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~

### 简要描述
调用me.chanjar.weixin.cp.api.WxCpOaService#getCheckinData接口，取得企业微信打卡记录时，在月底那天，下班时间超过晚上12点，无法取得下班打卡记录。

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号:4.5.0

### 详细描述
调用me.chanjar.weixin.cp.api.WxCpOaService#getCheckinData接口，取得企业微信打卡记录时，在月底那天，下班时间超过晚上12点，无法取得下班打卡记录。

例如：打卡时间段设置为每日4：00到次日03：59可打卡，那么在5月31日晚上下班超过12点以后，比如00：35，也就是6月1日凌晨00：35打卡下班，在这种情况下，用时间段2023-05-31 00:00:00 到 2023-05-31 23:59:59取不到00：35的下班打卡记录，用时间段2023-06-01 00:00:00 到 2023-06-01 23:59:59也取不到00：35的下班打卡记录。经测试，这种情况在非月底日期时是没问题的。

**Comment by binarywang** [comment]
你说的问题是微信接口的问题，还是sdk代码的问题？如果是后者欢迎直接提供修复代码PR

**Comment by honestno1** [comment]
看了sdk的代码，应该不是sdk的问题，是企业微信接口的问题。

**Comment by honestno1** [comment]
另外，找到了一个妥协的办法，取得每日的打卡记录时，不要把开始结束时间设置为 00:00:00 ~ 23:59:59，设置成 04:00:00 ~ 03:59:59 这样的时间范围（对应企业微信打卡时间段设置为每日4：00到次日03：59可打卡这种情况），这样就可以正常取得打卡记录数据了。如果公司有多个工作地点，可打卡时间范围不一样，就比较麻烦了。
