### ISSUE TITLE
获取员工打开规则缺少“排班信息”schedulelist，接口有返回数据，实体类没有这属性接受数据

### ISSUE THREAD

**Issue by 532780857** [Wechat-Group/WxJava#3048]
### 简要描述
获取员工打开规则缺少“排班信息”schedulelist，接口有返回数据，实体类没有这属性接受数据
![image](https://github.com/Wechat-Group/WxJava/assets/39074601/ebb373cf-48c4-4bf6-b15c-4c7be02b8576)
![image](https://github.com/Wechat-Group/WxJava/assets/39074601/b5fecb26-aa36-42a3-8b5a-a34cf5325f6c)

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号: 4.5.0
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-cp</artifactId>
            <version>4.5.0</version>
        </dependency>
### 详细描述

`
  /**
   * The type Group.
   */
  @Data
  public static class Group implements Serializable {

    private static final long serialVersionUID = -5888406969613403044L;

    @SerializedName("groupid")
    private Long id;

    @SerializedName("groupname")
    private String name;

    @SerializedName("grouptype")
    private Integer type;

    @SerializedName("checkindate")
    private List<CheckinDate> checkinDate;

    @SerializedName("spe_workdays")
    private List<SpeDay> speWorkdays;

    @SerializedName("spe_offdays")
    private List<SpeDay> speOffdays;

    @SerializedName("sync_holidays")
    private Boolean syncHolidays;

    @SerializedName("need_photo")
    private Boolean needPhoto;

    @SerializedName("note_can_use_local_pic")
    private Boolean noteCanUseLocalPic;

    @SerializedName("allow_checkin_offworkday")
    private Boolean allowCheckinOffWorkday;

    @SerializedName("allow_apply_offworkday")
    private Boolean allowApplyOffWorkday;

    @SerializedName("wifimac_infos")
    private List<WifiMacInfo> wifiMacInfos;

    @SerializedName("loc_infos")
    private List<LocInfo> locInfos;

  }`

### 日志
__如果日志不多，直接使用md代码引用格式贴在此处，否则如果太长，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，然后将其url地址贴在这里__
```
日志请写于此处
```

**Comment by binarywang** [comment]
欢迎直接PR修复此问题
