### ISSUE TITLE
小程序发货信息管理服务

### ISSUE THREAD

**Issue by zouxiaodong** [Wechat-Group/WxJava#3052]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
根据[《商家自营类小程序运营规范》](https://developers.weixin.qq.com/miniprogram/product/jiaoyilei/yunyingguifan.html#%E5%95%86%E5%AE%B6%E8%87%AA%E8%90%A5%E7%B1%BB%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%BF%90%E8%90%A5%E8%A7%84%E8%8C%83),特定类型的小程序需要在平台完成发货信息录入及确认收货流程后方可进行资金结算。

开发者可以通过该接入服务，完成商品发货信息录入、提醒用户确认收货、在小程序内调起确认收货组件等功能，提升发货信息录入效率，优化用户体验。
  现在必须录入物流信息，用户收货后，资金才会解冻，用户才有提现

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/business-capabilities/order-shipping/order-shipping.html#%E4%B8%80%E3%80%81%E5%8F%91%E8%B4%A7%E4%BF%A1%E6%81%AF%E5%BD%95%E5%85%A5%E6%8E%A5%E5%8F%A3

**Comment by binarywang** [comment]
欢迎直接贡献代码

**Comment by yixiaco** [comment]
我也遇到这个问题，请问有什么进展吗
