### ISSUE TITLE
FreightProductInfo中的productCnt类型应该为Integer，当前版本中是String，导致调用发货接口失败。

### ISSUE THREAD

**Issue by Kevin185** [Wechat-Group/WxJava#3058]
模块：weixin-java-channel
版本：4.5.1.B

bug描述：
me.chanjar.weixin.channel.bean.delivery.FreightProductInfo中的productCnt类型应该为Integer，当前版本中是String，导致调用发货接口失败。

腾讯接口参数示例：
![image](https://github.com/Wechat-Group/WxJava/assets/7291802/1823f265-fbac-4156-b663-2276e2e72c1a)

**Comment by binarywang** [comment]
欢迎直接提交PR修复
