### ISSUE TITLE
企业微信模块客户详情接口新增了视频号相关字段

### ISSUE THREAD

**Issue by tcsp** [Wechat-Group/WxJava#3059]
可以参考企微文档：https://developer.work.weixin.qq.com/document/path/92114
![image](https://github.com/Wechat-Group/WxJava/assets/10058952/56703c57-e630-4965-98a4-84967cc19509)

**Comment by tcsp** [comment]
me.chanjar.weixin.cp.bean.external.contact.FollowedUser该类中目前缺少视频号相关的字段定义

**Comment by binarywang** [comment]
欢迎直接提交PR代码添加相关字段
