### ISSUE TITLE
适配springboot3

### ISSUE THREAD

**Issue by xbitlabs** [Wechat-Group/WxJava#3060]
今天在做springboot3的项目，发现wxjava并没有适配，自己折腾了一下，升级一些库到最新，改一点代码就适配成功了，工作量不大

**Comment by binarywang** [comment]
所谓的不能适配是指什么？我们有demo完全支持没问题呀

**Comment by xbitlabs** [comment]
> 所谓的不能适配是指什么？我们有demo完全支持没问题呀

我的项目引入了spring-data-redis的最新版本，而wxjava里面涉及的redis相关库版本太低了，wxjava自动化装配的时候报找不到相关类，我自己把wxjava源码里的相关依赖改成最新版本并修改了部分代码问题就解决了

**Comment by binarywang** [comment]
那跟spring boot3也没关系
