### ISSUE TITLE
WxOAuth2UserInfo 里面好像没有是否关注公众号的字段，还是能通过其他方式获取，麻烦大佬解答，谢啦

### ISSUE THREAD

**Issue by lymmysy** [Wechat-Group/WxJava#3068]
WxOAuth2UserInfo 里面好像没有是否关注公众号的字段，还是能通过其他方式获取，麻烦大佬解答，谢啦

**Comment by sheep-recursion** [comment]
自己判断，关注公众号会有事件回调，将信息保存到数据库，如果你数据库有用户的openId，则表示用户关注过公众号，取消关注也有对应的回调，再处理具体逻辑就行

**Comment by zhongjun96** [comment]
拿用户OpenId 去获取用户基础信息。有返回是否关注标识。
[获取用户基本信息(UnionID机制)](https://developers.weixin.qq.com/doc/offiaccount/User_Management/Get_users_basic_information_UnionID.html#UinonId)
`me.chanjar.weixin.mp.api.WxMpUserService#userInfo(java.lang.String, java.lang.String)`
