### ISSUE TITLE
微信支付 FavorStocksGetResult对象 总预算等字段使用Integer

### ISSUE THREAD

**Issue by besehen** [Wechat-Group/WxJava#3071]
微信代金券 FavorStocksGetResult 类中总预算等字段使用Integer，单位为分，也就是最大预算为两千一百多万
![image](https://github.com/Wechat-Group/WxJava/assets/22188377/3a272715-fc3d-4152-a416-e8ad6008eb33)

微信官方提供的类型是uint64
![image](https://github.com/Wechat-Group/WxJava/assets/22188377/412f4776-1ee7-43f0-9b83-b855d1631e0f)

这里使用Long比较合适，不然超出两千多万会引发错误吧

**Comment by binarywang** [comment]
欢迎直接提供PR

**Comment by zhongjun96** [comment]
https://github.com/Wechat-Group/WxJava/commit/25cb090865f30460e7dd2a9f69ebfd0776c6f9f8
