### ISSUE TITLE
微信支付，代金券信息查询

### ISSUE THREAD

**Issue by hitushen** [Wechat-Group/WxJava#3082]
微信官方文档已修改代金券信息查询接口URL

### 模块版本情况
* WxJava 模块名:  wxjava-pay
* WxJava 版本号: 4.5.0

### 详细描述
模块代码里/mmpaymkttransfers/query_coupon_stock，现已修改为https://api.mch.weixin.qq.com/v3/marketing/favor/users/{openid}/coupons/{coupon_id}。附上官方接口文档地址：https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter9_1_6.shtml

**Comment by binarywang** [comment]
v3的接口跟v2的不一样，你确定你看到的是正确的？

**Comment by hitushen** [comment]
> 

那请问v3的在该包里是哪个方法呢，我找了半天没搜到相关v3的url

**Comment by binarywang** [comment]
com.github.binarywang.wxpay.service.MarketingFavorService

你咋搜索的

**Comment by hitushen** [comment]
> 

原来是这个，对不起，那我这样调用对吗？
FavorCouponsGetResult result = wxPayService.getMarketingFavorService().getFavorCouponsV3(String.valueOf(voucherList.getVoucherId()), wxPayService.getConfig().getAppId(), user.getOpenId());
appid，没有自动注入的使用方式吗请问
