### ISSUE TITLE
分账异常结果message解析不正确

### ISSUE THREAD

**Issue by witt-bit** [Wechat-Group/WxJava#3091]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~

### 简要描述
调用`profitSharingService.profitSharingReturn(profitSharingReturnRequest)`接口时，抛出的`WxPayException`在某些情况下，未解析到错误信息

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号:4.5.0

### 返回xml内容
```xml
<xml>
<return_code><![CDATA[FAIL]]></return_code>
<error_code><![CDATA[NOAUTH]]></error_code>
<error_msg><![CDATA[回退方没有开通分账回退功能]]></error_msg>
</xml>
```

异常截图
![image](https://github.com/Wechat-Group/WxJava/assets/52407727/bc5453d5-3999-46ef-a672-094e7764a4b2)

**Comment by binarywang** [comment]
看来是error_code 和err_code混用的问题，微信字段命名太随意了
