### ISSUE TITLE
企信向员工付款查询付款订单接口

### ISSUE THREAD

**Issue by Masquerade6** [Wechat-Group/WxJava#3093]
### 简要描述
我看到com.github.binarywang.wxpay.service.EntPayService#toEmpPay有向员工付款的接口，官方提供了查询付款记录的接口，但是这个接口为啥没有被封装进来？

### 官方文档地址
https://developer.work.weixin.qq.com/document/path/90279

**Comment by binarywang** [comment]
很显然是新增的接口吧，你如果急需，建议自行实现并提交PR，谢谢

**Comment by Masquerade6** [comment]
好的，我以为有啥特殊场景没封装呢
