### ISSUE TITLE
小程序偶尔获取手机号总是获取不到

### ISSUE THREAD

**Issue by lixunhui** [Wechat-Group/WxJava#3094]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~

### 简要描述
__请简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号:4.5.0

### 详细描述
开发测试过程中没有发现问题，实际使用（会议签到）客户在会议签到的时候，获取手机号，偶尔会有几个人无法获取手机号码

**Comment by binarywang** [comment]
看下置顶区issue，是否跟你描述问题吻合
