### ISSUE TITLE
weixin-java-cp  WxCpTpDefaultConfigImpl 中企业微信服务商一些参数 providerSecret 等的set方法都是 @deprecated 有些还没有set方法

### ISSUE THREAD

**Issue by wisty** [Wechat-Group/WxJava#3096]
WxCpTpDefaultConfigImpl 中企业微信服务商一些参数 providerSecret 等的set方法都是 @Deprecated 有些还没有set方法 看着有点懵逼

**Comment by binarywang** [comment]
@xworks

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/pull/1867
