### ISSUE TITLE
支持点金计划API

### ISSUE THREAD

**Issue by lemos1235** [Wechat-Group/WxJava#3105]
### 简要描述
goldplan 点金计划接口关闭了吗？我记得之前还有的。

### 官方文档地址
[__请提供所需功能对应的微信官方文档地址以便进行确认。__](https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter8_5_1.shtml)

**Comment by binarywang** [comment]
暂无支持计划，建议先自行实现并提交PR
