### ISSUE TITLE
微信退款回调返回值类型不匹配

### ISSUE THREAD

**Issue by lemos1235** [Wechat-Group/WxJava#3106]
[相关代码](https://github.com/Wechat-Group/WxJava/blob/0bfc9353d14c602dc69173a405c2f238d9907133/weixin-java-pay/src/main/java/com/github/binarywang/wxpay/bean/ecommerce/RefundNotifyResult.java#L202)
```
    /**
     * <pre>
     * 字段名：退款金额
     * 变量名：refund
     * 是否必填：是
     * 类型：int
     * 描述：
     *  退款金额，币种的最小单位，只能为整数，不能超过原订单支付金额，如果有使用券，后台会按比例退。
     * 示例值：999
     * </pre>
     */
    @SerializedName(value = "refund")
    private String refund;
```

类型貌似不对，应为 Integer

下面还有个 payerRefund 字段，也是同样的情况。

**Comment by binarywang** [comment]
其实你可以直接提交PR进行修复的，不过现在已经有人代劳了。
