### ISSUE TITLE
微信公众号认证

### ISSUE THREAD

**Issue by tianyin612** [Wechat-Group/WxJava#3109]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
完善微信公众号认证状态，在业务中可以进行逻辑判断时候有权限调用接口

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__
https://developers.weixin.qq.com/doc/offiaccount/Account_Management/Wechat_Accreditation_Event_Push.html

**Comment by binarywang** [comment]
自己接收消息进行处理就可以了
