### ISSUE TITLE
请问weixin-java-miniapp生成小程序二维码接口能否支持png？

### ISSUE THREAD

**Issue by lintiancheng01** [Wechat-Group/WxJava#3117]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
请问weixin-java-miniapp生成小程序二维码接口能否支持png？
cn.binarywang.wx.miniapp.api.WxMaQrcodeService#createWxaCodeUnlimit(java.lang.String, java.lang.String, boolean, java.lang.String, int, boolean, cn.binarywang.wx.miniapp.bean.WxMaCodeLineColor, boolean)
目前这个接口是返回jpg的，请问能不能支持png呢？

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__
https://developers.weixin.qq.com/miniprogram/dev/OpenApiDoc/qrcode-link/qr-code/getUnlimitedQRCode.html

**Comment by binarywang** [comment]
你自己转换就可以了

**Comment by lintiancheng01** [comment]
自己拿到FIle对象以后 然后 根据file里面的流 转换？ 我试了一下 好像没效果。

**Comment by 0katekate0** [comment]
> 自己拿到FIle对象以后 然后 根据file里面的流 转换？ 我试了一下 好像没效果。

仔细看接口或源码，有字节，可以自行保存

**Comment by StackTc** [comment]
看到了 多谢。
