### ISSUE TITLE
java多环境配置问题

### ISSUE THREAD

**Issue by wangqiuyuan1994** [Wechat-Group/WxJava#3120]
### 简要描述
有两个环境，正式环境和测试环境。正式环境强制刷新access_token后会导致测试环境的token有问题。该怎么配置或处理比较好？

### 详细描述
官方中相关描述如下，是希望有一个中控服务器来控制。
![image](https://github.com/Wechat-Group/WxJava/assets/115388698/514a60f3-c05e-4ab6-aeed-e1494aa0adf2)

### 测试环境中相关报错日志
```
- PhoneDTO(errcode=40001, errmsg=invalid credential, access_token is invalid or not latest, could get access_token by getStableAccessToken, more details at https://mmbizurl.cn/s/JtxxFh33r rid: 64e86423-2a8155ef-64e3c234, phone_info=null)

```

**Comment by shuiyihan12** [comment]
wxjava只是sdk,集成在项目中,在分布式或者多环境的情况下,sdk是无法统一监控和刷新token的,你可以写个单独的jar服务来监控和刷新token,业务服务都去redis中获取,应该不太难

**Comment by wangqiuyuan1994** [comment]
@shuiyihan12 
是可以单写一jar用于刷新，但wxjava设计原则中，应该是让开发者感知不到token变化，也不用处理token相关问题的吧？

在实际业务的处理过程中，如果把wxjava的sdk都单拿出来单独处理，会很繁琐，毕竟好多接口都没有直接处理token，如wxMaService.getUserService().getSessionInfo，wxMaService.getSubscribeService().sendSubscribeMsg等等。解决方案要么是这些代码都独立在一个jar里边完成，然后所有的服务都需要单开一个接口去做相关调用；要么是需要在每一个调用到相关函数前，需要主动显式的刷新token。 这时就需要**每一个**开发者都要处理**相同**的刷新的逻辑机制。我感觉这属于重复造轮子的行为，应该是要在sdk层面要完成的事情

另外，在不看完整体源码逻辑的情况下， wxMaService.getWxMaConfig().updateAccessToken 的函数是否能完成主动刷新token的需求？

**Comment by 0katekate0** [comment]
> @shuiyihan12 是可以单写一jar用于刷新，但wxjava设计原则中，应该是让开发者感知不到token变化，也不用处理token相关问题的吧？
> 
> 在实际业务的处理过程中，如果把wxjava的sdk都单拿出来单独处理，会很繁琐，毕竟好多接口都没有直接处理token，如wxMaService.getUserService().getSessionInfo，wxMaService.getSubscribeService().sendSubscribeMsg等等。解决方案要么是这些代码都独立在一个jar里边完成，然后所有的服务都需要单开一个接口去做相关调用；要么是需要在每一个调用到相关函数前，需要主动显式的刷新token。 这时就需要**每一个**开发者都要处理**相同**的刷新的逻辑机制。我感觉这属于重复造轮子的行为，应该是要在sdk层面要完成的事情
> 
> 另外，在不看完整体源码逻辑的情况下， wxMaService.getWxMaConfig().updateAccessToken 的函数是否能完成主动刷新token的需求？
为何要强制刷新accessToken？可以考虑共享accessToken到redis，请参考wiki第九条

**Comment by 0katekate0** [comment]
> 

为何要强制刷新accessToken？可以考虑共享accessToken到redis，请参考wiki第九条

**Comment by wangqiuyuan1994** [comment]
是的，所以感觉不太顺。在我的case里，测试redis和正式redis并不互通。

其次，wiki第9条跳转到
https://github.com/binarywang/weixin-java-cp-demo/blob/master/src/main/java/com/github/binarywang/demo/wx/cp/config/mutil/WxCpConfiguration.java
没看懂是怎么配置的。感觉关键的一句是：

`routers.put(a.getCorpId() + a.getAgentId(), this.newRouter(service));`

但token是怎么进入到redis，怎么能从redis取出来的，没怎么说清楚

**Comment by 0katekate0** [comment]
> 是的，所以感觉不太顺。在我的case里，测试redis和正式redis并不互通。
> 
> 其次，wiki第9条跳转到 https://github.com/binarywang/weixin-java-cp-demo/blob/master/src/main/java/com/github/binarywang/demo/wx/cp/config/mutil/WxCpConfiguration.java 没看懂是怎么配置的。感觉关键的一句是：
> 
> `routers.put(a.getCorpId() + a.getAgentId(), this.newRouter(service));`
> 
> 但token是怎么进入到redis，怎么能从redis取出来的，没怎么说清楚

redis需要先互通，WxMaRedissonConfigImpl，你去跟下源码

**Comment by wangqiuyuan1994** [comment]
> > 是的，所以感觉不太顺。在我的case里，测试redis和正式redis并不互通。
> > 其次，wiki第9条跳转到 https://github.com/binarywang/weixin-java-cp-demo/blob/master/src/main/java/com/github/binarywang/demo/wx/cp/config/mutil/WxCpConfiguration.java 没看懂是怎么配置的。感觉关键的一句是：
> > `routers.put(a.getCorpId() + a.getAgentId(), this.newRouter(service));`
> > 但token是怎么进入到redis，怎么能从redis取出来的，没怎么说清楚
> 
> redis需要先互通，WxMaRedissonConfigImpl，你去跟下源码

如果两个redis就不应该互通，该怎么处理？互通的话，测试数据和正式数据就混在一起了

**Comment by ifcute** [comment]
我以前是 覆盖了WxMaConfig 刷新token的实现，让他去调用中继服务器刷新实现的，其他地方的代码就不用改了

**Comment by wangqiuyuan1994** [comment]
具体是咋做的?能提供下方案吗，是重写了getAccessToken接口，其余的函数都走WxMaRedisConfigImpl的逻辑？另一个问题是，如果进行修改，是fork源码还是直接实现interface WxMaConfig 的接口就行？

**Comment by ifcute** [comment]
就是继承了WxMaServiceHttpClientImpl，重写了 cn.binarywang.wx.miniapp.api.impl.WxMaServiceHttpClientImpl#doGetAccessTokenRequest  这个方法，吧url改成了中继服务器的

**Comment by foreveryang321** [comment]
> 有两个环境，正式环境和测试环境。正式环境强制刷新access_token后会导致测试环境的token有问题。该怎么配置或处理比较好？

你这个 case 是不是生产、测试都是用的同一个小程序的 appid、appsecret？

**Comment by wangqiuyuan1994** [comment]
> > 有两个环境，正式环境和测试环境。正式环境强制刷新access_token后会导致测试环境的token有问题。该怎么配置或处理比较好？
> 
> 你这个 case 是不是生产、测试都是用的同一个小程序的 appid、appsecret？
是的

**Comment by foreveryang321** [comment]
> > > 有两个环境，正式环境和测试环境。正式环境强制刷新access_token后会导致测试环境的token有问题。该怎么配置或处理比较好？
> > 
> > 
> > 你这个 case 是不是生产、测试都是用的同一个小程序的 appid、appsecret？
> > 是的

2 个方案：
1. 生产、测试都配置强制刷新，这种方式可能会导致调用 token 接口的次数不断增加，如果 token 接口有次数限制不适合用这个方案，治标不治本
2. 生产、测试使用不同的小程序 appid、appsecret，可以完美解决你的问题

**Comment by 0katekate0** [comment]
> > > 有两个环境，正式环境和测试环境。正式环境强制刷新access_token后会导致测试环境的token有问题。该怎么配置或处理比较好？
> > 
> > 
> > 你这个 case 是不是生产、测试都是用的同一个小程序的 appid、appsecret？
> > 是的

最佳方案：
1、不同redis需要异步去维护accessToken，也就是楼上有说使用中继服务器
2、同一个redis，可以放在同一个库，如果使用不同库，需要手动去维护accessToken到不同库即可

**Comment by leeuoo11** [comment]
我的实现很简单，如果是本地或者测试环境，代码请求生产服务的接口，接口调用getAccessToken()。当然，需要一个代理能通生产。另一种办法是，测试环境提供一个手动setAccessToken的接口，先获从生产环境的接口/存储获取access_token及其过期时间，然后调用测试环境setAccessToken接口。
