### ISSUE TITLE
云托管资源复用，开放接口要求 url param：from_appid

### ISSUE THREAD

**Issue by ikook-wang** [Wechat-Group/WxJava#3125]
### 简要描述
希望可以自己指定 url param。比如给 url 添加 param：from_appid，就像这样："http://api.weixin.qq.com/wxa/msg_sec_check?from_appid=${req.headers['x-wx-from-appid']}"。这样就可以使用云托管的资源复用功能了。

### 官方文档地址
https://developers.weixin.qq.com/miniprogram/dev/wxcloudrun/src/guide/reuse/#%E8%B5%84%E6%BA%90%E5%A4%8D%E7%94%A8%E4%B8%8B%E7%9A%84%E5%BC%80%E6%94%BE%E6%8E%A5%E5%8F%A3%E8%B0%83%E7%94%A8

**Comment by binarywang** [comment]
欢迎直接提交PR帮忙完善
