### ISSUE TITLE
微信小程序 服务端API调用数据加密

### ISSUE THREAD

**Issue by zhanglongchina** [Wechat-Group/WxJava#3126]
大佬，请问我们对这块目前是没有支持码

https://developers.weixin.qq.com/miniprogram/dev/OpenApiDoc/getting_started/api_signature.html

**Comment by zhanglongchina** [comment]
在配置中没有找到可以设置API调用时  加密密钥和签名私钥的地方
还请大佬指点

**Comment by binarywang** [comment]
应该暂时还没有，如果需要，欢迎提供PR代码，谢谢
