### ISSUE TITLE
sendTemplateMsg 高峰期耗时很长

### ISSUE THREAD

**Issue by YXxy1002** [Wechat-Group/WxJava#3133]
### 简要描述
sendTemplateMsg 高峰期耗时很长

### 模块版本情况
* WxJava 模块名:  weixin-java-mp
* WxJava 版本号:  4.5.0

### 详细描述
sendTemplateMsg 平常耗时几百毫秒, 高峰期的时候达到30s, 接口无其他逻辑, 只有 wxMpService.getTemplateMsgService().sendTemplateMsg(templateMessage). 目前无法确定是微信耗时长还是wxJava项目耗时长, 关键信息在截图里, 麻烦帮忙看看

### 日志
![image](https://github.com/Wechat-Group/WxJava/assets/36941654/1d290cee-e495-49d3-b80d-46e08fc33270)
![image](https://github.com/Wechat-Group/WxJava/assets/36941654/f8e78642-feb3-4cba-a840-4e1d1c5a6e34)
![image](https://github.com/Wechat-Group/WxJava/assets/36941654/2e18d9ae-4beb-4a66-a3b7-152901d75281)
![image](https://github.com/Wechat-Group/WxJava/assets/36941654/0862d131-dc91-4a8d-81d4-d64fc19f740c)

**Comment by foreveryang321** [comment]
1、看你在这个日志追踪，感觉应该是网络带宽问题，可以查一下高峰期你们的cpu、内存、网络带宽等资源的占用情况。
2、可能和 https://github.com/Wechat-Group/WxJava/blob/e9dbd601a65580f440ea0e61171a21b28e979278/weixin-java-common/src/main/java/me/chanjar/weixin/common/util/http/apache/DefaultApacheHttpClientBuilder.java#L83-L90 配置的连接池大小有关。如果可以，将maxTotalConn调大到 500 以上，maxConnPerHost调到 50 以上，不宜调到过大的值。

**Comment by einsitang** [comment]
从你的描述和追踪链上看，应该就是高峰期内的请求连接积压导致的。
上述的解决方案应该奏效，但maxConnPerHost应该紧贴maxTotalConn，因为就这个wxJava sdk来说，估计就只有那么一个host，就是微信的openapi：api.weixin.qq.com

另外就是，如果sendTemplateMsg这个业务不需要和具体业务逻辑同步做的情况下，可以单独抽离成异步，这样在你的业务调用链过程中不会受到其影响
