### ISSUE TITLE
微信服务商支付分WxPartnerPayScoreResult确少部分字段 

### ISSUE THREAD

**Issue by UltramanNoa** [Wechat-Group/WxJava#3134]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
WxPartnerPayScoreResult返回字段和普通服务商接口里有差异 

### 官方文档地址
https://pay.weixin.qq.com/docs/partner/apis/partner-weixin-pay-score/partner-service-order/get-partner-service-order.html  

WxPartnerPayScoreResult 返回的字段和文档里的字段差了好多  而且好几个接口都差字段 能不能现在添加一下

**Comment by binarywang** [comment]
欢迎直接提供PR，谢谢

**Comment by UltramanNoa** [comment]
好的  我在根据文档添加完字段后会在https://gitee.com/上提交

**Comment by UltramanNoa** [comment]
已提交

**Comment by UltramanNoa** [comment]
你好 我看4.5.5.B的代码里有我提交的那部分 但是从maven 下下来的4.5.5.B的包里缺少部分代码导致我们现在发测试构建报错 能不能重推一版新的包呀

**Comment by UltramanNoa** [comment]
@binarywang

**Comment by UltramanNoa** [comment]
![1](https://github.com/Wechat-Group/WxJava/assets/16308510/2c34bf1c-b09a-4c11-9393-c226130108af)
![2](https://github.com/Wechat-Group/WxJava/assets/16308510/cfd5da0f-8b73-409f-8aa1-3fb3ce5a9d5b)

**Comment by einsitang** [comment]
你的日志应该是出现在compile阶段，如果发生在运行日志应该是 noSuchMehotdException 这样的信息还有调用栈。
如果出现在compile阶段，就是打包编译都成问题，就是发生在IDE内，那么就是你没有安装lombok插件
