### ISSUE TITLE
微信开放平台调用上传小程序代码一直提示超时，按照上面的方法修改配置还是出现此问题？

### ISSUE THREAD

**Issue by lianhehu** [Wechat-Group/WxJava#3139]
![上传失败](https://github.com/Wechat-Group/WxJava/assets/87899388/dbcf379d-cab2-4d8c-83b4-91bcaa287b69)
![配置信息](https://github.com/Wechat-Group/WxJava/assets/87899388/ec2ce703-fe44-490c-9e7c-028c333e265e)
![sdk的默认初化](https://github.com/Wechat-Group/WxJava/assets/87899388/c91bf13a-1b5e-45a3-83b7-86a2a0891ec1)
不知为什么改不了默认的http请求超时配置？请作者解答一下。

**Comment by binarywang** [comment]
看wiki常见问题

**Comment by binarywang** [comment]
楼主问题解决了吗？
