### ISSUE TITLE
commit 导致错误 2aa27cf12d4a3c7585a951e98db934b9eec9efa8 

### ISSUE THREAD

**Issue by playersun** [Wechat-Group/WxJava#3143]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~

### 简要描述
__请简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号: 4.5.5.B

### 详细描述
2023.7.21 的commit：2aa27cf12d4a3c7585a951e98db934b9eec9efa8 
将me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl#configStorageMap直接初始化，导致调用me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl#addConfigStorage()方法是不会触发initHttp()，从而没有httpClient实例

**Comment by binarywang** [comment]
欢迎直接提供修复代码

**Comment by binarywang** [comment]
@kilofox

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/pull/3092
