### ISSUE TITLE
企微ticket缓存过期处理策略

### ISSUE THREAD

**Issue by auroraforgithub** [Wechat-Group/WxJava#3147]
请问下，/cgi-bin/ticket/get 这个接口获取的ticket 发现过期时间永远返回7200s  redis缓存7200s和企微时间上的不一致怎么处理呢？

**Comment by binarywang** [comment]
自己redis缓存时间短一些不就可以了吗？

**Comment by Kylin824** [comment]
![image](https://github.com/Wechat-Group/WxJava/assets/31285778/65ad07c4-5714-4e71-b289-6f1cb5aa4243)
如果在这200秒内redis缓存过期了去拿到的ticket不还是旧的吗  然后又被重新设置过期时间为7200s？

**Comment by nadirvishun** [comment]
企业微信官方文档就是坑啊，根本没说明白，现在感觉也是模模糊糊的。
- 针对`access token`开放社区工作人员的意思是`access_token`只有2小时，`expires_in`压根不是真实的过期时间，参考：[请问企业微信的accessToken有效期，重新获取accessToken，会重置有效时间吗？](https://developers.weixin.qq.com/community/develop/doc/00042c80820ba04f102c43f335e400?highLine=access%2520token%2520%25E9%2587%258D%25E7%25BD%25AE)，但`expires_in`如果不是真实的，那么`redis`中设置的过期时间就可能有问题，但对于`access token`来说即便有问题也没什么，因为有全局的`access token`失效检测，即便`redis`中时间没到，但某接口返回了`access token`失效错误，那么就会重试来更新`access token`。
- 但是`jsapi_ticket`来说是没有全局检测的，如果提前失效了，但`redis`中的还没有失效，那么每次请求都会出错，直到失效为止，虽然获取方法中有个参数是设置强制失效，但是错误是前端`js-sdk`返回的，而且只返回`invalid signature`签名错误，还不一定能确定是`jsapi_ticket`过期的原因，感觉确实不好处理啊。
-----
又重新思考了下上方连接中的图片，如果是`access token`真实寿命是4小时的话，那么返回`expires_in`一直是`7200s`也是说的通的，因为`1~2`小时内请求返回的都是同一个`access token`，那么由于实际4小时才真正过期，那么`7200s`内则能保证一定不会过期，而`2~4`小时再请求，返回的就是新的`access token`，`7200s`同样也没有问题。感觉这是最合理的解释了。。。

![image](https://github.com/Wechat-Group/WxJava/assets/5761981/00a514e5-f1d8-4687-9fec-7306bf9c3725)
