### ISSUE TITLE
 ”查询 URL Link“   功能

### ISSUE THREAD

**Issue by von-agiler** [Wechat-Group/WxJava#3157]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述

weixin-java-miniapp  4.5.0
没有   ”查询 URL Link“   功能

### 官方文档地址
[__请提供所需功能对应的微信官方文档地址以便进行确认。__](https://developers.weixin.qq.com/miniprogram/dev/OpenApiDoc/qrcode-link/url-link/queryUrlLink.html)

**Comment by binarywang** [comment]
#3124 重复
