### ISSUE TITLE
微信申请退款V3接口微信时不时报异常api.mch.weixin.qq.com:443 failed to respond

### ISSUE THREAD

**Issue by liuwenfeng554** [Wechat-Group/WxJava#3158]
微信申请退款V3接口微信时不时报异常api.mch.weixin.qq.com:443 failed to respond
简要描述
调用v3申请退款，响应报异常api.mch.weixin.qq.com:443 failed to respond
该情况时好时坏，起初通过百度，以为是网上说的httpclient版本的问题 后来发现版本4.5.1 不存在说是4.4.版本的情况；

版本情况
版本号: weixin-java-pay v 4.5.0

WxPayConfiguration里面也设置
![image](https://github.com/Wechat-Group/WxJava/assets/11897356/b1fffed6-debc-42ac-a97a-d19aec5b6b36)

**Comment by binarywang** [comment]
这种问题，一般是网络环境原因导致，需要自己设置下超时相关参数，适当增加时间
