### ISSUE TITLE
javax.servlet-api需要更换为jakarta.servlet-api

### ISSUE THREAD

**Issue by witt-bit** [Wechat-Group/WxJava#3160]
目前如果只需要weixin-java-pay的小部分功能，项目仍然会引入`javax.servlet-api`依赖，导致项目中的`@ConditionalOnClass`在适配新老项目时出现问题

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号: 4.5.6.B

建议: 
1.尽快升级为`jakarta`
2.将`servlet-api`依赖不可传递，改为`optional`

**Comment by binarywang** [comment]
欢迎直接提供可靠的优化代码并提交PR
