### ISSUE TITLE
关于我提交的"接入微信支付分签约计划" 能合并一下吗 周五打算发生产了

### ISSUE THREAD

**Issue by UltramanNoa** [Wechat-Group/WxJava#3163]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

关于我提交的"接入微信支付分签约计划" 能合并一下吗 周五打算发生产了

**Comment by binarywang** [comment]
有冲突，请自己先处理下，另外请不要依赖这边的版本发布进度，如果确实生产环境需要，建议自己打本地包使用。

**Comment by binarywang** [comment]
另外不同的问题独立分支分别提交PR，这次我先帮你处理下，下次请注意下这块。本周内可能会发布新版本的

**Comment by binarywang** [comment]
还有，以后有问题可以看下这里（https://github.com/Wechat-Group/WxJava/issues/3057 ）入群，或者直接微信联系我，及时得到反馈

**Comment by UltramanNoa** [comment]
谢谢大佬 这次着急忙迷糊了  下次绝对注意  辛苦大佬了  好人一生平安


Binary Wang ***@***.***> 于2023年11月13日周一 11:31写道：
