### ISSUE TITLE
有没有类似延迟加载，或避免加载配置的方法

### ISSUE THREAD

**Issue by TaoTao-Zhao** [Wechat-Group/WxJava#3165]
如题，我现在在做一个支付的业务，我需要根据商户来加载配置信息，所以这些数据在项目启动时，是不确定的，只有等请求来的时候我才能明确需要加载的appId等一些信息。
现在项目启动不了，说是appId不能为空，我查了文档和一些博客，没发现相关的回复，所以这里提问一下。
如果有类似的功能的话，麻烦指点一下，谢谢了。

**Comment by binarywang** [comment]
自己修改代码，不执行相关的代码就可以了
