### ISSUE TITLE
wx-java-miniapp-spring-boot-starter当wx.miniapp.config-storage.type = RedisTemplate时 host的配置问题   

### ISSUE THREAD

**Issue by lzb-forever** [Wechat-Group/WxJava#3168]
wx-java-miniapp-spring-boot-starter

# 存储配置redis(可选)
# 注意: 指定redis.host值后不会使用容器注入的redis连接(JedisPool)
wx.miniapp.config-storage.type = Jedis                     # 配置类型: Memory(默认), Jedis, RedisTemplate
wx.miniapp.config-storage.key-prefix = wa                  # 相关redis前缀配置: wa(默认)
wx.miniapp.config-storage.redis.host = 127.0.0.1
wx.miniapp.config-storage.redis.port = 6379

如果我设置type=RedisTemplate后，host配置与否都不会使用了，我看源码中是直接从容器中取的
如果我不想使用项目里配置的redis 并且自己指定redis必须设置成type=Jedis?

**Comment by lzb-forever** [comment]
或者换另一种说法，我使用wx-java-miniapp-spring-boot-starter就不能手动注入RedisTemplate
如果想自己注入就还要换回wx-java-mp

**Comment by ema2207** [comment]
没有初始化配置文件中redis配置，使用了默认配置localhost
