### ISSUE TITLE
微信商户商场商圈的相关功能接口    

### ISSUE THREAD

**Issue by toLegend** [Wechat-Group/WxJava#3172]
官方接口地址 https://pay.weixin.qq.com/wiki/doc/apiv3/Offline/apis/chapter5_9_32.shtml

**Comment by binarywang** [comment]
暂无计划，欢迎自行仿照现有接口实现并进行调试，调试成功可以提交PR贡献代码

**Comment by binarywang** [comment]
官方接口地址 https://pay.weixin.qq.com/wiki/doc/apiv3/Offline/apis/chapter5_9_32.shtml
