### ISSUE TITLE
视频号助手开放接口 有计划加入么大佬？

### ISSUE THREAD

**Issue by forwaard** [Wechat-Group/WxJava#3188]
### 简要描述

视频号我看主要接入的是小店相关接口，请问视频号助手开放接口是否有计划加入，直播数据、留资信息那块

### 官方文档地址

(https://developers.weixin.qq.com/doc/channels/API/windowproduct/getaccesstoken.html)

**Comment by binarywang** [comment]
欢迎仿照现有代码自行实现代码，调试无误后可以直接提交PR贡献代码上来，谢谢
