### ISSUE TITLE
关于getAccessToken接口IP白名单问题

### ISSUE THREAD

**Issue by lkbtt** [Wechat-Group/WxJava#3199]
我在公司里部署启动后发现 getAccessToken ，公众号后台限制必须要IP白名单才可以访问（公司外网IP是不固定的）

接口报错：
`微信原始报文：{"errcode":40164,"errmsg":"invalid ip 114.221.21.30 ipv6 ::ffff:114.221.21.30, not in whitelist rid: 658cff8e-7783352d-44cb33e5"}`

我想到的方案：
我有阿里云公网IP，**如何 覆盖 getAccessToken  现有接口逻辑**；改成调用我阿里云上的接口（该接口再去调用微信AccessToken接口），这样IP就是固定的，才能满足微信 白名单的要求

或者还要其他办法吗？

**Comment by binarywang** [comment]
一般来说公司的ip 是可以固定的吧？真的没办法固定下来吗？
非固定 ip 会有很多风险，这也是为什么微信要求这么做，是有道理的。

不建议你想办法去绕过这个，除非你的服务器确实觉得没有任何风险。

**Comment by lkbtt** [comment]
老板觉得数据不安全，所以服务部署在公司机房，通过FRP配置的内网穿透；
又不是专线，所以IP不是固定的；
这种情况真的没办法解决吗？

**Comment by nadirvishun** [comment]
只代理一个接口有些费劲，目前貌似只暴露了修改基础url的方法，有用过企业微信通过`frp`来代理全部接口是可以的，以企业微信为例：
1、在配置中 `configStorage.setBaseApiUrl(‘xxx阿里云的地址url’);`，这样所有请求的`api`都会走这个代理地址。
2、在阿里云的代理中，在将这个请求转发到企业微信接口中，就相关于用的阿里云的`ip`来请求接口，用的是`caddy`配置如下，`nginx`同理：
  ```
  xxx阿里云.com:80, xxx阿里云.com:443 {
	handle_path /qyapi/* {
		reverse_proxy https://qyapi.weixin.qq.com {
			header_up Host {upstream_hostport}
		}
	}
  }
  ```
没有测试过微信公众号，但感觉应该也是差不多的原理配置。

**Comment by lkbtt** [comment]
实现方案如下：
阿里云openresty配置接口XXXX, 转发到lua脚本请求腾讯后台，本地定期请求该XXXX接口接口
