### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.lang.Long redis.clients.jedis.Jedis.ttl(java.lang.String)'

### ISSUE THREAD

**Issue by raymondZhong** [Wechat-Group/WxJava#3205]
springboot 3 + wxJava 4.6.0 + jredis 4.3.1 然后就报错了。

<jredis.version>4.3.1</jredis.version>

Handler dispatch failed: java.lang.NoSuchMethodError: 'java.lang.Long redis.clients.jedis.Jedis.ttl(java.lang.String)'
模块版本情况

    WxJava 模块名: weixin-java-open
    WxJava 版本号: 4.6.0正式版

**Comment by binarywang** [comment]
jedis 版本需要和本 sdk 所依赖的类库保持兼容，具体自己看下常见问题

**Comment by raymondZhong** [comment]
常见问题没有 对 jedis 版本配置的说明。  目前调回了 jedis 3.3.0.

**Comment by binarywang** [comment]
常见问题里没有提到 NoSuchMethodError 吗？
