### ISSUE TITLE
weixin-java-openx希望增加 快速设置小程序服务器域名

### ISSUE THREAD

**Issue by Nagi30001** [Wechat-Group/WxJava#3209]
目前4.6.0版本好像只支持https://api.weixin.qq.com/wxa/modify_domain?access_token=ACCESS_TOKEN
这个来设置小程序业务域名,这个官方必须需要先在开放平台设置服务器域名但是有上限，需要增加个快速设置小程序服务器域名，https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/2.0/api/Mini_Program_Basic_Info/modify_domain_directly.html

**Comment by binarywang** [comment]
欢迎直接 PR 贡献代码，谢谢

**Comment by lemos1235** [comment]
这种直接设置根域名就行，不然还得校验子域名啥的。
