### ISSUE TITLE
WxMpApiUrl  getUrl方法抛出'java.lang.reflect.InaccessibleObjectException'异常

### ISSUE THREAD

**Issue by piratekingtom** [Wechat-Group/WxJava#3214]
```
 public interface WxMpApiUrl {
    default String getUrl(WxMpConfigStorage config) {
        WxMpHostConfig hostConfig = null;
        if (config != null) {
            hostConfig = config.getHostConfig();
        }

        return WxMpHostConfig.buildUrl(hostConfig, this.getPrefix(), this.getPath());
    }
}

```
 config.getHostConfig(); 方法抛出'java.lang.reflect.InaccessibleObjectException'异常. 无法评估 me.chanjar.weixin.mp.config.impl.WxMpDefaultConfigImpl.toString()
获取微信模板列表报错
4.6版本

 this.wxService.switchoverTo(appid).getTemplateMsgService().getAllPrivateTemplate();
 
 但是我用获取菜单的接口是没有问题的

**Comment by binarywang** [comment]
异常信息不能给全一下吗？

**Comment by piratekingtom** [comment]
@binarywang 
![image](https://github.com/Wechat-Group/WxJava/assets/17740201/d9268e91-a047-42e2-968b-d82c92e18060)
已经给全了大佬，我写的代码也就一句，报错也是一句，没完整的堆栈
用的这个demo，就加了一句this.wxService.switchoverTo(appid).getTemplateMsgService().getAllPrivateTemplate();
https://gitee.com/binary/weixin-java-mp-demo-springboot.git
