### ISSUE TITLE
我看到有 springboot 的适配版本，是不是也可以有 solon 的适配版本？

### ISSUE THREAD

**Issue by noear** [Wechat-Group/WxJava#3217]
同题

**Comment by shuiyihan12** [comment]
心有余而力不足，目前正在PR小程序的接口变更和jdk兼容，solon可能要等等，玩的不是很熟练，我就不出来丢人了，期待大佬们的支持

**Comment by noear** [comment]
我找个用户对接试试：）

**Comment by binarywang** [comment]
都没听说过这玩意，你如果比较熟，建议可以自己搞

**Comment by noear** [comment]
@binarywang “玩意”？这口气，有点傲慢了吧：）

**Comment by binarywang** [comment]
> @binarywang “玩意”？这口气，有点傲慢了吧：）

抱歉大侠，真没听过，不好意思，你这边如果方便可以实现一份并提交PR吧，顺便可以让更多人了解你的项目

**Comment by noear** [comment]
@binarywang 是个好主意：）

**Comment by noear** [comment]
@binarywang 我正参考 springboot 的，适配 solon 版本。。。

发现，每个适配包关于 redis 那块的代码几乎一样。有没有可能，进一步抽象出基类来？

**Comment by noear** [comment]
https://github.com/Wechat-Group/WxJava/pull/3358

pr 已提交

**Comment by binarywang** [comment]
> @binarywang 我正参考 springboot 的，适配 solon 版本。。。
> 
> 发现，每个适配包关于 redis 那块的代码几乎一样。有没有可能，进一步抽象出基类来？

可以，你可以新开PR重构下吧

**Comment by noear** [comment]
@binarywang 先把今天的 pr 审了：）

**Comment by binarywang** [comment]
你是不是该出个教程讲下如何使用呢？或者简单写个文档吧，放到wiki里？

**Comment by noear** [comment]
好的。我补下 wiki 。。。。原则上，跟 spring 的用法一模一样；同时，在模块里的 reamd 里有描述了（从 spring 的适配包时，抄的）

**Comment by noear** [comment]
@binarywang 哪里有 spring 的使用 wiki 吗？？？我去抄下

**Comment by noear** [comment]
后面，麻烦各位照应了：）

**Comment by noear** [comment]
@binarywang   近期什么时候会发版啊？

**Comment by binarywang** [comment]
> @binarywang 哪里有 spring 的使用 wiki 吗？？？我去抄下

暂时也没有，如果你要写的话参考那些readme就可以吧

**Comment by binarywang** [comment]
> @binarywang 近期什么时候会发版啊？

前几天刚发了版本，新的版本可能再等等了

**Comment by noear** [comment]
ok

**Comment by noear** [comment]
@binarywang spring 的适配，有没有对应的单测的？？？如果有的话，我去加对应的 solon 单测。

**Comment by binarywang** [comment]
spring的都是starter，没有具体的业务代码，所以一般都没有测试代码。

**Comment by binarywang** [comment]
spring的都是starter，没有具体的业务代码，所以一般都没有测试代码。
