### ISSUE TITLE
WxMaEntrustRequest 中version字段必填，但是小程序纯签约场景，会带上version加签，导致最终拉不起签约页面（参数构造错误，请联系商家处理）

### ISSUE THREAD

**Issue by ni-shiliu** [Wechat-Group/WxJava#3219]
WxMaEntrustRequest 中version字段必填，但是小程序纯签约场景，会带上version加签，导致最终拉不起签约页面（参数构造错误，请联系商家处理）
<img width="631" alt="image" src="https://github.com/Wechat-Group/WxJava/assets/36874530/a83c306b-7dce-4c14-bd36-5856f8658c6b">
<img width="408" alt="image" src="https://github.com/Wechat-Group/WxJava/assets/36874530/627e5c08-91fb-4dd1-9361-3b432b4b8e02">

**Comment by binarywang** [comment]
麻烦规范一下发帖内容
