### ISSUE TITLE
BaseWxPayResult类checkResult时，是否校验结果或如果结果不正确，是否打error日志，应该支持可配置。

### ISSUE THREAD

**Issue by ni-shiliu** [Wechat-Group/WxJava#3220]
现在BaseWxPayResult，checkResult时，默认都会校验结果的正确性，如果错误就会打error日志，是否打error日志应该支持可配置，这样使用方才更加灵活，

**Comment by binarywang** [comment]
你有什么好的实现方式，欢迎直接 PR

**Comment by ni-shiliu** [comment]
可以参考支付宝的sdk，新增变量来控制是否打印error日志和是否校验结果，使用方在初始化client的时候，可以设置该参数：   
    private static boolean needEnableLogger = true;
    private static boolean needCheckSuccess = true; // 该功能源码里已可以控制是否checkSuccess，只是没有提供方法给使用方
    public static void setNeedEnableLogger(boolean needEnableLogger) {
        AlipayLogger.needEnableLogger = needEnableLogger;
    }
    public static void setNeedCheckSuccess(boolean needCheckSuccess) {
        this.needCheckSuccess = needEnableLogger;
    }

**Comment by ni-shiliu** [comment]
<img width="578" alt="image" src="https://github.com/Wechat-Group/WxJava/assets/36874530/f5b7eb89-d43f-46fa-abf0-a97947efddc4">
<img width="644" alt="image" src="https://github.com/Wechat-Group/WxJava/assets/36874530/6054355a-9aed-475c-8153-3d82ffda5516">
