### ISSUE TITLE
由于公众号和小程序有多个weixin-java-mp 能否支持类似 wx-java-cp-multi-spring-boot-starter 的能力

### ISSUE THREAD

**Issue by mnshun** [Wechat-Group/WxJava#3221]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by foreveryang321** [comment]
已加，可以验证一下，https://github.com/Wechat-Group/WxJava/pull/3224

**Comment by monchcc** [comment]
@binarywang 可以也支持下多个小程序的能力嘛
