### ISSUE TITLE
微信支付签名校验失败

### ISSUE THREAD

**Issue by applealpha** [Wechat-Group/WxJava#3223]
### 简要描述
微信官方文档 -> 平台能力 -> 行业能力 -> 虚拟支付
支付签名校验失败

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号: 4.6.0

### 详细描述
appKey、appid、env、secret都配置正确了，微信端依然报错支付签名校验失败
![image](https://github.com/Wechat-Group/WxJava/assets/43408257/76c61087-5174-42f7-a9fc-bc0c1bca6c99)

### 日志
![YXbz0f14L0](https://github.com/Wechat-Group/WxJava/assets/43408257/648ecbdb-4345-4ee4-a52a-53af205bd7f2)

**Comment by applealpha** [comment]
问题原因：
虚拟支付的接口中，添加的支付签名必须全部小写，但是现有的WxMaXPaySigParams内部生成的支付签名是大写的
![image](https://github.com/Wechat-Group/WxJava/assets/43408257/eb22ff45-54f3-4620-9c3d-9d9bc080f9ec)

解决方案：
重写一下WxMaXPaySigParams.calcPaySig(String url, String postBody)
![image](https://github.com/Wechat-Group/WxJava/assets/43408257/6adc5b7c-d876-45cb-9796-de38a3e47a88)

**Comment by binarywang** [comment]
欢迎直接提交 PR，测试没问题的话

**Comment by binarywang** [comment]
@kevinzhwl 有空的话可以看一眼
