### ISSUE TITLE
传运单接口 trace_waybill 缺少参数

### ISSUE THREAD

**Issue by lanxikun** [Wechat-Group/WxJava#3233]
文件：https://github.com/Wechat-Group/WxJava/blob/develop/weixin-java-miniapp/src/main/java/cn/binarywang/wx/miniapp/bean/delivery/TraceWaybillRequest.java
缺少字段

delivery_id： 运力id（运单号所属运力公司id），该字段从 [get_delivery_list](https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/industry/express/business/express_search.html#%E8%8E%B7%E5%8F%96%E8%BF%90%E5%8A%9Bid%E5%88%97%E8%A1%A8get-delivery-list) 获取。
该参数用于提高运单号识别的准确度；特别是对非主流快递公司，建议传入该参数，确保查询正确率。

goods_desc：商品详情描述，不传默认取“商品名称”值，最多40汉字

**Comment by binarywang** [comment]
欢迎直接提交 PR
