### ISSUE TITLE
企业微信-修改客户备注信息-无法清空全部备注手机号码

### ISSUE THREAD

**Issue by flygger** [Wechat-Group/WxJava#3236]
- 企微接口文档涉及备注手机的相关描述如下：

remark，description，remark_company，remark_mobiles和remark_pic_mediaid不可同时为空。
如果填写了remark_mobiles，将会覆盖旧的备注手机号。
如果要清除所有备注手机号,请在remark_mobiles填写一个空字符串("")。
<img width="943" alt="image" src="https://github.com/Wechat-Group/WxJava/assets/35088030/8b09dcb5-8832-4beb-9590-367963101bdb">

- 工具实际调用的WxCpUpdateRemarkRequest类中remarkMobiles仅支持数组格式

![image](https://github.com/Wechat-Group/WxJava/assets/35088030/b453a617-bf14-433f-89ce-deeaffa63790)

**Comment by binarywang** [comment]
这确实是个问题，欢迎直接提交 PR 代码实现功能
