### ISSUE TITLE
me.chanjar.weixin.cp.constant.WxCpApiPathConsts.OAuth2#GET_USER_DETAIL 4.6.0 路径与源码不一致

### ISSUE THREAD

**Issue by mnshun** [Wechat-Group/WxJava#3237]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~

### 简要描述
__请简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号:4.6.0

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__
me.chanjar.weixin.cp.constant.WxCpApiPathConsts.OAuth2#GET_USER_DETAIL 
4.6.0
期望    String GET_USER_DETAIL = "/cgi-bin/auth/getuserdetail";
但是从maven仓库获取的url为 
String GET_USER_DETAIL = "/cgi-bin/user/getuserdetail";

![image](https://github.com/Wechat-Group/WxJava/assets/12005228/c8e226bf-723c-41f0-bb39-4ad746060a28)

### 日志
__如果日志不多，直接使用md代码引用格式贴在此处，否则如果太长，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，然后将其url地址贴在这里__
```
日志请写于此处
```

**Comment by binarywang** [comment]
你确定看的是同一版本的代码吗？

**Comment by binarywang** [comment]
而且4.6.0的代码并不是你在这里看到的最新版的代码

**Comment by binarywang** [comment]
#3208
