### ISSUE TITLE
修改initApiV3HttpClient代码中的自动更新证书url地址

### ISSUE THREAD

**Issue by HaalandCR** [Wechat-Group/WxJava#3241]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
项目在内网服务器A部署，只有内网服务器B可以通外网，实际使用中通过服务器B转发请求，在方法initApiV3HttpClient -> AutoUpdateCertificatesVerifier -> autoUpdateCert中请求了`https://api.mch.weixin.qq.com/v3/certificates`地址，该地址没有使用WxPayConfig中设置的payBaseUrl，而是写死在代码里，导致initApiV3HttpClient方法报错，建议将固定地址修改为使用配置

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by binarywang** [comment]
欢迎直接提供修复代码，谢谢
