### ISSUE TITLE
refundqueryv2的 WxPayRefundQueryResult 定义错误

### ISSUE THREAD

**Issue by witt-bit** [Wechat-Group/WxJava#3255]
微信官方文档 https://pay.weixin.qq.com/wiki/doc/api/danpin.php?chapter=9_104&index=4

中返回值中有`refund_status`字段，虽然文档没有描述说明，但是实际有这个字段，现在WxPayRefundQueryResult对象在V2时并没有声明`refund_status`相关字段

如果没有这个字段，就无法区分是处理中的成功，还是实际到账成功

**Comment by binarywang** [comment]
欢迎直接提交PR代码，谢谢

**Comment by 0katekate0** [comment]
V2版本里面，WxPayRefundQueryResult有RefundRecord，RefundRecord里面有refund_status字段。

Q&A：
1、现在推荐用V3版本了，为什么在用V2版本？
2、这边能不能提供一下具体的返回值？
3、你现在那边是不是有一个空的refundRecords？
