### ISSUE TITLE
服务端 转发客服消息  无效

### ISSUE THREAD

**Issue by xiaodong1978** [Wechat-Group/WxJava#3264]
![微信截图_20240426203605](https://github.com/Wechat-Group/WxJava/assets/48702522/c9920dda-f0b4-42aa-862b-eb795ef0b964)

### 简要描述
需要实现上图，官网所说功能，服务端进行转发客服消息  没什么作用

### 模块版本情况
* WxJava 模块名: <weixin-java-miniapp.version>4.6.0</weixin-java-miniapp.version>
* WxJava 版本号: <weixin-java-miniapp.version>4.6.0</weixin-java-miniapp.version>

代码如下：
![微信截图_20240426204159](https://github.com/Wechat-Group/WxJava/assets/48702522/8b58cdf0-56a3-4898-9bff-2019d77309e4)

![微信截图_20240426204218](https://github.com/Wechat-Group/WxJava/assets/48702522/5307afa9-8c32-46da-99b3-8a01fa2258a0)

用户向小程序客服发消息，网页版客服工具无法收到消息。

后续：在WxPortalController Post中返回WxMaXmlOutMessage也不行，如下图

![微信截图_20240426235437](https://github.com/Wechat-Group/WxJava/assets/48702522/50b28875-806e-425c-8b41-7b20bc49fab8)

![微信截图_20240426235800](https://github.com/Wechat-Group/WxJava/assets/48702522/ad93de72-55ea-49e7-9edd-ed76e36b79fc)

实在是没招了。

**Comment by awaken233** [comment]
楼主此问题是如何解决的呢？没看到解决方法呢？怎么关闭了
