### ISSUE TITLE
开放平台部分url失效

### ISSUE THREAD

**Issue by waitxy** [Wechat-Group/WxJava#3270]
### 简要描述
1、 获取授权方选项信息 请求地址已经变化 API_GET_AUTHORIZER_OPTION_URL 由/cgi-bin/component/api_get_authorizer_option 变化为
/cgi-bin/component/get_authorizer_option
文档地址：https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/authorization-management/getAuthorizerOptionInfo.html
2、设置授权方选项信息 请求地址已经变化 API_SET_AUTHORIZER_OPTION_URL 由 /cgi-bin/component/api_set_authorizer_option变化为/cgi-bin/component/set_authorizer_option
文档地址：https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/authorization-management/setAuthorizerOptionInfo.html

### 模块版本情况
* `WxJava` 模块名: weixin-java-open
* `WxJava` 版本号:4.6.1.B

### 详细描述
`目前仅发现这两个`

**Comment by binarywang** [comment]
欢迎直接提交PR修复代码，谢谢
