### ISSUE TITLE
生成大量临时文件没有删除占用空间

### ISSUE THREAD

**Issue by zhaojp0411** [Wechat-Group/WxJava#3271]
![image](https://github.com/Wechat-Group/WxJava/assets/2330160/da5bd8a7-2a16-4d2d-84bf-9e7a54468ed3)
不知道是哪个模块产生的。

### 模块版本情况
* WxJava 模块名: weixin-java-cp wx-java-open-spring-boot-starter wx-java-miniapp-spring-boot-starter wx-java-mp-spring-boot-starter wx-java-pay-spring-boot-starter
* WxJava 版本号: 4.3.8.B

**Comment by binarywang** [comment]
应该是你调用了上传文件相关的接口，但是没有及时清理系统临时目录导致
