### ISSUE TITLE
请接入小程序推广员相关接口

### ISSUE THREAD

**Issue by huyanbin** [Wechat-Group/WxJava#3279]
### 简要描述
小程序推广员是微信官方提供的小程序经营工具，旨在帮助小程序商家更高效精准地触达、管理小程序推广员（包括导购、分销员等角色），提升小程序推广效率。

### 官方文档地址
https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/business-capabilities/promoter/instruction/instruction.html

**Comment by binarywang** [comment]
欢迎自行实现并提交PR贡献代码，谢谢
