### ISSUE TITLE
希望优化一下代码

### ISSUE THREAD

**Issue by ChenJiaXin520** [Wechat-Group/WxJava#3287]
我提交过两个简单的pr，查看项目代码的时候发现wxjava-java-mp公众号模块的RequestExecutor的实现类有很多重复代码，例如：
HttpPost httpPost = new HttpPost(uri);
    if (requestHttp.getRequestHttpProxy() != null) {
      RequestConfig config = RequestConfig.custom().setProxy(requestHttp.getRequestHttpProxy()).build();
      httpPost.setConfig(config);
    }
另外还有RequestHttp这个泛型类使用也不规范，很多类在使用中并没有明确指明泛型的类型

**Comment by binarywang** [comment]
你可以直接提交PR进行优化吧

**Comment by ChenJiaXin520** [comment]
牵涉有点多，改动比较大，建议还是你们主力开发者修改
