### ISSUE TITLE
没找到小程序备案的接口，自己根据楼主的风格，手搓了一份

### ISSUE THREAD

**Issue by sdf295953** [Wechat-Group/WxJava#3290]
不知道怎么提交……

**Comment by binarywang** [comment]
楼主不就是你本人吗？
参考代码贡献指南，很简单，首页有链接说明

**Comment by hersion** [comment]
期待提交

**Comment by sdf295953** [comment]
提交了，使用啊……  对github的了解太少了

**Comment by Molzx** [comment]
备案的在哪，没看到你的pr

**Comment by binarywang** [comment]
> 提交了，使用啊…… 对github的了解太少了

提交到哪里了？已经有其他人提交了，因此没有机会再合并你的代码了，记得及时共享代码啊，楼主同学！
