### ISSUE TITLE
视频号订单缺失属性AddressInfo.hash_code

### ISSUE THREAD

**Issue by zhouchengfei** [Wechat-Group/WxJava#3295]
### 简要描述
视频号订单缺失属性AddressInfo.hash_code

### 官方文档地址
https://developers.weixin.qq.com/doc/channels/API/order/get.html
AddressInfo.hash_code 标识当前店铺下一个唯一的用户收货地址

###疑问
像这种还你们没有及时更新的新属性,我们有什么便捷的方法新增属性,下载源码?自己加?自己打包?

**Comment by imyzt** [comment]
自己打包成本太高，提一个MR等官方版本太慢影响进度，少量字段没及时同步又想继续使用SDK的话，可以直接拷贝源码类到工程下覆盖源码包中的类，Java会优先加载`src`下面的类，等后续官方发版再删除即可。🙃
