### ISSUE TITLE
【feature】获取汇报记录详情

### ISSUE THREAD

**Issue by Ero-Cat** [Wechat-Group/WxJava#3296]
### 简要描述
全局搜索了下 没有汇报相关的issue和接口
https://developer.work.weixin.qq.com/document/path/93394#%E6%A6%82%E8%BF%B0
https://qyapi.weixin.qq.com/cgi-bin/oa/journal/get_record_detail?access_token=ACCESS_TOKEN
请求添加获取汇报记录详情接口
### 官方文档地址
https://developer.work.weixin.qq.com/document/path/93394

**Comment by binarywang** [comment]
欢迎直接实现代码提交PR

**Comment by Ero-Cat** [comment]
> 欢迎直接实现代码提交PR

之前fork了在写   最近工作太忙了...有空会pr

**Comment by binarywang** [comment]
> > 欢迎直接实现代码提交PR
> 
> 之前fork了在写 最近工作太忙了...有空会pr

那非常期待你的代码
