### ISSUE TITLE
是否可以加入企业微信文档相关接口

### ISSUE THREAD

**Issue by liusenb** [Wechat-Group/WxJava#3304]
![image](https://github.com/Wechat-Group/WxJava/assets/76118202/9d25b4b8-8ddc-41f0-9946-9ff94f6ec18f)

**Comment by binarywang** [comment]
请直接帖地址，不要发截图。

**Comment by Angoulemi** [comment]
> 请直接帖地址，不要发截图。

https://developer.work.weixin.qq.com/document/path/97392

**Comment by binarywang** [comment]
#3226 已实现
