### ISSUE TITLE
TransferCreateResult 商家转账到零钱,新增 batch_status 返回值,版本4.6.0

### ISSUE THREAD

**Issue by 13547995471** [Wechat-Group/WxJava#3319]
商家转账到零钱,微信返回了batch_status,希望可以加上
![111111](https://github.com/Wechat-Group/WxJava/assets/13552051/ff0d48b7-80e3-4072-a5a9-f259b2d86b45)
![22222](https://github.com/Wechat-Group/WxJava/assets/13552051/f8a6efce-dc87-4804-9623-88d9b8ea34b0)

**Comment by binarywang** [comment]
欢迎直接提供修复代码
