### ISSUE TITLE
weixin-java-cp-solon-plugin redisson配置失败

### ISSUE THREAD

**Issue by freezaee** [Wechat-Group/WxJava#3321]
### 简要描述
使用weixin-java-cp-solon-plugin，配置redisson存储模式，solon无法解析
由于找不到weixin-java-cp-solon-plugin项目，只能在这里提issue了。

### 模块版本情况
* WxJava 模块名: weixin-java-cp-solon-plugin
* weixin-java-cp-solon-plugin 版本号:2.7.1

### 详细描述
如果配置type为redisson时，solon框架解析时会按照枚举类型StorageType 解析，但是该枚举中没有redisson枚举值，导致解析失败。
```
wx:
  cp:
    config-storage:
      type: "redisson"
```

```   /**
     * 存储类型
     */
    private StorageType type = StorageType.memory;
    public enum StorageType {
    /**
     * 内存
     */
    memory
  }
```

**Comment by binarywang** [comment]
weixin-java-cp-solon-plugin  这个东西你是从哪里看到的？

**Comment by binarywang** [comment]
应该跟本项目没有任何关系的

**Comment by freezaee** [comment]
哦，打扰了，您可以关闭这个issue了，我再找找负责维护这个插件的作者。

**Comment by binarywang** [comment]
刚给你找到了，是这里

https://github.com/opensolon/solon-integration/tree/main/solon-plugin-weixin

**Comment by noear** [comment]
正在适配新的：）。。。以这个项目为底子的。。。。之前，是以另一个项目为底子的（之前不知道，哈哈）
