### ISSUE TITLE
可否增加小程序 生物认证秘钥签名验证

### ISSUE THREAD

**Issue by zpf463526081** [Wechat-Group/WxJava#3322]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
能增加下小程序生物认证秘钥签名验证接口吗

### 官方文档地址
[__请提供所需功能对应的微信官方文档地址以便进行确认。__](https://developers.weixin.qq.com/miniprogram/dev/OpenApiDoc/soter/verifySignature.html)

**Comment by binarywang** [comment]
暂时无计划，如果急需，欢迎自行按照现有代码仿照实现，并提交PR贡献代码，谢谢
