### ISSUE TITLE
GenerateShortLinkRequest结构

### ISSUE THREAD

**Issue by bombergithub** [Wechat-Group/WxJava#3326]
大佬您好，请问GenerateShortLinkRequest为什么没有空参和全参构造器，而只使用Builder，类似GenerateUrlLinkRequest都有这些注解，请问这么做是故意为之吗，有什么原因吗

**Comment by binarywang** [comment]
个人习惯而已，如果你觉得不方便，可以提供更新代码PR上来，需要确保不影响其他功能
