### ISSUE TITLE
缺少接口 平台收付通-提交注销申请单等

### ISSUE THREAD

**Issue by 1143240141** [Wechat-Group/WxJava#3327]
### 简要描述
缺少平台收付通接口
平台收付通-提交注销申请单
平台收付通-查询注销单状态
平台收付通-注销单图片上传API

### 官方文档地址
https://pay.weixin.qq.com/docs/partner/apis/ecommerce-cancel/cancel-applications/create-cancel-application.html
https://pay.weixin.qq.com/docs/partner/apis/ecommerce-cancel/cancel-applications/get-cancel-application.html
https://pay.weixin.qq.com/docs/partner/apis/ecommerce-cancel/media/upload-media.html

**Comment by binarywang** [comment]
欢迎直接提交PR贡献代码

**Comment by yantao** [comment]
【异常信息】：输入源“[/body/application_info/0]”映射到字段“注销申请材料”多重性规则校验失败，此字段个数为 1 个，低于最小值 2 ，按说接入的应该没有问题

【请求数据】：

{"sub_mchid":"16846？？？","out_apply_no":"asa？？？？？","application_info":[{"application_type":"SUB_CANCEL_ACCOUNT_APPLICATION","application_media_id":"oBnMWyXhOGtdWn2guwsFR/ouyfPEjFLzf6XjECXUe+OGa0WCa2cxMSF2latbXKqmlnnqt9X/MVgiJoDPKm5Kw？？？？"}]}

怎么@开发者   @binarywang

**Comment by binarywang** [comment]
@zhuangzibin 麻烦看下楼上的问题

**Comment by zhuangzibin** [comment]
> 【异常信息】：输入源“[/body/application_info/0]”映射到字段“注销申请材料”多重性规则校验失败，此字段个数为 1 个，低于最小值 2 ，按说接入的应该没有问题
> 
> 【请求数据】：
> 
> {"sub_mchid":"16846？？？","out_apply_no":"asa？？？？？","application_info":[{"application_type":"SUB_CANCEL_ACCOUNT_APPLICATION","application_media_id":"oBnMWyXhOGtdWn2guwsFR/ouyfPEjFLzf6XjECXUe+OGa0WCa2cxMSF2latbXKqmlnnqt9X/MVgiJoDPKm5Kw？？？？"}]}
> 
> 怎么@开发者 @binarywang

@yantao 
文档地址：https://doc.weixin.qq.com/doc/w3_AOMA_gZYACowbRu21L6Qi2tJlRszx
社区问答：https://developers.weixin.qq.com/community/develop/doc/0002a8f6f608884d7342ddc3661c00
社区问答：https://developers.weixin.qq.com/community/develop/doc/000628e71a8d48b233314956961000
两份资料你都要上传：
SP_CANCEL_ACCOUNT_APPLICATION: 电商服务商注销电商子申请书，请下载模板打印纸质版、填写盖章后拍照
SUB_CANCEL_ACCOUNT_APPLICATION: 电商服务商子商户注销申请书
