### ISSUE TITLE
媒资管理返回信息封装的实体中缺少status字段

### ISSUE THREAD

**Issue by cherl** [Wechat-Group/WxJava#3343]
### 简要描述
媒资管理，获取剧目接口返回信息封装的实体中缺少status字段。
### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号:4.6.0

### 详细描述
在调用public WxMaVodDramaInfo getDrama(WxMaVodGetDramaRequest request) throws WxErrorException 方法获取剧目信息时返回的数据有status字段，但是未封装进WxMaVodDramaInfo，请注意这个接口会返回两个status,而我们只封装了一个,封装的是DramaAuditDetail下面的那个。
以下是官方返回信息示例：
`{
    "errcode": 0,
    "errmsg": "ok",
    "drama_info": {
        "drama_id": 28918028,
        "create_time": 1682214878,
        "name": "我的演艺",
        "playwright": "编剧名",
        "producer": "制作方名",
        "production_license": "abd123",
        "cover_url": "https://developers.weixin.qq.com/test.jpg",
        "media_count": 2,
        "recommendations": "这是这部剧的推荐语。",
        "description": "剧目的简介。",
        "promotion_poster": "xxxxxxxxx",
        "other_material":"xxxxxxxxx",
        "status": 0,
        "media_list":[
            {"media_id": 10001},
            {"media_id": 10002}
        ],
        "audit_detail": {
            "status": 3,
            "create_time": 1682215878,
            "audit_time": 1682235878
        },
        "actor_list": {
            "actor": [{
                "name": "演员1",
                "photo_material_id": "xxxxxxxx",
                "role": "角色1",
                "profile": "简介"
            }, {
                "name": "演员2",
                "photo_material_id": "xxxxxxxx",
                "role": "角色2",
                "profile": "简介"
            }]
        }
    }
}
`
### 日志
```
无
```

**Comment by binarywang** [comment]
欢迎直接PR添加，谢谢

**Comment by cherl** [comment]
好的
