### ISSUE TITLE
获取用户手机号码getPhoneNoInfo

### ISSUE THREAD

**Issue by Molzx** [Wechat-Group/WxJava#3345]
#    WxMaPhoneNumberInfo getPhoneNoInfo(String sessionKey, String encryptedData, String ivStr); 

### 简要描述
这个方法移除掉，旧版本要做兼容，只能自己实现了吗

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号: 4.6.3.B

### 详细描述
![image](https://github.com/user-attachments/assets/aa0034d5-b54a-471b-ade3-4f775bbb0bd3)

**Comment by binarywang** [comment]
是因为官方不支持了，你自己写要怎么写？

**Comment by Molzx** [comment]
> 是因为官方不支持了，你自己写要怎么写？

不是说旧方式可以继续使用吗

> 从基础库2.21.2开始，对步骤2中换取手机号信息的方式进行了安全升级，上述为新方式使用指南。（[旧方式](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/deprecatedGetPhoneNumber.html)目前可以继续使用，但建议开发者使用新方式，以增强小程序安全性）另外，新方式不再需要提前调用wx.login进行登录。

**Comment by binarywang** [comment]
你没看到有另外新写的方法吗？getPhoneNumber

**Comment by Molzx** [comment]
> 你没看到有另外新写的方法吗？getPhoneNumber

我知道有新的方法，getPhoneNumber用code去换，但是要升级基础库到2.21.2上，如果要把全部的小程序升级适配上去，工程量太大，这个也只能是后期去做。原有的getPhoneNumber方法保持兼容也没问题的吧

**Comment by binarywang** [comment]
@shuiyihan12 麻烦看下这个问题吧，我看是你当初给移除的。

**Comment by shuiyihan12** [comment]
> > 你没看到有另外新写的方法吗？getPhoneNumber
> 
> 我知道有新的方法，getPhoneNumber用code去换，但是要升级基础库到2.21.2上，如果要把全部的小程序升级适配上去，工程量太大，这个也只能是后期去做。原有的getPhoneNumber方法保持兼容也没问题的吧

抱歉，未考虑旧版本细节，已提交新的PR 还原对旧版本的支持。以下提供两种方式：
1.暂缓对Jdk的更新，等新版本发布（推荐）。
2.简单对Jdk做兼容 （新版本发布后，推荐二次修改），相关实现核心代码如下
```  java
  public WxMaPhoneNumberInfo getPhoneNoInfo(String sessionKey, String encryptedData, String ivStr) {
    return WxMaPhoneNumberInfo.fromJson(WxMaCryptUtils.decrypt(sessionKey, encryptedData, ivStr));
  }
```
