### ISSUE TITLE
可以添加一下we统计的功能吗

### ISSUE THREAD

**Issue by a27856704** [Wechat-Group/WxJava#3349]
[# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
we分析接口

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__
](https://wedata.weixin.qq.com/mp2/api-manage/perm-guid)

**Comment by binarywang** [comment]
要做什么？有对应的API吗？

**Comment by a27856704** [comment]
api在issue里写了，做数据看板用



---- 回复的原邮件 ----
| 发件人 | Binary ***@***.***> |
| 日期 | 2024年08月19日 00:19 |
| 收件人 | ***@***.***> |
| 抄送至 | yuan ***@***.***>***@***.***> |
| 主题 | Re: [Wechat-Group/WxJava] 可以添加一下we统计的功能吗 (Issue #3349) |

要做什么？有对应的API吗？

**Comment by binarywang** [comment]
首先，如果你希望别人帮你实现，就尽量写详细些。
其次，这块需求不高，如果是你自己需求特别强烈，建议仿照现有代码自己尝试编写代码，调试没问题通过后，可以提交PR上来供其他人参考。

**Comment by a27856704** [comment]
已经自己实现了，只是提个建议



---- 回复的原邮件 ----
| 发件人 | Binary ***@***.***> |
| 日期 | 2024年08月19日 00:33 |
| 收件人 | ***@***.***> |
| 抄送至 | yuan ***@***.***>***@***.***> |
| 主题 | Re: [Wechat-Group/WxJava] 可以添加一下we统计的功能吗 (Issue #3349) |

首先，如果你希望别人帮你实现，就尽量写详细些。
其次，这块需求不高，如果是你自己需求特别强烈，建议仿照现有代码自己尝试编写代码，调试没问题通过后，可以提交PR上来供其他人参考。

**Comment by binarywang** [comment]
> 已经自己实现了，只是提个建议

那你可以把你的代码提交上来吧？可以让大家也帮你优化下。

**Comment by a27856704** [comment]
你都说了，需求不高不提了



---- 回复的原邮件 ----
| 发件人 | Binary ***@***.***> |
| 日期 | 2024年08月20日 12:40 |
| 收件人 | ***@***.***> |
| 抄送至 | yuan ***@***.***>***@***.***> |
| 主题 | Re: [Wechat-Group/WxJava] 可以添加一下we统计的功能吗 (Issue #3349) |

已经自己实现了，只是提个建议

那你可以把你的代码提交上来吧？可以让大家也帮你优化下。

**Comment by binarywang** [comment]
懂了，如果不想贡献就算了。
再次谢谢留言，祝好。

**Comment by a27856704** [comment]
我们的方式，只满足业务需要而已并不适用通用。提出需求只是觉得缺了这块，至于该怎么维护，由你们自己抉择，这个不强求的



---- 回复的原邮件 ----
| 发件人 | Binary ***@***.***> |
| 日期 | 2024年08月21日 14:48 |
| 收件人 | ***@***.***> |
| 抄送至 | yuan ***@***.***>***@***.***> |
| 主题 | Re: [Wechat-Group/WxJava] 可以添加一下we统计的功能吗 (Issue #3349) |

懂了，如果不想贡献就算了。
再次谢谢留言，祝好。
