### ISSUE TITLE
新建草稿api-缺少设置封面的参数

### ISSUE THREAD

**Issue by wxc1207** [Wechat-Group/WxJava#3356]
![image](https://github.com/user-attachments/assets/249e15e3-4d6a-4078-ab79-9ed9891a2e3f)

![image](https://github.com/user-attachments/assets/678f2319-e2c5-4e1b-bf5a-3e3a140d91eb)

**Comment by binarywang** [comment]
麻烦不要只发截图，谢谢！！！尽量文字描述

**Comment by wxc1207** [comment]
好的，公众号新建草稿接口的api缺少pic_crop_235_1和pic_crop_1_1两个参数，
这两个参数是用来裁剪封面图片的（下次我会用文字描述清楚的）

**Comment by binarywang** [comment]
麻烦提供文档地址，方便开发者实现。
或者你可以直接贡献代码，更快速些

**Comment by wxc1207** [comment]
https://developers.weixin.qq.com/doc/offiaccount/Draft_Box/Add_draft.html
新建草稿的api地址，

![image](https://github.com/user-attachments/assets/b7161655-9afd-43f0-bab2-483edc07b81b)

**Comment by wxc1207** [comment]
抽时间我PR上去，现在有个任务，正在上线，还有其他问题，我都跟大佬PR一下
