### ISSUE TITLE
现在有小程序的多账号配置嘛？

### ISSUE THREAD

**Issue by monchcc** [Wechat-Group/WxJava#3360]
这里支持了公众号和企业微信的多账号配置，有小程序的多账号配置嘛？

<img width="441" alt="image" src="https://github.com/user-attachments/assets/5e329d4d-7b9d-46a3-928d-866660c64900">

**Comment by binarywang** [comment]
你看到的没有，就是暂时没有了，如果急需，欢迎提交PR实现

**Comment by monchcc** [comment]
好的，一般多久能merge进去呀？

**Comment by binarywang** [comment]
merge 很快，但是发版要看时间，不固定。

**Comment by monchcc** [comment]
好的
