### ISSUE TITLE
【文档错误】 wx-java-qidian-spring-boot-starter 下的 readme 有误

### ISSUE THREAD

**Issue by noear** [Wechat-Group/WxJava#3361]
https://github.com/Wechat-Group/WxJava/blob/develop/spring-boot-starters/wx-java-qidian-spring-boot-starter/README.md

情况：

* 代码里的配置前缀是 "wx.qidian"。但 readme 里是 "wx.mq"

**Comment by binarywang** [comment]
你可以直接提交PR修复吧
