### ISSUE TITLE
企微拉取附件的时候报错

### ISSUE THREAD

**Issue by tzwhyqq** [Wechat-Group/WxJava#3365]
### 简要描述
使用了spring boot 3.3.3  ,4.6.4.B , jdk21 。6月份企微官方更新了 so文件包，不知道这个有没有影响。
（https://developer.work.weixin.qq.com/document/path/91774）
__请简单概括描述下你所遇到的问题。__
拉取附件时候报错,先是报
 错误代码：-99, 错误信息：getmediadata err ret 10010
 然后再接着运行运行几分钟。 就程序挂了

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号:4.6.4.B

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__
错误代码：-99, 错误信息：getmediadata err ret 10010，百度了下说是 超过多少天后拉取的附件就无法拉取。不知道是不是这个情况。
### 日志
__如果日志不多，直接使用md代码引用格式贴在此处，否则如果太长，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，然后将其url地址贴在这里__
```
日志请写于此处
```
 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f5e838f7ec3, pid=3642448, tid=3642518

 JRE version: Java(TM) SE Runtime Environment (21.0.2+13) (build 21.0.2+13-LTS-58)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (21.0.2+13-LTS-58, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
 Problematic frame:
 C  [libWeWorkFinanceSdk_Java.so+0x208ec3]  WeWorkFinanceSdk::TryRefresh(std::string const&, std::string const&, int)+0x23

 Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e" (or dumping to /www/wwwroot/wxcp/core.3642448)

 An error report file with more information is saved as:
 /www/wwwroot/wxcp/hs_err_pid3642448.log

 If you would like to submit a bug report, please visit:
   https://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

**Comment by binarywang** [comment]
请规范下你的发帖内容！
