### ISSUE TITLE
能在邀请下么？刚看到邮箱的邮件

### ISSUE THREAD

**Issue by wisty** [Wechat-Group/WxJava#3385]
![image](https://github.com/user-attachments/assets/b0adfb96-6189-4052-b6d0-221c98dfe33e)

**Comment by binarywang** [comment]
请直接联系我，谢谢

**Comment by binarywang** [comment]
如果你贡献过代码的话，请联系我，如果没有，忽略即可。

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/issues/3057
还有这个，也可以看下
