### ISSUE TITLE
获取已服务的外部联系人接口支持

### ISSUE THREAD

**Issue by cenggel** [Wechat-Group/WxJava#3405]
# 获取已服务的外部联系人接口支持

### 简要描述
企业可通过此接口获取所有已服务的外部联系人，及其添加人和加入的群聊。外部联系人分为客户和其他外部联系人，如果是客户，接口将返回外部联系人临时ID和externaluserid；如果是其他外部联系人，接口将只返回外部联系人临时ID。

企业可通过外部联系人临时ID排除重复数据，外部联系人临时ID有效期为4小时。

### 官方文档地址
[__请提供所需功能对应的微信官方文档地址以便进行确认。__](https://developer.work.weixin.qq.com/document/path/99434)

**Comment by binarywang** [comment]
欢迎直接提交PR来实现该接口

**Comment by zhanyan-Ader1y** [comment]
正在开发中
