### ISSUE TITLE
http框架 能增加hutool的http的吗

### ISSUE THREAD

**Issue by javahui** [Wechat-Group/WxJava#3419]
国内用第三方类库htool能增加下吗
hutool的http说明文档在下面
https://doc.hutool.cn/pages/HttpUtil

**Comment by binarywang** [comment]
为什么需要用它？
现在的代码用得好好的，你如果自己需要，可以在自己的项目里增加他的依赖就可以吧。
除非你愿意帮忙重写SDK，把现有的代码都给改写了，然后还要保证一点问题都没有。
