### ISSUE TITLE
4.6.5.B版本 报错 Consider defining a bean of type 'cn.binarywang.wx.miniapp.config.impl.WxMaDefaultConfigImpl' in your configuration. 

### ISSUE THREAD

**Issue by zchbluetear** [Wechat-Group/WxJava#3420]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~

### 简要描述
__请简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: 
* WxJava 版本号:（旧版本不予支持，谢谢配合）

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__

### 日志
__如果日志不多，直接使用md代码引用格式贴在此处，否则如果太长，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，然后将其url地址贴在这里__
```
日志请写于此处
```

**Comment by zchbluetear** [comment]
WxMaService maService = new WxMaServiceImpl();
        maService.setMultiConfigs(
                uniAppExternalSocialDtoList.stream()
                        .map(a -> {
                            //WxMaDefaultConfigImpl config = new WxMaDefaultConfigImpl();
                            WxMaDefaultConfigImpl config = new WxMaRedisConfigImpl(new JedisPool());
                            // 使用上面的配置时，需要同时引入jedis-lock的依赖，否则会报类无法找到的异常
                            config.setAppid(a.getAppId());
                            config.setSecret(a.getAppSecret());
                            //config.setToken(a.getToken());
                            //config.setAesKey(a.getAesKey());
                            //config.setMsgDataFormat(a.getMsgDataFormat());
                            return config;
                        }).collect(Collectors.toMap(WxMaDefaultConfigImpl::getAppid, a -> a, (o, n) -> o)));
        return maService;

**Comment by binarywang** [comment]
哥，你能否规范下发帖格式。
另外参考demo代码，先理解再引用，不要断章取义，别想着只取其中一部分代码就能跑起来了

**Comment by zchbluetear** [comment]
好的 已经解决 明天撤回



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Binary Wang ***@***.***&gt;
发送时间: 2024年11月25日 21:44
收件人: binarywang/WxJava ***@***.***&gt;
抄送: zchbluetear ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [binarywang/WxJava] 4.6.5.B版本 报错 Consider defining a bean of type 'cn.binarywang.wx.miniapp.config.impl.WxMaDefaultConfigImpl' in your configuration.  (Issue #3420)
