### ISSUE TITLE
近期微信支付V3接口推出的公钥ID验签适配 

### ISSUE THREAD

**Issue by GongLe** [Wechat-Group/WxJava#3430]
### 简要描述
关于近期微信支付V3接口推出的公钥ID验签，原先的sdk中只支持微信证书验签，询问一下针对微信推出新的验签方式，请问有维护计划吗?

### 官方文档地址
 https://pay.weixin.qq.com/doc/v3/merchant/4012153196
![截图_20241204_172905](https://github.com/user-attachments/assets/9c101de6-01c5-4828-88ed-c1658446d51d)

**Comment by binarywang** [comment]
最新版已经支持了，注意及时关注公众号最新推文

**Comment by collinsliucn** [comment]
请问使用4.6.7.B在WxPayConfig中需要配置哪些属性？keyPath对应的文件是apiclient_cert.p12文件吗？

**Comment by collinsliucn** [comment]
> 请问使用4.6.7.B在WxPayConfig中需要配置哪些属性？keyPath对应的文件是apiclient_cert.p12文件吗？

之前的配置是如图，使用微信支付公钥后，多了序列号和pub_key.pem文件，应该如何配置？
![WX20241206-200117@2x](https://github.com/user-attachments/assets/43f74990-e5a7-459f-b59d-5a7390e347d4)

**Comment by zhanyan-Ader1y** [comment]
> 请问使用4.6.7.B在WxPayConfig中需要配置哪些属性？keyPath对应的文件是apiclient_cert.p12文件吗？

可以看看WxPayCofig的源码, 公钥无法通过p12获取 需要设置publicKey和 publicPath/publicContent
