### ISSUE TITLE
V3支付接口为什么一定强制要求配置p12证书。

### ISSUE THREAD

**Issue by zzq517** [Wechat-Group/WxJava#3436]
配置了其他的证书信息，但是调用接口会走p12证书的加载逻辑，变成一定要配置p12证书了。然后报错提示：请确保证书文件地址【p12证书】或者内容已配置。应该改成可以尝试从p12加载证书信息，但是没有加载到不应该报错，下面可能还有其他加载其他证书的逻辑。
<img width="832" alt="image" src="https://github.com/user-attachments/assets/3971ebb2-eb4f-4cf3-9453-7e3e65f2b45e" />

**Comment by binarywang** [comment]
你用的是最新版吗？

**Comment by zzq517** [comment]
> 你用的是最新版吗？
是最新的呀，就是我配置了其他私钥、序列号啥的了，为啥还要配置p12证书呢。这段代码强制读p12证书了，没读取到就抛出异常。

**Comment by binarywang** [comment]
你不说版本号，怎么知道是最新的呢？
你看下首页项目说明相关部分对比下看看，我记得这个问题最近修复过。

**Comment by zzq517** [comment]
> 你不说版本号，怎么知道是最新的呢？ 你看下首页项目说明相关部分对比下看看，我记得这个问题最近修复过。

我用的就是4.6.8B的啊😂

**Comment by binarywang** [comment]
那你看看要如何修复这个问题，欢迎直接提交PR代码

**Comment by zzq517** [comment]
> 你不说版本号，怎么知道是最新的呢？ 你看下首页项目说明相关部分对比下看看，我记得这个问题最近修复过。

最新的代码依然加载p12。就是抛了异常，导致没有读取我下面的
<img width="955" alt="image" src="https://github.com/user-attachments/assets/bcd3930d-c1ba-435c-bb84-62bb6510a187" />

**Comment by zzq517** [comment]
> 那你看看要如何修复这个问题，欢迎直接提交PR代码

可以加载p12，但是没加载到是不是不应该抛出异常？我不知道这段,请确保证书文件地址【" + fileName + "】或者内容已配置,代码是不是在其他地方有作用呢
<img width="839" alt="image" src="https://github.com/user-attachments/assets/8485a7cb-0143-4290-9096-99596ac08508" />

**Comment by binarywang** [comment]
https://github.com/binarywang/WxJava/pull/3428  你看下这个提交是否已经解决问题了

**Comment by binarywang** [comment]
据说目前最新版本只是报错，但不影响程序运行而已。
目前已经有人提供了新的修复代码，不抛异常，后面会发新版本。

**Comment by zzq517** [comment]
> 据说目前最新版本只是报错，但不影响程序运行而已。 目前已经有人提供了新的修复代码，不抛异常，后面会发新版本。

这个pr应该解决我说的问题，但是我看回复好像引申出了其他问题了，我暂时先使用p12证书，等后续更新吧。
