### ISSUE TITLE
v3商家转账到零钱回调提示需要P12证书

### ISSUE THREAD

**Issue by yjh-0917** [Wechat-Group/WxJava#3441]
v3商家转账到零钱回调提示需要P12证书
版本是：4.6.9.B
![image](https://github.com/user-attachments/assets/23ed9a49-8884-419d-8da1-bb636ded94d8)

**Comment by binarywang** [comment]
你确定使用的是最新版本吗？麻烦核实下，代码行数没对上

**Comment by binarywang** [comment]
还有，以后尽量不要发截图，能发文字就发文字，谢谢！

**Comment by yjh-0917** [comment]
> 你确定使用的是最新版本吗？麻烦核实下，代码行数没对上

找到原因了，根目录pom和子模块pom文件中版本不一致导致的
