### ISSUE TITLE
发起商家转账接口TransferBatchesRequest缺少notify_url参数

### ISSUE THREAD

**Issue by devin6888** [Wechat-Group/WxJava#3444]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~

### 简要描述
发起商家转账接口TransferBatchesRequest缺少notify_url参数

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号: 4.6.0

### 详细描述
商家转账接口中的请求参数TransferBatchesRequest缺少notify_url参数， 无法实现回调通知
![image](https://github.com/user-attachments/assets/fe524cf4-61e7-41db-a9a5-5eb6d2ddb569)
![image](https://github.com/user-attachments/assets/87173a33-fe8b-444d-8d6e-0708d7fba91a)

**Comment by imyzt** [comment]
升级4.6.4.B+版本，对应提交：https://github.com/binarywang/WxJava/commit/43d270ac78fbe75c13ce1895969bbc86cfdecf41

**Comment by devin6888** [comment]
感谢作者
