### ISSUE TITLE
在wiki文档中发送模板消息的代码错误

### ISSUE THREAD

**Issue by wallbase** [Wechat-Group/WxJava#552]
地址信息：
[https://github.com/Wechat-Group/weixin-java-tools/wiki/MP_%E5%8F%91%E9%80%81%E6%A8%A1%E6%9D%BF%E6%B6%88%E6%81%AF](https://github.com/Wechat-Group/weixin-java-tools/wiki/MP_%E5%8F%91%E9%80%81%E6%A8%A1%E6%9D%BF%E6%B6%88%E6%81%AF)
- 旧版的代码版本2.9.0 已过时
```
templateMessage.getData().add(new WxMpTemplateData(name1, value1, color2));
templateMessage.getData().add(new WxMpTemplateData(name2, value2, color2));
```
-  新版的正确写法,代码版本3.0.0
```
templateMessage.addData(templateData);
```
具体变动版本COMMIT
[https://github.com/Wechat-Group/weixin-java-tools/commit/ce281bea325f6d1d24e13dd0804503ca31b86f4f#diff-3f8cb29f7048d1ab811f4919249a9475](https://github.com/Wechat-Group/weixin-java-tools/commit/ce281bea325f6d1d24e13dd0804503ca31b86f4f#diff-3f8cb29f7048d1ab811f4919249a9475)

**Comment by wallbase** [comment]
请及时更新一下文档，thanks

**Comment by wallbase** [comment]
顺便说一下代码如果直接getData，返回的是NULL的对象，最好在getData判断中加上如下代码：
`  
if(this.data == null) {
            this.data = new ArrayList();
        }
`

**Comment by binarywang** [comment]
谢谢提出，顺便说下，wiki是公开的，大家都可以修改，代码你也可以直接提交PR的

**Comment by binarywang** [comment]
以前的代码getData是没问题的，因为有初始值，不过现在还是可以加上那个初始值的
