### ISSUE TITLE
spring-cloud中集成weixin-java-tools后，作为服务化项目，token存储在redis中, 启动多个服务化项目，是否对token刷新有影响 ？

### ISSUE THREAD

**Issue by 15838028035** [Wechat-Group/WxJava#592]
spring-cloud中集成weixin-java-tools后，作为服务化项目，token存储在redis中, 启动多个服务化项目，是否对token刷新有影响 ？
@binarywang

**Comment by xwsg** [comment]
同问。
目前我也打算这么做，但是还没有测试，我理解的是，虽然redis是单线程的，但是如果多个服务同时刷新，感觉也是有问题的。

**Comment by 15838028035** [comment]
@xhusky  我们目前在测试环境上部署了两个一样的程序，端口不一样， 一个供生产使用，一个供测试使用， 感觉好像有影响。

**Comment by xwsg** [comment]
@15838028035 最近忙了些其他事情，还没时间看这个问题，今天大概找到一个思路，就是使用redis分布式锁，可以了解一下

**Comment by libran7** [comment]
同问

**Comment by xwsg** [comment]
经qq群管理提醒

[获取access_token](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140183)

> 2、目前Access_token的有效期通过返回的expire_in来传达，目前是7200秒之内的值。中控服务器需要根据这个有效时间提前去刷新新access_token。在刷新过程中，中控服务器可对外继续输出的老access_token，此时公众平台后台会保证在5分钟内，新老access_token都可用，这保证了第三方业务的平滑过渡；

也就是说新旧token会有5分钟的冗余，这个应该是没有问题的

官方文档还建议

> 1、建议公众号开发者使用中控服务器统一获取和刷新Access_token，其他业务逻辑服务器所使用的access_token均来自于该中控服务器，不应该各自去刷新，否则容易造成冲突，导致access_token覆盖而影响业务；
> 3、Access_token的有效时间可能会在未来有调整，所以中控服务器不仅需要内部定时主动刷新，还需要提供被动刷新access_token的接口，这样便于业务服务器在API调用获知access_token已超时的情况下，可以触发access_token的刷新流程。

**Comment by binarywang** [comment]
参考楼上所说即可
