### ISSUE TITLE
通过code和卡券id获取基本信息缺少字段

### ISSUE THREAD

**Issue by thomas2050** [Wechat-Group/WxJava#894]
https://api.weixin.qq.com/card/code/get
现在有如下字段：
{
    "errcode": 0,
    "errmsg": "ok",
    "card": {
        "card_id": "p0eK60jD5OeGfhLbUC22222rsjR9toAx4",
        "begin_time": 0,
        "end_time": 4294967222295,
        "bonus": 120,
        "code": "223424393077",
        "membership_number": "223424393077"
    },
    "openid": "o0eK60hF4tI2222uXFF2OMCTCNn50iYs",
    "can_consume": true,
    "user_card_status": "NORMAL",
    "outer_str": "Floph5_1217",
    "background_pic_url": "xxxxxx",
    "unionid": "xxxx"
}

目前只返回了
{
    "errcode": 0,
    "errmsg": "ok",
    "card": {
        "card_id": "p0eK60jD5OeGfhLbUC22222rsjR9toAx4",
        "begin_time": 0,
        "end_time": 4294967222295,
        "bonus": 120
    },
    "openid": "o0eK60hF4tI2222uXFF2OMCTCNn50iYs",
    "can_consume": true,
    "user_card_status": "NORMAL"
}

**Comment by binarywang** [comment]
请提供下能够描述字段含义的文档地址，谢谢

**Comment by binarywang** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1451025272&anchor=1
只找到这个文档地址，里面没发现对应描述，先按你提供的字段补充一下。

**Comment by binarywang** [comment]
3.3.2.B测试版本 已完善
