### ISSUE TITLE
公众平台推送模板 字段与微信不一致

### ISSUE THREAD

**Issue by MarchNineteen** [Wechat-Group/WxJava#993]
微信文档 这两个字段都是小写
           "touser":"OPENID",
           "template_id":"ngqIpbwh8bUfcSsECmogfXcV14J0tQlEpBO27izEYtY"
Entity 中 按照 下面字段名 生成的string 不符合微信的 要求 会报错
  private String toUser;
  private String templateId;

**Comment by binarywang** [comment]
仔细看下代码？json生成的机制？
